// advanced-data.js - 300 كلمة للمستوى المتقدم
const ADVANCED_WORDS = [
    // ========== مشاعر متقدمة جداً ========== (20 كلمة)
    { id: 3001, word: "euphoric", arabic: "نشوان", pronunciation: "يوفوريك", example: "She felt euphoric after winning.", exampleArabic: "شعرت بنشوة بعد الفوز", category: "مشاعر" },
    { id: 3002, word: "melancholy", arabic: "كآبة", pronunciation: "ميلانكولي", example: "A feeling of melancholy.", exampleArabic: "شعور بالكآبة", category: "مشاعر" },
    { id: 3003, word: "nostalgic", arabic: "حنين", pronunciation: "نوستالجيك", example: "I feel nostalgic about my childhood.", exampleArabic: "أشعر بالحنين لطفولتي", category: "مشاعر" },
    { id: 3004, word: "serene", arabic: "هادئ", pronunciation: "سيرين", example: "The lake was serene.", exampleArabic: "البحيرة كانت هادئة", category: "مشاعر" },
    { id: 3005, word: "tranquil", arabic: "ساكن", pronunciation: "ترانكويل", example: "A tranquil evening.", exampleArabic: "مساء ساكن", category: "مشاعر" },
    { id: 3006, word: "apathetic", arabic: "لا مبالٍ", pronunciation: "أباثيتيك", example: "He was apathetic about the issue.", exampleArabic: "كان لا مبالياً حيال القضية", category: "مشاعر" },
    { id: 3007, word: "indifferent", arabic: "غير مكترث", pronunciation: "إنديفرنت", example: "She seems indifferent to criticism.", exampleArabic: "تبدو غير مكترثة بالنقد", category: "مشاعر" },
    { id: 3008, word: "bittersweet", arabic: "حلو ومر", pronunciation: "بيترسويت", example: "A bittersweet memory.", exampleArabic: "ذكرى حلوة ومرة", category: "مشاعر" },
    { id: 3009, word: "elated", arabic: "منتعش", pronunciation: "إليتيد", example: "He was elated by the news.", exampleArabic: "انتعش بالخبر", category: "مشاعر" },
    { id: 3010, word: "ecstatic", arabic: "منتشي", pronunciation: "إكستاتيك", example: "The fans were ecstatic.", exampleArabic: "الجماهير كانت منتشية", category: "مشاعر" },
    { id: 3011, word: "jubilant", arabic: "مبتهج", pronunciation: "جوبيلانت", example: "Jubilant celebrations.", exampleArabic: "احتفالات مبتهجة", category: "مشاعر" },
    { id: 3012, word: "exhilarated", arabic: "منتعش", pronunciation: "إكزيلريتد", example: "I felt exhilarated after the run.", exampleArabic: "شعرت بانتعاش بعد الجري", category: "مشاعر" },
    { id: 3013, word: "anguished", arabic: "متعذب", pronunciation: "أنجويشت", example: "An anguished cry.", exampleArabic: "صرخة متعذبة", category: "مشاعر" },
    { id: 3014, word: "despondent", arabic: "مكتئب", pronunciation: "ديسبوندنت", example: "He was despondent after failure.", exampleArabic: "كان مكتئباً بعد الفشل", category: "مشاعر" },
    { id: 3015, word: "morose", arabic: "عبوس", pronunciation: "موروس", example: "He sat in morose silence.", exampleArabic: "جلس في صمت عابس", category: "مشاعر" },
    { id: 3016, word: "somber", arabic: "قاتم", pronunciation: "سومبر", example: "A somber mood.", exampleArabic: "مزاج قاتم", category: "مشاعر" },
    { id: 3017, word: "wistful", arabic: "حزين", pronunciation: "ويستفول", example: "A wistful look.", exampleArabic: "نظرة حزينة", category: "مشاعر" },
    { id: 3018, word: "yearning", arabic: "شوق", pronunciation: "يرنينغ", example: "Yearning for home.", exampleArabic: "شوق للوطن", category: "مشاعر" },
    { id: 3019, word: "longing", arabic: "اشتياق", pronunciation: "لونغينغ", example: "Longing for her return.", exampleArabic: "اشتياق لعودتها", category: "مشاعر" },
    { id: 3020, word: "craving", arabic: "رغبة شديدة", pronunciation: "كريفينغ", example: "I have a craving for chocolate.", exampleArabic: "لدي رغبة شديدة بالشوكولاتة", category: "مشاعر" },

    // ========== صفات متقدمة ========== (20 كلمة)
    { id: 3101, word: "meticulous", arabic: "دقيق", pronunciation: "ميتيكيولوس", example: "He is meticulous about details.", exampleArabic: "هو دقيق في التفاصيل", category: "صفات" },
    { id: 3102, word: "fastidious", arabic: "صعب الإرضاء", pronunciation: "فاستيدياس", example: "She is fastidious about cleanliness.", exampleArabic: "هي صعبة الإرضاء بشأن النظافة", category: "صفات" },
    { id: 3103, word: "diligent", arabic: "مجتهد", pronunciation: "ديليجنت", example: "A diligent student.", exampleArabic: "طالب مجتهد", category: "صفات" },
    { id: 3104, word: "assiduous", arabic: "مواظب", pronunciation: "أسيديواس", example: "Assiduous effort.", exampleArabic: "جهد مواظب", category: "صفات" },
    { id: 3105, word: "persistent", arabic: "مثابر", pronunciation: "بيرسيستنت", example: "Persistent attempts.", exampleArabic: "محاولات مثابرة", category: "صفات" },
    { id: 3106, word: "tenacious", arabic: "عنيد", pronunciation: "تينيشس", example: "A tenacious defender.", exampleArabic: "مدافع عنيد", category: "صفات" },
    { id: 3107, word: "resilient", arabic: "مرن", pronunciation: "ريزليانت", example: "Resilient spirit.", exampleArabic: "روح مرنة", category: "صفات" },
    { id: 3108, word: "adaptable", arabic: "قابل للتكيف", pronunciation: "أدابتابل", example: "She is adaptable to change.", exampleArabic: "هي قابلة للتكيف مع التغيير", category: "صفات" },
    { id: 3109, word: "versatile", arabic: "متعدد المواهب", pronunciation: "فيرساتايل", example: "A versatile actor.", exampleArabic: "ممثل متعدد المواهب", category: "صفات" },
    { id: 3110, word: "proficient", arabic: "بارع", pronunciation: "بروفيشنت", example: "Proficient in English.", exampleArabic: "بارع في الإنجليزية", category: "صفات" },
    { id: 3111, word: "adept", arabic: "ماهر", pronunciation: "أديبت", example: "Adept at problem-solving.", exampleArabic: "ماهر في حل المشكلات", category: "صفات" },
    { id: 3112, word: "competent", arabic: "كفؤ", pronunciation: "كومبيتنت", example: "A competent manager.", exampleArabic: "مدير كفؤ", category: "صفات" },
    { id: 3113, word: "capable", arabic: "قادر", pronunciation: "كيبيبل", example: "Capable of great things.", exampleArabic: "قادر على أشياء عظيمة", category: "صفات" },
    { id: 3114, word: "efficient", arabic: "فعال", pronunciation: "إفيشنت", example: "Efficient worker.", exampleArabic: "عامل فعال", category: "صفات" },
    { id: 3115, word: "productive", arabic: "منتج", pronunciation: "برودكتيف", example: "A productive day.", exampleArabic: "يوم منتج", category: "صفات" },
    { id: 3116, word: "innovative", arabic: "مبتكر", pronunciation: "إنوفيتيف", example: "Innovative idea.", exampleArabic: "فكرة مبتكرة", category: "صفات" },
    { id: 3117, word: "ingenious", arabic: "عبقري", pronunciation: "إنجينيوس", example: "An ingenious invention.", exampleArabic: "اختراع عبقري", category: "صفات" },
    { id: 3118, word: "resourceful", arabic: "واسع الحيلة", pronunciation: "ريسورسفول", example: "A resourceful person.", exampleArabic: "شخص واسع الحيلة", category: "صفات" },
    { id: 3119, word: "tactful", arabic: "لبق", pronunciation: "تاكتفول", example: "A tactful response.", exampleArabic: "رد لبق", category: "صفات" },
    { id: 3120, word: "diplomatic", arabic: "دبلوماسي", pronunciation: "ديبلوماتيك", example: "Diplomatic approach.", exampleArabic: "نهج دبلوماسي", category: "صفات" },

    // ========== أفعال متقدمة ========== (20 كلمة)
    { id: 3201, word: "articulate", arabic: "يعبر بوضوح", pronunciation: "أرتيكيوليت", example: "He articulated his thoughts well.", exampleArabic: "عبر عن أفكاره بوضوح", category: "أفعال" },
    { id: 3202, word: "convey", arabic: "ينقل", pronunciation: "كونفاي", example: "Convey the message.", exampleArabic: "انقل الرسالة", category: "أفعال" },
    { id: 3203, word: "express", arabic: "يعبر", pronunciation: "إكسبريس", example: "Express your feelings.", exampleArabic: "عبر عن مشاعرك", category: "أفعال" },
    { id: 3204, word: "communicate", arabic: "يتواصل", pronunciation: "كوميونيكيت", example: "Communicate effectively.", exampleArabic: "تواصل بفعالية", category: "أفعال" },
    { id: 3205, word: "negotiate", arabic: "يتفاوض", pronunciation: "نيغوتشيت", example: "Negotiate a deal.", exampleArabic: "تفاوض على صفقة", category: "أفعال" },
    { id: 3206, word: "mediate", arabic: "يتوسط", pronunciation: "ميديت", example: "Mediate between parties.", exampleArabic: "توسط بين الأطراف", category: "أفعال" },
    { id: 3207, word: "reconcile", arabic: "يتصالح", pronunciation: "ريكنسايل", example: "Reconcile differences.", exampleArabic: "تصالح مع الاختلافات", category: "أفعال" },
    { id: 3208, word: "compromise", arabic: "يتنازل", pronunciation: "كومبرومايز", example: "Learn to compromise.", exampleArabic: "تعلم أن تتنازل", category: "أفعال" },
    { id: 3209, word: "analyze", arabic: "يحلل", pronunciation: "أنالايز", example: "Analyze the data.", exampleArabic: "حلل البيانات", category: "أفعال" },
    { id: 3210, word: "evaluate", arabic: "يقيم", pronunciation: "إيفالويت", example: "Evaluate the results.", exampleArabic: "قيم النتائج", category: "أفعال" },
    { id: 3211, word: "assess", arabic: "يقدر", pronunciation: "آسيس", example: "Assess the situation.", exampleArabic: "قدر الموقف", category: "أفعال" },
    { id: 3212, word: "scrutinize", arabic: "يدقق", pronunciation: "سكروتينايز", example: "Scrutinize the details.", exampleArabic: "دقق في التفاصيل", category: "أفعال" },
    { id: 3213, word: "examine", arabic: "يفحص", pronunciation: "إكزامين", example: "Examine the evidence.", exampleArabic: "افحص الأدلة", category: "أفعال" },
    { id: 3214, word: "investigate", arabic: "يحقق", pronunciation: "إنفيستيغيت", example: "Investigate the crime.", exampleArabic: "حقق في الجريمة", category: "أفعال" },
    { id: 3215, word: "interrogate", arabic: "يستجوب", pronunciation: "إنتروغيت", example: "Interrogate the suspect.", exampleArabic: "استجوب المشتبه به", category: "أفعال" },
    { id: 3216, word: "inquire", arabic: "يستفسر", pronunciation: "إنكواير", example: "Inquire about the price.", exampleArabic: "استفسر عن السعر", category: "أفعال" },
    { id: 3217, word: "question", arabic: "يسأل", pronunciation: "كيستشن", example: "Question the witness.", exampleArabic: "اسأل الشاهد", category: "أفعال" },
    { id: 3218, word: "challenge", arabic: "يتحدى", pronunciation: "تشالينج", example: "Challenge the idea.", exampleArabic: "تحدى الفكرة", category: "أفعال" },
    { id: 3219, word: "debate", arabic: "يناقش", pronunciation: "ديبيت", example: "Debate the issue.", exampleArabic: "ناقش القضية", category: "أفعال" },
    { id: 3220, word: "argue", arabic: "يجادل", pronunciation: "أرجيو", example: "Argue your point.", exampleArabic: "جادل بنقطتك", category: "أفعال" },

    // ========== أعمال ========== (20 كلمة)
    { id: 3301, word: "entrepreneur", arabic: "رائد أعمال", pronunciation: "أنتربرينور", example: "He is a successful entrepreneur.", exampleArabic: "هو رائد أعمال ناجح", category: "أعمال" },
    { id: 3302, word: "investor", arabic: "مستثمر", pronunciation: "إنفيستور", example: "Investors put money in startups.", exampleArabic: "المستثمرون يضعون المال في الشركات الناشئة", category: "أعمال" },
    { id: 3303, word: "shareholder", arabic: "مساهم", pronunciation: "شيرهولدر", example: "Shareholders own the company.", exampleArabic: "المساهمون يملكون الشركة", category: "أعمال" },
    { id: 3304, word: "stakeholder", arabic: "صاحب مصلحة", pronunciation: "ستيكهولدر", example: "Stakeholders have interest.", exampleArabic: "أصحاب المصلحة لهم مصلحة", category: "أعمال" },
    { id: 3305, word: "merger", arabic: "اندماج", pronunciation: "مرجر", example: "The merger of two companies.", exampleArabic: "اندماج شركتين", category: "أعمال" },
    { id: 3306, word: "acquisition", arabic: "استحواذ", pronunciation: "أكويزيشن", example: "The acquisition of the startup.", exampleArabic: "استحواذ على الشركة الناشئة", category: "أعمال" },
    { id: 3307, word: "takeover", arabic: "سيطرة", pronunciation: "تيك أوفر", example: "The takeover bid.", exampleArabic: "عرض السيطرة", category: "أعمال" },
    { id: 3308, word: "bankruptcy", arabic: "إفلاس", pronunciation: "بانكربتسي", example: "The company filed for bankruptcy.", exampleArabic: "الشركة أعلنت الإفلاس", category: "أعمال" },
    { id: 3309, word: "insolvency", arabic: "إعسار", pronunciation: "إنسولفينسي", example: "Facing insolvency.", exampleArabic: "مواجهة الإعسار", category: "أعمال" },
    { id: 3310, word: "liquidation", arabic: "تصفية", pronunciation: "ليكويدايشن", example: "Liquidation of assets.", exampleArabic: "تصفية الأصول", category: "أعمال" },
    { id: 3311, word: "revenue", arabic: "إيرادات", pronunciation: "ريفينيو", example: "The company's revenue increased.", exampleArabic: "إيرادات الشركة زادت", category: "أعمال" },
    { id: 3312, word: "profit", arabic: "ربح", pronunciation: "بروفيت", example: "Net profit after tax.", exampleArabic: "صافي الربح بعد الضريبة", category: "أعمال" },
    { id: 3313, word: "loss", arabic: "خسارة", pronunciation: "لوس", example: "The company made a loss.", exampleArabic: "الشركة حققت خسارة", category: "أعمال" },
    { id: 3314, word: "dividend", arabic: "أرباح موزعة", pronunciation: "ديفيدند", example: "Shareholders receive dividends.", exampleArabic: "المساهمون يتلقون أرباحاً موزعة", category: "أعمال" },
    { id: 3315, word: "interest", arabic: "فائدة", pronunciation: "إنترست", example: "Interest on loans.", exampleArabic: "فائدة على القروض", category: "أعمال" },
    { id: 3316, word: "principal", arabic: "أصل الدين", pronunciation: "برينسيبال", example: "Pay the principal amount.", exampleArabic: "ادفع مبلغ أصل الدين", category: "أعمال" },
    { id: 3317, word: "collateral", arabic: "ضمان", pronunciation: "كولاتيرال", example: "Use property as collateral.", exampleArabic: "استخدم العقار كضمان", category: "أعمال" },
    { id: 3318, word: "mortgage", arabic: "رهن", pronunciation: "مورغيج", example: "Mortgage on the house.", exampleArabic: "رهن على المنزل", category: "أعمال" },
    { id: 3319, word: "credit", arabic: "ائتمان", pronunciation: "كريديت", example: "Buy on credit.", exampleArabic: "اشتر بالائتمان", category: "أعمال" },
    { id: 3320, word: "debt", arabic: "دين", pronunciation: "ديت", example: "Pay off your debt.", exampleArabic: "اسدد دينك", category: "أعمال" },

    // ========== قانون ========== (20 كلمة)
    { id: 3401, word: "attorney", arabic: "محام", pronunciation: "أتورني", example: "The attorney presented the case.", exampleArabic: "المحامي قدم القضية", category: "قانون" },
    { id: 3402, word: "lawyer", arabic: "محام", pronunciation: "لويير", example: "Hire a lawyer.", exampleArabic: "استأجر محامياً", category: "قانون" },
    { id: 3403, word: "judge", arabic: "قاض", pronunciation: "جادج", example: "The judge made a ruling.", exampleArabic: "القاضي أصدر حكماً", category: "قانون" },
    { id: 3404, word: "jury", arabic: "هيئة محلفين", pronunciation: "جوري", example: "The jury reached a verdict.", exampleArabic: "هيئة المحلفين وصلت إلى قرار", category: "قانون" },
    { id: 3405, word: "plaintiff", arabic: "مدعي", pronunciation: "بلينتيف", example: "The plaintiff filed a lawsuit.", exampleArabic: "المدعي رفع دعوى", category: "قانون" },
    { id: 3406, word: "defendant", arabic: "مدعى عليه", pronunciation: "ديفيندنت", example: "The defendant pleaded not guilty.", exampleArabic: "المدعى عليه دفع بغير مذنب", category: "قانون" },
    { id: 3407, word: "witness", arabic: "شاهد", pronunciation: "ويتنس", example: "The witness testified.", exampleArabic: "الشاهد شهد", category: "قانون" },
    { id: 3408, word: "testimony", arabic: "شهادة", pronunciation: "تيستيموني", example: "Her testimony was crucial.", exampleArabic: "شهادتها كانت حاسمة", category: "قانون" },
    { id: 3409, word: "evidence", arabic: "دليل", pronunciation: "إيفيدنس", example: "The evidence was clear.", exampleArabic: "الدليل كان واضحاً", category: "قانون" },
    { id: 3410, word: "verdict", arabic: "حكم", pronunciation: "فيرديكت", example: "The verdict was guilty.", exampleArabic: "الحكم كان مذنباً", category: "قانون" },
    { id: 3411, word: "sentence", arabic: "عقوبة", pronunciation: "سينتنز", example: "The sentence was 10 years.", exampleArabic: "العقوبة كانت 10 سنوات", category: "قانون" },
    { id: 3412, word: "appeal", arabic: "استئناف", pronunciation: "أبيل", example: "File an appeal.", exampleArabic: "قدم استئنافاً", category: "قانون" },
    { id: 3413, word: "overturn", arabic: "نقض", pronunciation: "أوفرترن", example: "The court overturned the decision.", exampleArabic: "المحكمة نقضت القرار", category: "قانون" },
    { id: 3414, word: "acquit", arabic: "تبرئة", pronunciation: "أكويت", example: "The jury acquitted him.", exampleArabic: "هيئة المحلفين برأته", category: "قانون" },
    { id: 3415, word: "convict", arabic: "إدانة", pronunciation: "كونفيكت", example: "He was convicted of theft.", exampleArabic: "أدين بالسرقة", category: "قانون" },
    { id: 3416, word: "plea", arabic: "دفع", pronunciation: "بلي", example: "Enter a plea of guilty.", exampleArabic: "قدم دفعاً بالذنب", category: "قانون" },
    { id: 3417, word: "bail", arabic: "كفالة", pronunciation: "بيل", example: "He was released on bail.", exampleArabic: "أطلق سراحه بكفالة", category: "قانون" },
    { id: 3418, word: "parole", arabic: "إفراج شرطي", pronunciation: "بارول", example: "He was released on parole.", exampleArabic: "أطلق سراحه بإفراج شرطي", category: "قانون" },
    { id: 3419, word: "probation", arabic: "تحت المراقبة", pronunciation: "بروبيشن", example: "He was put on probation.", exampleArabic: "وضع تحت المراقبة", category: "قانون" },
    { id: 3420, word: "fine", arabic: "غرامة", pronunciation: "فاين", example: "Pay a fine.", exampleArabic: "ادفع غرامة", category: "قانون" },

    // ========== تكنولوجيا ========== (20 كلمة)
    { id: 3501, word: "algorithm", arabic: "خوارزمية", pronunciation: "ألغوريزم", example: "The algorithm solves the problem.", exampleArabic: "الخوارزمية تحل المشكلة", category: "تكنولوجيا" },
    { id: 3502, word: "bandwidth", arabic: "عرض النطاق", pronunciation: "باندويدث", example: "High bandwidth internet.", exampleArabic: "إنترنت عالي النطاق", category: "تكنولوجيا" },
    { id: 3503, word: "blockchain", arabic: "سلسلة الكتل", pronunciation: "بلوكتشين", example: "Blockchain technology.", exampleArabic: "تقنية سلسلة الكتل", category: "تكنولوجيا" },
    { id: 3504, word: "cloud computing", arabic: "حوسبة سحابية", pronunciation: "كلاود كمبيوتنغ", example: "Store data in the cloud.", exampleArabic: "خزن البيانات في السحابة", category: "تكنولوجيا" },
    { id: 3505, word: "cybersecurity", arabic: "أمن سيبراني", pronunciation: "سايبر سكيوريتي", example: "Protect against cyber attacks.", exampleArabic: "احمِ من الهجمات السيبرانية", category: "تكنولوجيا" },
    { id: 3506, word: "database", arabic: "قاعدة بيانات", pronunciation: "داتابيس", example: "The database contains information.", exampleArabic: "قاعدة البيانات تحتوي معلومات", category: "تكنولوجيا" },
    { id: 3507, word: "encryption", arabic: "تشفير", pronunciation: "إنكريبشن", example: "Encryption keeps data safe.", exampleArabic: "التشفير يحافظ على أمان البيانات", category: "تكنولوجيا" },
    { id: 3508, word: "firewall", arabic: "جدار ناري", pronunciation: "فايروول", example: "The firewall blocks threats.", exampleArabic: "الجدار الناري يصد التهديدات", category: "تكنولوجيا" },
    { id: 3509, word: "hardware", arabic: "عتاد", pronunciation: "هاردوير", example: "Computer hardware.", exampleArabic: "عتاد الكمبيوتر", category: "تكنولوجيا" },
    { id: 3510, word: "software", arabic: "برمجيات", pronunciation: "سوفتوير", example: "Install new software.", exampleArabic: "ثبت برمجيات جديدة", category: "تكنولوجيا" },
    { id: 3511, word: "malware", arabic: "برمجيات خبيثة", pronunciation: "مالوير", example: "Malware can harm your computer.", exampleArabic: "البرمجيات الخبيثة قد تضر جهازك", category: "تكنولوجيا" },
    { id: 3512, word: "phishing", arabic: "تصيد", pronunciation: "فيشينغ", example: "Beware of phishing emails.", exampleArabic: "احذر من رسائل التصيد", category: "تكنولوجيا" },
    { id: 3513, word: "server", arabic: "خادم", pronunciation: "سيرفر", example: "The server hosts the website.", exampleArabic: "الخادم يستضيف الموقع", category: "تكنولوجيا" },
    { id: 3514, word: "network", arabic: "شبكة", pronunciation: "نيتورك", example: "Connect to the network.", exampleArabic: "اتصل بالشبكة", category: "تكنولوجيا" },
    { id: 3515, word: "interface", arabic: "واجهة", pronunciation: "إنترفيس", example: "User-friendly interface.", exampleArabic: "واجهة سهلة الاستخدام", category: "تكنولوجيا" },
    { id: 3516, word: "protocol", arabic: "بروتوكول", pronunciation: "بروتوكول", example: "Follow the protocol.", exampleArabic: "اتبع البروتوكول", category: "تكنولوجيا" },
    { id: 3517, word: "encryption", arabic: "تشفير", pronunciation: "إنكريبشن", example: "End-to-end encryption.", exampleArabic: "تشفير من طرف لطرف", category: "تكنولوجيا" },
    { id: 3518, word: "authentication", arabic: "مصادقة", pronunciation: "أوثنتيكيشن", example: "Two-factor authentication.", exampleArabic: "مصادقة ثنائية العامل", category: "تكنولوجيا" },
    { id: 3519, word: "bandwidth", arabic: "عرض نطاق", pronunciation: "باندويدث", example: "Limited bandwidth.", exampleArabic: "عرض نطاق محدود", category: "تكنولوجيا" },
    { id: 3520, word: "latency", arabic: "زمن الوصول", pronunciation: "ليتنزي", example: "Low latency connection.", exampleArabic: "اتصال قليل زمن الوصول", category: "تكنولوجيا" },

    // ========== طبيعة متقدمة ========== (20 كلمة)
    { id: 3601, word: "ecosystem", arabic: "نظام بيئي", pronunciation: "إيكوسيستم", example: "Protect the ecosystem.", exampleArabic: "احمِ النظام البيئي", category: "طبيعة" },
    { id: 3602, word: "biodiversity", arabic: "تنوع بيولوجي", pronunciation: "بايو دايفرسيتي", example: "Rainforests have high biodiversity.", exampleArabic: "الغابات المطيرة ذات تنوع بيولوجي عال", category: "طبيعة" },
    { id: 3603, word: "conservation", arabic: "حماية", pronunciation: "كونسيرفيشن", example: "Wildlife conservation.", exampleArabic: "حماية الحياة البرية", category: "طبيعة" },
    { id: 3604, word: "deforestation", arabic: "إزالة الغابات", pronunciation: "ديفورستيشن", example: "Deforestation harms the planet.", exampleArabic: "إزالة الغابات تضر الكوكب", category: "طبيعة" },
    { id: 3605, word: "reforestation", arabic: "إعادة تشجير", pronunciation: "ريفورستيشن", example: "Plant trees for reforestation.", exampleArabic: "ازرع أشجاراً لإعادة التشجير", category: "طبيعة" },
    { id: 3606, word: "climate", arabic: "مناخ", pronunciation: "كلايميت", example: "Climate change is real.", exampleArabic: "التغير المناخي حقيقي", category: "طبيعة" },
    { id: 3607, word: "atmosphere", arabic: "غلاف جوي", pronunciation: "أتوموسفير", example: "The Earth's atmosphere.", exampleArabic: "الغلاف الجوي للأرض", category: "طبيعة" },
    { id: 3608, word: "ozone", arabic: "أوزون", pronunciation: "أوزون", example: "The ozone layer.", exampleArabic: "طبقة الأوزون", category: "طبيعة" },
    { id: 3609, word: "greenhouse", arabic: "دفيئة", pronunciation: "غرينهاوس", example: "Greenhouse effect.", exampleArabic: "تأثير الدفيئة", category: "طبيعة" },
    { id: 3610, word: "pollution", arabic: "تلوث", pronunciation: "بولوشن", example: "Air pollution.", exampleArabic: "تلوث الهواء", category: "طبيعة" },
    { id: 3611, word: "contamination", arabic: "تلوث", pronunciation: "كونتامينيشن", example: "Water contamination.", exampleArabic: "تلوث الماء", category: "طبيعة" },
    { id: 3612, word: "sustainable", arabic: "مستدام", pronunciation: "ساستينابل", example: "Sustainable development.", exampleArabic: "تطوير مستدام", category: "طبيعة" },
    { id: 3613, word: "renewable", arabic: "متجدد", pronunciation: "رينيوبل", example: "Renewable energy.", exampleArabic: "طاقة متجددة", category: "طبيعة" },
    { id: 3614, word: "fossil", arabic: "أحفوري", pronunciation: "فوسل", example: "Fossil fuels.", exampleArabic: "وقود أحفوري", category: "طبيعة" },
    { id: 3615, word: "solar", arabic: "شمسي", pronunciation: "سولار", example: "Solar power.", exampleArabic: "طاقة شمسية", category: "طبيعة" },
    { id: 3616, word: "wind", arabic: "رياح", pronunciation: "ويند", example: "Wind energy.", exampleArabic: "طاقة رياح", category: "طبيعة" },
    { id: 3617, word: "geothermal", arabic: "حراري أرضي", pronunciation: "جيوثيرمال", example: "Geothermal energy.", exampleArabic: "طاقة حرارية أرضية", category: "طبيعة" },
    { id: 3618, word: "hydroelectric", arabic: "مائي", pronunciation: "هايدروإلكتريك", example: "Hydroelectric dam.", exampleArabic: "سد مائي لتوليد الكهرباء", category: "طبيعة" },
    { id: 3619, word: "erosion", arabic: "تعرية", pronunciation: "إيروجن", example: "Soil erosion.", exampleArabic: "تعرية التربة", category: "طبيعة" },
    { id: 3620, word: "landslide", arabic: "انهيار أرضي", pronunciation: "لاندسلايد", example: "The landslide destroyed homes.", exampleArabic: "الانهيار الأرضي دمر منازل", category: "طبيعة" },

    // ========== كلمات أكاديمية ========== (20 كلمة)
    { id: 3701, word: "hypothesis", arabic: "فرضية", pronunciation: "هايبوثيسيس", example: "Formulate a hypothesis.", exampleArabic: "صغ فرضية", category: "أكاديمي" },
    { id: 3702, word: "theory", arabic: "نظرية", pronunciation: "ثيري", example: "Einstein's theory of relativity.", exampleArabic: "نظرية أينشتاين للنسبية", category: "أكاديمي" },
    { id: 3703, word: "thesis", arabic: "أطروحة", pronunciation: "ثيسيس", example: "Write a thesis.", exampleArabic: "اكتب أطروحة", category: "أكاديمي" },
    { id: 3704, word: "dissertation", arabic: "رسالة دكتوراه", pronunciation: "ديسيرتيشن", example: "Defend your dissertation.", exampleArabic: "دافع عن رسالتك", category: "أكاديمي" },
    { id: 3705, word: "research", arabic: "بحث", pronunciation: "ريسرتش", example: "Conduct research.", exampleArabic: "قم ببحث", category: "أكاديمي" },
    { id: 3706, word: "analysis", arabic: "تحليل", pronunciation: "أناليسيس", example: "Data analysis.", exampleArabic: "تحليل البيانات", category: "أكاديمي" },
    { id: 3707, word: "synthesis", arabic: "تجميع", pronunciation: "سينثيسيس", example: "Synthesis of ideas.", exampleArabic: "تجميع الأفكار", category: "أكاديمي" },
    { id: 3708, word: "methodology", arabic: "منهجية", pronunciation: "ميثودولوجي", example: "Research methodology.", exampleArabic: "منهجية البحث", category: "أكاديمي" },
    { id: 3709, word: "empirical", arabic: "تجريبي", pronunciation: "إمبيريكال", example: "Empirical evidence.", exampleArabic: "دليل تجريبي", category: "أكاديمي" },
    { id: 3710, word: "quantitative", arabic: "كمي", pronunciation: "كوونتيتاتيف", example: "Quantitative research.", exampleArabic: "بحث كمي", category: "أكاديمي" },
    { id: 3711, word: "qualitative", arabic: "نوعي", pronunciation: "كووليتاتيف", example: "Qualitative analysis.", exampleArabic: "تحليل نوعي", category: "أكاديمي" },
    { id: 3712, word: "variable", arabic: "متغير", pronunciation: "فيريابل", example: "Control the variables.", exampleArabic: "تحكم في المتغيرات", category: "أكاديمي" },
    { id: 3713, word: "correlation", arabic: "ارتباط", pronunciation: "كوريلايشن", example: "Correlation between factors.", exampleArabic: "ارتباط بين العوامل", category: "أكاديمي" },
    { id: 3714, word: "causation", arabic: "سببية", pronunciation: "كوزيشن", example: "Correlation is not causation.", exampleArabic: "الارتباط ليس سبباً", category: "أكاديمي" },
    { id: 3715, word: "significant", arabic: "معنوي", pronunciation: "سيغنتيفيكانت", example: "Significant difference.", exampleArabic: "فرق معنوي", category: "أكاديمي" },
    { id: 3716, word: "validity", arabic: "صدق", pronunciation: "فاليديتي", example: "Ensure validity of results.", exampleArabic: "تأكد من صدق النتائج", category: "أكاديمي" },
    { id: 3717, word: "reliability", arabic: "ثبات", pronunciation: "ريليابيليتي", example: "Reliability of the test.", exampleArabic: "ثبات الاختبار", category: "أكاديمي" },
    { id: 3718, word: "sample", arabic: "عينة", pronunciation: "سامبل", example: "Representative sample.", exampleArabic: "عينة ممثلة", category: "أكاديمي" },
    { id: 3719, word: "population", arabic: "مجتمع", pronunciation: "بوبيولايشن", example: "The study population.", exampleArabic: "مجتمع الدراسة", category: "أكاديمي" },
    { id: 3720, word: "peer review", arabic: "مراجعة الأقران", pronunciation: "بير ريفيو", example: "Submit for peer review.", exampleArabic: "قدم لمراجعة الأقران", category: "أكاديمي" },

    // ========== روابط متقدمة ========== (20 كلمة)
    { id: 3801, word: "furthermore", arabic: "علاوة على ذلك", pronunciation: "فيرذر مور", example: "Furthermore, it is important.", exampleArabic: "علاوة على ذلك، إنه مهم", category: "روابط" },
    { id: 3802, word: "moreover", arabic: "زيادة على ذلك", pronunciation: "مور أوفر", example: "Moreover, the price is reasonable.", exampleArabic: "زيادة على ذلك، السعر معقول", category: "روابط" },
    { id: 3803, word: "nevertheless", arabic: "مع ذلك", pronunciation: "نيفرذايليس", example: "It was hard; nevertheless, I did it.", exampleArabic: "كان صعباً؛ مع ذلك، فعلته", category: "روابط" },
    { id: 3804, word: "nonetheless", arabic: "مع ذلك", pronunciation: "نونذايليس", example: "Nonetheless, we must try.", exampleArabic: "مع ذلك، يجب أن نحاول", category: "روابط" },
    { id: 3805, word: "however", arabic: "ومع ذلك", pronunciation: "هاوإيفر", example: "However, I disagree.", exampleArabic: "ومع ذلك، أنا لا أوافق", category: "روابط" },
    { id: 3806, word: "therefore", arabic: "لذلك", pronunciation: "ذيرفور", example: "Therefore, we must act.", exampleArabic: "لذلك، يجب أن نتحرك", category: "روابط" },
    { id: 3807, word: "consequently", arabic: "وبالتالي", pronunciation: "كونسيكوينتلي", example: "He didn't study; consequently, he failed.", exampleArabic: "لم يدرس؛ وبالتالي، رسب", category: "روابط" },
    { id: 3808, word: "thus", arabic: "وهكذا", pronunciation: "ذاس", example: "Thus, we see the result.", exampleArabic: "وهكذا، نرى النتيجة", category: "روابط" },
    { id: 3809, word: "hence", arabic: "من هنا", pronunciation: "هنس", example: "Hence, the conclusion.", exampleArabic: "من هنا، الاستنتاج", category: "روابط" },
    { id: 3810, word: "meanwhile", arabic: "في هذه الأثناء", pronunciation: "مينوايل", example: "Meanwhile, back at home...", exampleArabic: "في هذه الأثناء، في المنزل...", category: "روابط" },
    { id: 3811, word: "subsequently", arabic: "بعد ذلك", pronunciation: "سابسيكوينتلي", example: "Subsequently, things improved.", exampleArabic: "بعد ذلك، تحسنت الأمور", category: "روابط" },
    { id: 3812, word: "previously", arabic: "سابقاً", pronunciation: "بريفيسلي", example: "As mentioned previously.", exampleArabic: "كما ذكر سابقاً", category: "روابط" },
    { id: 3813, word: "subsequently", arabic: "لاحقاً", pronunciation: "سابسيكوينتلي", example: "Subsequently, he apologized.", exampleArabic: "لاحقاً، اعتذر", category: "روابط" },
    { id: 3814, word: "conversely", arabic: "على العكس", pronunciation: "كونفرسلي", example: "Conversely, it could be better.", exampleArabic: "على العكس، يمكن أن يكون أفضل", category: "روابط" },
    { id: 3815, word: "likewise", arabic: "وبالمثل", pronunciation: "ليكوايز", example: "Likewise, I agree.", exampleArabic: "وبالمثل، أوافق", category: "روابط" },
    { id: 3816, word: "similarly", arabic: "بشكل مماثل", pronunciation: "سيميلارلي", example: "Similarly, we can apply this.", exampleArabic: "بشكل مماثل، نطبق هذا", category: "روابط" },
    { id: 3817, word: "alternatively", arabic: "بدلاً من ذلك", pronunciation: "ألترناتيفلي", example: "Alternatively, we could wait.", exampleArabic: "بدلاً من ذلك، ننتظر", category: "روابط" },
    { id: 3818, word: "otherwise", arabic: "وإلا", pronunciation: "آذروايز", example: "Hurry up; otherwise, we'll be late.", exampleArabic: "أسرع؛ وإلا سنتأخر", category: "روابط" },
    { id: 3819, word: "whereas", arabic: "بينما", pronunciation: "ويرياس", example: "He is tall, whereas I am short.", exampleArabic: "هو طويل بينما أنا قصير", category: "روابط" },
    { id: 3820, word: "while", arabic: "بينما", pronunciation: "وايل", example: "While I agree, I have concerns.", exampleArabic: "بينما أوافق، لدي مخاوف", category: "روابط" },
];

// التحقق من التحميل
console.log('✅ advanced-data.js loaded with', ADVANCED_WORDS.length, 'words');
