// advanced-data.js - 500 كلمة للمستوى المتقدم
const ADVANCED_WORDS = [
    // تحيات ومجاملات متقدمة
    { id: 5001, word: "hospitality", arabic: "ضيافة", pronunciation: "هوسبيتاليتي", example: "Thank you for your hospitality.", exampleArabic: "شكراً لكرم ضيافتكم", category: "تحيات" },
    { id: 5002, word: "courtesy", arabic: "لباقة", pronunciation: "كورتيسي", example: "He treated us with courtesy.", exampleArabic: "عاملنا بلباقة", category: "تحيات" },
    { id: 5003, word: "etiquette", arabic: "آداب", pronunciation: "إيتيكيت", example: "Learn proper etiquette.", exampleArabic: "تعلم الآداب الصحيحة", category: "تحيات" },
    { id: 5004, word: "diplomacy", arabic: "دبلوماسية", pronunciation: "ديبلوماسي", example: "He handled it with diplomacy.", exampleArabic: "تعامل معها بدبلوماسية", category: "تحيات" },
    { id: 5005, word: "tact", arabic: "لباقة", pronunciation: "تاكت", example: "She has great tact.", exampleArabic: "لديها لباقة كبيرة", category: "تحيات" },
    { id: 5006, word: "grace", arabic: "رشاقة", pronunciation: "جرايس", example: "She accepted with grace.", exampleArabic: "قبلت برشاقة", category: "تحيات" },
    { id: 5007, word: "dignity", arabic: "كرامة", pronunciation: "ديجنتي", example: "Maintain your dignity.", exampleArabic: "حافظ على كرامتك", category: "تحيات" },
    { id: 5008, word: "respectful", arabic: "محترم", pronunciation: "ريسبكتفول", example: "Be respectful to others.", exampleArabic: "كن محترماً تجاه الآخرين", category: "تحيات" },
    { id: 5009, word: "cordial", arabic: "ودود", pronunciation: "كورديال", example: "A cordial welcome.", exampleArabic: "ترحيب ودود", category: "تحيات" },
    { id: 5010, word: "genuine", arabic: "صادق", pronunciation: "جينيوين", example: "Genuine smile.", exampleArabic: "ابتسامة صادقة", category: "تحيات" },
    { id: 5011, word: "sincere", arabic: "مخلص", pronunciation: "سينسير", example: "Sincere apologies.", exampleArabic: "اعتذار مخلص", category: "تحيات" },
    { id: 5012, word: "heartfelt", arabic: "صادق", pronunciation: "هارتفيلت", example: "Heartfelt thanks.", exampleArabic: "شكر صادق", category: "تحيات" },
    { id: 5013, word: "gracious", arabic: "كريم", pronunciation: "جرايشس", example: "Gracious host.", exampleArabic: "مضيف كريم", category: "تحيات" },
    { id: 5014, word: "humble", arabic: "متواضع", pronunciation: "هامبل", example: "He is humble.", exampleArabic: "هو متواضع", category: "تحيات" },
    { id: 5015, word: "modest", arabic: "متواضع", pronunciation: "موديست", example: "Modest behavior.", exampleArabic: "سلوك متواضع", category: "تحيات" },
    { id: 5016, word: "generous", arabic: "كريم", pronunciation: "جينيروس", example: "Generous offer.", exampleArabic: "عرض كريم", category: "تحيات" },
    { id: 5017, word: "benevolent", arabic: "خيري", pronunciation: "بينيفولنت", example: "Benevolent organization.", exampleArabic: "منظمة خيرية", category: "تحيات" },
    { id: 5018, word: "charitable", arabic: "خيري", pronunciation: "تشاريتابل", example: "Charitable work.", exampleArabic: "عمل خيري", category: "تحيات" },
    { id: 5019, word: "philanthropist", arabic: "محسن", pronunciation: "فيلانثروبيست", example: "He is a philanthropist.", exampleArabic: "هو محسن", category: "تحيات" },
    { id: 5020, word: "altruistic", arabic: "إيثاري", pronunciation: "ألترويستيك", example: "Altruistic behavior.", exampleArabic: "سلوك إيثاري", category: "تحيات" },
    { id: 5021, word: "selfless", arabic: "غير أناني", pronunciation: "سيلفليس", example: "Selfless service.", exampleArabic: "خدمة غير أنانية", category: "تحيات" },
    { id: 5022, word: "considerate", arabic: "مراعٍ", pronunciation: "كونسيديريت", example: "Considerate of others.", exampleArabic: "مراعٍ للآخرين", category: "تحيات" },
    { id: 5023, word: "thoughtful", arabic: "مراعٍ", pronunciation: "ثوتفول", example: "Thoughtful gesture.", exampleArabic: "بادرة مراعاة", category: "تحيات" },
    { id: 5024, word: "courteous", arabic: "مهذب", pronunciation: "كورتيس", example: "Courteous behavior.", exampleArabic: "سلوك مهذب", category: "تحيات" },
    { id: 5025, word: "polite", arabic: "مؤدب", pronunciation: "بولايت", example: "Polite response.", exampleArabic: "رد مؤدب", category: "تحيات" },

    // المنزل والأثاث
    { id: 5101, word: "interior", arabic: "داخلي", pronunciation: "إنتيريور", example: "Interior design.", exampleArabic: "تصميم داخلي", category: "منزل" },
    { id: 5102, word: "exterior", arabic: "خارجي", pronunciation: "إكستيريور", example: "Exterior paint.", exampleArabic: "دهان خارجي", category: "منزل" },
    { id: 5103, word: "architecture", arabic: "هندسة معمارية", pronunciation: "أركيتيكتشر", example: "Modern architecture.", exampleArabic: "هندسة معمارية حديثة", category: "منزل" },
    { id: 5104, word: "renovate", arabic: "يجدد", pronunciation: "رينوفيت", example: "We renovated the kitchen.", exampleArabic: "جددنا المطبخ", category: "منزل" },
    { id: 5105, word: "restore", arabic: "يستعيد", pronunciation: "ريستور", example: "Restore old furniture.", exampleArabic: "استعادة الأثاث القديم", category: "منزل" },
    { id: 5106, word: "remodel", arabic: "يعيد تشكيل", pronunciation: "ري مودل", example: "Remodel the bathroom.", exampleArabic: "أعد تشكيل الحمام", category: "منزل" },
    { id: 5107, word: "furnish", arabic: "يؤثث", pronunciation: "فيرنيش", example: "Furnish the apartment.", exampleArabic: "أثث الشقة", category: "منزل" },
    { id: 5108, word: "decor", arabic: "ديكور", pronunciation: "ديكور", example: "Beautiful decor.", exampleArabic: "ديكور جميل", category: "منزل" },
    { id: 5109, word: "aesthetic", arabic: "جمالي", pronunciation: "إيستثيتيك", example: "Aesthetic appeal.", exampleArabic: "جاذبية جمالية", category: "منزل" },
    { id: 5110, word: "ambiance", arabic: "أجواء", pronunciation: "أمبيانس", example: "Cozy ambiance.", exampleArabic: "أجواء مريحة", category: "منزل" },
    { id: 5111, word: "atmosphere", arabic: "جو", pronunciation: "أتوموسفير", example: "Warm atmosphere.", exampleArabic: "جو دافئ", category: "منزل" },
    { id: 5112, word: "ventilation", arabic: "تهوية", pronunciation: "فينتيليشن", example: "Good ventilation.", exampleArabic: "تهوية جيدة", category: "منزل" },
    { id: 5113, word: "insulation", arabic: "عزل", pronunciation: "إنسيوليشن", example: "Sound insulation.", exampleArabic: "عزل صوتي", category: "منزل" },
    { id: 5114, word: "plumbing", arabic: "سباكة", pronunciation: "بلومينغ", example: "Plumbing issues.", exampleArabic: "مشاكل سباكة", category: "منزل" },
    { id: 5115, word: "electrical", arabic: "كهربائي", pronunciation: "إليكتريكال", example: "Electrical wiring.", exampleArabic: "أسلاك كهربائية", category: "منزل" },
    { id: 5116, word: "maintenance", arabic: "صيانة", pronunciation: "مينتينانس", example: "Home maintenance.", exampleArabic: "صيانة المنزل", category: "منزل" },
    { id: 5117, word: "household", arabic: "منزلي", pronunciation: "هاوسهولد", example: "Household items.", exampleArabic: "أغراض منزلية", category: "منزل" },
    { id: 5118, word: "appliance", arabic: "جهاز", pronunciation: "أبلايانس", example: "Kitchen appliances.", exampleArabic: "أجهزة المطبخ", category: "منزل" },
    { id: 5119, word: "refrigerator", arabic: "ثلاجة", pronunciation: "ريفرجيريتور", example: "Keep food in refrigerator.", exampleArabic: "احفظ الطعام في الثلاجة", category: "منزل" },
    { id: 5120, word: "microwave", arabic: "ميكروويف", pronunciation: "مايكروويف", example: "Heat food in microwave.", exampleArabic: "سخن الطعام في الميكروويف", category: "منزل" },
    { id: 5121, word: "dishwasher", arabic: "غسالة أطباق", pronunciation: "ديشواشر", example: "Load the dishwasher.", exampleArabic: "حمّل غسالة الأطباق", category: "منزل" },
    { id: 5122, word: "washing machine", arabic: "غسالة", pronunciation: "واشينغ ماشين", example: "Put clothes in washing machine.", exampleArabic: "ضع الملابس في الغسالة", category: "منزل" },
    { id: 5123, word: "dryer", arabic: "نشافة", pronunciation: "دراير", example: "Clothes dryer.", exampleArabic: "نشافة ملابس", category: "منزل" },
    { id: 5124, word: "furniture", arabic: "أثاث", pronunciation: "فيرنيشور", example: "Modern furniture.", exampleArabic: "أثاث حديث", category: "منزل" },
    { id: 5125, word: "carpet", arabic: "سجاد", pronunciation: "كاربت", example: "Persian carpet.", exampleArabic: "سجاد فارسي", category: "منزل" },

    // العائلة والعلاقات
    { id: 5201, word: "ancestry", arabic: "نسب", pronunciation: "أنسيستري", example: "Trace your ancestry.", exampleArabic: "تتبع نسبك", category: "عائلة" },
    { id: 5202, word: "lineage", arabic: "سلالة", pronunciation: "لينيج", example: "Royal lineage.", exampleArabic: "سلالة ملكية", category: "عائلة" },
    { id: 5203, word: "descendant", arabic: "سليل", pronunciation: "ديسيندنت", example: "He is a descendant of kings.", exampleArabic: "هو سليل ملوك", category: "عائلة" },
    { id: 5204, word: "offspring", arabic: "نسل", pronunciation: "أوفسبرينغ", example: "Protect your offspring.", exampleArabic: "احمِ نسلك", category: "عائلة" },
    { id: 5205, word: "progeny", arabic: "ذرية", pronunciation: "بروجيني", example: "His progeny will inherit.", exampleArabic: "ذريته سترث", category: "عائلة" },
    { id: 5206, word: "kinship", arabic: "قرابة", pronunciation: "كينشيب", example: "Kinship ties are strong.", exampleArabic: "روابط القرابة قوية", category: "عائلة" },
    { id: 5207, word: "bond", arabic: "رابطة", pronunciation: "بوند", example: "Family bond.", exampleArabic: "رابطة عائلية", category: "عائلة" },
    { id: 5208, word: "affection", arabic: "عاطفة", pronunciation: "أفيكشن", example: "Show affection.", exampleArabic: "أظهر العاطفة", category: "عائلة" },
    { id: 5209, word: "attachment", arabic: "ارتباط", pronunciation: "أتاتشمنت", example: "Emotional attachment.", exampleArabic: "ارتباط عاطفي", category: "عائلة" },
    { id: 5210, word: "devotion", arabic: "تفانٍ", pronunciation: "ديفوشن", example: "Devotion to family.", exampleArabic: "تفانٍ للعائلة", category: "عائلة" },
    { id: 5211, word: "loyalty", arabic: "ولاء", pronunciation: "لويالتي", example: "Loyalty to family.", exampleArabic: "ولاء للعائلة", category: "عائلة" },
    { id: 5212, word: "fidelity", arabic: "إخلاص", pronunciation: "فيديلتي", example: "Fidelity in marriage.", exampleArabic: "إخلاص في الزواج", category: "عائلة" },
    { id: 5213, word: "commitment", arabic: "التزام", pronunciation: "كوميتمنت", example: "Family commitment.", exampleArabic: "التزام عائلي", category: "عائلة" },
    { id: 5214, word: "responsibility", arabic: "مسؤولية", pronunciation: "ريسبونسيبليتي", example: "Family responsibilities.", exampleArabic: "مسؤوليات عائلية", category: "عائلة" },
    { id: 5215, word: "obligation", arabic: "واجب", pronunciation: "أوبليجايشن", example: "Moral obligation.", exampleArabic: "واجب أخلاقي", category: "عائلة" },
    { id: 5216, word: "guardian", arabic: "وصي", pronunciation: "غارديان", example: "Legal guardian.", exampleArabic: "وصي قانوني", category: "عائلة" },
    { id: 5217, word: "custody", arabic: "حضانة", pronunciation: "كاستودي", example: "Child custody.", exampleArabic: "حضانة الأطفال", category: "عائلة" },
    { id: 5218, word: "upbringing", arabic: "تنشئة", pronunciation: "أببرينغينغ", example: "Good upbringing.", exampleArabic: "تنشئة جيدة", category: "عائلة" },
    { id: 5219, word: "nurture", arabic: "تربية", pronunciation: "نيرتشر", example: "Nurture your children.", exampleArabic: "ربِّ أطفالك", category: "عائلة" },
    { id: 5220, word: "cherish", arabic: "يعتز", pronunciation: "تشيريش", example: "Cherish your family.", exampleArabic: "اعتز بعائلتك", category: "عائلة" },
    { id: 5221, word: "treasure", arabic: "يكنز", pronunciation: "تريجر", example: "Treasure every moment.", exampleArabic: "كنز كل لحظة", category: "عائلة" },
    { id: 5222, word: "appreciate", arabic: "يقدر", pronunciation: "أبريشيت", example: "Appreciate your parents.", exampleArabic: "قدر والديك", category: "عائلة" },
    { id: 5223, word: "value", arabic: "يقدر", pronunciation: "فاليو", example: "Value your relationships.", exampleArabic: "قدر علاقاتك", category: "عائلة" },
    { id: 5224, word: "respect", arabic: "احترام", pronunciation: "ريسبكت", example: "Respect your elders.", exampleArabic: "احترم كبارك", category: "عائلة" },
    { id: 5225, word: "honor", arabic: "شرف", pronunciation: "أونر", example: "Family honor.", exampleArabic: "شرف العائلة", category: "عائلة" },

    // الطعام والشراب
    { id: 5301, word: "gourmet", arabic: "ذواقة", pronunciation: "غورميه", example: "Gourmet food.", exampleArabic: "طعام الذواقة", category: "طعام" },
    { id: 5302, word: "cuisine", arabic: "مطبخ", pronunciation: "كويسين", example: "French cuisine.", exampleArabic: "المطبخ الفرنسي", category: "طعام" },
    { id: 5303, word: "delicacy", arabic: "طعام شهي", pronunciation: "ديليكاسي", example: "Local delicacy.", exampleArabic: "طعام شهي محلي", category: "طعام" },
    { id: 5304, word: "appetizing", arabic: "فاتح للشهية", pronunciation: "أبيتايزينغ", example: "Appetizing smell.", exampleArabic: "رائحة تفتح الشهية", category: "طعام" },
    { id: 5305, word: "delectable", arabic: "لذيذ", pronunciation: "ديليكتابل", example: "Delectable dessert.", exampleArabic: "حلوى لذيذة", category: "طعام" },
    { id: 5306, word: "succulent", arabic: "شهي", pronunciation: "ساكيولنت", example: "Succulent meat.", exampleArabic: "لحم شهي", category: "طعام" },
    { id: 5307, word: "tender", arabic: "طري", pronunciation: "تندر", example: "Tender chicken.", exampleArabic: "دجاج طري", category: "طعام" },
    { id: 5308, word: "crispy", arabic: "مقرمش", pronunciation: "كريسبي", example: "Crispy fries.", exampleArabic: "بطاطس مقلية مقرمشة", category: "طعام" },
    { id: 5309, word: "creamy", arabic: "كريمي", pronunciation: "كريمي", example: "Creamy soup.", exampleArabic: "شوربة كريمية", category: "طعام" },
    { id: 5310, word: "spicy", arabic: "حار", pronunciation: "سبايسي", example: "Spicy curry.", exampleArabic: "كاري حار", category: "طعام" },
    { id: 5311, word: "mild", arabic: "معتدل", pronunciation: "مايلد", example: "Mild flavor.", exampleArabic: "نكهة معتدلة", category: "طعام" },
    { id: 5312, word: "tangy", arabic: "لاذع", pronunciation: "تانغي", example: "Tangy sauce.", exampleArabic: "صلصة لاذعة", category: "طعام" },
    { id: 5313, word: "zesty", arabic: "منعش", pronunciation: "زيستي", example: "Zesty flavor.", exampleArabic: "نكهة منعشة", category: "طعام" },
    { id: 5314, word: "aroma", arabic: "رائحة", pronunciation: "أروما", example: "Pleasant aroma.", exampleArabic: "رائحة لطيفة", category: "طعام" },
    { id: 5315, word: "scent", arabic: "عطر", pronunciation: "سينت", example: "Sweet scent.", exampleArabic: "عطر حلو", category: "طعام" },
    { id: 5316, word: "fragrance", arabic: "عبير", pronunciation: "فريغرانس", example: "Fragrance of spices.", exampleArabic: "عبير التوابل", category: "طعام" },
    { id: 5317, word: "seasoning", arabic: "توابل", pronunciation: "سيزونينغ", example: "Add seasoning.", exampleArabic: "أضف توابل", category: "طعام" },
    { id: 5318, word: "marinate", arabic: "ينقع", pronunciation: "مارينيت", example: "Marinate the meat.", exampleArabic: "انقع اللحم", category: "طعام" },
    { id: 5319, word: "grill", arabic: "يشوي", pronunciation: "غريل", example: "Grill the fish.", exampleArabic: "اشوِ السمك", category: "طعام" },
    { id: 5320, word: "roast", arabic: "يشوي", pronunciation: "روست", example: "Roast chicken.", exampleArabic: "دجاج مشوي", category: "طعام" },
    { id: 5321, word: "bake", arabic: "يخبز", pronunciation: "بيك", example: "Bake bread.", exampleArabic: "اخبز خبزاً", category: "طعام" },
    { id: 5322, word: "fry", arabic: "يقلي", pronunciation: "فراي", example: "Fry the eggs.", exampleArabic: "اقلِ البيض", category: "طعام" },
    { id: 5323, word: "boil", arabic: "يغلي", pronunciation: "بويل", example: "Boil the water.", exampleArabic: "اغلي الماء", category: "طعام" },
    { id: 5324, word: "steam", arabic: "يبخر", pronunciation: "ستيم", example: "Steam vegetables.", exampleArabic: "بخّر الخضار", category: "طعام" },
    { id: 5325, word: "simmer", arabic: "يترك على نار هادئة", pronunciation: "سيمر", example: "Simmer for 20 minutes.", exampleArabic: "اتركه على نار هادئة لمدة 20 دقيقة", category: "طعام" },

    // التسوق والمال
    { id: 5401, word: "investment", arabic: "استثمار", pronunciation: "إنفيستمينت", example: "Good investment.", exampleArabic: "استثمار جيد", category: "تسوق" },
    { id: 5402, word: "finance", arabic: "تمويل", pronunciation: "فاينانس", example: "Personal finance.", exampleArabic: "تمويل شخصي", category: "تسوق" },
    { id: 5403, word: "economy", arabic: "اقتصاد", pronunciation: "إيكونومي", example: "Global economy.", exampleArabic: "الاقتصاد العالمي", category: "تسوق" },
    { id: 5404, word: "budget", arabic: "ميزانية", pronunciation: "باجت", example: "Monthly budget.", exampleArabic: "ميزانية شهرية", category: "تسوق" },
    { id: 5405, word: "expense", arabic: "مصروف", pronunciation: "إكسبنس", example: "Track your expenses.", exampleArabic: "تتبع مصروفاتك", category: "تسوق" },
    { id: 5406, word: "income", arabic: "دخل", pronunciation: "إنكام", example: "Monthly income.", exampleArabic: "دخل شهري", category: "تسوق" },
    { id: 5407, word: "profit", arabic: "ربح", pronunciation: "بروفيت", example: "Net profit.", exampleArabic: "صافي الربح", category: "تسوق" },
    { id: 5408, word: "loss", arabic: "خسارة", pronunciation: "لوس", example: "Business loss.", exampleArabic: "خسارة تجارية", category: "تسوق" },
    { id: 5409, word: "revenue", arabic: "إيرادات", pronunciation: "ريفينيو", example: "Annual revenue.", exampleArabic: "إيرادات سنوية", category: "تسوق" },
    { id: 5410, word: "tax", arabic: "ضريبة", pronunciation: "تاكس", example: "Income tax.", exampleArabic: "ضريبة دخل", category: "تسوق" },
    { id: 5411, word: "invoice", arabic: "فاتورة", pronunciation: "إنفويس", example: "Pay the invoice.", exampleArabic: "ادفع الفاتورة", category: "تسوق" },
    { id: 5412, word: "receipt", arabic: "إيصال", pronunciation: "ريسيبت", example: "Keep the receipt.", exampleArabic: "احتفظ بالإيصال", category: "تسوق" },
    { id: 5413, word: "transaction", arabic: "معاملة", pronunciation: "ترانزاكشن", example: "Bank transaction.", exampleArabic: "معاملة بنكية", category: "تسوق" },
    { id: 5414, word: "withdrawal", arabic: "سحب", pronunciation: "ويدراول", example: "Cash withdrawal.", exampleArabic: "سحب نقدي", category: "تسوق" },
    { id: 5415, word: "deposit", arabic: "إيداع", pronunciation: "ديبوزيت", example: "Make a deposit.", exampleArabic: "قم بإيداع", category: "تسوق" },
    { id: 5416, word: "transfer", arabic: "تحويل", pronunciation: "ترانسفير", example: "Money transfer.", exampleArabic: "تحويل أموال", category: "تسوق" },
    { id: 5417, word: "balance", arabic: "رصيد", pronunciation: "بالانس", example: "Check your balance.", exampleArabic: "تحقق من رصيدك", category: "تسوق" },
    { id: 5418, word: "credit", arabic: "ائتمان", pronunciation: "كريديت", example: "Credit card.", exampleArabic: "بطاقة ائتمان", category: "تسوق" },
    { id: 5419, word: "debt", arabic: "دين", pronunciation: "ديت", example: "Pay off debt.", exampleArabic: "سدد الدين", category: "تسوق" },
    { id: 5420, word: "loan", arabic: "قرض", pronunciation: "لون", example: "Bank loan.", exampleArabic: "قرض بنكي", category: "تسوق" },
    { id: 5421, word: "mortgage", arabic: "رهن", pronunciation: "مورغيج", example: "Home mortgage.", exampleArabic: "رهن منزلي", category: "تسوق" },
    { id: 5422, word: "interest", arabic: "فائدة", pronunciation: "إنترست", example: "Interest rate.", exampleArabic: "معدل الفائدة", category: "تسوق" },
    { id: 5423, word: "currency", arabic: "عملة", pronunciation: "كارنسي", example: "Foreign currency.", exampleArabic: "عملة أجنبية", category: "تسوق" },
    { id: 5424, word: "exchange", arabic: "صرف", pronunciation: "إكس تشينج", example: "Currency exchange.", exampleArabic: "صرف عملات", category: "تسوق" },
    { id: 5425, word: "discount", arabic: "خصم", pronunciation: "ديسكاونت", example: "Get a discount.", exampleArabic: "احصل على خصم", category: "تسوق" },

    // المواصلات والسفر
    { id: 5501, word: "itinerary", arabic: "خط سير", pronunciation: "آيتنيراري", example: "Plan your itinerary.", exampleArabic: "خطط لخط سيرك", category: "مواصلات" },
    { id: 5502, word: "destination", arabic: "وجهة", pronunciation: "ديستينيشن", example: "Popular destination.", exampleArabic: "وجهة شعبية", category: "مواصلات" },
    { id: 5503, word: "accommodation", arabic: "إقامة", pronunciation: "أكوموديشن", example: "Find accommodation.", exampleArabic: "ابحث عن إقامة", category: "مواصلات" },
    { id: 5504, word: "reservation", arabic: "حجز", pronunciation: "ريزيرفيشن", example: "Hotel reservation.", exampleArabic: "حجز فندق", category: "مواصلات" },
    { id: 5505, word: "cancellation", arabic: "إلغاء", pronunciation: "كانسليشن", example: "Flight cancellation.", exampleArabic: "إلغاء رحلة", category: "مواصلات" },
    { id: 5506, word: "delay", arabic: "تأخير", pronunciation: "ديلاي", example: "Train delay.", exampleArabic: "تأخير قطار", category: "مواصلات" },
    { id: 5507, word: "layover", arabic: "توقف", pronunciation: "لاي أوفر", example: "Long layover.", exampleArabic: "توقف طويل", category: "مواصلات" },
    { id: 5508, word: "stopover", arabic: "توقف", pronunciation: "ستوب أوفر", example: "Stopover in Dubai.", exampleArabic: "توقف في دبي", category: "مواصلات" },
    { id: 5509, word: "commute", arabic: "تنقل", pronunciation: "كوميوت", example: "Daily commute.", exampleArabic: "تنقل يومي", category: "مواصلات" },
    { id: 5510, word: "traffic", arabic: "حركة مرور", pronunciation: "ترافيك", example: "Heavy traffic.", exampleArabic: "حركة مرور كثيفة", category: "مواصلات" },
    { id: 5511, word: "congestion", arabic: "ازدحام", pronunciation: "كونجستشن", example: "Traffic congestion.", exampleArabic: "ازدحام مروري", category: "مواصلات" },
    { id: 5512, word: "rush hour", arabic: "ساعة الذروة", pronunciation: "راش آور", example: "Avoid rush hour.", exampleArabic: "تجنب ساعة الذروة", category: "مواصلات" },
    { id: 5513, word: "peak time", arabic: "وقت الذروة", pronunciation: "بيك تايم", example: "Travel at peak time.", exampleArabic: "سفر في وقت الذروة", category: "مواصلات" },
    { id: 5514, word: "off-peak", arabic: "غير ذروة", pronunciation: "أوف بيك", example: "Off-peak hours.", exampleArabic: "ساعات غير الذروة", category: "مواصلات" },
    { id: 5515, word: "fare", arabic: "أجرة", pronunciation: "فير", example: "Bus fare.", exampleArabic: "أجرة حافلة", category: "مواصلات" },
    { id: 5516, word: "toll", arabic: "رسوم", pronunciation: "تول", example: "Road toll.", exampleArabic: "رسوم طريق", category: "مواصلات" },
    { id: 5517, word: "pass", arabic: "تصريح", pronunciation: "باس", example: "Monthly pass.", exampleArabic: "تصريح شهري", category: "مواصلات" },
    { id: 5518, word: "visa", arabic: "تأشيرة", pronunciation: "فيزا", example: "Tourist visa.", exampleArabic: "تأشيرة سياحية", category: "مواصلات" },
    { id: 5519, word: "passport", arabic: "جواز سفر", pronunciation: "باسبورت", example: "Valid passport.", exampleArabic: "جواز سفر ساري", category: "مواصلات" },
    { id: 5520, word: "customs", arabic: "جمارك", pronunciation: "كاستومز", example: "Customs declaration.", exampleArabic: "إقرار جمركي", category: "مواصلات" },
    { id: 5521, word: "immigration", arabic: "هجرة", pronunciation: "إميغريشن", example: "Immigration officer.", exampleArabic: "ضابط هجرة", category: "مواصلات" },
    { id: 5522, word: "boarding", arabic: "صعود", pronunciation: "بوردينغ", example: "Boarding pass.", exampleArabic: "بطاقة صعود", category: "مواصلات" },
    { id: 5523, word: "gate", arabic: "بوابة", pronunciation: "جيت", example: "Gate number.", exampleArabic: "رقم البوابة", category: "مواصلات" },
    { id: 5524, word: "terminal", arabic: "صالة", pronunciation: "تيرمينال", example: "Departure terminal.", exampleArabic: "صالة المغادرة", category: "مواصلات" },
    { id: 5525, word: "baggage", arabic: "أمتعة", pronunciation: "باجيدج", example: "Baggage claim.", exampleArabic: "استلام الأمتعة", category: "مواصلات" },

    // الصحة والجسم
    { id: 5601, word: "wellness", arabic: "عافية", pronunciation: "ويلنس", example: "Wellness center.", exampleArabic: "مركز عافية", category: "صحة" },
    { id: 5602, word: "hygiene", arabic: "نظافة", pronunciation: "هايجين", example: "Personal hygiene.", exampleArabic: "نظافة شخصية", category: "صحة" },
    { id: 5603, word: "sanitation", arabic: "صرف صحي", pronunciation: "سانيتيشن", example: "Proper sanitation.", exampleArabic: "صرف صحي مناسب", category: "صحة" },
    { id: 5604, word: "nutrition", arabic: "تغذية", pronunciation: "نيوتريشن", example: "Good nutrition.", exampleArabic: "تغذية جيدة", category: "صحة" },
    { id: 5605, word: "dietary", arabic: "غذائي", pronunciation: "دايتيري", example: "Dietary needs.", exampleArabic: "احتياجات غذائية", category: "صحة" },
    { id: 5606, word: "vitamin", arabic: "فيتامين", pronunciation: "فيتامين", example: "Vitamin deficiency.", exampleArabic: "نقص فيتامين", category: "صحة" },
    { id: 5607, word: "mineral", arabic: "معدن", pronunciation: "مينيرال", example: "Essential minerals.", exampleArabic: "معادن أساسية", category: "صحة" },
    { id: 5608, word: "protein", arabic: "بروتين", pronunciation: "بروتين", example: "Protein intake.", exampleArabic: "تناول البروتين", category: "صحة" },
    { id: 5609, word: "carbohydrate", arabic: "كربوهيدرات", pronunciation: "كاربوهيدريت", example: "Complex carbohydrates.", exampleArabic: "كربوهيدرات معقدة", category: "صحة" },
    { id: 5610, word: "calorie", arabic: "سعرة حرارية", pronunciation: "كالوري", example: "Low calorie.", exampleArabic: "قليل السعرات", category: "صحة" },
    { id: 5611, word: "metabolism", arabic: "أيض", pronunciation: "ميتابوليزم", example: "Fast metabolism.", exampleArabic: "أيض سريع", category: "صحة" },
    { id: 5612, word: "immunity", arabic: "مناعة", pronunciation: "إميونيتي", example: "Boost immunity.", exampleArabic: "عزز المناعة", category: "صحة" },
    { id: 5613, word: "infection", arabic: "عدوى", pronunciation: "إنفيكشن", example: "Prevent infection.", exampleArabic: "امنع العدوى", category: "صحة" },
    { id: 5614, word: "inflammation", arabic: "التهاب", pronunciation: "إنفلايميشن", example: "Reduce inflammation.", exampleArabic: "قلل الالتهاب", category: "صحة" },
    { id: 5615, word: "chronic", arabic: "مزمن", pronunciation: "كرونيك", example: "Chronic disease.", exampleArabic: "مرض مزمن", category: "صحة" },
    { id: 5616, word: "acute", arabic: "حاد", pronunciation: "أكيوت", example: "Acute pain.", exampleArabic: "ألم حاد", category: "صحة" },
    { id: 5617, word: "diagnosis", arabic: "تشخيص", pronunciation: "دايغ نوسيس", example: "Early diagnosis.", exampleArabic: "تشخيص مبكر", category: "صحة" },
    { id: 5618, word: "prognosis", arabic: "توقعات", pronunciation: "بروغنوسيس", example: "Good prognosis.", exampleArabic: "توقعات جيدة", category: "صحة" },
    { id: 5619, word: "therapy", arabic: "علاج", pronunciation: "ثيرابي", example: "Physical therapy.", exampleArabic: "علاج طبيعي", category: "صحة" },
    { id: 5620, word: "rehabilitation", arabic: "تأهيل", pronunciation: "ريهابيليتيشن", example: "Rehabilitation center.", exampleArabic: "مركز تأهيل", category: "صحة" },
    { id: 5621, word: "surgery", arabic: "جراحة", pronunciation: "سيرجري", example: "Minor surgery.", exampleArabic: "جراحة بسيطة", category: "صحة" },
    { id: 5622, word: "transplant", arabic: "زرع", pronunciation: "ترانسبلانت", example: "Organ transplant.", exampleArabic: "زرع أعضاء", category: "صحة" },
    { id: 5623, word: "medicine", arabic: "دواء", pronunciation: "ميديسين", example: "Take medicine.", exampleArabic: "تناول الدواء", category: "صحة" },
    { id: 5624, word: "prescription", arabic: "روشتة", pronunciation: "بريسكريبشن", example: "Doctor's prescription.", exampleArabic: "روشتة الطبيب", category: "صحة" },
    { id: 5625, word: "treatment", arabic: "علاج", pronunciation: "تريتمنت", example: "Effective treatment.", exampleArabic: "علاج فعال", category: "صحة" },

    // العمل والوظائف
    { id: 5701, word: "corporate", arabic: "شركات", pronunciation: "كوربوريت", example: "Corporate world.", exampleArabic: "عالم الشركات", category: "عمل" },
    { id: 5702, word: "executive", arabic: "تنفيذي", pronunciation: "إكزكيوتيف", example: "Executive position.", exampleArabic: "منصب تنفيذي", category: "عمل" },
    { id: 5703, word: "management", arabic: "إدارة", pronunciation: "مانيدجمنت", example: "Management team.", exampleArabic: "فريق إدارة", category: "عمل" },
    { id: 5704, word: "leadership", arabic: "قيادة", pronunciation: "ليدرشيب", example: "Leadership skills.", exampleArabic: "مهارات قيادية", category: "عمل" },
    { id: 5705, word: "supervision", arabic: "إشراف", pronunciation: "سوبرفيجن", example: "Under supervision.", exampleArabic: "تحت الإشراف", category: "عمل" },
    { id: 5706, word: "coordination", arabic: "تنسيق", pronunciation: "كوردينيشن", example: "Project coordination.", exampleArabic: "تنسيق مشروع", category: "عمل" },
    { id: 5707, word: "collaboration", arabic: "تعاون", pronunciation: "كولابورايشن", example: "Team collaboration.", exampleArabic: "تعاون جماعي", category: "عمل" },
    { id: 5708, word: "partnership", arabic: "شراكة", pronunciation: "بارتنرشيب", example: "Business partnership.", exampleArabic: "شراكة تجارية", category: "عمل" },
    { id: 5709, word: "entrepreneur", arabic: "رائد أعمال", pronunciation: "أنتربرينور", example: "Successful entrepreneur.", exampleArabic: "رائد أعمال ناجح", category: "عمل" },
    { id: 5710, word: "startup", arabic: "شركة ناشئة", pronunciation: "ستارت أب", example: "Tech startup.", exampleArabic: "شركة ناشئة تقنية", category: "عمل" },
    { id: 5711, word: "freelance", arabic: "حر", pronunciation: "فري لانس", example: "Freelance work.", exampleArabic: "عمل حر", category: "عمل" },
    { id: 5712, word: "remote", arabic: "عن بعد", pronunciation: "ريموت", example: "Remote work.", exampleArabic: "عمل عن بعد", category: "عمل" },
    { id: 5713, word: "deadline", arabic: "موعد نهائي", pronunciation: "ديدلاين", example: "Meet the deadline.", exampleArabic: "التزم بالموعد النهائي", category: "عمل" },
    { id: 5714, word: "workload", arabic: "عبء عمل", pronunciation: "وركلود", example: "Heavy workload.", exampleArabic: "عبء عمل ثقيل", category: "عمل" },
    { id: 5715, word: "overtime", arabic: "عمل إضافي", pronunciation: "أوفرتايم", example: "Work overtime.", exampleArabic: "اعمل عملاً إضافياً", category: "عمل" },
    { id: 5716, word: "promotion", arabic: "ترقية", pronunciation: "بروموشن", example: "Get a promotion.", exampleArabic: "احصل على ترقية", category: "عمل" },
    { id: 5717, word: "transfer", arabic: "نقل", pronunciation: "ترانسفير", example: "Job transfer.", exampleArabic: "نقل وظيفي", category: "عمل" },
    { id: 5718, word: "resignation", arabic: "استقالة", pronunciation: "ريزيجنيشن", example: "Submit resignation.", exampleArabic: "قدم استقالة", category: "عمل" },
    { id: 5719, word: "retirement", arabic: "تقاعد", pronunciation: "ريتايرمنت", example: "Retirement plan.", exampleArabic: "خطة تقاعد", category: "عمل" },
    { id: 5720, word: "pension", arabic: "معاش", pronunciation: "بينشن", example: "Pension fund.", exampleArabic: "صندوق معاشات", category: "عمل" },
    { id: 5721, word: "benefits", arabic: "مزايا", pronunciation: "بينيفيتس", example: "Employee benefits.", exampleArabic: "مزايا الموظفين", category: "عمل" },
    { id: 5722, word: "insurance", arabic: "تأمين", pronunciation: "إنشورانس", example: "Health insurance.", exampleArabic: "تأمين صحي", category: "عمل" },
    { id: 5723, word: "salary", arabic: "راتب", pronunciation: "سالاري", example: "Monthly salary.", exampleArabic: "راتب شهري", category: "عمل" },
    { id: 5724, word: "wage", arabic: "أجر", pronunciation: "ويج", example: "Hourly wage.", exampleArabic: "أجر بالساعة", category: "عمل" },
    { id: 5725, word: "bonus", arabic: "مكافأة", pronunciation: "بونس", example: "Annual bonus.", exampleArabic: "مكافأة سنوية", category: "عمل" },

    // التعليم والدراسة
    { id: 5801, word: "academic", arabic: "أكاديمي", pronunciation: "أكاديميك", example: "Academic year.", exampleArabic: "سنة أكاديمية", category: "تعليم" },
    { id: 5802, word: "curriculum", arabic: "منهج", pronunciation: "كيريكيولوم", example: "School curriculum.", exampleArabic: "منهج مدرسي", category: "تعليم" },
    { id: 5803, word: "syllabus", arabic: "مقرر", pronunciation: "سيلابس", example: "Course syllabus.", exampleArabic: "مقرر الدورة", category: "تعليم" },
    { id: 5804, word: "lecture", arabic: "محاضرة", pronunciation: "ليكشر", example: "Attend lecture.", exampleArabic: "احضر محاضرة", category: "تعليم" },
    { id: 5805, word: "seminar", arabic: "ندوة", pronunciation: "سيمينار", example: "Research seminar.", exampleArabic: "ندوة بحثية", category: "تعليم" },
    { id: 5806, word: "workshop", arabic: "ورشة عمل", pronunciation: "وركشوب", example: "Training workshop.", exampleArabic: "ورشة تدريبية", category: "تعليم" },
    { id: 5807, word: "tutorial", arabic: "درس خصوصي", pronunciation: "توتوريال", example: "Online tutorial.", exampleArabic: "درس خصوصي عبر الإنترنت", category: "تعليم" },
    { id: 5808, word: "assignment", arabic: "واجب", pronunciation: "أسانمنت", example: "Complete assignment.", exampleArabic: "أكمل الواجب", category: "تعليم" },
    { id: 5809, word: "dissertation", arabic: "أطروحة", pronunciation: "ديسيرتيشن", example: "Write dissertation.", exampleArabic: "اكتب أطروحة", category: "تعليم" },
    { id: 5810, word: "thesis", arabic: "رسالة", pronunciation: "ثيسيس", example: "Master's thesis.", exampleArabic: "رسالة ماجستير", category: "تعليم" },
    { id: 5811, word: "research", arabic: "بحث", pronunciation: "ريسرتش", example: "Conduct research.", exampleArabic: "قم ببحث", category: "تعليم" },
    { id: 5812, word: "analysis", arabic: "تحليل", pronunciation: "أناليسيس", example: "Data analysis.", exampleArabic: "تحليل بيانات", category: "تعليم" },
    { id: 5813, word: "evaluation", arabic: "تقييم", pronunciation: "إيفاليواشن", example: "Course evaluation.", exampleArabic: "تقييم الدورة", category: "تعليم" },
    { id: 5814, word: "assessment", arabic: "تقدير", pronunciation: "أسيسمينت", example: "Student assessment.", exampleArabic: "تقدير الطالب", category: "تعليم" },
    { id: 5815, word: "examination", arabic: "امتحان", pronunciation: "إكزامينيشن", example: "Final examination.", exampleArabic: "امتحان نهائي", category: "تعليم" },
    { id: 5816, word: "qualification", arabic: "مؤهل", pronunciation: "كوالي فيكايشن", example: "Professional qualification.", exampleArabic: "مؤهل مهني", category: "تعليم" },
    { id: 5817, word: "certification", arabic: "شهادة", pronunciation: "سيرتيفيكيشن", example: "Get certification.", exampleArabic: "احصل على شهادة", category: "تعليم" },
    { id: 5818, word: "accreditation", arabic: "اعتماد", pronunciation: "أكريديتيشن", example: "Program accreditation.", exampleArabic: "اعتماد البرنامج", category: "تعليم" },
    { id: 5819, word: "tuition", arabic: "رسوم", pronunciation: "تويشن", example: "Tuition fees.", exampleArabic: "رسوم دراسية", category: "تعليم" },
    { id: 5820, word: "scholarship", arabic: "منحة", pronunciation: "سكولارشيب", example: "Win a scholarship.", exampleArabic: "احصل على منحة", category: "تعليم" },
    { id: 5821, word: "fellowship", arabic: "زمالة", pronunciation: "فيلوشيب", example: "Research fellowship.", exampleArabic: "زمالة بحثية", category: "تعليم" },
    { id: 5822, word: "internship", arabic: "تدريب", pronunciation: "إنترنشيب", example: "Summer internship.", exampleArabic: "تدريب صيفي", category: "تعليم" },
    { id: 5823, word: "apprenticeship", arabic: "تدريب مهني", pronunciation: "أبرينتيسشيب", example: "Apprenticeship program.", exampleArabic: "برنامج تدريب مهني", category: "تعليم" },
    { id: 5824, word: "degree", arabic: "درجة", pronunciation: "ديغري", example: "University degree.", exampleArabic: "درجة جامعية", category: "تعليم" },
    { id: 5825, word: "diploma", arabic: "دبلوم", pronunciation: "ديبلوما", example: "Diploma course.", exampleArabic: "دورة دبلوم", category: "تعليم" },

    // الوقت والتاريخ
    { id: 5901, word: "chronological", arabic: "تسلسل زمني", pronunciation: "كرونولوجيكال", example: "Chronological order.", exampleArabic: "ترتيب زمني", category: "وقت" },
    { id: 5902, word: "simultaneous", arabic: "متزامن", pronunciation: "سيمولتينيوس", example: "Simultaneous events.", exampleArabic: "أحداث متزامنة", category: "وقت" },
    { id: 5903, word: "concurrent", arabic: "متواز", pronunciation: "كونكارنت", example: "Concurrent sessions.", exampleArabic: "جلسات متوازية", category: "وقت" },
    { id: 5904, word: "subsequent", arabic: "لاحق", pronunciation: "سابسيكوينت", example: "Subsequent events.", exampleArabic: "أحداث لاحقة", category: "وقت" },
    { id: 5905, word: "previous", arabic: "سابق", pronunciation: "بريفيس", example: "Previous meeting.", exampleArabic: "اجتماع سابق", category: "وقت" },
    { id: 5906, word: "prior", arabic: "سابق", pronunciation: "برايور", example: "Prior experience.", exampleArabic: "خبرة سابقة", category: "وقت" },
    { id: 5907, word: "subsequent", arabic: "لاحق", pronunciation: "سابسيكوينت", example: "Subsequent chapters.", exampleArabic: "فصول لاحقة", category: "وقت" },
    { id: 5908, word: "contemporary", arabic: "معاصر", pronunciation: "كونتمبوراري", example: "Contemporary art.", exampleArabic: "فن معاصر", category: "وقت" },
    { id: 5909, word: "modern", arabic: "حديث", pronunciation: "مودرن", example: "Modern times.", exampleArabic: "عصور حديثة", category: "وقت" },
    { id: 5910, word: "ancient", arabic: "قديم", pronunciation: "إينشنت", example: "Ancient history.", exampleArabic: "تاريخ قديم", category: "وقت" },
    { id: 5911, word: "medieval", arabic: "عصور وسطى", pronunciation: "ميديفال", example: "Medieval period.", exampleArabic: "فترة العصور الوسطى", category: "وقت" },
    { id: 5912, word: "era", arabic: "عصر", pronunciation: "إيرا", example: "Victorian era.", exampleArabic: "العصر الفيكتوري", category: "وقت" },
    { id: 5913, word: "epoch", arabic: "حقبة", pronunciation: "إيبوك", example: "Geological epoch.", exampleArabic: "حقبة جيولوجية", category: "وقت" },
    { id: 5914, word: "millennium", arabic: "ألفية", pronunciation: "ميلينيوم", example: "New millennium.", exampleArabic: "ألفية جديدة", category: "وقت" },
    { id: 5915, word: "century", arabic: "قرن", pronunciation: "سينتشري", example: "21st century.", exampleArabic: "القرن 21", category: "وقت" },
    { id: 5916, word: "decade", arabic: "عقد", pronunciation: "ديكيد", example: "This decade.", exampleArabic: "هذا العقد", category: "وقت" },
    { id: 5917, word: "annual", arabic: "سنوي", pronunciation: "أنوال", example: "Annual event.", exampleArabic: "حدث سنوي", category: "وقت" },
    { id: 5918, word: "biennial", arabic: "كل سنتين", pronunciation: "باي إنيال", example: "Biennial conference.", exampleArabic: "مؤتمر كل سنتين", category: "وقت" },
    { id: 5919, word: "quarterly", arabic: "ربع سنوي", pronunciation: "كوارترلي", example: "Quarterly report.", exampleArabic: "تقرير ربع سنوي", category: "وقت" },
    { id: 5920, word: "monthly", arabic: "شهري", pronunciation: "مانثلي", example: "Monthly meeting.", exampleArabic: "اجتماع شهري", category: "وقت" },
    { id: 5921, word: "weekly", arabic: "أسبوعي", pronunciation: "ويكلي", example: "Weekly schedule.", exampleArabic: "جدول أسبوعي", category: "وقت" },
    { id: 5922, word: "daily", arabic: "يومي", pronunciation: "دايلي", example: "Daily routine.", exampleArabic: "روتين يومي", category: "وقت" },
    { id: 5923, word: "hourly", arabic: "كل ساعة", pronunciation: "أورلي", example: "Hourly rate.", exampleArabic: "سعر بالساعة", category: "وقت" },
    { id: 5924, word: "nightly", arabic: "ليلي", pronunciation: "نايتلي", example: "Nightly news.", exampleArabic: "أخبار ليلية", category: "وقت" },
    { id: 5925, word: "daylight", arabic: "ضوء النهار", pronunciation: "داي لايت", example: "Daylight saving.", exampleArabic: "التوقيت الصيفي", category: "وقت" },

    // الملابس والموضة
    { id: 6001, word: "fashionable", arabic: "أنيق", pronunciation: "فاشونابل", example: "Fashionable clothes.", exampleArabic: "ملابس أنيقة", category: "ملابس" },
    { id: 6002, word: "stylish", arabic: "أنيق", pronunciation: "ستايليش", example: "Stylish outfit.", exampleArabic: "زي أنيق", category: "ملابس" },
    { id: 6003, word: "trendy", arabic: "رائج", pronunciation: "تريندي", example: "Trendy fashion.", exampleArabic: "موضة رائجة", category: "ملابس" },
    { id: 6004, word: "vintage", arabic: "عتيق", pronunciation: "فينتج", example: "Vintage clothing.", exampleArabic: "ملابس عتيقة", category: "ملابس" },
    { id: 6005, word: "retro", arabic: "رجعي", pronunciation: "ريترو", example: "Retro style.", exampleArabic: "أسلوب رجعي", category: "ملابس" },
    { id: 6006, word: "classic", arabic: "كلاسيكي", pronunciation: "كلاسيك", example: "Classic design.", exampleArabic: "تصميم كلاسيكي", category: "ملابس" },
    { id: 6007, word: "elegant", arabic: "أنيق", pronunciation: "إليجنت", example: "Elegant dress.", exampleArabic: "فستان أنيق", category: "ملابس" },
    { id: 6008, word: "sophisticated", arabic: "راقٍ", pronunciation: "سوفيس تيكيتد", example: "Sophisticated look.", exampleArabic: "إطلالة راقية", category: "ملابس" },
    { id: 6009, word: "chic", arabic: "أنيق", pronunciation: "شيك", example: "Chic outfit.", exampleArabic: "زي أنيق", category: "ملابس" },
    { id: 6010, word: "casual", arabic: "غير رسمي", pronunciation: "كاجوال", example: "Casual wear.", exampleArabic: "ملابس غير رسمية", category: "ملابس" },
    { id: 6011, word: "formal", arabic: "رسمي", pronunciation: "فورمال", example: "Formal attire.", exampleArabic: "ملابس رسمية", category: "ملابس" },
    { id: 6012, word: "business", arabic: "أعمال", pronunciation: "بيزنيس", example: "Business suit.", exampleArabic: "بدلة أعمال", category: "ملابس" },
    { id: 6013, word: "sportswear", arabic: "ملابس رياضية", pronunciation: "سبورتس وير", example: "Comfortable sportswear.", exampleArabic: "ملابس رياضية مريحة", category: "ملابس" },
    { id: 6014, word: "leisurewear", arabic: "ملابس ترفيه", pronunciation: "ليجر وير", example: "Casual leisurewear.", exampleArabic: "ملابس ترفيه غير رسمية", category: "ملابس" },
    { id: 6015, word: "accessory", arabic: "إكسسوار", pronunciation: "أكسيسوري", example: "Fashion accessory.", exampleArabic: "إكسسوار موضة", category: "ملابس" },
    { id: 6016, word: "jewelry", arabic: "مجوهرات", pronunciation: "جولري", example: "Fine jewelry.", exampleArabic: "مجوهرات ثمينة", category: "ملابس" },
    { id: 6017, word: "necklace", arabic: "قلادة", pronunciation: "نيكليس", example: "Pearl necklace.", exampleArabic: "قلادة لؤلؤ", category: "ملابس" },
    { id: 6018, word: "bracelet", arabic: "سوار", pronunciation: "بريسلت", example: "Gold bracelet.", exampleArabic: "سوار ذهب", category: "ملابس" },
    { id: 6019, word: "earrings", arabic: "أقراط", pronunciation: "إيرينغز", example: "Diamond earrings.", exampleArabic: "أقراط ألماس", category: "ملابس" },
    { id: 6020, word: "ring", arabic: "خاتم", pronunciation: "رينغ", example: "Wedding ring.", exampleArabic: "خاتم زواج", category: "ملابس" },
    { id: 6021, word: "watch", arabic: "ساعة", pronunciation: "واتش", example: "Luxury watch.", exampleArabic: "ساعة فاخرة", category: "ملابس" },
    { id: 6022, word: "belt", arabic: "حزام", pronunciation: "بيلت", example: "Leather belt.", exampleArabic: "حزام جلد", category: "ملابس" },
    { id: 6023, word: "scarf", arabic: "وشاح", pronunciation: "سكارف", example: "Silk scarf.", exampleArabic: "وشاح حرير", category: "ملابس" },
    { id: 6024, word: "hat", arabic: "قبعة", pronunciation: "هات", example: "Summer hat.", exampleArabic: "قبعة صيفية", category: "ملابس" },
    { id: 6025, word: "gloves", arabic: "قفازات", pronunciation: "غلوفز", example: "Leather gloves.", exampleArabic: "قفازات جلدية", category: "ملابس" },

    // الاتجاهات والأماكن
    { id: 6101, word: "geographical", arabic: "جغرافي", pronunciation: "جيوغرافيكال", example: "Geographical location.", exampleArabic: "موقع جغرافي", category: "اتجاهات" },
    { id: 6102, word: "topographical", arabic: "طبوغرافي", pronunciation: "توبوغرافيكال", example: "Topographical map.", exampleArabic: "خريطة طبوغرافية", category: "اتجاهات" },
    { id: 6103, word: "urban", arabic: "حضري", pronunciation: "أوربان", example: "Urban area.", exampleArabic: "منطقة حضرية", category: "اتجاهات" },
    { id: 6104, word: "rural", arabic: "ريفي", pronunciation: "رورال", example: "Rural area.", exampleArabic: "منطقة ريفية", category: "اتجاهات" },
    { id: 6105, word: "suburban", arabic: "ضواحي", pronunciation: "سابوربان", example: "Suburban neighborhood.", exampleArabic: "حي ضواحي", category: "اتجاهات" },
    { id: 6106, word: "metropolitan", arabic: "عاصمة", pronunciation: "ميتروبوليتان", example: "Metropolitan area.", exampleArabic: "منطقة العاصمة", category: "اتجاهات" },
    { id: 6107, word: "downtown", arabic: "وسط المدينة", pronunciation: "داون تاون", example: "Downtown district.", exampleArabic: "منطقة وسط المدينة", category: "اتجاهات" },
    { id: 6108, word: "uptown", arabic: "أعلى المدينة", pronunciation: "أب تاون", example: "Uptown area.", exampleArabic: "منطقة أعلى المدينة", category: "اتجاهات" },
    { id: 6109, word: "coastal", arabic: "ساحلي", pronunciation: "كوستال", example: "Coastal city.", exampleArabic: "مدينة ساحلية", category: "اتجاهات" },
    { id: 6110, word: "inland", arabic: "داخلي", pronunciation: "إنلاند", example: "Inland region.", exampleArabic: "منطقة داخلية", category: "اتجاهات" },
    { id: 6111, word: "border", arabic: "حدود", pronunciation: "بوردر", example: "Border crossing.", exampleArabic: "عبور حدود", category: "اتجاهات" },
    { id: 6112, word: "boundary", arabic: "حد فاصل", pronunciation: "باوندري", example: "Property boundary.", exampleArabic: "حدود الملكية", category: "اتجاهات" },
    { id: 6113, word: "frontier", arabic: "حدود", pronunciation: "فرونتير", example: "Western frontier.", exampleArabic: "الحدود الغربية", category: "اتجاهات" },
    { id: 6114, word: "landmark", arabic: "معلم", pronunciation: "لاند مارك", example: "Famous landmark.", exampleArabic: "معلم مشهور", category: "اتجاهات" },
    { id: 6115, word: "monument", arabic: "نصب تذكاري", pronunciation: "مونيومنت", example: "Historical monument.", exampleArabic: "نصب تذكاري تاريخي", category: "اتجاهات" },
    { id: 6116, word: "memorial", arabic: "نصب", pronunciation: "ميموريال", example: "War memorial.", exampleArabic: "نصب الحرب", category: "اتجاهات" },
    { id: 6117, word: "shrine", arabic: "ضريح", pronunciation: "شراين", example: "Sacred shrine.", exampleArabic: "ضريح مقدس", category: "اتجاهات" },
    { id: 6118, word: "temple", arabic: "معبد", pronunciation: "تيمبل", example: "Ancient temple.", exampleArabic: "معبد قديم", category: "اتجاهات" },
    { id: 6119, word: "cathedral", arabic: "كاتدرائية", pronunciation: "كاثيدرال", example: "St. Paul's Cathedral.", exampleArabic: "كاتدرائية القديس بولس", category: "اتجاهات" },
    { id: 6120, word: "mosque", arabic: "مسجد", pronunciation: "موسك", example: "Beautiful mosque.", exampleArabic: "مسجد جميل", category: "اتجاهات" },
    { id: 6121, word: "church", arabic: "كنيسة", pronunciation: "تشيرتش", example: "Old church.", exampleArabic: "كنيسة قديمة", category: "اتجاهات" },
    { id: 6122, word: "synagogue", arabic: "كنيس", pronunciation: "سيناجوج", example: "Historic synagogue.", exampleArabic: "كنيس تاريخي", category: "اتجاهات" },
    { id: 6123, word: "square", arabic: "ميدان", pronunciation: "سكوير", example: "Town square.", exampleArabic: "ميدان المدينة", category: "اتجاهات" },
    { id: 6124, word: "avenue", arabic: "جادة", pronunciation: "أفنيو", example: "Fifth Avenue.", exampleArabic: "الجادة الخامسة", category: "اتجاهات" },
    { id: 6125, word: "boulevard", arabic: "شارع", pronunciation: "بوليفارد", example: "Sunset Boulevard.", exampleArabic: "شارع الغروب", category: "اتجاهات" },

    // المشاعر والأحاسيس
    { id: 6201, word: "compassion", arabic: "تعاطف", pronunciation: "كومباشن", example: "Show compassion.", exampleArabic: "أظهر تعاطفاً", category: "مشاعر" },
    { id: 6202, word: "empathy", arabic: "تفهم", pronunciation: "إمباثي", example: "Feel empathy.", exampleArabic: "اشعر بالتفهم", category: "مشاعر" },
    { id: 6203, word: "sympathy", arabic: "تعاطف", pronunciation: "سيمباثي", example: "Express sympathy.", exampleArabic: "أعرب عن تعاطفك", category: "مشاعر" },
    { id: 6204, word: "affection", arabic: "عاطفة", pronunciation: "أفيكشن", example: "Deep affection.", exampleArabic: "عاطفة عميقة", category: "مشاعر" },
    { id: 6205, word: "tenderness", arabic: "حنو", pronunciation: "تيندرنس", example: "Show tenderness.", exampleArabic: "أظهر حنواً", category: "مشاعر" },
    { id: 6206, word: "warmth", arabic: "دفء", pronunciation: "وورمث", example: "Warmth of heart.", exampleArabic: "دفء القلب", category: "مشاعر" },
    { id: 6207, word: "intimacy", arabic: "حميمية", pronunciation: "إنتيماسي", example: "Emotional intimacy.", exampleArabic: "حميمية عاطفية", category: "مشاعر" },
    { id: 6208, word: "passion", arabic: "شغف", pronunciation: "باشن", example: "Passion for work.", exampleArabic: "شغف بالعمل", category: "مشاعر" },
    { id: 6209, word: "enthusiasm", arabic: "حماس", pronunciation: "إنثوزيازم", example: "Great enthusiasm.", exampleArabic: "حماس كبير", category: "مشاعر" },
    { id: 6210, word: "zeal", arabic: "غيرة", pronunciation: "زيل", example: "Religious zeal.", exampleArabic: "غيرة دينية", category: "مشاعر" },
    { id: 6211, word: "ardor", arabic: "حرارة", pronunciation: "آردور", example: "Ardor for justice.", exampleArabic: "حرارة للعدالة", category: "مشاعر" },
    { id: 6212, word: "fervor", arabic: "حماسة", pronunciation: "فيرفور", example: "Patriotic fervor.", exampleArabic: "حماسة وطنية", category: "مشاعر" },
    { id: 6213, word: "melancholy", arabic: "كآبة", pronunciation: "ميلانكولي", example: "Feel melancholy.", exampleArabic: "اشعر بالكآبة", category: "مشاعر" },
    { id: 6214, word: "nostalgia", arabic: "حنين", pronunciation: "نوستالجيا", example: "Nostalgia for past.", exampleArabic: "حنين للماضي", category: "مشاعر" },
    { id: 6215, word: "longing", arabic: "شوق", pronunciation: "لونغينغ", example: "Longing for home.", exampleArabic: "شوق للوطن", category: "مشاعر" },
    { id: 6216, word: "yearning", arabic: "توق", pronunciation: "يرنينغ", example: "Yearning for peace.", exampleArabic: "توق للسلام", category: "مشاعر" },
    { id: 6217, word: "desire", arabic: "رغبة", pronunciation: "ديزاير", example: "Strong desire.", exampleArabic: "رغبة قوية", category: "مشاعر" },
    { id: 6218, word: "aspiration", arabic: "طموح", pronunciation: "أسبرايرشن", example: "Career aspirations.", exampleArabic: "طموحات مهنية", category: "مشاعر" },
    { id: 6219, word: "ambition", arabic: "طموح", pronunciation: "أمبيشن", example: "High ambitions.", exampleArabic: "طموحات عالية", category: "مشاعر" },
    { id: 6220, word: "contentment", arabic: "قناعة", pronunciation: "كونتينتمنت", example: "Feel contentment.", exampleArabic: "اشعر بالقناعة", category: "مشاعر" },
    { id: 6221, word: "satisfaction", arabic: "رضا", pronunciation: "ساتيسفاكشن", example: "Job satisfaction.", exampleArabic: "رضا وظيفي", category: "مشاعر" },
    { id: 6222, word: "fulfillment", arabic: "إشباع", pronunciation: "فولفيلمنت", example: "Personal fulfillment.", exampleArabic: "إشباع شخصي", category: "مشاعر" },
    { id: 6223, word: "gratitude", arabic: "امتنان", pronunciation: "غراتيتيود", example: "Express gratitude.", exampleArabic: "أعرب عن امتنانك", category: "مشاعر" },
    { id: 6224, word: "appreciation", arabic: "تقدير", pronunciation: "أبريشييشن", example: "Show appreciation.", exampleArabic: "أظهر التقدير", category: "مشاعر" },
    { id: 6225, word: "admiration", arabic: "إعجاب", pronunciation: "أدميريشن", example: "Great admiration.", exampleArabic: "إعجاب كبير", category: "مشاعر" },

    // الأفعال اليومية
    { id: 6301, word: "accomplish", arabic: "ينجز", pronunciation: "أكامبليش", example: "Accomplish goals.", exampleArabic: "أنجز الأهداف", category: "أفعال" },
    { id: 6302, word: "achieve", arabic: "يحقق", pronunciation: "أتشيف", example: "Achieve success.", exampleArabic: "حقق نجاحاً", category: "أفعال" },
    { id: 6303, word: "attain", arabic: "ينال", pronunciation: "أتين", example: "Attain knowledge.", exampleArabic: "ينال المعرفة", category: "أفعال" },
    { id: 6304, word: "pursue", arabic: "يسعى", pronunciation: "بيرسو", example: "Pursue dreams.", exampleArabic: "اسعَ لتحقيق الأحلام", category: "أفعال" },
    { id: 6305, word: "strive", arabic: "يكافح", pronunciation: "سترايف", example: "Strive for excellence.", exampleArabic: "كافح من أجل التميز", category: "أفعال" },
    { id: 6306, word: "endeavor", arabic: "يسعى", pronunciation: "إنديفور", example: "Endeavor to succeed.", exampleArabic: "اسعَ للنجاح", category: "أفعال" },
    { id: 6307, word: "attempt", arabic: "يحاول", pronunciation: "أتمبت", example: "Attempt again.", exampleArabic: "حاول مرة أخرى", category: "أفعال" },
    { id: 6308, word: "persist", arabic: "يثابر", pronunciation: "بيرسيست", example: "Persist despite difficulties.", exampleArabic: "اثابر رغم الصعوبات", category: "أفعال" },
    { id: 6309, word: "continue", arabic: "يواصل", pronunciation: "كونتينيو", example: "Continue working.", exampleArabic: "واصل العمل", category: "أفعال" },
    { id: 6310, word: "proceed", arabic: "يتابع", pronunciation: "بروسيد", example: "Proceed with caution.", exampleArabic: "تابع بحذر", category: "أفعال" },
    { id: 6311, word: "commence", arabic: "يبدأ", pronunciation: "كومنس", example: "Commence project.", exampleArabic: "ابدأ المشروع", category: "أفعال" },
    { id: 6312, word: "initiate", arabic: "يبادر", pronunciation: "إنيشيت", example: "Initiate conversation.", exampleArabic: "بادِر بالحديث", category: "أفعال" },
    { id: 6313, word: "launch", arabic: "يطلق", pronunciation: "لونش", example: "Launch product.", exampleArabic: "أطلق المنتج", category: "أفعال" },
    { id: 6314, word: "establish", arabic: "يؤسس", pronunciation: "إستابليش", example: "Establish company.", exampleArabic: "أسس شركة", category: "أفعال" },
    { id: 6315, word: "found", arabic: "يؤسس", pronunciation: "فاوند", example: "Founded in 2000.", exampleArabic: "تأسست عام 2000", category: "أفعال" },
    { id: 6316, word: "create", arabic: "يبدع", pronunciation: "كرييت", example: "Create art.", exampleArabic: "أبدع فناً", category: "أفعال" },
    { id: 6317, word: "innovate", arabic: "يبتكر", pronunciation: "إنوفيت", example: "Innovate new ideas.", exampleArabic: "ابتكر أفكاراً جديدة", category: "أفعال" },
    { id: 6318, word: "develop", arabic: "يطور", pronunciation: "ديفيلوب", example: "Develop skills.", exampleArabic: "طور المهارات", category: "أفعال" },
    { id: 6319, word: "improve", arabic: "يحسن", pronunciation: "إمبروف", example: "Improve yourself.", exampleArabic: "حسّن نفسك", category: "أفعال" },
    { id: 6320, word: "enhance", arabic: "يعزز", pronunciation: "إنهانس", example: "Enhance performance.", exampleArabic: "عزز الأداء", category: "أفعال" },
    { id: 6321, word: "refine", arabic: "يصقل", pronunciation: "ري فاين", example: "Refine skills.", exampleArabic: "صقل المهارات", category: "أفعال" },
    { id: 6322, word: "perfect", arabic: "يتقن", pronunciation: "بيرفكت", example: "Perfect your craft.", exampleArabic: "أتقن حرفتك", category: "أفعال" },
    { id: 6323, word: "master", arabic: "يتقن", pronunciation: "ماستر", example: "Master language.", exampleArabic: "أتقن اللغة", category: "أفعال" },
    { id: 6324, word: "learn", arabic: "يتعلم", pronunciation: "ليرن", example: "Learn new things.", exampleArabic: "تعلم أشياء جديدة", category: "أفعال" },
    { id: 6325, word: "understand", arabic: "يفهم", pronunciation: "أندرستاند", example: "Understand the lesson.", exampleArabic: "افهم الدرس", category: "أفعال" },

    // التكنولوجيا والإنترنت
    { id: 6401, word: "artificial intelligence", arabic: "ذكاء اصطناعي", pronunciation: "آرفيشال إنتليجنس", example: "AI technology.", exampleArabic: "تقنية الذكاء الاصطناعي", category: "تكنولوجيا" },
    { id: 6402, word: "machine learning", arabic: "تعلم آلة", pronunciation: "ماشين ليرنينغ", example: "Machine learning algorithms.", exampleArabic: "خوارزميات تعلم الآلة", category: "تكنولوجيا" },
    { id: 6403, word: "virtual reality", arabic: "واقع افتراضي", pronunciation: "فيرتشوال رياليتي", example: "VR experience.", exampleArabic: "تجربة واقع افتراضي", category: "تكنولوجيا" },
    { id: 6404, word: "augmented reality", arabic: "واقع معزز", pronunciation: "أوغمينتيد رياليتي", example: "AR applications.", exampleArabic: "تطبيقات واقع معزز", category: "تكنولوجيا" },
    { id: 6405, word: "blockchain", arabic: "سلسلة كتل", pronunciation: "بلوكتشين", example: "Blockchain technology.", exampleArabic: "تقنية سلسلة الكتل", category: "تكنولوجيا" },
    { id: 6406, word: "cryptocurrency", arabic: "عملة رقمية", pronunciation: "كريبتوكارنسي", example: "Bitcoin cryptocurrency.", exampleArabic: "عملة بيتكوين رقمية", category: "تكنولوجيا" },
    { id: 6407, word: "cybersecurity", arabic: "أمن سيبراني", pronunciation: "سايبر سكيوريتي", example: "Cybersecurity measures.", exampleArabic: "إجراءات الأمن السيبراني", category: "تكنولوجيا" },
    { id: 6408, word: "encryption", arabic: "تشفير", pronunciation: "إنكريبشن", example: "Data encryption.", exampleArabic: "تشفير البيانات", category: "تكنولوجيا" },
    { id: 6409, word: "firewall", arabic: "جدار ناري", pronunciation: "فايروول", example: "Firewall protection.", exampleArabic: "حماية جدار ناري", category: "تكنولوجيا" },
    { id: 6410, word: "malware", arabic: "برمجيات خبيثة", pronunciation: "مالوير", example: "Malware attack.", exampleArabic: "هجوم برمجيات خبيثة", category: "تكنولوجيا" },
    { id: 6411, word: "phishing", arabic: "تصيد", pronunciation: "فيشينغ", example: "Phishing scam.", exampleArabic: "احتيال تصيدي", category: "تكنولوجيا" },
    { id: 6412, word: "hacker", arabic: "هاكر", pronunciation: "هاكر", example: "Computer hacker.", exampleArabic: "هاكر كمبيوتر", category: "تكنولوجيا" },
    { id: 6413, word: "algorithm", arabic: "خوارزمية", pronunciation: "ألغوريزم", example: "Search algorithm.", exampleArabic: "خوارزمية بحث", category: "تكنولوجيا" },
    { id: 6414, word: "database", arabic: "قاعدة بيانات", pronunciation: "داتابيس", example: "Customer database.", exampleArabic: "قاعدة بيانات العملاء", category: "تكنولوجيا" },
    { id: 6415, word: "server", arabic: "خادم", pronunciation: "سيرفر", example: "Web server.", exampleArabic: "خادم ويب", category: "تكنولوجيا" },
    { id: 6416, word: "cloud", arabic: "سحابة", pronunciation: "كلاود", example: "Cloud storage.", exampleArabic: "تخزين سحابي", category: "تكنولوجيا" },
    { id: 6417, word: "network", arabic: "شبكة", pronunciation: "نيتورك", example: "Computer network.", exampleArabic: "شبكة كمبيوتر", category: "تكنولوجيا" },
    { id: 6418, word: "bandwidth", arabic: "عرض نطاق", pronunciation: "باندويدث", example: "High bandwidth.", exampleArabic: "عرض نطاق عالٍ", category: "تكنولوجيا" },
    { id: 6419, word: "latency", arabic: "زمن وصول", pronunciation: "ليتنزي", example: "Low latency.", exampleArabic: "زمن وصول منخفض", category: "تكنولوجيا" },
    { id: 6420, word: "interface", arabic: "واجهة", pronunciation: "إنترفيس", example: "User interface.", exampleArabic: "واجهة مستخدم", category: "تكنولوجيا" },
    { id: 6421, word: "protocol", arabic: "بروتوكول", pronunciation: "بروتوكول", example: "Network protocol.", exampleArabic: "بروتوكول شبكة", category: "تكنولوجيا" },
    { id: 6422, word: "encryption", arabic: "تشفير", pronunciation: "إنكريبشن", example: "End-to-end encryption.", exampleArabic: "تشفير من طرف لطرف", category: "تكنولوجيا" },
    { id: 6423, word: "software", arabic: "برمجيات", pronunciation: "سوفتوير", example: "Computer software.", exampleArabic: "برمجيات كمبيوتر", category: "تكنولوجيا" },
    { id: 6424, word: "hardware", arabic: "عتاد", pronunciation: "هاردوير", example: "Computer hardware.", exampleArabic: "عتاد كمبيوتر", category: "تكنولوجيا" },
    { id: 6425, word: "application", arabic: "تطبيق", pronunciation: "أبليكايشن", example: "Mobile application.", exampleArabic: "تطبيق جوال", category: "تكنولوجيا" },

    // البيئة والطبيعة
    { id: 6501, word: "environment", arabic: "بيئة", pronunciation: "إنفايرونمنت", example: "Protect the environment.", exampleArabic: "احمِ البيئة", category: "بيئة" },
    { id: 6502, word: "ecosystem", arabic: "نظام بيئي", pronunciation: "إيكوسيستم", example: "Marine ecosystem.", exampleArabic: "نظام بيئي بحري", category: "بيئة" },
    { id: 6503, word: "biodiversity", arabic: "تنوع حيوي", pronunciation: "بايو دايفيرسيتي", example: "Rich biodiversity.", exampleArabic: "تنوع حيوي غني", category: "بيئة" },
    { id: 6504, word: "conservation", arabic: "حماية", pronunciation: "كونسيرفيشن", example: "Wildlife conservation.", exampleArabic: "حماية الحياة البرية", category: "بيئة" },
    { id: 6505, word: "sustainable", arabic: "مستدام", pronunciation: "ساستينابل", example: "Sustainable development.", exampleArabic: "تنمية مستدامة", category: "بيئة" },
    { id: 6506, word: "renewable", arabic: "متجدد", pronunciation: "رينيوابل", example: "Renewable energy.", exampleArabic: "طاقة متجددة", category: "بيئة" },
    { id: 6507, word: "solar", arabic: "شمسي", pronunciation: "سولار", example: "Solar power.", exampleArabic: "طاقة شمسية", category: "بيئة" },
    { id: 6508, word: "wind", arabic: "رياح", pronunciation: "ويند", example: "Wind energy.", exampleArabic: "طاقة رياح", category: "بيئة" },
    { id: 6509, word: "pollution", arabic: "تلوث", pronunciation: "بولوشن", example: "Air pollution.", exampleArabic: "تلوث هواء", category: "بيئة" },
    { id: 6510, word: "emission", arabic: "انبعاث", pronunciation: "إميشين", example: "Carbon emissions.", exampleArabic: "انبعاثات كربون", category: "بيئة" },
    { id: 6511, word: "recycle", arabic: "يعيد تدوير", pronunciation: "ريسايكل", example: "Recycle plastic.", exampleArabic: "أعد تدوير البلاستيك", category: "بيئة" },
    { id: 6512, word: "waste", arabic: "نفايات", pronunciation: "ويست", example: "Reduce waste.", exampleArabic: "قلل النفايات", category: "بيئة" },
    { id: 6513, word: "climate", arabic: "مناخ", pronunciation: "كلايميت", example: "Climate change.", exampleArabic: "تغير المناخ", category: "بيئة" },
    { id: 6514, word: "global warming", arabic: "احتباس حراري", pronunciation: "غلوبال وورمينغ", example: "Combat global warming.", exampleArabic: "حارب الاحتباس الحراري", category: "بيئة" },
    { id: 6515, word: "ozone", arabic: "أوزون", pronunciation: "أوزون", example: "Ozone layer.", exampleArabic: "طبقة الأوزون", category: "بيئة" },
    { id: 6516, word: "deforestation", arabic: "إزالة غابات", pronunciation: "دي فورستيشن", example: "Stop deforestation.", exampleArabic: "أوقف إزالة الغابات", category: "بيئة" },
    { id: 6517, word: "endangered", arabic: "مهدد بالانقراض", pronunciation: "إيندينجرد", example: "Endangered species.", exampleArabic: "أنواع مهددة بالانقراض", category: "بيئة" },
    { id: 6518, word: "extinct", arabic: "منقرض", pronunciation: "إكستينكت", example: "Extinct animals.", exampleArabic: "حيوانات منقرضة", category: "بيئة" },
    { id: 6519, word: "habitat", arabic: "موطن", pronunciation: "هابيتات", example: "Natural habitat.", exampleArabic: "موطن طبيعي", category: "بيئة" },
    { id: 6520, word: "wildlife", arabic: "حياة برية", pronunciation: "وايلدلايف", example: "Protect wildlife.", exampleArabic: "احمِ الحياة البرية", category: "بيئة" },
    { id: 6521, word: "forest", arabic: "غابة", pronunciation: "فورست", example: "Rain forest.", exampleArabic: "غابة مطيرة", category: "بيئة" },
    { id: 6522, word: "ocean", arabic: "محيط", pronunciation: "أوشن", example: "Pacific Ocean.", exampleArabic: "المحيط الهادئ", category: "بيئة" },
    { id: 6523, word: "atmosphere", arabic: "غلاف جوي", pronunciation: "أتوموسفير", example: "Earth's atmosphere.", exampleArabic: "الغلاف الجوي للأرض", category: "بيئة" },
    { id: 6524, word: "ecology", arabic: "علم البيئة", pronunciation: "إيكولوجي", example: "Study ecology.", exampleArabic: "ادرس علم البيئة", category: "بيئة" },
    { id: 6525, word: "greenhouse", arabic: "دفيئة", pronunciation: "جرين هاوس", example: "Greenhouse effect.", exampleArabic: "تأثير الدفيئة", category: "بيئة" },

    // الرياضة
    { id: 6601, word: "athlete", arabic: "رياضي", pronunciation: "أثليت", example: "Professional athlete.", exampleArabic: "رياضي محترف", category: "رياضة" },
    { id: 6602, word: "tournament", arabic: "بطولة", pronunciation: "تورنامنت", example: "Tennis tournament.", exampleArabic: "بطولة تنس", category: "رياضة" },
    { id: 6603, word: "championship", arabic: "بطولة", pronunciation: "تشامبيونشيب", example: "World championship.", exampleArabic: "بطولة العالم", category: "رياضة" },
    { id: 6604, word: "competition", arabic: "منافسة", pronunciation: "كومبيتيشن", example: "Fierce competition.", exampleArabic: "منافسة شرسة", category: "رياضة" },
    { id: 6605, word: "opponent", arabic: "خصم", pronunciation: "أوبوننت", example: "Defeat opponent.", exampleArabic: "اهزم الخصم", category: "رياضة" },
    { id: 6606, word: "stadium", arabic: "ملعب", pronunciation: "ستاديوم", example: "Football stadium.", exampleArabic: "ملعب كرة قدم", category: "رياضة" },
    { id: 6607, word: "gym", arabic: "نادي رياضي", pronunciation: "جيم", example: "Go to the gym.", exampleArabic: "اذهب للنادي الرياضي", category: "رياضة" },
    { id: 6608, word: "workout", arabic: "تمرين", pronunciation: "ورك أوت", example: "Daily workout.", exampleArabic: "تمرين يومي", category: "رياضة" },
    { id: 6609, word: "fitness", arabic: "لياقة", pronunciation: "فيتنس", example: "Fitness center.", exampleArabic: "مركز لياقة", category: "رياضة" },
    { id: 6610, word: "endurance", arabic: "تحمل", pronunciation: "إينديورانس", example: "Build endurance.", exampleArabic: "ابنِ التحمل", category: "رياضة" },
    { id: 6611, word: "strength", arabic: "قوة", pronunciation: "سترينغث", example: "Physical strength.", exampleArabic: "قوة بدنية", category: "رياضة" },
    { id: 6612, word: "flexibility", arabic: "مرونة", pronunciation: "فليكس بيليتي", example: "Improve flexibility.", exampleArabic: "حسّن المرونة", category: "رياضة" },
    { id: 6613, word: "stamina", arabic: "قدرة تحمل", pronunciation: "ستامينا", example: "Increase stamina.", exampleArabic: "زد القدرة على التحمل", category: "رياضة" },
    { id: 6614, word: "coach", arabic: "مدرب", pronunciation: "كوتش", example: "Team coach.", exampleArabic: "مدرب الفريق", category: "رياضة" },
    { id: 6615, word: "referee", arabic: "حكم", pronunciation: "ريفيري", example: "Football referee.", exampleArabic: "حكم كرة قدم", category: "رياضة" },
    { id: 6616, word: "score", arabic: "نتيجة", pronunciation: "سكور", example: "Final score.", exampleArabic: "النتيجة النهائية", category: "رياضة" },
    { id: 6617, word: "goal", arabic: "هدف", pronunciation: "جول", example: "Score a goal.", exampleArabic: "سجل هدفاً", category: "رياضة" },
    { id: 6618, word: "medal", arabic: "ميدالية", pronunciation: "ميدال", example: "Gold medal.", exampleArabic: "ميدالية ذهبية", category: "رياضة" },
    { id: 6619, word: "victory", arabic: "انتصار", pronunciation: "فيكتوري", example: "Celebrate victory.", exampleArabic: "احتفل بالانتصار", category: "رياضة" },
    { id: 6620, word: "defeat", arabic: "هزيمة", pronunciation: "ديفيت", example: "Accept defeat.", exampleArabic: "تقبل الهزيمة", category: "رياضة" },
    { id: 6621, word: "marathon", arabic: "ماراثون", pronunciation: "ماراثون", example: "Run marathon.", exampleArabic: "اركض ماراثون", category: "رياضة" },
    { id: 6622, word: "sprint", arabic: "ركض سريع", pronunciation: "سبرينت", example: "Short sprint.", exampleArabic: "ركض سريع قصير", category: "رياضة" },
    { id: 6623, word: "swimming", arabic: "سباحة", pronunciation: "سويمينغ", example: "Swimming pool.", exampleArabic: "حمام سباحة", category: "رياضة" },
    { id: 6624, word: "cycling", arabic: "ركوب دراجات", pronunciation: "سايكلينغ", example: "Mountain cycling.", exampleArabic: "ركوب دراجات جبلية", category: "رياضة" },
    { id: 6625, word: "yoga", arabic: "يوغا", pronunciation: "يوغا", example: "Practice yoga.", exampleArabic: "مارس اليوغا", category: "رياضة" },

    // الفن والثقافة
    { id: 6701, word: "art", arabic: "فن", pronunciation: "آرت", example: "Modern art.", exampleArabic: "فن حديث", category: "فن" },
    { id: 6702, word: "culture", arabic: "ثقافة", pronunciation: "كلتشر", example: "Local culture.", exampleArabic: "ثقافة محلية", category: "فن" },
    { id: 6703, word: "heritage", arabic: "تراث", pronunciation: "هيريتيدج", example: "Cultural heritage.", exampleArabic: "تراث ثقافي", category: "فن" },
    { id: 6704, word: "tradition", arabic: "تقليد", pronunciation: "تراديشن", example: "Family tradition.", exampleArabic: "تقليد عائلي", category: "فن" },
    { id: 6705, word: "custom", arabic: "عادة", pronunciation: "كاستم", example: "Local customs.", exampleArabic: "عادات محلية", category: "فن" },
    { id: 6706, word: "festival", arabic: "مهرجان", pronunciation: "فيستيفال", example: "Music festival.", exampleArabic: "مهرجان موسيقي", category: "فن" },
    { id: 6707, word: "ceremony", arabic: "حفل", pronunciation: "سيريموني", example: "Opening ceremony.", exampleArabic: "حفل افتتاح", category: "فن" },
    { id: 6708, word: "performance", arabic: "أداء", pronunciation: "بيرفورمانس", example: "Live performance.", exampleArabic: "أداء حي", category: "فن" },
    { id: 6709, word: "exhibition", arabic: "معرض", pronunciation: "إكزيبيشن", example: "Art exhibition.", exampleArabic: "معرض فني", category: "فن" },
    { id: 6710, word: "museum", arabic: "متحف", pronunciation: "ميوزيام", example: "History museum.", exampleArabic: "متحف تاريخي", category: "فن" },
    { id: 6711, word: "gallery", arabic: "جاليري", pronunciation: "جاليري", example: "Art gallery.", exampleArabic: "جاليري فني", category: "فن" },
    { id: 6712, word: "sculpture", arabic: "نحت", pronunciation: "سكلبتشر", example: "Marble sculpture.", exampleArabic: "نحت رخامي", category: "فن" },
    { id: 6713, word: "painting", arabic: "لوحة", pronunciation: "بينتينغ", example: "Oil painting.", exampleArabic: "لوحة زيتية", category: "فن" },
    { id: 6714, word: "drawing", arabic: "رسم", pronunciation: "درونغ", example: "Pencil drawing.", exampleArabic: "رسم بقلم الرصاص", category: "فن" },
    { id: 6715, word: "photography", arabic: "تصوير", pronunciation: "فوتوغرافي", example: "Nature photography.", exampleArabic: "تصوير طبيعي", category: "فن" },
    { id: 6716, word: "literature", arabic: "أدب", pronunciation: "ليتراتشر", example: "English literature.", exampleArabic: "أدب إنجليزي", category: "فن" },
    { id: 6717, word: "poetry", arabic: "شعر", pronunciation: "بويتري", example: "Write poetry.", exampleArabic: "اكتب شعراً", category: "فن" },
    { id: 6718, word: "novel", arabic: "رواية", pronunciation: "نوفل", example: "Read a novel.", exampleArabic: "اقرأ رواية", category: "فن" },
    { id: 6719, word: "music", arabic: "موسيقى", pronunciation: "ميوزيك", example: "Classical music.", exampleArabic: "موسيقى كلاسيكية", category: "فن" },
    { id: 6720, word: "instrument", arabic: "آلة", pronunciation: "إنسترومنت", example: "Musical instrument.", exampleArabic: "آلة موسيقية", category: "فن" },
    { id: 6721, word: "theater", arabic: "مسرح", pronunciation: "ثياتر", example: "Go to theater.", exampleArabic: "اذهب إلى المسرح", category: "فن" },
    { id: 6722, word: "cinema", arabic: "سينما", pronunciation: "سينيما", example: "French cinema.", exampleArabic: "سينما فرنسية", category: "فن" },
    { id: 6723, word: "dance", arabic: "رقص", pronunciation: "دانس", example: "Traditional dance.", exampleArabic: "رقص تقليدي", category: "فن" },
    { id: 6724, word: "opera", arabic: "أوبرا", pronunciation: "أوبرا", example: "Opera house.", exampleArabic: "دار أوبرا", category: "فن" },
    { id: 6725, word: "orchestra", arabic: "أوركسترا", pronunciation: "أوركيسترا", example: "Symphony orchestra.", exampleArabic: "أوركسترا سيمفونية", category: "فن" },

    // القانون والعدالة
    { id: 6801, word: "law", arabic: "قانون", pronunciation: "لو", example: "Obey the law.", exampleArabic: "أطع القانون", category: "قانون" },
    { id: 6802, word: "justice", arabic: "عدالة", pronunciation: "جاستس", example: "Justice for all.", exampleArabic: "العدالة للجميع", category: "قانون" },
    { id: 6803, word: "rights", arabic: "حقوق", pronunciation: "رايتس", example: "Human rights.", exampleArabic: "حقوق الإنسان", category: "قانون" },
    { id: 6804, word: "freedom", arabic: "حرية", pronunciation: "فريدوم", example: "Freedom of speech.", exampleArabic: "حرية التعبير", category: "قانون" },
    { id: 6805, word: "court", arabic: "محكمة", pronunciation: "كورت", example: "The court is in session.", exampleArabic: "المحكمة منعقدة", category: "قانون" },
    { id: 6806, word: "judge", arabic: "قاضي", pronunciation: "جادج", example: "The judge made a decision.", exampleArabic: "القاضي اتخذ قراراً", category: "قانون" },
    { id: 6807, word: "lawyer", arabic: "محامي", pronunciation: "لويير", example: "The lawyer defended him.", exampleArabic: "المحامي دافع عنه", category: "قانون" },
    { id: 6808, word: "jury", arabic: "هيئة محلفين", pronunciation: "جوري", example: "The jury reached a verdict.", exampleArabic: "هيئة المحلفين توصلت إلى حكم", category: "قانون" },
    { id: 6809, word: "trial", arabic: "محاكمة", pronunciation: "ترايال", example: "The trial lasted a week.", exampleArabic: "المحاكمة استمرت أسبوعاً", category: "قانون" },
    { id: 6810, word: "evidence", arabic: "دليل", pronunciation: "إيفيدنس", example: "The evidence was clear.", exampleArabic: "الدليل كان واضحاً", category: "قانون" },
    { id: 6811, word: "witness", arabic: "شاهد", pronunciation: "ويتنس", example: "The witness testified.", exampleArabic: "الشاهد أدلى بشهادته", category: "قانون" },
    { id: 6812, word: "verdict", arabic: "حكم", pronunciation: "فيرديكت", example: "The verdict is guilty.", exampleArabic: "الحكم مذنب", category: "قانون" },
    { id: 6813, word: "guilty", arabic: "مذنب", pronunciation: "جيلتي", example: "He was found guilty.", exampleArabic: "تم العثور عليه مذنباً", category: "قانون" },
    { id: 6814, word: "innocent", arabic: "بريء", pronunciation: "إينوسنت", example: "She is innocent.", exampleArabic: "هي بريئة", category: "قانون" },
    { id: 6815, word: "crime", arabic: "جريمة", pronunciation: "كرايم", example: "Crime is decreasing.", exampleArabic: "الجريمة في تناقص", category: "قانون" },
    { id: 6816, word: "criminal", arabic: "مجرم", pronunciation: "كرايمنل", example: "The criminal was arrested.", exampleArabic: "المجرم تم اعتقاله", category: "قانون" },
    { id: 6817, word: "punishment", arabic: "عقاب", pronunciation: "بانيشمنت", example: "The punishment fits the crime.", exampleArabic: "العقاب يناسب الجريمة", category: "قانون" },
    { id: 6818, word: "sentence", arabic: "حكم بالسجن", pronunciation: "سينتنز", example: "He received a life sentence.", exampleArabic: "تلقى حكماً بالسجن مدى الحياة", category: "قانون" },
    { id: 6819, word: "prison", arabic: "سجن", pronunciation: "بريزن", example: "He was sent to prison.", exampleArabic: "تم إرساله إلى السجن", category: "قانون" },
    { id: 6820, word: "appeal", arabic: "استئناف", pronunciation: "أبيل", example: "They filed an appeal.", exampleArabic: "قدموا استئنافاً", category: "قانون" },
    { id: 6821, word: "legal", arabic: "قانوني", pronunciation: "ليغال", example: "Legal advice.", exampleArabic: "نصيحة قانونية", category: "قانون" },
    { id: 6822, word: "illegal", arabic: "غير قانوني", pronunciation: "إليغال", example: "It's illegal to steal.", exampleArabic: "السرقة غير قانونية", category: "قانون" },
    { id: 6823, word: "contract", arabic: "عقد", pronunciation: "كونتراكت", example: "Sign the contract.", exampleArabic: "وقع العقد", category: "قانون" },
    { id: 6824, word: "agreement", arabic: "اتفاقية", pronunciation: "أغريمنت", example: "They reached an agreement.", exampleArabic: "توصلوا إلى اتفاقية", category: "قانون" },
    { id: 6825, word: "testimony", arabic: "شهادة", pronunciation: "تستيموني", example: "Her testimony was convincing.", exampleArabic: "شهادتها كانت مقنعة", category: "قانون" }
];

// التحقق من التحميل
console.log('✅ advanced-data.js loaded with', ADVANCED_WORDS.length, 'words');

// تصدير البيانات للاستخدام في ملفات أخرى
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ADVANCED_WORDS;
        }
