// beginner-data.js - 300 كلمة للمستوى المبتدئ
const BEGINNER_WORDS = [
    // ========== تحيات ========== (20 كلمة)
    { id: 1001, word: "hello", arabic: "مرحباً", pronunciation: "هالو", example: "Hello, how are you?", exampleArabic: "مرحباً، كيف حالك؟", category: "تحيات" },
    { id: 1002, word: "goodbye", arabic: "وداعاً", pronunciation: "جود باي", example: "Say goodbye to your friends.", exampleArabic: "قل وداعاً لأصدقائك", category: "تحيات" },
    { id: 1003, word: "good morning", arabic: "صباح الخير", pronunciation: "جود مورنينغ", example: "Good morning, everyone!", exampleArabic: "صباح الخير للجميع!", category: "تحيات" },
    { id: 1004, word: "good evening", arabic: "مساء الخير", pronunciation: "جود إيفنينغ", example: "Good evening, how was your day?", exampleArabic: "مساء الخير، كيف كان يومك؟", category: "تحيات" },
    { id: 1005, word: "good night", arabic: "تصبح على خير", pronunciation: "جود نايت", example: "Good night, sleep well.", exampleArabic: "تصبح على خير، نم جيداً", category: "تحيات" },
    { id: 1006, word: "welcome", arabic: "أهلاً وسهلاً", pronunciation: "ويلكم", example: "Welcome to our home!", exampleArabic: "أهلاً وسهلاً في بيتنا!", category: "تحيات" },
    { id: 1007, word: "hi", arabic: "مرحباً", pronunciation: "هاي", example: "Hi, nice to see you!", exampleArabic: "مرحباً، سعيد برؤيتك!", category: "تحيات" },
    { id: 1008, word: "how are you", arabic: "كيف حالك", pronunciation: "هاو آر يو", example: "How are you today?", exampleArabic: "كيف حالك اليوم؟", category: "تحيات" },
    { id: 1009, word: "I'm fine", arabic: "أنا بخير", pronunciation: "آيم فاين", example: "I'm fine, thank you.", exampleArabic: "أنا بخير، شكراً", category: "تحيات" },
    { id: 1010, word: "nice to meet you", arabic: "تشرفت بمقابلتك", pronunciation: "نايس تو ميت يو", example: "Nice to meet you, I'm Ahmed.", exampleArabic: "تشرفت بمقابلتك، أنا أحمد", category: "تحيات" },
    { id: 1011, word: "see you later", arabic: "أراك لاحقاً", pronunciation: "سي يو ليتير", example: "I have to go, see you later!", exampleArabic: "يجب أن أذهب، أراك لاحقاً!", category: "تحيات" },
    { id: 1012, word: "see you soon", arabic: "أراك قريباً", pronunciation: "سي يو سون", example: "Thanks for coming, see you soon!", exampleArabic: "شكراً لحضورك، أراك قريباً!", category: "تحيات" },
    { id: 1013, word: "take care", arabic: "اعتني بنفسك", pronunciation: "تيك كير", example: "Take care of yourself!", exampleArabic: "اعتني بنفسك!", category: "تحيات" },
    { id: 1014, word: "have a nice day", arabic: "أتمنى لك يوماً سعيداً", pronunciation: "هاف أ نايس داي", example: "Goodbye, have a nice day!", exampleArabic: "وداعاً، أتمنى لك يوماً سعيداً!", category: "تحيات" },
    { id: 1015, word: "howdy", arabic: "مرحبا", pronunciation: "هاودي", example: "Howdy, partner!", exampleArabic: "مرحباً، يا صديقي!", category: "تحيات" },
    { id: 1016, word: "greetings", arabic: "تحياتي", pronunciation: "غريتينغز", example: "Greetings from all of us!", exampleArabic: "تحياتنا من الجميع!", category: "تحيات" },
    { id: 1017, word: "pleased to meet you", arabic: "سُعدت بلقائك", pronunciation: "بليزد تو ميت يو", example: "Pleased to meet you, sir.", exampleArabic: "سعدت بلقائك يا سيد", category: "تحيات" },
    { id: 1018, word: "long time no see", arabic: "لم نرك منذ زمن", pronunciation: "لونغ تايم نو سي", example: "Long time no see, my friend!", exampleArabic: "لم نرك منذ زمن، يا صديقي!", category: "تحيات" },
    { id: 1019, word: "what's up", arabic: "كيف الحال", pronunciation: "واتس أب", example: "Hey, what's up?", exampleArabic: "مرحباً، كيف الحال؟", category: "تحيات" },
    { id: 1020, word: "how's it going", arabic: "كيف الأمور", pronunciation: "هاوز إت غوينغ", example: "How's it going with you?", exampleArabic: "كيف الأمور معك؟", category: "تحيات" },

    // ========== ألوان ========== (20 كلمة)
    { id: 1101, word: "red", arabic: "أحمر", pronunciation: "ريد", example: "The apple is red.", exampleArabic: "التفاحة حمراء", category: "ألوان" },
    { id: 1102, word: "blue", arabic: "أزرق", pronunciation: "بلو", example: "The sky is blue.", exampleArabic: "السماء زرقاء", category: "ألوان" },
    { id: 1103, word: "yellow", arabic: "أصفر", pronunciation: "يلو", example: "The sun is yellow.", exampleArabic: "الشمس صفراء", category: "ألوان" },
    { id: 1104, word: "green", arabic: "أخضر", pronunciation: "جرين", example: "The grass is green.", exampleArabic: "العشب أخضر", category: "ألوان" },
    { id: 1105, word: "black", arabic: "أسود", pronunciation: "بلاك", example: "The night is black.", exampleArabic: "الليل أسود", category: "ألوان" },
    { id: 1106, word: "white", arabic: "أبيض", pronunciation: "وايت", example: "The snow is white.", exampleArabic: "الثلج أبيض", category: "ألوان" },
    { id: 1107, word: "orange", arabic: "برتقالي", pronunciation: "أورانج", example: "The orange is orange.", exampleArabic: "البرتقالة برتقالية", category: "ألوان" },
    { id: 1108, word: "purple", arabic: "بنفسجي", pronunciation: "بيربل", example: "I like purple flowers.", exampleArabic: "أحب الزهور البنفسجية", category: "ألوان" },
    { id: 1109, word: "pink", arabic: "وردي", pronunciation: "بينك", example: "She wears a pink dress.", exampleArabic: "هي ترتدي فستاناً وردياً", category: "ألوان" },
    { id: 1110, word: "brown", arabic: "بني", pronunciation: "براون", example: "The chocolate is brown.", exampleArabic: "الشوكولاتة بنية", category: "ألوان" },
    { id: 1111, word: "gray", arabic: "رمادي", pronunciation: "جري", example: "The cloud is gray.", exampleArabic: "السحابة رمادية", category: "ألوان" },
    { id: 1112, word: "gold", arabic: "ذهبي", pronunciation: "جولد", example: "The ring is gold.", exampleArabic: "الخاتم ذهبي", category: "ألوان" },
    { id: 1113, word: "silver", arabic: "فضي", pronunciation: "سيلفر", example: "The car is silver.", exampleArabic: "السيارة فضية", category: "ألوان" },
    { id: 1114, word: "beige", arabic: "بيج", pronunciation: "بيج", example: "The sofa is beige.", exampleArabic: "الأريكة بيج", category: "ألوان" },
    { id: 1115, word: "cream", arabic: "كريمي", pronunciation: "كريم", example: "The wall is cream.", exampleArabic: "الجدار كريمي", category: "ألوان" },
    { id: 1116, word: "navy", arabic: "كحلي", pronunciation: "نيفي", example: "He wears a navy suit.", exampleArabic: "يرتدي بدلة كحلية", category: "ألوان" },
    { id: 1117, word: "turquoise", arabic: "فيروزي", pronunciation: "توركواز", example: "The sea is turquoise.", exampleArabic: "البحر فيروزي", category: "ألوان" },
    { id: 1118, word: "lime", arabic: "ليموني", pronunciation: "لايم", example: "The juice is lime green.", exampleArabic: "العصير ليموني", category: "ألوان" },
    { id: 1119, word: "maroon", arabic: "كستنائي", pronunciation: "مارون", example: "The curtain is maroon.", exampleArabic: "الستارة كستنائية", category: "ألوان" },
    { id: 1120, word: "violet", arabic: "بنفسجي فاتح", pronunciation: "فايولت", example: "Violet flowers are beautiful.", exampleArabic: "الزهور البنفسجية جميلة", category: "ألوان" },

    // ========== فواكه ========== (20 كلمة)
    { id: 1201, word: "apple", arabic: "تفاح", pronunciation: "آبل", example: "I eat an apple every day.", exampleArabic: "أكل تفاحة كل يوم", category: "فواكه" },
    { id: 1202, word: "banana", arabic: "موز", pronunciation: "بانانا", example: "Monkeys like bananas.", exampleArabic: "القرود تحب الموز", category: "فواكه" },
    { id: 1203, word: "orange", arabic: "برتقال", pronunciation: "أورانج", example: "Orange juice is healthy.", exampleArabic: "عصير البرتقال صحي", category: "فواكه" },
    { id: 1204, word: "strawberry", arabic: "فراولة", pronunciation: "ستروبيري", example: "Strawberry ice cream.", exampleArabic: "آيس كريم فراولة", category: "فواكه" },
    { id: 1205, word: "grape", arabic: "عنب", pronunciation: "جريب", example: "These grapes are sweet.", exampleArabic: "هذا العنب حلو", category: "فواكه" },
    { id: 1206, word: "watermelon", arabic: "بطيخ", pronunciation: "ووترميلون", example: "Watermelon is refreshing.", exampleArabic: "البطيخ منعش", category: "فواكه" },
    { id: 1207, word: "melon", arabic: "شمام", pronunciation: "ميلون", example: "Melon is delicious.", exampleArabic: "الشمام لذيذ", category: "فواكه" },
    { id: 1208, word: "peach", arabic: "خوخ", pronunciation: "بيتش", example: "Peaches are soft.", exampleArabic: "الخوخ ناعم", category: "فواكه" },
    { id: 1209, word: "pear", arabic: "كمثرى", pronunciation: "بير", example: "Pears are sweet.", exampleArabic: "الكمثرى حلوة", category: "فواكه" },
    { id: 1210, word: "cherry", arabic: "كرز", pronunciation: "تشيري", example: "Cherries are red.", exampleArabic: "الكرز أحمر", category: "فواكه" },
    { id: 1211, word: "pineapple", arabic: "أناناس", pronunciation: "باينابل", example: "Pineapple is yellow.", exampleArabic: "الأناناس أصفر", category: "فواكه" },
    { id: 1212, word: "mango", arabic: "مانجو", pronunciation: "مانغو", example: "Mango is my favorite.", exampleArabic: "المانجو المفضلة لدي", category: "فواكه" },
    { id: 1213, word: "lemon", arabic: "ليمون", pronunciation: "ليمون", example: "Lemon is sour.", exampleArabic: "الليمون حامض", category: "فواكه" },
    { id: 1214, word: "kiwi", arabic: "كيوي", pronunciation: "كيوي", example: "Kiwi is green.", exampleArabic: "الكيوي أخضر", category: "فواكه" },
    { id: 1215, word: "coconut", arabic: "جوز هند", pronunciation: "كوكونات", example: "Coconut water is healthy.", exampleArabic: "ماء جوز الهند صحي", category: "فواكه" },
    { id: 1216, word: "fig", arabic: "تين", pronunciation: "فيغ", example: "Figs are sweet.", exampleArabic: "التين حلو", category: "فواكه" },
    { id: 1217, word: "date", arabic: "تمر", pronunciation: "ديت", example: "Dates are healthy.", exampleArabic: "التمر صحي", category: "فواكه" },
    { id: 1218, word: "pomegranate", arabic: "رمان", pronunciation: "بومغرانت", example: "Pomegranate is red.", exampleArabic: "الرمان أحمر", category: "فواكه" },
    { id: 1219, word: "apricot", arabic: "مشمش", pronunciation: "أبريكوت", example: "Apricots are orange.", exampleArabic: "المشمش برتقالي", category: "فواكه" },
    { id: 1220, word: "raspberry", arabic: "توت", pronunciation: "رازبيري", example: "Raspberries are small.", exampleArabic: "التوت صغير", category: "فواكه" },

    // ========== خضروات ========== (20 كلمة)
    { id: 1301, word: "carrot", arabic: "جزر", pronunciation: "كاروت", example: "Carrots are good for eyes.", exampleArabic: "الجزر مفيد للعيون", category: "خضروات" },
    { id: 1302, word: "potato", arabic: "بطاطس", pronunciation: "بوتيتو", example: "Potatoes are delicious.", exampleArabic: "البطاطس لذيذة", category: "خضروات" },
    { id: 1303, word: "tomato", arabic: "طماطم", pronunciation: "توماتو", example: "Tomatoes are red.", exampleArabic: "الطماطم حمراء", category: "خضروات" },
    { id: 1304, word: "onion", arabic: "بصل", pronunciation: "أونيون", example: "Onions make you cry.", exampleArabic: "البصل يبكيك", category: "خضروات" },
    { id: 1305, word: "garlic", arabic: "ثوم", pronunciation: "غارليك", example: "Garlic is strong.", exampleArabic: "الثوم قوي", category: "خضروات" },
    { id: 1306, word: "cucumber", arabic: "خيار", pronunciation: "كيوكمبر", example: "Cucumber is fresh.", exampleArabic: "الخيار طازج", category: "خضروات" },
    { id: 1307, word: "pepper", arabic: "فلفل", pronunciation: "بيبر", example: "Pepper can be hot.", exampleArabic: "الفلفل قد يكون حاراً", category: "خضروات" },
    { id: 1308, word: "lettuce", arabic: "خس", pronunciation: "ليتس", example: "Lettuce is green.", exampleArabic: "الخس أخضر", category: "خضروات" },
    { id: 1309, word: "cabbage", arabic: "كرنب", pronunciation: "كابدج", example: "Cabbage is healthy.", exampleArabic: "الكرنب صحي", category: "خضروات" },
    { id: 1310, word: "broccoli", arabic: "بروكلي", pronunciation: "بروكلي", example: "Broccoli is good for you.", exampleArabic: "البروكلي مفيد لك", category: "خضروات" },
    { id: 1311, word: "cauliflower", arabic: "قرنبيط", pronunciation: "كوليفلاور", example: "Cauliflower is white.", exampleArabic: "القرنبيط أبيض", category: "خضروات" },
    { id: 1312, word: "spinach", arabic: "سبانخ", pronunciation: "سبانش", example: "Spinach is healthy.", exampleArabic: "السبانخ صحي", category: "خضروات" },
    { id: 1313, word: "eggplant", arabic: "باذنجان", pronunciation: "إيغبلانت", example: "Eggplant is purple.", exampleArabic: "الباذنجان بنفسجي", category: "خضروات" },
    { id: 1314, word: "zucchini", arabic: "كوسة", pronunciation: "زوكيني", example: "Zucchini is green.", exampleArabic: "الكوسة خضراء", category: "خضروات" },
    { id: 1315, word: "peas", arabic: "بازلاء", pronunciation: "بيز", example: "Peas are small.", exampleArabic: "البازلاء صغيرة", category: "خضروات" },
    { id: 1316, word: "beans", arabic: "فاصوليا", pronunciation: "بينز", example: "Beans are healthy.", exampleArabic: "الفاصوليا صحية", category: "خضروات" },
    { id: 1317, word: "corn", arabic: "ذرة", pronunciation: "كورن", example: "Corn is yellow.", exampleArabic: "الذرة صفراء", category: "خضروات" },
    { id: 1318, word: "mushroom", arabic: "فطر", pronunciation: "مشروم", example: "Mushrooms are fungi.", exampleArabic: "الفطر فطريات", category: "خضروات" },
    { id: 1319, word: "radish", arabic: "فجل", pronunciation: "راديش", example: "Radish is spicy.", exampleArabic: "الفجل حار", category: "خضروات" },
    { id: 1320, word: "pumpkin", arabic: "يقطين", pronunciation: "بامبكن", example: "Pumpkin is orange.", exampleArabic: "اليقطين برتقالي", category: "خضروات" },

    // ========== حيوانات ========== (20 كلمة)
    { id: 1401, word: "cat", arabic: "قطة", pronunciation: "كات", example: "The cat is sleeping.", exampleArabic: "القطة نائمة", category: "حيوانات" },
    { id: 1402, word: "dog", arabic: "كلب", pronunciation: "دوج", example: "The dog is barking.", exampleArabic: "الكلب ينبح", category: "حيوانات" },
    { id: 1403, word: "lion", arabic: "أسد", pronunciation: "لايون", example: "The lion is strong.", exampleArabic: "الأسد قوي", category: "حيوانات" },
    { id: 1404, word: "tiger", arabic: "نمر", pronunciation: "تيغر", example: "Tigers have stripes.", exampleArabic: "النمور لها خطوط", category: "حيوانات" },
    { id: 1405, word: "elephant", arabic: "فيل", pronunciation: "إليفنت", example: "The elephant is big.", exampleArabic: "الفيل كبير", category: "حيوانات" },
    { id: 1406, word: "giraffe", arabic: "زرافة", pronunciation: "جيراف", example: "The giraffe is tall.", exampleArabic: "الزرافة طويلة", category: "حيوانات" },
    { id: 1407, word: "monkey", arabic: "قرد", pronunciation: "مانكي", example: "Monkeys love bananas.", exampleArabic: "القرود تحب الموز", category: "حيوانات" },
    { id: 1408, word: "bird", arabic: "طائر", pronunciation: "بيرد", example: "The bird is flying.", exampleArabic: "الطائر يطير", category: "حيوانات" },
    { id: 1409, word: "fish", arabic: "سمكة", pronunciation: "فيش", example: "The fish is swimming.", exampleArabic: "السمكة تسبح", category: "حيوانات" },
    { id: 1410, word: "horse", arabic: "حصان", pronunciation: "هورس", example: "The horse runs fast.", exampleArabic: "الحصان يركض بسرعة", category: "حيوانات" },
    { id: 1411, word: "cow", arabic: "بقرة", pronunciation: "كاو", example: "Cows give milk.", exampleArabic: "الأبقار تعطي حليباً", category: "حيوانات" },
    { id: 1412, word: "sheep", arabic: "خروف", pronunciation: "شيب", example: "Sheep have wool.", exampleArabic: "الخراف لديها صوف", category: "حيوانات" },
    { id: 1413, word: "goat", arabic: "ماعز", pronunciation: "غوت", example: "Goats climb mountains.", exampleArabic: "الماعز يتسلق الجبال", category: "حيوانات" },
    { id: 1414, word: "chicken", arabic: "دجاجة", pronunciation: "تشيكن", example: "Chickens lay eggs.", exampleArabic: "الدجاج يبيض", category: "حيوانات" },
    { id: 1415, word: "duck", arabic: "بطة", pronunciation: "داك", example: "Ducks swim in water.", exampleArabic: "البط يسبح في الماء", category: "حيوانات" },
    { id: 1416, word: "rabbit", arabic: "أرنب", pronunciation: "رابت", example: "Rabbits eat carrots.", exampleArabic: "الأرانب تأكل الجزر", category: "حيوانات" },
    { id: 1417, word: "fox", arabic: "ثعلب", pronunciation: "فوكس", example: "The fox is clever.", exampleArabic: "الثعلب ذكي", category: "حيوانات" },
    { id: 1418, word: "bear", arabic: "دب", pronunciation: "بير", example: "Bears love honey.", exampleArabic: "الدببة تحب العسل", category: "حيوانات" },
    { id: 1419, word: "wolf", arabic: "ذئب", pronunciation: "وولف", example: "Wolves howl at night.", exampleArabic: "الذئاب تعوي في الليل", category: "حيوانات" },
    { id: 1420, word: "deer", arabic: "غزال", pronunciation: "دير", example: "Deer run fast.", exampleArabic: "الغزلان تجري بسرعة", category: "حيوانات" },

    // ========== عائلة ========== (20 كلمة)
    { id: 1501, word: "mother", arabic: "أم", pronunciation: "ماذر", example: "My mother loves me.", exampleArabic: "أمي تحبني", category: "عائلة" },
    { id: 1502, word: "father", arabic: "أب", pronunciation: "فاذر", example: "My father works hard.", exampleArabic: "أبي يعمل بجد", category: "عائلة" },
    { id: 1503, word: "brother", arabic: "أخ", pronunciation: "براذر", example: "I play with my brother.", exampleArabic: "ألعب مع أخي", category: "عائلة" },
    { id: 1504, word: "sister", arabic: "أخت", pronunciation: "سيستر", example: "My sister is kind.", exampleArabic: "أختي لطيفة", category: "عائلة" },
    { id: 1505, word: "son", arabic: "ابن", pronunciation: "سان", example: "My son is young.", exampleArabic: "ابني صغير", category: "عائلة" },
    { id: 1506, word: "daughter", arabic: "ابنة", pronunciation: "دوتير", example: "My daughter is pretty.", exampleArabic: "ابنتي جميلة", category: "عائلة" },
    { id: 1507, word: "grandmother", arabic: "جدة", pronunciation: "غراندماذر", example: "My grandmother cooks well.", exampleArabic: "جدتي تطبخ جيداً", category: "عائلة" },
    { id: 1508, word: "grandfather", arabic: "جد", pronunciation: "غراندفاذر", example: "My grandfather tells stories.", exampleArabic: "جدي يحكي قصصاً", category: "عائلة" },
    { id: 1509, word: "uncle", arabic: "عم/خال", pronunciation: "أنكل", example: "My uncle is funny.", exampleArabic: "عمي مضحك", category: "عائلة" },
    { id: 1510, word: "aunt", arabic: "عمة/خالة", pronunciation: "آنت", example: "My aunt is nice.", exampleArabic: "عمتي لطيفة", category: "عائلة" },
    { id: 1511, word: "cousin", arabic: "ابن عم/خال", pronunciation: "كازن", example: "I play with my cousin.", exampleArabic: "ألعب مع ابن عمي", category: "عائلة" },
    { id: 1512, word: "baby", arabic: "طفل", pronunciation: "بيبي", example: "The baby is sleeping.", exampleArabic: "الطفل نائم", category: "عائلة" },
    { id: 1513, word: "parents", arabic: "والدان", pronunciation: "بيرنتس", example: "My parents love me.", exampleArabic: "والداي يحباني", category: "عائلة" },
    { id: 1514, word: "children", arabic: "أطفال", pronunciation: "تشيلدرن", example: "The children are playing.", exampleArabic: "الأطفال يلعبون", category: "عائلة" },
    { id: 1515, word: "husband", arabic: "زوج", pronunciation: "هازبند", example: "My husband is kind.", exampleArabic: "زوجي لطيف", category: "عائلة" },
    { id: 1516, word: "wife", arabic: "زوجة", pronunciation: "وايف", example: "My wife is beautiful.", exampleArabic: "زوجتي جميلة", category: "عائلة" },
    { id: 1517, word: "family", arabic: "أسرة", pronunciation: "فاميلي", example: "I love my family.", exampleArabic: "أنا أحب أسرتي", category: "عائلة" },
    { id: 1518, word: "twin", arabic: "توأم", pronunciation: "توين", example: "They are twins.", exampleArabic: "هم توأم", category: "عائلة" },
    { id: 1519, word: "stepfather", arabic: "زوج الأم", pronunciation: "ستيبفاذر", example: "My stepfather is nice.", exampleArabic: "زوج أمي لطيف", category: "عائلة" },
    { id: 1520, word: "stepmother", arabic: "زوجة الأب", pronunciation: "ستيبماذر", example: "My stepmother cares for me.", exampleArabic: "زوجة أبي تهتم بي", category: "عائلة" },

    // ========== مشاعر ========== (20 كلمة)
    { id: 1601, word: "happy", arabic: "سعيد", pronunciation: "هابي", example: "I am happy today.", exampleArabic: "أنا سعيد اليوم", category: "مشاعر" },
    { id: 1602, word: "sad", arabic: "حزين", pronunciation: "ساد", example: "She is sad.", exampleArabic: "هي حزينة", category: "مشاعر" },
    { id: 1603, word: "angry", arabic: "غاضب", pronunciation: "أنغري", example: "He is angry.", exampleArabic: "هو غاضب", category: "مشاعر" },
    { id: 1604, word: "scared", arabic: "خائف", pronunciation: "سكارد", example: "I am scared of dogs.", exampleArabic: "أنا خائف من الكلاب", category: "مشاعر" },
    { id: 1605, word: "excited", arabic: "متحمس", pronunciation: "إكسايتد", example: "I am excited for the party.", exampleArabic: "أنا متحمس للحفلة", category: "مشاعر" },
    { id: 1606, word: "tired", arabic: "متعب", pronunciation: "تايرد", example: "I am tired after work.", exampleArabic: "أنا متعب بعد العمل", category: "مشاعر" },
    { id: 1607, word: "bored", arabic: "يشعر بالملل", pronunciation: "بورد", example: "I am bored at home.", exampleArabic: "أنا أشعر بالملل في المنزل", category: "مشاعر" },
    { id: 1608, word: "surprised", arabic: "متفاجئ", pronunciation: "سوربرايزد", example: "I was surprised!", exampleArabic: "كنت متفاجئاً!", category: "مشاعر" },
    { id: 1609, word: "worried", arabic: "قلق", pronunciation: "وريد", example: "I am worried about you.", exampleArabic: "أنا قلق عليك", category: "مشاعر" },
    { id: 1610, word: "confused", arabic: "مرتبك", pronunciation: "كونفيوزد", example: "I am confused.", exampleArabic: "أنا مرتبك", category: "مشاعر" },
    { id: 1611, word: "jealous", arabic: "غيور", pronunciation: "جيلوس", example: "He is jealous.", exampleArabic: "هو غيور", category: "مشاعر" },
    { id: 1612, word: "proud", arabic: "فخور", pronunciation: "براود", example: "I am proud of you.", exampleArabic: "أنا فخور بك", category: "مشاعر" },
    { id: 1613, word: "shy", arabic: "خجول", pronunciation: "شاي", example: "She is shy.", exampleArabic: "هي خجولة", category: "مشاعر" },
    { id: 1614, word: "lonely", arabic: "وحيد", pronunciation: "لونلي", example: "I feel lonely.", exampleArabic: "أشعر بالوحدة", category: "مشاعر" },
    { id: 1615, word: "love", arabic: "حب", pronunciation: "لوف", example: "I love my family.", exampleArabic: "أنا أحب عائلتي", category: "مشاعر" },
    { id: 1616, word: "hate", arabic: "كره", pronunciation: "هيت", example: "I hate lies.", exampleArabic: "أنا أكره الكذب", category: "مشاعر" },
    { id: 1617, word: "calm", arabic: "هادئ", pronunciation: "كالم", example: "Stay calm.", exampleArabic: "ابق هادئاً", category: "مشاعر" },
    { id: 1618, word: "nervous", arabic: "عصبي", pronunciation: "نيرفوس", example: "I am nervous before exams.", exampleArabic: "أنا عصبي قبل الامتحانات", category: "مشاعر" },
    { id: 1619, word: "grateful", arabic: "ممتن", pronunciation: "غريتفول", example: "I am grateful for your help.", exampleArabic: "أنا ممتن لمساعدتك", category: "مشاعر" },
    { id: 1620, word: "hopeful", arabic: "متفائل", pronunciation: "هوبفول", example: "I am hopeful for the future.", exampleArabic: "أنا متفائل بالمستقبل", category: "مشاعر" },
];

// التحقق من التحميل
console.log('✅ beginner-data.js loaded with', BEGINNER_WORDS.length, 'words');
