// beginner-data.js - 500 كلمة للمستوى المبتدئ (كلمات بسيطة يومية)
const BEGINNER_WORDS = [
    // تحيات ومجاملات
    { id: 1001, word: "hello", arabic: "مرحباً", pronunciation: "هالو", example: "Hello, how are you?", exampleArabic: "مرحباً، كيف حالك؟", category: "تحيات" },
    { id: 1002, word: "goodbye", arabic: "وداعاً", pronunciation: "جود باي", example: "Goodbye, see you tomorrow.", exampleArabic: "وداعاً، أراك غداً", category: "تحيات" },
    { id: 1003, word: "good morning", arabic: "صباح الخير", pronunciation: "جود مورنينغ", example: "Good morning, everyone!", exampleArabic: "صباح الخير للجميع!", category: "تحيات" },
    { id: 1004, word: "good afternoon", arabic: "مساء الخير", pronunciation: "جود آفترنون", example: "Good afternoon, how was your day?", exampleArabic: "مساء الخير، كيف كان يومك؟", category: "تحيات" },
    { id: 1005, word: "good evening", arabic: "مساء الخير", pronunciation: "جود إيفنينغ", example: "Good evening, nice to see you.", exampleArabic: "مساء الخير، سعيد برؤيتك", category: "تحيات" },
    { id: 1006, word: "good night", arabic: "تصبح على خير", pronunciation: "جود نايت", example: "Good night, sleep well.", exampleArabic: "تصبح على خير، نم جيداً", category: "تحيات" },
    { id: 1007, word: "please", arabic: "من فضلك", pronunciation: "بليز", example: "Please sit down.", exampleArabic: "من فضلك اجلس", category: "تحيات" },
    { id: 1008, word: "thank you", arabic: "شكراً لك", pronunciation: "ثانك يو", example: "Thank you for your help.", exampleArabic: "شكراً لك على مساعدتك", category: "تحيات" },
    { id: 1009, word: "thanks", arabic: "شكراً", pronunciation: "ثانكس", example: "Thanks very much!", exampleArabic: "شكراً جزيلاً!", category: "تحيات" },
    { id: 1010, word: "welcome", arabic: "أهلاً وسهلاً", pronunciation: "ويلكم", example: "Welcome to our home!", exampleArabic: "أهلاً وسهلاً في منزلنا!", category: "تحيات" },
    { id: 1011, word: "you're welcome", arabic: "عفواً", pronunciation: "يور ويلكم", example: "You're welcome, anytime.", exampleArabic: "عفواً، في أي وقت", category: "تحيات" },
    { id: 1012, word: "sorry", arabic: "آسف", pronunciation: "سوري", example: "I'm sorry, I'm late.", exampleArabic: "أنا آسف، أنا متأخر", category: "تحيات" },
    { id: 1013, word: "excuse me", arabic: "عذراً", pronunciation: "إكسكيو مي", example: "Excuse me, where is the bathroom?", exampleArabic: "عذراً، أين الحمام؟", category: "تحيات" },
    { id: 1014, word: "yes", arabic: "نعم", pronunciation: "يس", example: "Yes, I understand.", exampleArabic: "نعم، أنا أفهم", category: "تحيات" },
    { id: 1015, word: "no", arabic: "لا", pronunciation: "نو", example: "No, thank you.", exampleArabic: "لا، شكراً", category: "تحيات" },
    { id: 1016, word: "okay", arabic: "حسناً", pronunciation: "أوكي", example: "Okay, I'll do it.", exampleArabic: "حسناً، سأفعلها", category: "تحيات" },
    { id: 1017, word: "how are you", arabic: "كيف حالك", pronunciation: "هاو آر يو", example: "Hello, how are you today?", exampleArabic: "مرحباً، كيف حالك اليوم؟", category: "تحيات" },
    { id: 1018, word: "I'm fine", arabic: "أنا بخير", pronunciation: "آيم فاين", example: "I'm fine, thank you.", exampleArabic: "أنا بخير، شكراً", category: "تحيات" },
    { id: 1019, word: "nice to meet you", arabic: "تشرفت بمقابلتك", pronunciation: "نايس تو ميت يو", example: "Nice to meet you, I'm Ahmed.", exampleArabic: "تشرفت بمقابلتك، أنا أحمد", category: "تحيات" },
    { id: 1020, word: "see you later", arabic: "أراك لاحقاً", pronunciation: "سي يو ليتير", example: "I have to go, see you later!", exampleArabic: "يجب أن أذهب، أراك لاحقاً!", category: "تحيات" },
    { id: 1021, word: "take care", arabic: "اعتني بنفسك", pronunciation: "تيك كير", example: "Take care of yourself!", exampleArabic: "اعتني بنفسك!", category: "تحيات" },
    { id: 1022, word: "have a nice day", arabic: "أتمنى لك يوماً سعيداً", pronunciation: "هاف أ نايس داي", example: "Goodbye, have a nice day!", exampleArabic: "وداعاً، أتمنى لك يوماً سعيداً!", category: "تحيات" },
    { id: 1023, word: "nice to see you", arabic: "سعيد برؤيتك", pronunciation: "نايس تو سي يو", example: "Nice to see you again!", exampleArabic: "سعيد برؤيتك مجدداً!", category: "تحيات" },
    { id: 1024, word: "long time no see", arabic: "لم أرك منذ فترة", pronunciation: "لونغ تايم نو سي", example: "Long time no see, how have you been?", exampleArabic: "لم أرك منذ فترة، كيف كان حالك؟", category: "تحيات" },
    { id: 1025, word: "take it easy", arabic: "خذ الأمر ببساطة", pronunciation: "تيك إت إيزي", example: "Take it easy and relax.", exampleArabic: "خذ الأمر ببساطة واسترخِ", category: "تحيات" },

    // المنزل والأثاث
    { id: 1101, word: "house", arabic: "منزل", pronunciation: "هاوس", example: "I live in a big house.", exampleArabic: "أنا أعيش في منزل كبير", category: "منزل" },
    { id: 1102, word: "apartment", arabic: "شقة", pronunciation: "أبارتمنت", example: "She lives in an apartment.", exampleArabic: "هي تعيش في شقة", category: "منزل" },
    { id: 1103, word: "room", arabic: "غرفة", pronunciation: "روم", example: "This is my room.", exampleArabic: "هذه غرفتي", category: "منزل" },
    { id: 1104, word: "living room", arabic: "غرفة معيشة", pronunciation: "ليفينغ روم", example: "We watch TV in the living room.", exampleArabic: "نشاهد التلفاز في غرفة المعيشة", category: "منزل" },
    { id: 1105, word: "bedroom", arabic: "غرفة نوم", pronunciation: "بيدروم", example: "My bedroom is small.", exampleArabic: "غرفة نومي صغيرة", category: "منزل" },
    { id: 1106, word: "kitchen", arabic: "مطبخ", pronunciation: "كيتشن", example: "My mother cooks in the kitchen.", exampleArabic: "أمي تطبخ في المطبخ", category: "منزل" },
    { id: 1107, word: "bathroom", arabic: "حمام", pronunciation: "باثروم", example: "Where is the bathroom?", exampleArabic: "أين الحمام؟", category: "منزل" },
    { id: 1108, word: "door", arabic: "باب", pronunciation: "دور", example: "Please close the door.", exampleArabic: "من فضلك أغلق الباب", category: "منزل" },
    { id: 1109, word: "window", arabic: "نافذة", pronunciation: "ويندو", example: "Open the window, please.", exampleArabic: "افتح النافذة من فضلك", category: "منزل" },
    { id: 1110, word: "wall", arabic: "جدار", pronunciation: "وول", example: "The wall is white.", exampleArabic: "الجدار أبيض", category: "منزل" },
    { id: 1111, word: "floor", arabic: "أرضية", pronunciation: "فلور", example: "The floor is clean.", exampleArabic: "الأرضية نظيفة", category: "منزل" },
    { id: 1112, word: "ceiling", arabic: "سقف", pronunciation: "سيلينغ", example: "The ceiling is high.", exampleArabic: "السقف مرتفع", category: "منزل" },
    { id: 1113, word: "bed", arabic: "سرير", pronunciation: "بيد", example: "I sleep on my bed.", exampleArabic: "أنام على سريري", category: "منزل" },
    { id: 1114, word: "table", arabic: "طاولة", pronunciation: "تيبل", example: "Put the book on the table.", exampleArabic: "ضع الكتاب على الطاولة", category: "منزل" },
    { id: 1115, word: "chair", arabic: "كرسي", pronunciation: "تشير", example: "Sit on the chair.", exampleArabic: "اجلس على الكرسي", category: "منزل" },
    { id: 1116, word: "sofa", arabic: "أريكة", pronunciation: "سوفا", example: "The sofa is comfortable.", exampleArabic: "الأريكة مريحة", category: "منزل" },
    { id: 1117, word: "desk", arabic: "مكتب", pronunciation: "ديسك", example: "I study at my desk.", exampleArabic: "أدرس على مكتبي", category: "منزل" },
    { id: 1118, word: "lamp", arabic: "مصباح", pronunciation: "لامب", example: "Turn on the lamp.", exampleArabic: "شغل المصباح", category: "منزل" },
    { id: 1119, word: "light", arabic: "ضوء", pronunciation: "لايت", example: "The light is bright.", exampleArabic: "الضوء ساطع", category: "منزل" },
    { id: 1120, word: "clock", arabic: "ساعة", pronunciation: "كلوك", example: "The clock on the wall.", exampleArabic: "الساعة على الحائط", category: "منزل" },
    { id: 1121, word: "mirror", arabic: "مرآة", pronunciation: "ميرور", example: "Look in the mirror.", exampleArabic: "انظر في المرآة", category: "منزل" },
    { id: 1122, word: "carpet", arabic: "سجادة", pronunciation: "كاربت", example: "The carpet is soft.", exampleArabic: "السجادة ناعمة", category: "منزل" },
    { id: 1123, word: "curtain", arabic: "ستارة", pronunciation: "كيرتن", example: "Open the curtains.", exampleArabic: "افتح الستائر", category: "منزل" },
    { id: 1124, word: "pillow", arabic: "وسادة", pronunciation: "بيلو", example: "I need a soft pillow.", exampleArabic: "أحتاج وسادة ناعمة", category: "منزل" },
    { id: 1125, word: "blanket", arabic: "بطانية", pronunciation: "بلانكت", example: "The blanket is warm.", exampleArabic: "البطانية دافئة", category: "منزل" },

    // العائلة والعلاقات
    { id: 1201, word: "family", arabic: "عائلة", pronunciation: "فاميلي", example: "I love my family.", exampleArabic: "أنا أحب عائلتي", category: "عائلة" },
    { id: 1202, word: "mother", arabic: "أم", pronunciation: "ماذر", example: "My mother is kind.", exampleArabic: "أمي لطيفة", category: "عائلة" },
    { id: 1203, word: "father", arabic: "أب", pronunciation: "فاذر", example: "My father works hard.", exampleArabic: "أبي يعمل بجد", category: "عائلة" },
    { id: 1204, word: "parents", arabic: "والدان", pronunciation: "بيرنتس", example: "My parents love me.", exampleArabic: "والداي يحباني", category: "عائلة" },
    { id: 1205, word: "brother", arabic: "أخ", pronunciation: "براذر", example: "I play with my brother.", exampleArabic: "ألعب مع أخي", category: "عائلة" },
    { id: 1206, word: "sister", arabic: "أخت", pronunciation: "سيستر", example: "My sister is younger.", exampleArabic: "أختي أصغر مني", category: "عائلة" },
    { id: 1207, word: "son", arabic: "ابن", pronunciation: "سان", example: "My son is a student.", exampleArabic: "ابني طالب", category: "عائلة" },
    { id: 1208, word: "daughter", arabic: "ابنة", pronunciation: "دوتير", example: "My daughter is pretty.", exampleArabic: "ابنتي جميلة", category: "عائلة" },
    { id: 1209, word: "baby", arabic: "طفل", pronunciation: "بيبي", example: "The baby is sleeping.", exampleArabic: "الطفل نائم", category: "عائلة" },
    { id: 1210, word: "children", arabic: "أطفال", pronunciation: "تشيلدرن", example: "The children are playing.", exampleArabic: "الأطفال يلعبون", category: "عائلة" },
    { id: 1211, word: "grandmother", arabic: "جدة", pronunciation: "غراندماذر", example: "My grandmother tells stories.", exampleArabic: "جدتي تحكي قصصاً", category: "عائلة" },
    { id: 1212, word: "grandfather", arabic: "جد", pronunciation: "غراندفاذر", example: "My grandfather is old.", exampleArabic: "جدي كبير في السن", category: "عائلة" },
    { id: 1213, word: "grandparents", arabic: "أجداد", pronunciation: "غراندبيرنتس", example: "I visit my grandparents.", exampleArabic: "أزور أجدادي", category: "عائلة" },
    { id: 1214, word: "uncle", arabic: "عم/خال", pronunciation: "أنكل", example: "My uncle is funny.", exampleArabic: "عمي مضحك", category: "عائلة" },
    { id: 1215, word: "aunt", arabic: "عمة/خالة", pronunciation: "آنت", example: "My aunt cooks well.", exampleArabic: "عمتي تطبخ جيداً", category: "عائلة" },
    { id: 1216, word: "cousin", arabic: "ابن عم/خال", pronunciation: "كازن", example: "I play with my cousin.", exampleArabic: "ألعب مع ابن عمي", category: "عائلة" },
    { id: 1217, word: "husband", arabic: "زوج", pronunciation: "هازبند", example: "My husband is kind.", exampleArabic: "زوجي لطيف", category: "عائلة" },
    { id: 1218, word: "wife", arabic: "زوجة", pronunciation: "وايف", example: "My wife is beautiful.", exampleArabic: "زوجتي جميلة", category: "عائلة" },
    { id: 1219, word: "friend", arabic: "صديق", pronunciation: "فريند", example: "He is my best friend.", exampleArabic: "هو صديقي المفضل", category: "عائلة" },
    { id: 1220, word: "neighbor", arabic: "جار", pronunciation: "نيبر", example: "Our neighbor is friendly.", exampleArabic: "جارنا ودود", category: "عائلة" },
    { id: 1221, word: "guest", arabic: "ضيف", pronunciation: "جيست", example: "We have guests today.", exampleArabic: "لدينا ضيوف اليوم", category: "عائلة" },
    { id: 1222, word: "host", arabic: "مضيف", pronunciation: "هوست", example: "He is a good host.", exampleArabic: "هو مضيف جيد", category: "عائلة" },
    { id: 1223, word: "twin", arabic: "توأم", pronunciation: "توين", example: "They are twins.", exampleArabic: "هما توأم", category: "عائلة" },
    { id: 1224, word: "relative", arabic: "قريب", pronunciation: "ريلاتيف", example: "We have relatives in Canada.", exampleArabic: "لدينا أقارب في كندا", category: "عائلة" },
    { id: 1225, word: "fiancé", arabic: "خطيب", pronunciation: "فيانسي", example: "My fiancé is from Egypt.", exampleArabic: "خطيبي من مصر", category: "عائلة" },

    // الطعام والشراب
    { id: 1301, word: "food", arabic: "طعام", pronunciation: "فود", example: "The food is delicious.", exampleArabic: "الطعام لذيذ", category: "طعام" },
    { id: 1302, word: "drink", arabic: "شراب", pronunciation: "درينك", example: "I want a cold drink.", exampleArabic: "أريد شراباً بارداً", category: "طعام" },
    { id: 1303, word: "water", arabic: "ماء", pronunciation: "ووتر", example: "Drink water every day.", exampleArabic: "اشرب الماء كل يوم", category: "طعام" },
    { id: 1304, word: "milk", arabic: "حليب", pronunciation: "ميلك", example: "Children drink milk.", exampleArabic: "الأطفال يشربون الحليب", category: "طعام" },
    { id: 1305, word: "juice", arabic: "عصير", pronunciation: "جوس", example: "I like orange juice.", exampleArabic: "أحب عصير البرتقال", category: "طعام" },
    { id: 1306, word: "coffee", arabic: "قهوة", pronunciation: "كوفي", example: "I drink coffee in the morning.", exampleArabic: "أشرب القهوة في الصباح", category: "طعام" },
    { id: 1307, word: "tea", arabic: "شاي", pronunciation: "تي", example: "Would you like some tea?", exampleArabic: "هل تريد بعض الشاي؟", category: "طعام" },
    { id: 1308, word: "bread", arabic: "خبز", pronunciation: "بريد", example: "Fresh bread from the oven.", exampleArabic: "خبز طازج من الفرن", category: "طعام" },
    { id: 1309, word: "rice", arabic: "أرز", pronunciation: "رايس", example: "Rice with chicken is delicious.", exampleArabic: "الأرز بالدجاج لذيذ", category: "طعام" },
    { id: 1310, word: "meat", arabic: "لحم", pronunciation: "ميت", example: "I eat meat once a week.", exampleArabic: "أكل اللحم مرة في الأسبوع", category: "طعام" },
    { id: 1311, word: "chicken", arabic: "دجاج", pronunciation: "تشيكن", example: "Grilled chicken is healthy.", exampleArabic: "الدجاج المشوي صحي", category: "طعام" },
    { id: 1312, word: "fish", arabic: "سمك", pronunciation: "فيش", example: "I like fried fish.", exampleArabic: "أحب السمك المقلي", category: "طعام" },
    { id: 1313, word: "egg", arabic: "بيض", pronunciation: "إيغ", example: "I eat an egg for breakfast.", exampleArabic: "أكل بيضة على الفطور", category: "طعام" },
    { id: 1314, word: "cheese", arabic: "جبن", pronunciation: "تشيز", example: "Sandwich with cheese.", exampleArabic: "ساندويتش بالجبن", category: "طعام" },
    { id: 1315, word: "apple", arabic: "تفاح", pronunciation: "آبل", example: "An apple a day keeps the doctor away.", exampleArabic: "تفاحة في اليوم تبعد الطبيب", category: "طعام" },
    { id: 1316, word: "banana", arabic: "موز", pronunciation: "بانانا", example: "Bananas are yellow.", exampleArabic: "الموز أصفر", category: "طعام" },
    { id: 1317, word: "orange", arabic: "برتقال", pronunciation: "أورانج", example: "Oranges are rich in vitamin C.", exampleArabic: "البرتقال غني بفيتامين سي", category: "طعام" },
    { id: 1318, word: "tomato", arabic: "طماطم", pronunciation: "توماتو", example: "Tomatoes are red.", exampleArabic: "الطماطم حمراء", category: "طعام" },
    { id: 1319, word: "potato", arabic: "بطاطس", pronunciation: "بوتيتو", example: "I like fried potatoes.", exampleArabic: "أحب البطاطس المقلية", category: "طعام" },
    { id: 1320, word: "salad", arabic: "سلطة", pronunciation: "سلاد", example: "Fresh salad with vegetables.", exampleArabic: "سلطة طازجة بالخضروات", category: "طعام" },
    { id: 1321, word: "soup", arabic: "شوربة", pronunciation: "سوب", example: "Hot soup in winter.", exampleArabic: "شوربة ساخنة في الشتاء", category: "طعام" },
    { id: 1322, word: "breakfast", arabic: "فطور", pronunciation: "بريكفاست", example: "Breakfast is the most important meal.", exampleArabic: "الفطور أهم وجبة", category: "طعام" },
    { id: 1323, word: "lunch", arabic: "غداء", pronunciation: "لانتش", example: "I have lunch at 1 pm.", exampleArabic: "أتناول الغداء الساعة 1 ظهراً", category: "طعام" },
    { id: 1324, word: "dinner", arabic: "عشاء", pronunciation: "دينر", example: "We have dinner together.", exampleArabic: "نتناول العشاء معاً", category: "طعام" },
    { id: 1325, word: "dessert", arabic: "حلوى", pronunciation: "ديزرت", example: "I love chocolate dessert.", exampleArabic: "أحب حلوى الشوكولاتة", category: "طعام" },

    // التسوق والمال
    { id: 1401, word: "shop", arabic: "متجر", pronunciation: "شوب", example: "I go to the shop.", exampleArabic: "أذهب إلى المتجر", category: "تسوق" },
    { id: 1402, word: "store", arabic: "متجر", pronunciation: "ستور", example: "The store is open.", exampleArabic: "المتجر مفتوح", category: "تسوق" },
    { id: 1403, word: "market", arabic: "سوق", pronunciation: "ماركت", example: "We buy vegetables from the market.", exampleArabic: "نشتري الخضروات من السوق", category: "تسوق" },
    { id: 1404, word: "supermarket", arabic: "سوبرماركت", pronunciation: "سوبرماركت", example: "I go to the supermarket every week.", exampleArabic: "أذهب للسوبرماركت كل أسبوع", category: "تسوق" },
    { id: 1405, word: "mall", arabic: "مول", pronunciation: "مول", example: "The mall is crowded on Friday.", exampleArabic: "المول مزدحم يوم الجمعة", category: "تسوق" },
    { id: 1406, word: "buy", arabic: "يشتري", pronunciation: "باي", example: "I want to buy a new phone.", exampleArabic: "أريد شراء هاتف جديد", category: "تسوق" },
    { id: 1407, word: "sell", arabic: "يبيع", pronunciation: "سيل", example: "They sell fresh fruit.", exampleArabic: "يبيعون فواكه طازجة", category: "تسوق" },
    { id: 1408, word: "pay", arabic: "يدفع", pronunciation: "باي", example: "I pay at the counter.", exampleArabic: "أدفع عند الشباك", category: "تسوق" },
    { id: 1409, word: "price", arabic: "سعر", pronunciation: "برايس", example: "The price is reasonable.", exampleArabic: "السعر معقول", category: "تسوق" },
    { id: 1410, word: "cost", arabic: "تكلفة", pronunciation: "كوست", example: "How much does it cost?", exampleArabic: "كم تكلفته؟", category: "تسوق" },
    { id: 1411, word: "cheap", arabic: "رخيص", pronunciation: "تشيب", example: "This shirt is cheap.", exampleArabic: "هذا القميص رخيص", category: "تسوق" },
    { id: 1412, word: "expensive", arabic: "غالي", pronunciation: "إكسبينسيف", example: "The car is expensive.", exampleArabic: "السيارة غالية", category: "تسوق" },
    { id: 1413, word: "money", arabic: "مال", pronunciation: "ماني", example: "Save your money.", exampleArabic: "وفر نقودك", category: "تسوق" },
    { id: 1414, word: "cash", arabic: "نقداً", pronunciation: "كاش", example: "I pay with cash.", exampleArabic: "أدفع نقداً", category: "تسوق" },
    { id: 1415, word: "credit card", arabic: "بطاقة ائتمان", pronunciation: "كريديت كارد", example: "I use my credit card.", exampleArabic: "أستخدم بطاقة الائتمان", category: "تسوق" },
    { id: 1416, word: "wallet", arabic: "محفظة", pronunciation: "ووليت", example: "I lost my wallet.", exampleArabic: "فقدت محفظتي", category: "تسوق" },
    { id: 1417, word: "basket", arabic: "سلة", pronunciation: "باسكت", example: "Put the items in the basket.", exampleArabic: "ضع الأغراض في السلة", category: "تسوق" },
    { id: 1418, word: "cart", arabic: "عربة", pronunciation: "كارط", example: "Use a shopping cart.", exampleArabic: "استخدم عربة التسوق", category: "تسوق" },
    { id: 1419, word: "discount", arabic: "خصم", pronunciation: "ديسكاونت", example: "There is a 20% discount.", exampleArabic: "هناك خصم 20٪", category: "تسوق" },
    { id: 1420, word: "sale", arabic: "تخفيضات", pronunciation: "سيل", example: "The store has a sale.", exampleArabic: "المتجر عنده تخفيضات", category: "تسوق" },
    { id: 1421, word: "receipt", arabic: "فاتورة", pronunciation: "ريسيبت", example: "Check your receipt.", exampleArabic: "تحقق من فاتورتك", category: "تسوق" },
    { id: 1422, word: "refund", arabic: "استرداد نقود", pronunciation: "ريفاند", example: "I want a refund.", exampleArabic: "أريد استرداد نقودي", category: "تسوق" },
    { id: 1423, word: "bargain", arabic: "مساومة", pronunciation: "بارغين", example: "I like to bargain.", exampleArabic: "أحب المساومة", category: "تسوق" },
    { id: 1424, word: "receipt", arabic: "وصل", pronunciation: "ريسيبت", example: "Here is your receipt.", exampleArabic: "هذا هو الوصل", category: "تسوق" },
    { id: 1425, word: "price tag", arabic: "بطاقة سعر", pronunciation: "برايس تاغ", example: "Look at the price tag.", exampleArabic: "انظر إلى بطاقة السعر", category: "تسوق" },

    // المواصلات والسفر
    { id: 1501, word: "car", arabic: "سيارة", pronunciation: "كار", example: "I drive a car.", exampleArabic: "أنا أقود سيارة", category: "مواصلات" },
    { id: 1502, word: "bus", arabic: "حافلة", pronunciation: "باس", example: "I take the bus to work.", exampleArabic: "أستقل الحافلة للعمل", category: "مواصلات" },
    { id: 1503, word: "train", arabic: "قطار", pronunciation: "ترين", example: "The train is fast.", exampleArabic: "القطار سريع", category: "مواصلات" },
    { id: 1504, word: "taxi", arabic: "تاكسي", pronunciation: "تاكسي", example: "Call a taxi, please.", exampleArabic: "اتصل بتاكسي من فضلك", category: "مواصلات" },
    { id: 1505, word: "bicycle", arabic: "دراجة", pronunciation: "بايسيكل", example: "I ride a bicycle.", exampleArabic: "أنا أركب دراجة", category: "مواصلات" },
    { id: 1506, word: "motorcycle", arabic: "دراجة نارية", pronunciation: "موتورسايكل", example: "He drives a motorcycle.", exampleArabic: "يقود دراجة نارية", category: "مواصلات" },
    { id: 1507, word: "airplane", arabic: "طائرة", pronunciation: "إيربلين", example: "I travel by airplane.", exampleArabic: "أسافر بالطائرة", category: "مواصلات" },
    { id: 1508, word: "ship", arabic: "سفينة", pronunciation: "شيب", example: "The ship sails on the sea.", exampleArabic: "السفينة تبحر في البحر", category: "مواصلات" },
    { id: 1509, word: "boat", arabic: "قارب", pronunciation: "بوت", example: "We ride a small boat.", exampleArabic: "نركب قارباً صغيراً", category: "مواصلات" },
    { id: 1510, word: "airport", arabic: "مطار", pronunciation: "إيربورت", example: "I arrive at the airport.", exampleArabic: "أصل إلى المطار", category: "مواصلات" },
    { id: 1511, word: "station", arabic: "محطة", pronunciation: "ستيشن", example: "The bus station is near.", exampleArabic: "محطة الحافلات قريبة", category: "مواصلات" },
    { id: 1512, word: "ticket", arabic: "تذكرة", pronunciation: "تيكيت", example: "I buy a ticket.", exampleArabic: "أشتري تذكرة", category: "مواصلات" },
    { id: 1513, word: "passport", arabic: "جواز سفر", pronunciation: "باسبورت", example: "Show your passport.", exampleArabic: "أظهر جواز سفرك", category: "مواصلات" },
    { id: 1514, word: "hotel", arabic: "فندق", pronunciation: "هوتيل", example: "I stay in a hotel.", exampleArabic: "أبقى في فندق", category: "مواصلات" },
    { id: 1515, word: "trip", arabic: "رحلة", pronunciation: "تريب", example: "We go on a trip.", exampleArabic: "نذهب في رحلة", category: "مواصلات" },
    { id: 1516, word: "travel", arabic: "يسافر", pronunciation: "ترافل", example: "I love to travel.", exampleArabic: "أحب السفر", category: "مواصلات" },
    { id: 1517, word: "drive", arabic: "يقود", pronunciation: "درايف", example: "He drives carefully.", exampleArabic: "يقود بحذر", category: "مواصلات" },
    { id: 1518, word: "ride", arabic: "يركب", pronunciation: "رايد", example: "I ride a bike.", exampleArabic: "أركب دراجة", category: "مواصلات" },
    { id: 1519, word: "fly", arabic: "يطير", pronunciation: "فلاي", example: "We fly to Paris.", exampleArabic: "نطير إلى باريس", category: "مواصلات" },
    { id: 1520, word: "sail", arabic: "يبحر", pronunciation: "سيل", example: "They sail on the boat.", exampleArabic: "يبحرون على القارب", category: "مواصلات" },
    { id: 1521, word: "arrive", arabic: "يصل", pronunciation: "أرايف", example: "We arrive at noon.", exampleArabic: "نصل ظهراً", category: "مواصلات" },
    { id: 1522, word: "depart", arabic: "يغادر", pronunciation: "ديبارت", example: "The train departs at 5.", exampleArabic: "القطار يغادر الساعة 5", category: "مواصلات" },
    { id: 1523, word: "luggage", arabic: "أمتعة", pronunciation: "لاغيدج", example: "My luggage is heavy.", exampleArabic: "أمتعتي ثقيلة", category: "مواصلات" },
    { id: 1524, word: "suitcase", arabic: "حقيبة سفر", pronunciation: "سوتكيس", example: "I packed my suitcase.", exampleArabic: "حزمت حقيبة سفري", category: "مواصلات" },
    { id: 1525, word: "destination", arabic: "وجهة", pronunciation: "ديستينيشن", example: "Our destination is London.", exampleArabic: "وجهتنا لندن", category: "مواصلات" },

    // الصحة والجسم
    { id: 1601, word: "health", arabic: "صحة", pronunciation: "هيلث", example: "Good health is important.", exampleArabic: "الصحة الجيدة مهمة", category: "صحة" },
    { id: 1602, word: "body", arabic: "جسم", pronunciation: "بودي", example: "The body needs exercise.", exampleArabic: "الجسم يحتاج لتمارين", category: "صحة" },
    { id: 1603, word: "head", arabic: "رأس", pronunciation: "هيد", example: "My head hurts.", exampleArabic: "رأسي يؤلمني", category: "صحة" },
    { id: 1604, word: "hair", arabic: "شعر", pronunciation: "هير", example: "She has long hair.", exampleArabic: "لديها شعر طويل", category: "صحة" },
    { id: 1605, word: "face", arabic: "وجه", pronunciation: "فيس", example: "Wash your face.", exampleArabic: "اغسل وجهك", category: "صحة" },
    { id: 1606, word: "eye", arabic: "عين", pronunciation: "آي", example: "She has blue eyes.", exampleArabic: "لديها عيون زرقاء", category: "صحة" },
    { id: 1607, word: "ear", arabic: "أذن", pronunciation: "إير", example: "I hear with my ears.", exampleArabic: "أسمع بأذني", category: "صحة" },
    { id: 1608, word: "nose", arabic: "أنف", pronunciation: "نوز", example: "I smell with my nose.", exampleArabic: "أشم بأنفي", category: "صحة" },
    { id: 1609, word: "mouth", arabic: "فم", pronunciation: "ماوث", example: "Open your mouth.", exampleArabic: "افتح فمك", category: "صحة" },
    { id: 1610, word: "tooth", arabic: "سن", pronunciation: "توث", example: "Brush your teeth.", exampleArabic: "نظف أسنانك", category: "صحة" },
    { id: 1611, word: "hand", arabic: "يد", pronunciation: "هاند", example: "Wash your hands.", exampleArabic: "اغسل يديك", category: "صحة" },
    { id: 1612, word: "arm", arabic: "ذراع", pronunciation: "آرم", example: "He broke his arm.", exampleArabic: "كسر ذراعه", category: "صحة" },
    { id: 1613, word: "leg", arabic: "ساق", pronunciation: "ليغ", example: "My leg hurts.", exampleArabic: "ساقي تؤلمني", category: "صحة" },
    { id: 1614, word: "foot", arabic: "قدم", pronunciation: "فوت", example: "My feet are cold.", exampleArabic: "قدماي باردتان", category: "صحة" },
    { id: 1615, word: "back", arabic: "ظهر", pronunciation: "باك", example: "I have back pain.", exampleArabic: "لدي ألم في الظهر", category: "صحة" },
    { id: 1616, word: "heart", arabic: "قلب", pronunciation: "هارت", example: "My heart beats fast.", exampleArabic: "قلبي يدق بسرعة", category: "صحة" },
    { id: 1617, word: "doctor", arabic: "طبيب", pronunciation: "داكتر", example: "I visit the doctor.", exampleArabic: "أزور الطبيب", category: "صحة" },
    { id: 1618, word: "nurse", arabic: "ممرض", pronunciation: "نيرس", example: "The nurse is kind.", exampleArabic: "الممرضة لطيفة", category: "صحة" },
    { id: 1619, word: "hospital", arabic: "مستشفى", pronunciation: "هوسبيتل", example: "He is in the hospital.", exampleArabic: "هو في المستشفى", category: "صحة" },
    { id: 1620, word: "medicine", arabic: "دواء", pronunciation: "ميديسن", example: "Take your medicine.", exampleArabic: "خذ دواءك", category: "صحة" },
    { id: 1621, word: "pain", arabic: "ألم", pronunciation: "باين", example: "I have a headache.", exampleArabic: "لدي ألم في الرأس", category: "صحة" },
    { id: 1622, word: "sick", arabic: "مريض", pronunciation: "سيك", example: "I feel sick.", exampleArabic: "أشعر بالمرض", category: "صحة" },
    { id: 1623, word: "fever", arabic: "حمى", pronunciation: "فيفر", example: "I have a fever.", exampleArabic: "عندي حمى", category: "صحة" },
    { id: 1624, word: "cough", arabic: "سعال", pronunciation: "كوف", example: "I have a bad cough.", exampleArabic: "عندي سعال شديد", category: "صحة" },
    { id: 1625, word: "exercise", arabic: "تمرين", pronunciation: "إكسيرسايز", example: "I exercise every day.", exampleArabic: "أتمرن كل يوم", category: "صحة" },

    // العمل والوظائف
    { id: 1701, word: "job", arabic: "وظيفة", pronunciation: "جوب", example: "I have a new job.", exampleArabic: "لدي وظيفة جديدة", category: "عمل" },
    { id: 1702, word: "work", arabic: "عمل", pronunciation: "ورك", example: "I go to work at 8.", exampleArabic: "أذهب للعمل الساعة 8", category: "عمل" },
    { id: 1703, word: "office", arabic: "مكتب", pronunciation: "أوفيس", example: "My office is downtown.", exampleArabic: "مكتبي في وسط المدينة", category: "عمل" },
    { id: 1704, word: "company", arabic: "شركة", pronunciation: "كومباني", example: "She works for a big company.", exampleArabic: "هي تعمل في شركة كبيرة", category: "عمل" },
    { id: 1705, word: "boss", arabic: "مدير", pronunciation: "بوس", example: "My boss is strict.", exampleArabic: "مديري صارم", category: "عمل" },
    { id: 1706, word: "manager", arabic: "مدير", pronunciation: "مانيدجر", example: "The manager helps us.", exampleArabic: "المدير يساعدنا", category: "عمل" },
    { id: 1707, word: "employee", arabic: "موظف", pronunciation: "إمبلويي", example: "The employees work hard.", exampleArabic: "الموظفون يعملون بجد", category: "عمل" },
    { id: 1708, word: "worker", arabic: "عامل", pronunciation: "وركر", example: "He is a hard worker.", exampleArabic: "هو عامل مجتهد", category: "عمل" },
    { id: 1709, word: "colleague", arabic: "زميل", pronunciation: "كوليج", example: "My colleague is friendly.", exampleArabic: "زميلي ودود", category: "عمل" },
    { id: 1710, word: "meeting", arabic: "اجتماع", pronunciation: "ميتينغ", example: "We have a meeting at 10.", exampleArabic: "لدينا اجتماع الساعة 10", category: "عمل" },
    { id: 1711, word: "salary", arabic: "راتب", pronunciation: "سالاري", example: "I get my salary monthly.", exampleArabic: "أتلقى راتبي شهرياً", category: "عمل" },
    { id: 1712, word: "interview", arabic: "مقابلة", pronunciation: "إنترفيو", example: "I have a job interview.", exampleArabic: "لدي مقابلة عمل", category: "عمل" },
    { id: 1713, word: "experience", arabic: "خبرة", pronunciation: "إكسبيرينس", example: "I have five years experience.", exampleArabic: "لدي خبرة خمس سنوات", category: "عمل" },
    { id: 1714, word: "skill", arabic: "مهارة", pronunciation: "سكيل", example: "Learn new skills.", exampleArabic: "تعلم مهارات جديدة", category: "عمل" },
    { id: 1715, word: "resume", arabic: "سيرة ذاتية", pronunciation: "ريزومي", example: "Send your resume.", exampleArabic: "أرسل سيرتك الذاتية", category: "عمل" },
    { id: 1716, word: "hire", arabic: "يوظف", pronunciation: "هاير", example: "The company will hire new people.", exampleArabic: "الشركة ستوظف أشخاصاً جدد", category: "عمل" },
    { id: 1717, word: "fire", arabic: "يطرد", pronunciation: "فاير", example: "He was fired from work.", exampleArabic: "تم طرده من العمل", category: "عمل" },
    { id: 1718, word: "promotion", arabic: "ترقية", pronunciation: "بروموشن", example: "She got a promotion.", exampleArabic: "حصلت على ترقية", category: "عمل" },
    { id: 1719, word: "retire", arabic: "يتقاعد", pronunciation: "ريتاير", example: "My father retired.", exampleArabic: "والدي تقاعد", category: "عمل" },
    { id: 1720, word: "business", arabic: "أعمال", pronunciation: "بيزنيس", example: "He is in business.", exampleArabic: "هو في مجال الأعمال", category: "عمل" },
    { id: 1721, word: "customer", arabic: "زبون", pronunciation: "كاستمر", example: "The customer is always right.", exampleArabic: "الزبون دائماً على حق", category: "عمل" },
    { id: 1722, word: "client", arabic: "عميل", pronunciation: "كلاينت", example: "We have a new client.", exampleArabic: "لدينا عميل جديد", category: "عمل" },
    { id: 1723, word: "deadline", arabic: "موعد نهائي", pronunciation: "ديدلاين", example: "The deadline is Friday.", exampleArabic: "الموعد النهائي يوم الجمعة", category: "عمل" },
    { id: 1724, word: "project", arabic: "مشروع", pronunciation: "بروجكت", example: "I'm working on a project.", exampleArabic: "أعمل على مشروع", category: "عمل" },
    { id: 1725, word: "team", arabic: "فريق", pronunciation: "تيم", example: "We have a great team.", exampleArabic: "لدينا فريق رائع", category: "عمل" },

    // التعليم والدراسة
    { id: 1801, word: "school", arabic: "مدرسة", pronunciation: "سكول", example: "Children go to school.", exampleArabic: "الأطفال يذهبون للمدرسة", category: "تعليم" },
    { id: 1802, word: "university", arabic: "جامعة", pronunciation: "يونيفرسيتي", example: "She studies at the university.", exampleArabic: "هي تدرس في الجامعة", category: "تعليم" },
    { id: 1803, word: "college", arabic: "كلية", pronunciation: "كوليدج", example: "I go to college.", exampleArabic: "أذهب إلى الكلية", category: "تعليم" },
    { id: 1804, word: "class", arabic: "فصل", pronunciation: "كلاس", example: "The class starts at 9.", exampleArabic: "الفصل يبدأ الساعة 9", category: "تعليم" },
    { id: 1805, word: "teacher", arabic: "معلم", pronunciation: "تيتشر", example: "The teacher explains well.", exampleArabic: "المعلم يشرح جيداً", category: "تعليم" },
    { id: 1806, word: "student", arabic: "طالب", pronunciation: "ستودنت", example: "He is a good student.", exampleArabic: "هو طالب جيد", category: "تعليم" },
    { id: 1807, word: "book", arabic: "كتاب", pronunciation: "بوك", example: "Read your book.", exampleArabic: "اقرأ كتابك", category: "تعليم" },
    { id: 1808, word: "notebook", arabic: "دفتر", pronunciation: "نوت بوك", example: "Write in your notebook.", exampleArabic: "اكتب في دفترك", category: "تعليم" },
    { id: 1809, word: "pen", arabic: "قلم", pronunciation: "بين", example: "I write with a pen.", exampleArabic: "أكتب بقلم", category: "تعليم" },
    { id: 1810, word: "pencil", arabic: "قلم رصاص", pronunciation: "بنسل", example: "Draw with a pencil.", exampleArabic: "ارسم بقلم رصاص", category: "تعليم" },
    { id: 1811, word: "paper", arabic: "ورق", pronunciation: "بيبر", example: "I need paper.", exampleArabic: "أحتاج ورقاً", category: "تعليم" },
    { id: 1812, word: "desk", arabic: "مكتب", pronunciation: "ديسك", example: "Sit at your desk.", exampleArabic: "اجلس على مكتبك", category: "تعليم" },
    { id: 1813, word: "chair", arabic: "كرسي", pronunciation: "تشير", example: "The chair is comfortable.", exampleArabic: "الكرسي مريح", category: "تعليم" },
    { id: 1814, word: "board", arabic: "سبورة", pronunciation: "بورد", example: "Write on the board.", exampleArabic: "اكتب على السبورة", category: "تعليم" },
    { id: 1815, word: "homework", arabic: "واجب", pronunciation: "هوم وورك", example: "I do my homework.", exampleArabic: "أقوم بواجبي", category: "تعليم" },
    { id: 1816, word: "exam", arabic: "امتحان", pronunciation: "إكزام", example: "The exam is difficult.", exampleArabic: "الامتحان صعب", category: "تعليم" },
    { id: 1817, word: "test", arabic: "اختبار", pronunciation: "تست", example: "We have a test today.", exampleArabic: "لدينا اختبار اليوم", category: "تعليم" },
    { id: 1818, word: "grade", arabic: "درجة", pronunciation: "جرايد", example: "I got a good grade.", exampleArabic: "حصلت على درجة جيدة", category: "تعليم" },
    { id: 1819, word: "learn", arabic: "يتعلم", pronunciation: "ليرن", example: "I want to learn English.", exampleArabic: "أريد تعلم الإنجليزية", category: "تعليم" },
    { id: 1820, word: "study", arabic: "يدرس", pronunciation: "ستادي", example: "I study every day.", exampleArabic: "أدرس كل يوم", category: "تعليم" },
    { id: 1821, word: "teach", arabic: "يعلم", pronunciation: "تيتش", example: "She teaches math.", exampleArabic: "هي تدرس الرياضيات", category: "تعليم" },
    { id: 1822, word: "understand", arabic: "يفهم", pronunciation: "أندرستاند", example: "I understand the lesson.", exampleArabic: "أنا أفهم الدرس", category: "تعليم" },
    { id: 1823, word: "dictionary", arabic: "قاموس", pronunciation: "ديكشنري", example: "Look up the word in the dictionary.", exampleArabic: "ابحث عن الكلمة في القاموس", category: "تعليم" },
    { id: 1824, word: "lesson", arabic: "درس", pronunciation: "ليسن", example: "Today's lesson is easy.", exampleArabic: "درس اليوم سهل", category: "تعليم" },
    { id: 1825, word: "degree", arabic: "شهادة", pronunciation: "ديغري", example: "She has a university degree.", exampleArabic: "لديها شهادة جامعية", category: "تعليم" },

    // الوقت والتاريخ
    { id: 1901, word: "time", arabic: "وقت", pronunciation: "تايم", example: "What time is it?", exampleArabic: "كم الساعة؟", category: "وقت" },
    { id: 1902, word: "clock", arabic: "ساعة", pronunciation: "كلوك", example: "Look at the clock.", exampleArabic: "انظر إلى الساعة", category: "وقت" },
    { id: 1903, word: "hour", arabic: "ساعة", pronunciation: "أور", example: "One hour has 60 minutes.", exampleArabic: "الساعة فيها 60 دقيقة", category: "وقت" },
    { id: 1904, word: "minute", arabic: "دقيقة", pronunciation: "مينيت", example: "Wait a minute.", exampleArabic: "انتظر دقيقة", category: "وقت" },
    { id: 1905, word: "second", arabic: "ثانية", pronunciation: "سيكند", example: "I'll be back in a second.", exampleArabic: "سأعود بعد ثانية", category: "وقت" },
    { id: 1906, word: "morning", arabic: "صباح", pronunciation: "مورنينغ", example: "Good morning!", exampleArabic: "صباح الخير!", category: "وقت" },
    { id: 1907, word: "afternoon", arabic: "بعد الظهر", pronunciation: "آفترنون", example: "I sleep in the afternoon.", exampleArabic: "أنام بعد الظهر", category: "وقت" },
    { id: 1908, word: "evening", arabic: "مساء", pronunciation: "إيفنينغ", example: "I watch TV in the evening.", exampleArabic: "أشاهد التلفاز مساءً", category: "وقت" },
    { id: 1909, word: "night", arabic: "ليل", pronunciation: "نايت", example: "Good night!", exampleArabic: "تصبح على خير!", category: "وقت" },
    { id: 1910, word: "today", arabic: "اليوم", pronunciation: "توداي", example: "Today is Monday.", exampleArabic: "اليوم الإثنين", category: "وقت" },
    { id: 1911, word: "tomorrow", arabic: "غداً", pronunciation: "تومورو", example: "See you tomorrow.", exampleArabic: "أراك غداً", category: "وقت" },
    { id: 1912, word: "yesterday", arabic: "أمس", pronunciation: "يستردي", example: "I was tired yesterday.", exampleArabic: "كنت متعباً أمس", category: "وقت" },
    { id: 1913, word: "week", arabic: "أسبوع", pronunciation: "ويك", example: "A week has 7 days.", exampleArabic: "الأسبوع فيه 7 أيام", category: "وقت" },
    { id: 1914, word: "month", arabic: "شهر", pronunciation: "مونث", example: "This month is hot.", exampleArabic: "هذا الشهر حار", category: "وقت" },
    { id: 1915, word: "year", arabic: "سنة", pronunciation: "يير", example: "Happy new year!", exampleArabic: "سنة جديدة سعيدة!", category: "وقت" },
    { id: 1916, word: "day", arabic: "يوم", pronunciation: "داي", example: "Have a nice day.", exampleArabic: "أتمنى لك يوماً سعيداً", category: "وقت" },
    { id: 1917, word: "date", arabic: "تاريخ", pronunciation: "ديت", example: "What's the date today?", exampleArabic: "ما تاريخ اليوم؟", category: "وقت" },
    { id: 1918, word: "Monday", arabic: "الإثنين", pronunciation: "ماندي", example: "Monday is the first day.", exampleArabic: "الإثنين أول يوم", category: "وقت" },
    { id: 1919, word: "Tuesday", arabic: "الثلاثاء", pronunciation: "تيوزدي", example: "See you on Tuesday.", exampleArabic: "أراك الثلاثاء", category: "وقت" },
    { id: 1920, word: "Wednesday", arabic: "الأربعاء", pronunciation: "وينزدي", example: "Wednesday is middle of week.", exampleArabic: "الأربعاء وسط الأسبوع", category: "وقت" },
    { id: 1921, word: "Thursday", arabic: "الخميس", pronunciation: "ثيرزدي", example: "Thursday is before Friday.", exampleArabic: "الخميس قبل الجمعة", category: "وقت" },
    { id: 1922, word: "Friday", arabic: "الجمعة", pronunciation: "فرايدي", example: "Friday is a holiday.", exampleArabic: "الجمعة عطلة", category: "وقت" },
    { id: 1923, word: "Saturday", arabic: "السبت", pronunciation: "ساتردي", example: "I relax on Saturday.", exampleArabic: "أسترخي يوم السبت", category: "وقت" },
    { id: 1924, word: "Sunday", arabic: "الأحد", pronunciation: "صندي", example: "Sunday is a day off.", exampleArabic: "الأحد يوم عطلة", category: "وقت" },
    { id: 1925, word: "weekend", arabic: "عطلة نهاية الأسبوع", pronunciation: "ويك إند", example: "I enjoy the weekend.", exampleArabic: "أستمتع بعطلة نهاية الأسبوع", category: "وقت" },

    // الملابس والموضة
    { id: 2001, word: "clothes", arabic: "ملابس", pronunciation: "كلوز", example: "I buy new clothes.", exampleArabic: "أشتري ملابس جديدة", category: "ملابس" },
    { id: 2002, word: "shirt", arabic: "قميص", pronunciation: "شيرت", example: "He wears a white shirt.", exampleArabic: "يرتدي قميصاً أبيض", category: "ملابس" },
    { id: 2003, word: "pants", arabic: "بنطال", pronunciation: "بانتس", example: "These pants are black.", exampleArabic: "هذا البنطال أسود", category: "ملابس" },
    { id: 2004, word: "jeans", arabic: "جينز", pronunciation: "جينز", example: "I like blue jeans.", exampleArabic: "أحب الجينز الأزرق", category: "ملابس" },
    { id: 2005, word: "dress", arabic: "فستان", pronunciation: "دريس", example: "She wears a red dress.", exampleArabic: "ترتدي فستاناً أحمر", category: "ملابس" },
    { id: 2006, word: "skirt", arabic: "تنورة", pronunciation: "سكيرت", example: "She has a long skirt.", exampleArabic: "لديها تنورة طويلة", category: "ملابس" },
    { id: 2007, word: "jacket", arabic: "جاكيت", pronunciation: "جاكيت", example: "Wear a jacket in winter.", exampleArabic: "ارتدِ جاكيت في الشتاء", category: "ملابس" },
    { id: 2008, word: "coat", arabic: "معطف", pronunciation: "كوت", example: "He wears a heavy coat.", exampleArabic: "يرتدي معطفاً ثقيلاً", category: "ملابس" },
    { id: 2009, word: "sweater", arabic: "سترة", pronunciation: "سويتر", example: "This sweater is warm.", exampleArabic: "هذه السترة دافئة", category: "ملابس" },
    { id: 2010, word: "hat", arabic: "قبعة", pronunciation: "هات", example: "I wear a hat in the sun.", exampleArabic: "أرتدي قبعة في الشمس", category: "ملابس" },
    { id: 2011, word: "cap", arabic: "كاب", pronunciation: "كاب", example: "He wears a baseball cap.", exampleArabic: "يرتدي كاب بيسبول", category: "ملابس" },
    { id: 2012, word: "shoes", arabic: "أحذية", pronunciation: "شوز", example: "I buy new shoes.", exampleArabic: "أشتري أحذية جديدة", category: "ملابس" },
    { id: 2013, word: "boots", arabic: "أحذية طويلة", pronunciation: "بوتس", example: "Wear boots in the rain.", exampleArabic: "ارتدِ أحذية طويلة في المطر", category: "ملابس" },
    { id: 2014, word: "socks", arabic: "جوارب", pronunciation: "سوكس", example: "I need clean socks.", exampleArabic: "أحتاج جوارب نظيفة", category: "ملابس" },
    { id: 2015, word: "gloves", arabic: "قفازات", pronunciation: "غلوفز", example: "Wear gloves in the cold.", exampleArabic: "ارتدِ قفازات في البرد", category: "ملابس" },
    { id: 2016, word: "scarf", arabic: "وشاح", pronunciation: "سكارف", example: "She wears a red scarf.", exampleArabic: "ترتدي وشاحاً أحمر", category: "ملابس" },
    { id: 2017, word: "belt", arabic: "حزام", pronunciation: "بيلت", example: "He wears a brown belt.", exampleArabic: "يرتدي حزاماً بنياً", category: "ملابس" },
    { id: 2018, word: "watch", arabic: "ساعة يد", pronunciation: "واتش", example: "My watch is new.", exampleArabic: "ساعتي جديدة", category: "ملابس" },
    { id: 2019, word: "glasses", arabic: "نظارات", pronunciation: "غلاسيز", example: "She wears glasses.", exampleArabic: "هي ترتدي نظارات", category: "ملابس" },
    { id: 2020, word: "sunglasses", arabic: "نظارات شمسية", pronunciation: "سنغلاسيز", example: "I wear sunglasses in summer.", exampleArabic: "أرتدي نظارات شمسية في الصيف", category: "ملابس" },
    { id: 2021, word: "umbrella", arabic: "مظلة", pronunciation: "أمبريلا", example: "Take an umbrella, it's raining.", exampleArabic: "خذ مظلة، إنها تمطر", category: "ملابس" },
    { id: 2022, word: "bag", arabic: "حقيبة", pronunciation: "باغ", example: "I carry my bag.", exampleArabic: "أحمل حقيبتي", category: "ملابس" },
    { id: 2023, word: "tie", arabic: "ربطة عنق", pronunciation: "تاي", example: "He wears a tie at work.", exampleArabic: "يرتدي ربطة عنق في العمل", category: "ملابس" },
    { id: 2024, word: "suit", arabic: "بدلة", pronunciation: "سوت", example: "He wears a formal suit.", exampleArabic: "يرتدي بدلة رسمية", category: "ملابس" },
    { id: 2025, word: "pajamas", arabic: "بيجاما", pronunciation: "باجاماز", example: "I wear comfortable pajamas.", exampleArabic: "أرتدي بيجاما مريحة", category: "ملابس" },

    // الاتجاهات والأماكن
    { id: 2101, word: "place", arabic: "مكان", pronunciation: "بليس", example: "This is a nice place.", exampleArabic: "هذا مكان جميل", category: "اتجاهات" },
    { id: 2102, word: "direction", arabic: "اتجاه", pronunciation: "دايركشن", example: "Which direction should I go?", exampleArabic: "أي اتجاه يجب أن أذهب؟", category: "اتجاهات" },
    { id: 2103, word: "left", arabic: "يسار", pronunciation: "ليفت", example: "Turn left.", exampleArabic: "انعطف يساراً", category: "اتجاهات" },
    { id: 2104, word: "right", arabic: "يمين", pronunciation: "رايت", example: "Turn right.", exampleArabic: "انعطف يميناً", category: "اتجاهات" },
    { id: 2105, word: "straight", arabic: "مستقيم", pronunciation: "ستريت", example: "Go straight ahead.", exampleArabic: "اذهب مباشرة للأمام", category: "اتجاهات" },
    { id: 2106, word: "forward", arabic: "للأمام", pronunciation: "فوروارد", example: "Move forward.", exampleArabic: "تحرك للأمام", category: "اتجاهات" },
    { id: 2107, word: "back", arabic: "للخلف", pronunciation: "باك", example: "Step back.", exampleArabic: "تراجع للخلف", category: "اتجاهات" },
    { id: 2108, word: "north", arabic: "شمال", pronunciation: "نورث", example: "Canada is north of USA.", exampleArabic: "كندا شمال الولايات المتحدة", category: "اتجاهات" },
    { id: 2109, word: "south", arabic: "جنوب", pronunciation: "ساوث", example: "Egypt is south of Europe.", exampleArabic: "مصر جنوب أوروبا", category: "اتجاهات" },
    { id: 2110, word: "east", arabic: "شرق", pronunciation: "إيست", example: "The sun rises in the east.", exampleArabic: "الشمس تشرق من الشرق", category: "اتجاهات" },
    { id: 2111, word: "west", arabic: "غرب", pronunciation: "ويست", example: "The sun sets in the west.", exampleArabic: "الشمس تغرب في الغرب", category: "اتجاهات" },
    { id: 2112, word: "near", arabic: "قريب", pronunciation: "نير", example: "The bank is near.", exampleArabic: "البنك قريب", category: "اتجاهات" },
    { id: 2113, word: "far", arabic: "بعيد", pronunciation: "فار", example: "The airport is far.", exampleArabic: "المطار بعيد", category: "اتجاهات" },
    { id: 2114, word: "here", arabic: "هنا", pronunciation: "هير", example: "I am here.", exampleArabic: "أنا هنا", category: "اتجاهات" },
    { id: 2115, word: "there", arabic: "هناك", pronunciation: "ذير", example: "The store is over there.", exampleArabic: "المتجر هناك", category: "اتجاهات" },
    { id: 2116, word: "map", arabic: "خريطة", pronunciation: "ماب", example: "Look at the map.", exampleArabic: "انظر إلى الخريطة", category: "اتجاهات" },
    { id: 2117, word: "street", arabic: "شارع", pronunciation: "ستريت", example: "Main street is busy.", exampleArabic: "الشارع الرئيسي مزدحم", category: "اتجاهات" },
    { id: 2118, word: "road", arabic: "طريق", pronunciation: "رود", example: "The road is long.", exampleArabic: "الطريق طويل", category: "اتجاهات" },
    { id: 2119, word: "building", arabic: "مبنى", pronunciation: "بيلدينغ", example: "That's a tall building.", exampleArabic: "هذا مبنى طويل", category: "اتجاهات" },
    { id: 2120, word: "corner", arabic: "زاوية", pronunciation: "كورنر", example: "The store is on the corner.", exampleArabic: "المتجر على الزاوية", category: "اتجاهات" },
    { id: 2121, word: "bridge", arabic: "جسر", pronunciation: "بريدج", example: "Cross the bridge.", exampleArabic: "اعبر الجسر", category: "اتجاهات" },
    { id: 2122, word: "traffic light", arabic: "إشارة مرور", pronunciation: "ترافيك لايت", example: "Stop at the traffic light.", exampleArabic: "توقف عند إشارة المرور", category: "اتجاهات" },
    { id: 2123, word: "crosswalk", arabic: "ممر مشاة", pronunciation: "كروس ووك", example: "Use the crosswalk.", exampleArabic: "استخدم ممر المشاة", category: "اتجاهات" },
    { id: 2124, word: "downtown", arabic: "وسط البلد", pronunciation: "داون تاون", example: "I work downtown.", exampleArabic: "أعمل في وسط البلد", category: "اتجاهات" },
    { id: 2125, word: "neighborhood", arabic: "حي", pronunciation: "نيبرهود", example: "This is a quiet neighborhood.", exampleArabic: "هذا حي هادئ", category: "اتجاهات" },

    // المشاعر والأحاسيس
    { id: 2201, word: "happy", arabic: "سعيد", pronunciation: "هابي", example: "I am happy today.", exampleArabic: "أنا سعيد اليوم", category: "مشاعر" },
    { id: 2202, word: "sad", arabic: "حزين", pronunciation: "ساد", example: "She is sad.", exampleArabic: "هي حزينة", category: "مشاعر" },
    { id: 2203, word: "angry", arabic: "غاضب", pronunciation: "أنغري", example: "He is angry.", exampleArabic: "هو غاضب", category: "مشاعر" },
    { id: 2204, word: "tired", arabic: "متعب", pronunciation: "تايرد", example: "I am tired after work.", exampleArabic: "أنا متعب بعد العمل", category: "مشاعر" },
    { id: 2205, word: "scared", arabic: "خائف", pronunciation: "سكارد", example: "I am scared of dogs.", exampleArabic: "أنا خائف من الكلاب", category: "مشاعر" },
    { id: 2206, word: "excited", arabic: "متحمس", pronunciation: "إكسايتد", example: "I am excited for the party.", exampleArabic: "أنا متحمس للحفلة", category: "مشاعر" },
    { id: 2207, word: "bored", arabic: "يشعر بالملل", pronunciation: "بورد", example: "I am bored.", exampleArabic: "أشعر بالملل", category: "مشاعر" },
    { id: 2208, word: "surprised", arabic: "متفاجئ", pronunciation: "سوربرايزد", example: "I was surprised!", exampleArabic: "كنت متفاجئاً!", category: "مشاعر" },
    { id: 2209, word: "worried", arabic: "قلق", pronunciation: "وريد", example: "I am worried about you.", exampleArabic: "أنا قلق عليك", category: "مشاعر" },
    { id: 2210, word: "confused", arabic: "مرتبك", pronunciation: "كونفيوزد", example: "I am confused.", exampleArabic: "أنا مرتبك", category: "مشاعر" },
    { id: 2211, word: "jealous", arabic: "غيور", pronunciation: "جيلوس", example: "He is jealous.", exampleArabic: "هو غيور", category: "مشاعر" },
    { id: 2212, word: "proud", arabic: "فخور", pronunciation: "براود", example: "I am proud of you.", exampleArabic: "أنا فخور بك", category: "مشاعر" },
    { id: 2213, word: "shy", arabic: "خجول", pronunciation: "شاي", example: "She is shy.", exampleArabic: "هي خجولة", category: "مشاعر" },
    { id: 2214, word: "lonely", arabic: "وحيد", pronunciation: "لونلي", example: "I feel lonely.", exampleArabic: "أشعر بالوحدة", category: "مشاعر" },
    { id: 2215, word: "love", arabic: "حب", pronunciation: "لوف", example: "I love my family.", exampleArabic: "أنا أحب عائلتي", category: "مشاعر" },
    { id: 2216, word: "hate", arabic: "كره", pronunciation: "هيت", example: "I hate lies.", exampleArabic: "أنا أكره الكذب", category: "مشاعر" },
    { id: 2217, word: "calm", arabic: "هادئ", pronunciation: "كالم", example: "Stay calm.", exampleArabic: "ابق هادئاً", category: "مشاعر" },
    { id: 2218, word: "nervous", arabic: "عصبي", pronunciation: "نيرفوس", example: "I am nervous before exams.", exampleArabic: "أنا عصبي قبل الامتحانات", category: "مشاعر" },
    { id: 2219, word: "grateful", arabic: "ممتن", pronunciation: "غريتفول", example: "I am grateful for your help.", exampleArabic: "أنا ممتن لمساعدتك", category: "مشاعر" },
    { id: 2220, word: "hopeful", arabic: "متفائل", pronunciation: "هوبفول", example: "I am hopeful for the future.", exampleArabic: "أنا متفائل بالمستقبل", category: "مشاعر" },
    { id: 2221, word: "relaxed", arabic: "مسترخي", pronunciation: "ريلاكست", example: "I feel relaxed at home.", exampleArabic: "أشعر بالاسترخاء في المنزل", category: "مشاعر" },
    { id: 2222, word: "stress", arabic: "توتر", pronunciation: "ستريس", example: "Work causes stress.", exampleArabic: "العمل يسبب التوتر", category: "مشاعر" },
    { id: 2223, word: "embarrassed", arabic: "محرج", pronunciation: "إمباراست", example: "I was embarrassed.", exampleArabic: "كنت محرجاً", category: "مشاعر" },
    { id: 2224, word: "disappointed", arabic: "خائب الأمل", pronunciation: "ديسابوينتد", example: "I am disappointed.", exampleArabic: "أنا خائب الأمل", category: "مشاعر" },
    { id: 2225, word: "curious", arabic: "فضولي", pronunciation: "كيوريوس", example: "I am curious.", exampleArabic: "أنا فضولي", category: "مشاعر" },

    // الأفعال اليومية
    { id: 2301, word: "wake up", arabic: "يستيقظ", pronunciation: "ويك أب", example: "I wake up at 7 am.", exampleArabic: "أستيقظ الساعة 7 صباحاً", category: "أفعال" },
    { id: 2302, word: "get up", arabic: "ينهض", pronunciation: "جيت أب", example: "I get up from bed.", exampleArabic: "أنهض من السرير", category: "أفعال" },
    { id: 2303, word: "eat", arabic: "يأكل", pronunciation: "إيت", example: "I eat breakfast.", exampleArabic: "أتناول الفطور", category: "أفعال" },
    { id: 2304, word: "drink", arabic: "يشرب", pronunciation: "درينك", example: "I drink water.", exampleArabic: "أشرب الماء", category: "أفعال" },
    { id: 2305, word: "cook", arabic: "يطبخ", pronunciation: "كوك", example: "My mother cooks dinner.", exampleArabic: "أمي تطبخ العشاء", category: "أفعال" },
    { id: 2306, word: "have breakfast", arabic: "يتناول الفطور", pronunciation: "هاف بريكفاست", example: "I have breakfast at 8.", exampleArabic: "أتناول الفطور الساعة 8", category: "أفعال" },
    { id: 2307, word: "have lunch", arabic: "يتناول الغداء", pronunciation: "هاف لانتش", example: "We have lunch together.", exampleArabic: "نتناول الغداء معاً", category: "أفعال" },
    { id: 2308, word: "have dinner", arabic: "يتناول العشاء", pronunciation: "هاف دينر", example: "They have dinner at 7.", exampleArabic: "يتناولون العشاء الساعة 7", category: "أفعال" },
    { id: 2309, word: "go", arabic: "يذهب", pronunciation: "غو", example: "I go to school.", exampleArabic: "أذهب إلى المدرسة", category: "أفعال" },
    { id: 2310, word: "come", arabic: "يأتي", pronunciation: "كام", example: "Come here, please.", exampleArabic: "تعال هنا من فضلك", category: "أفعال" },
    { id: 2311, word: "arrive", arabic: "يصل", pronunciation: "أرايف", example: "I arrive at work at 9.", exampleArabic: "أصل إلى العمل الساعة 9", category: "أفعال" },
    { id: 2312, word: "leave", arabic: "يغادر", pronunciation: "ليف", example: "I leave home at 8.", exampleArabic: "أغادر المنزل الساعة 8", category: "أفعال" },
    { id: 2313, word: "work", arabic: "يعمل", pronunciation: "ورك", example: "I work from 9 to 5.", exampleArabic: "أعمل من 9 إلى 5", category: "أفعال" },
    { id: 2314, word: "study", arabic: "يدرس", pronunciation: "ستادي", example: "I study English.", exampleArabic: "أدرس الإنجليزية", category: "أفعال" },
    { id: 2315, word: "read", arabic: "يقرأ", pronunciation: "ريد", example: "I read books.", exampleArabic: "أقرأ الكتب", category: "أفعال" },
    { id: 2316, word: "write", arabic: "يكتب", pronunciation: "رايت", example: "I write in my notebook.", exampleArabic: "أكتب في دفتري", category: "أفعال" },
    { id: 2317, word: "play", arabic: "يلعب", pronunciation: "بلاي", example: "Children play in the park.", exampleArabic: "الأطفال يلعبون في الحديقة", category: "أفعال" },
    { id: 2318, word: "run", arabic: "يركض", pronunciation: "ران", example: "I run in the morning.", exampleArabic: "أركض في الصباح", category: "أفعال" },
    { id: 2319, word: "walk", arabic: "يمشي", pronunciation: "ووك", example: "We walk to school.", exampleArabic: "نحن نمشي إلى المدرسة", category: "أفعال" },
    { id: 2320, word: "sleep", arabic: "ينام", pronunciation: "سليب", example: "I sleep at night.", exampleArabic: "أنام في الليل", category: "أفعال" },
    { id: 2321, word: "rest", arabic: "يستريح", pronunciation: "ريست", example: "I rest after work.", exampleArabic: "أستريح بعد العمل", category: "أفعال" },
    { id: 2322, word: "take a shower", arabic: "يستحم", pronunciation: "تيك أ شاور", example: "I take a shower every morning.", exampleArabic: "أستحم كل صباح", category: "أفعال" },
    { id: 2323, word: "brush", arabic: "يفرش", pronunciation: "براش", example: "I brush my teeth.", exampleArabic: "أفرش أسناني", category: "أفعال" },
    { id: 2324, word: "wash", arabic: "يغسل", pronunciation: "ووش", example: "I wash my hands.", exampleArabic: "أغسل يدي", category: "أفعال" },
    { id: 2325, word: "clean", arabic: "ينظف", pronunciation: "كلين", example: "I clean my room.", exampleArabic: "أنظف غرفتي", category: "أفعال" },

    // التكنولوجيا والإنترنت
    { id: 2401, word: "phone", arabic: "هاتف", pronunciation: "فون", example: "I talk on the phone.", exampleArabic: "أتحدث على الهاتف", category: "تكنولوجيا" },
    { id: 2402, word: "cell phone", arabic: "هاتف محمول", pronunciation: "سيل فون", example: "My cell phone is new.", exampleArabic: "هاتفي المحمول جديد", category: "تكنولوجيا" },
    { id: 2403, word: "smartphone", arabic: "هاتف ذكي", pronunciation: "سمارت فون", example: "I use my smartphone.", exampleArabic: "أستخدم هاتفي الذكي", category: "تكنولوجيا" },
    { id: 2404, word: "computer", arabic: "كمبيوتر", pronunciation: "كمبيوتر", example: "I work on my computer.", exampleArabic: "أعمل على كمبيوتري", category: "تكنولوجيا" },
    { id: 2405, word: "laptop", arabic: "لابتوب", pronunciation: "لابتوب", example: "I take my laptop to work.", exampleArabic: "آخذ لابتوبي للعمل", category: "تكنولوجيا" },
    { id: 2406, word: "tablet", arabic: "جهاز لوحي", pronunciation: "تابلت", example: "I read on my tablet.", exampleArabic: "أقرأ على جهازي اللوحي", category: "تكنولوجيا" },
    { id: 2407, word: "internet", arabic: "إنترنت", pronunciation: "إنترنت", example: "I use the internet every day.", exampleArabic: "أستخدم الإنترنت كل يوم", category: "تكنولوجيا" },
    { id: 2408, word: "WiFi", arabic: "واي فاي", pronunciation: "واي فاي", example: "What is the WiFi password?", exampleArabic: "ما هي كلمة سر الواي فاي؟", category: "تكنولوجيا" },
    { id: 2409, word: "website", arabic: "موقع", pronunciation: "ويبسايت", example: "I visit that website.", exampleArabic: "أزور ذلك الموقع", category: "تكنولوجيا" },
    { id: 2410, word: "email", arabic: "بريد إلكتروني", pronunciation: "إيميل", example: "Send me an email.", exampleArabic: "أرسل لي بريداً إلكترونياً", category: "تكنولوجيا" },
    { id: 2411, word: "message", arabic: "رسالة", pronunciation: "ميسيدج", example: "I got your message.", exampleArabic: "استلمت رسالتك", category: "تكنولوجيا" },
    { id: 2412, word: "text", arabic: "نص", pronunciation: "تيكست", example: "I'll text you later.", exampleArabic: "سأرسل لك رسالة نصية لاحقاً", category: "تكنولوجيا" },
    { id: 2413, word: "call", arabic: "مكالمة", pronunciation: "كول", example: "I'll call you tonight.", exampleArabic: "سأتصل بك الليلة", category: "تكنولوجيا" },
    { id: 2414, word: "app", arabic: "تطبيق", pronunciation: "آب", example: "I downloaded a new app.", exampleArabic: "حمّلت تطبيقاً جديداً", category: "تكنولوجيا" },
    { id: 2415, word: "social media", arabic: "تواصل اجتماعي", pronunciation: "سوشل ميديا", example: "I use social media.", exampleArabic: "أستخدم وسائل التواصل الاجتماعي", category: "تكنولوجيا" },
    { id: 2416, word: "Facebook", arabic: "فيسبوك", pronunciation: "فيسبوك", example: "I post on Facebook.", exampleArabic: "أنشر على فيسبوك", category: "تكنولوجيا" },
    { id: 2417, word: "Instagram", arabic: "انستغرام", pronunciation: "انستغرام", example: "I share photos on Instagram.", exampleArabic: "أشارك الصور على انستغرام", category: "تكنولوجيا" },
    { id: 2418, word: "Twitter", arabic: "تويتر", pronunciation: "تويتر", example: "I read news on Twitter.", exampleArabic: "أقرأ الأخبار على تويتر", category: "تكنولوجيا" },
    { id: 2419, word: "WhatsApp", arabic: "واتساب", pronunciation: "واتساب", example: "I chat on WhatsApp.", exampleArabic: "أدردش على واتساب", category: "تكنولوجيا" },
    { id: 2420, word: "YouTube", arabic: "يوتيوب", pronunciation: "يوتيوب", example: "I watch videos on YouTube.", exampleArabic: "أشاهد فيديوهات على يوتيوب", category: "تكنولوجيا" },
    { id: 2421, word: "download", arabic: "تحميل", pronunciation: "داونلود", example: "Download the file.", exampleArabic: "حمّل الملف", category: "تكنولوجيا" },
    { id: 2422, word: "upload", arabic: "رفع", pronunciation: "أبلود", example: "Upload the photo.", exampleArabic: "ارفع الصورة", category: "تكنولوجيا" },
    { id: 2423, word: "password", arabic: "كلمة سر", pronunciation: "باسوورد", example: "Don't share your password.", exampleArabic: "لا تشارك كلمة سرك", category: "تكنولوجيا" },
    { id: 2424, word: "screen", arabic: "شاشة", pronunciation: "سكرين", example: "The screen is bright.", exampleArabic: "الشاشة ساطعة", category: "تكنولوجيا" },
    { id: 2425, word: "keyboard", arabic: "لوحة مفاتيح", pronunciation: "كي بورد", example: "I type on the keyboard.", exampleArabic: "أكتب على لوحة المفاتيح", category: "تكنولوجيا" },

    // الطقس والطبيعة
    { id: 2501, word: "weather", arabic: "طقس", pronunciation: "ويذر", example: "The weather is nice.", exampleArabic: "الطقس لطيف", category: "طقس" },
    { id: 2502, word: "sun", arabic: "شمس", pronunciation: "سان", example: "The sun is hot.", exampleArabic: "الشمس حارة", category: "طقس" },
    { id: 2503, word: "rain", arabic: "مطر", pronunciation: "رين", example: "It's raining.", exampleArabic: "إنها تمطر", category: "طقس" },
    { id: 2504, word: "snow", arabic: "ثلج", pronunciation: "سنو", example: "It snows in winter.", exampleArabic: "تثلج في الشتاء", category: "طقس" },
    { id: 2505, word: "wind", arabic: "رياح", pronunciation: "ويند", example: "The wind is strong.", exampleArabic: "الرياح قوية", category: "طقس" },
    { id: 2506, word: "cloud", arabic: "سحابة", pronunciation: "كلاود", example: "The sky is cloudy.", exampleArabic: "السماء غائمة", category: "طقس" },
    { id: 2507, word: "storm", arabic: "عاصفة", pronunciation: "ستورم", example: "There is a storm.", exampleArabic: "هناك عاصفة", category: "طقس" },
    { id: 2508, word: "thunder", arabic: "رعد", pronunciation: "ثاندر", example: "I hear thunder.", exampleArabic: "أسمع رعداً", category: "طقس" },
    { id: 2509, word: "lightning", arabic: "برق", pronunciation: "لايتنينغ", example: "Lightning is dangerous.", exampleArabic: "البرق خطير", category: "طقس" },
    { id: 2510, word: "temperature", arabic: "درجة حرارة", pronunciation: "تمبراتشر", example: "The temperature is high.", exampleArabic: "درجة الحرارة مرتفعة", category: "طقس" },
    { id: 2511, word: "hot", arabic: "حار", pronunciation: "هوت", example: "Summer is hot.", exampleArabic: "الصيف حار", category: "طقس" },
    { id: 2512, word: "cold", arabic: "بارد", pronunciation: "كولد", example: "Winter is cold.", exampleArabic: "الشتاء بارد", category: "طقس" },
    { id: 2513, word: "warm", arabic: "دافئ", pronunciation: "وورم", example: "The weather is warm.", exampleArabic: "الطقس دافئ", category: "طقس" },
    { id: 2514, word: "cool", arabic: "منعش", pronunciation: "كول", example: "It's cool in the evening.", exampleArabic: "الجو منعش في المساء", category: "طقس" },
    { id: 2515, word: "spring", arabic: "ربيع", pronunciation: "سبرينغ", example: "Spring is beautiful.", exampleArabic: "الربيع جميل", category: "طقس" },
    { id: 2516, word: "summer", arabic: "صيف", pronunciation: "سمر", example: "I love summer.", exampleArabic: "أحب الصيف", category: "طقس" },
    { id: 2517, word: "autumn", arabic: "خريف", pronunciation: "أوتام", example: "Leaves fall in autumn.", exampleArabic: "تتساقط الأوراق في الخريف", category: "طقس" },
    { id: 2518, word: "winter", arabic: "شتاء", pronunciation: "وينتر", example: "Winter is cold.", exampleArabic: "الشتاء بارد", category: "طقس" },
    { id: 2519, word: "nature", arabic: "طبيعة", pronunciation: "نيشور", example: "I love nature.", exampleArabic: "أحب الطبيعة", category: "طقس" },
    { id: 2520, word: "tree", arabic: "شجرة", pronunciation: "تري", example: "This tree is old.", exampleArabic: "هذه الشجرة قديمة", category: "طقس" },
    { id: 2521, word: "flower", arabic: "زهرة", pronunciation: "فلاور", example: "The flower is red.", exampleArabic: "الزهرة حمراء", category: "طقس" },
    { id: 2522, word: "grass", arabic: "عشب", pronunciation: "غراس", example: "The grass is green.", exampleArabic: "العشب أخضر", category: "طقس" },
    { id: 2523, word: "river", arabic: "نهر", pronunciation: "ريفر", example: "The river is long.", exampleArabic: "النهر طويل", category: "طقس" },
    { id: 2524, word: "mountain", arabic: "جبل", pronunciation: "ماونتن", example: "The mountain is high.", exampleArabic: "الجبل عالي", category: "طقس" },
    { id: 2525, word: "beach", arabic: "شاطئ", pronunciation: "بيتش", example: "I go to the beach.", exampleArabic: "أذهب إلى الشاطئ", category: "طقس" },

    // الحيوانات
    { id: 2601, word: "animal", arabic: "حيوان", pronunciation: "أنيمال", example: "I love animals.", exampleArabic: "أحب الحيوانات", category: "حيوانات" },
    { id: 2602, word: "dog", arabic: "كلب", pronunciation: "دوغ", example: "The dog is friendly.", exampleArabic: "الكلب ودود", category: "حيوانات" },
    { id: 2603, word: "cat", arabic: "قطة", pronunciation: "كات", example: "The cat is sleeping.", exampleArabic: "القطة نائمة", category: "حيوانات" },
    { id: 2604, word: "bird", arabic: "طائر", pronunciation: "بيرد", example: "The bird is singing.", exampleArabic: "الطائر يغرد", category: "حيوانات" },
    { id: 2605, word: "rabbit", arabic: "أرنب", pronunciation: "رابت", example: "The rabbit is fast.", exampleArabic: "الأرنب سريع", category: "حيوانات" },
    { id: 2606, word: "horse", arabic: "حصان", pronunciation: "هورس", example: "The horse runs fast.", exampleArabic: "الحصان يجري بسرعة", category: "حيوانات" },
    { id: 2607, word: "cow", arabic: "بقرة", pronunciation: "كاو", example: "The cow gives milk.", exampleArabic: "البقرة تعطي الحليب", category: "حيوانات" },
    { id: 2608, word: "sheep", arabic: "خروف", pronunciation: "شيب", example: "The sheep is white.", exampleArabic: "الخروف أبيض", category: "حيوانات" },
    { id: 2609, word: "goat", arabic: "ماعز", pronunciation: "غوت", example: "The goat climbs.", exampleArabic: "الماعز يتسلق", category: "حيوانات" },
    { id: 2610, word: "chicken", arabic: "دجاجة", pronunciation: "تشيكن", example: "The chicken lays eggs.", exampleArabic: "الدجاجة تبيض", category: "حيوانات" },
    { id: 2611, word: "duck", arabic: "بطة", pronunciation: "دوك", example: "The duck swims.", exampleArabic: "البطة تسبح", category: "حيوانات" },
    { id: 2612, word: "lion", arabic: "أسد", pronunciation: "لايون", example: "The lion is strong.", exampleArabic: "الأسد قوي", category: "حيوانات" },
    { id: 2613, word: "tiger", arabic: "نمر", pronunciation: "تايغر", example: "The tiger has stripes.", exampleArabic: "النمر مخطط", category: "حيوانات" },
    { id: 2614, word: "elephant", arabic: "فيل", pronunciation: "إليفنت", example: "The elephant is big.", exampleArabic: "الفيل كبير", category: "حيوانات" },
    { id: 2615, word: "giraffe", arabic: "زرافة", pronunciation: "جيراف", example: "The giraffe has long neck.", exampleArabic: "الزرافة عنقها طويل", category: "حيوانات" },
    { id: 2616, word: "monkey", arabic: "قرد", pronunciation: "مونكي", example: "The monkey is funny.", exampleArabic: "القرد مضحك", category: "حيوانات" },
    { id: 2617, word: "bear", arabic: "دب", pronunciation: "بير", example: "The bear is big.", exampleArabic: "الدب كبير", category: "حيوانات" },
    { id: 2618, word: "camel", arabic: "جمل", pronunciation: "كاميل", example: "The camel lives in desert.", exampleArabic: "الجمل يعيش في الصحراء", category: "حيوانات" },
    { id: 2619, word: "mouse", arabic: "فأر", pronunciation: "ماوس", example: "The mouse is small.", exampleArabic: "الفأر صغير", category: "حيوانات" },
    { id: 2620, word: "snake", arabic: "ثعبان", pronunciation: "سنايك", example: "The snake is long.", exampleArabic: "الثعبان طويل", category: "حيوانات" },
    { id: 2621, word: "frog", arabic: "ضفدع", pronunciation: "فروغ", example: "The frog jumps.", exampleArabic: "الضفدع يقفز", category: "حيوانات" },
    { id: 2622, word: "bee", arabic: "نحلة", pronunciation: "بي", example: "The bee makes honey.", exampleArabic: "النحلة تصنع العسل", category: "حيوانات" },
    { id: 2623, word: "butterfly", arabic: "فراشة", pronunciation: "باترفلاي", example: "The butterfly is beautiful.", exampleArabic: "الفراشة جميلة", category: "حيوانات" },
    { id: 2624, word: "panda", arabic: "باندا", pronunciation: "باندا", example: "The panda is black and white.", exampleArabic: "الباندا أسود وأبيض", category: "حيوانات" },
    { id: 2625, word: "kangaroo", arabic: "كنغر", pronunciation: "كانغارو", example: "The kangaroo jumps high.", exampleArabic: "الكنغر يقفز عالياً", category: "حيوانات" },

    // الألوان
    { id: 2701, word: "color", arabic: "لون", pronunciation: "كالر", example: "What color do you like?", exampleArabic: "ما هو اللون الذي تحب؟", category: "ألوان" },
    { id: 2702, word: "red", arabic: "أحمر", pronunciation: "ريد", example: "The apple is red.", exampleArabic: "التفاحة حمراء", category: "ألوان" },
    { id: 2703, word: "blue", arabic: "أزرق", pronunciation: "بلو", example: "The sky is blue.", exampleArabic: "السماء زرقاء", category: "ألوان" },
    { id: 2704, word: "green", arabic: "أخضر", pronunciation: "جرين", example: "The grass is green.", exampleArabic: "العشب أخضر", category: "ألوان" },
    { id: 2705, word: "yellow", arabic: "أصفر", pronunciation: "يلو", example: "The sun is yellow.", exampleArabic: "الشمس صفراء", category: "ألوان" },
    { id: 2706, word: "orange", arabic: "برتقالي", pronunciation: "أورانج", example: "The orange fruit is orange.", exampleArabic: "ثمرة البرتقال برتقالية", category: "ألوان" },
    { id: 2707, word: "purple", arabic: "بنفسجي", pronunciation: "بيربل", example: "She likes purple flowers.", exampleArabic: "هي تحب الزهور البنفسجية", category: "ألوان" },
    { id: 2708, word: "pink", arabic: "وردي", pronunciation: "بينك", example: "The dress is pink.", exampleArabic: "الفستان وردي", category: "ألوان" },
    { id: 2709, word: "brown", arabic: "بني", pronunciation: "براون", example: "The chocolate is brown.", exampleArabic: "الشوكولاتة بنية", category: "ألوان" },
    { id: 2710, word: "black", arabic: "أسود", pronunciation: "بلاك", example: "The cat is black.", exampleArabic: "القطة سوداء", category: "ألوان" },
    { id: 2711, word: "white", arabic: "أبيض", pronunciation: "وايت", example: "The snow is white.", exampleArabic: "الثلج أبيض", category: "ألوان" },
    { id: 2712, word: "gray", arabic: "رمادي", pronunciation: "جري", example: "The cloud is gray.", exampleArabic: "السحابة رمادية", category: "ألوان" },
    { id: 2713, word: "gold", arabic: "ذهبي", pronunciation: "جولد", example: "The ring is gold.", exampleArabic: "الخاتم ذهبي", category: "ألوان" },
    { id: 2714, word: "silver", arabic: "فضي", pronunciation: "سيلفر", example: "The coin is silver.", exampleArabic: "العملة فضية", category: "ألوان" },
    { id: 2715, word: "beige", arabic: "بيج", pronunciation: "بيج", example: "The sofa is beige.", exampleArabic: "الأريكة بيج", category: "ألوان" },
    { id: 2716, word: "cream", arabic: "كريمي", pronunciation: "كريم", example: "The walls are cream.", exampleArabic: "الجدران كريمية", category: "ألوان" },
    { id: 2717, word: "navy", arabic: "كحلي", pronunciation: "نيفي", example: "He wears a navy suit.", exampleArabic: "يرتدي بدلة كحلية", category: "ألوان" },
    { id: 2718, word: "turquoise", arabic: "فيروزي", pronunciation: "توركواز", example: "The sea is turquoise.", exampleArabic: "البحر فيروزي", category: "ألوان" },
    { id: 2719, word: "violet", arabic: "بنفسجي", pronunciation: "فايولت", example: "Violet flowers are pretty.", exampleArabic: "الزهور البنفسجية جميلة", category: "ألوان" },
    { id: 2720, word: "maroon", arabic: "عنابي", pronunciation: "مارون", example: "She likes maroon lipstick.", exampleArabic: "تحب أحمر الشفاه العنابي", category: "ألوان" },
    { id: 2721, word: "olive", arabic: "زيتوني", pronunciation: "أوليف", example: "Olive green is nice.", exampleArabic: "الأخضر الزيتوني جميل", category: "ألوان" },
    { id: 2722, word: "coral", arabic: "مرجاني", pronunciation: "كورال", example: "Coral pink is trendy.", exampleArabic: "الوردي المرجاني رائج", category: "ألوان" },
    { id: 2723, word: "indigo", arabic: "نيلي", pronunciation: "إنديغو", example: "Indigo is a deep blue.", exampleArabic: "النيلي هو أزرق غامق", category: "ألوان" },
    { id: 2724, word: "lavender", arabic: "خزامي", pronunciation: "لافيندر", example: "Lavender color is soft.", exampleArabic: "اللون الخزامي ناعم", category: "ألوان" },
    { id: 2725, word: "peach", arabic: "خوخي", pronunciation: "بيتش", example: "Peach is a warm color.", exampleArabic: "الخوخي لون دافئ", category: "ألوان" },

    // المهن
    { id: 2801, word: "job", arabic: "مهنة", pronunciation: "جوب", example: "What is your job?", exampleArabic: "ما هي مهنتك؟", category: "مهن" },
    { id: 2802, word: "doctor", arabic: "طبيب", pronunciation: "داكتر", example: "The doctor helps sick people.", exampleArabic: "الطبيب يساعد المرضى", category: "مهن" },
    { id: 2803, word: "teacher", arabic: "معلم", pronunciation: "تيتشر", example: "The teacher explains lessons.", exampleArabic: "المعلم يشرح الدروس", category: "مهن" },
    { id: 2804, word: "engineer", arabic: "مهندس", pronunciation: "إنجينير", example: "The engineer designs buildings.", exampleArabic: "المهندس يصمم المباني", category: "مهن" },
    { id: 2805, word: "nurse", arabic: "ممرض", pronunciation: "نيرس", example: "The nurse takes care of patients.", exampleArabic: "الممرض يعتني بالمرضى", category: "مهن" },
    { id: 2806, word: "pilot", arabic: "طيار", pronunciation: "بايلوت", example: "The pilot flies the plane.", exampleArabic: "الطيار يقود الطائرة", category: "مهن" },
    { id: 2807, word: "police", arabic: "شرطي", pronunciation: "بوليس", example: "The police keeps us safe.", exampleArabic: "الشرطي يحمينا", category: "مهن" },
    { id: 2808, word: "firefighter", arabic: "رجل إطفاء", pronunciation: "فاير فايتر", example: "The firefighter puts out fires.", exampleArabic: "رجل الإطفاء يطفئ الحرائق", category: "مهن" },
    { id: 2809, word: "chef", arabic: "طاهي", pronunciation: "شيف", example: "The chef cooks delicious food.", exampleArabic: "الطاهي يطبخ طعاماً لذيذاً", category: "مهن" },
    { id: 2810, word: "driver", arabic: "سائق", pronunciation: "درايفر", example: "The driver drives the bus.", exampleArabic: "السائق يقود الحافلة", category: "مهن" },
    { id: 2811, word: "farmer", arabic: "مزارع", pronunciation: "فارمر", example: "The farmer grows vegetables.", exampleArabic: "المزارع يزرع الخضروات", category: "مهن" },
    { id: 2812, word: "artist", arabic: "فنان", pronunciation: "أرتست", example: "The artist paints pictures.", exampleArabic: "الفنان يرسم اللوحات", category: "مهن" },
    { id: 2813, word: "musician", arabic: "موسيقي", pronunciation: "ميوزيشن", example: "The musician plays music.", exampleArabic: "الموسيقي يعزف الموسيقى", category: "مهن" },
    { id: 2814, word: "singer", arabic: "مطرب", pronunciation: "سينغر", example: "The singer has a beautiful voice.", exampleArabic: "المطرب صوته جميل", category: "مهن" },
    { id: 2815, word: "actor", arabic: "ممثل", pronunciation: "أكتور", example: "The actor performs in movies.", exampleArabic: "الممثل يمثل في الأفلام", category: "مهن" },
    { id: 2816, word: "lawyer", arabic: "محامي", pronunciation: "لويير", example: "The lawyer defends clients.", exampleArabic: "المحامي يدافع عن العملاء", category: "مهن" },
    { id: 2817, word: "journalist", arabic: "صحفي", pronunciation: "جورناليست", example: "The journalist writes news.", exampleArabic: "الصحفي يكتب الأخبار", category: "مهن" },
    { id: 2818, word: "scientist", arabic: "عالم", pronunciation: "ساينتست", example: "The scientist does research.", exampleArabic: "العالم يقوم بالبحث", category: "مهن" },
    { id: 2819, word: "architect", arabic: "مهندس معماري", pronunciation: "أركيتكت", example: "The architect designs houses.", exampleArabic: "المهندس المعماري يصمم المنازل", category: "مهن" },
    { id: 2820, word: "electrician", arabic: "كهربائي", pronunciation: "إلكتريشن", example: "The electrician fixes wires.", exampleArabic: "الكهربائي يصلح الأسلاك", category: "مهن" },
    { id: 2821, word: "plumber", arabic: "سباك", pronunciation: "بلومبر", example: "The plumber fixes pipes.", exampleArabic: "السباك يصلح الأنابيب", category: "مهن" },
    { id: 2822, word: "carpenter", arabic: "نجار", pronunciation: "كاربنتر", example: "The carpenter makes furniture.", exampleArabic: "النجار يصنع الأثاث", category: "مهن" },
    { id: 2823, word: "mechanic", arabic: "ميكانيكي", pronunciation: "ميكانيك", example: "The mechanic repairs cars.", exampleArabic: "الميكانيكي يصلح السيارات", category: "مهن" },
    { id: 2824, word: "barber", arabic: "حلاق", pronunciation: "باربر", example: "The barber cuts hair.", exampleArabic: "الحلاق يقص الشعر", category: "مهن" },
    { id: 2825, word: "waiter", arabic: "نادل", pronunciation: "ويتر", example: "The waiter serves food.", exampleArabic: "النادل يقدم الطعام", category: "مهن" },

    // الرياضة
    { id: 2901, word: "sport", arabic: "رياضة", pronunciation: "سبورت", example: "Sport is good for health.", exampleArabic: "الرياضة مفيدة للصحة", category: "رياضة" },
    { id: 2902, word: "football", arabic: "كرة قدم", pronunciation: "فوت بول", example: "I play football.", exampleArabic: "ألعب كرة القدم", category: "رياضة" },
    { id: 2903, word: "basketball", arabic: "كرة سلة", pronunciation: "باسكت بول", example: "He is tall, he plays basketball.", exampleArabic: "هو طويل، يلعب كرة السلة", category: "رياضة" },
    { id: 2904, word: "tennis", arabic: "تنس", pronunciation: "تينيس", example: "She plays tennis.", exampleArabic: "هي تلعب التنس", category: "رياضة" },
    { id: 2905, word: "swimming", arabic: "سباحة", pronunciation: "سويمينغ", example: "Swimming is fun.", exampleArabic: "السباحة ممتعة", category: "رياضة" },
    { id: 2906, word: "running", arabic: "جري", pronunciation: "رانينغ", example: "I go running every morning.", exampleArabic: "أذهب للجري كل صباح", category: "رياضة" },
    { id: 2907, word: "cycling", arabic: "ركوب دراجات", pronunciation: "سايكلينغ", example: "Cycling is good exercise.", exampleArabic: "ركوب الدراجات تمرين جيد", category: "رياضة" },
    { id: 2908, word: "gym", arabic: "نادي رياضي", pronunciation: "جيم", example: "I go to the gym.", exampleArabic: "أذهب إلى النادي الرياضي", category: "رياضة" },
    { id: 2909, word: "yoga", arabic: "يوغا", pronunciation: "يوغا", example: "Yoga helps me relax.", exampleArabic: "اليوغا تساعدني على الاسترخاء", category: "رياضة" },
    { id: 2910, word: "team", arabic: "فريق", pronunciation: "تيم", example: "We are a good team.", exampleArabic: "نحن فريق جيد", category: "رياضة" },
    { id: 2911, word: "player", arabic: "لاعب", pronunciation: "بلاير", example: "He is a professional player.", exampleArabic: "هو لاعب محترف", category: "رياضة" },
    { id: 2912, word: "coach", arabic: "مدرب", pronunciation: "كوتش", example: "The coach teaches us.", exampleArabic: "المدرب يعلمنا", category: "رياضة" },
    { id: 2913, word: "game", arabic: "مباراة", pronunciation: "جايم", example: "The game is exciting.", exampleArabic: "المباراة مثيرة", category: "رياضة" },
    { id: 2914, word: "match", arabic: "مباراة", pronunciation: "ماتش", example: "We won the match.", exampleArabic: "فزنا بالمباراة", category: "رياضة" },
    { id: 2915, word: "score", arabic: "نتيجة", pronunciation: "سكور", example: "What is the score?", exampleArabic: "ما هي النتيجة؟", category: "رياضة" },
    { id: 2916, word: "goal", arabic: "هدف", pronunciation: "جول", example: "He scored a goal.", exampleArabic: "سجل هدفاً", category: "رياضة" },
    { id: 2917, word: "win", arabic: "يفوز", pronunciation: "وين", example: "We want to win.", exampleArabic: "نريد أن نفوز", category: "رياضة" },
    { id: 2918, word: "lose", arabic: "يخسر", pronunciation: "لوز", example: "Don't lose hope.", exampleArabic: "لا تخسر الأمل", category: "رياضة" },
    { id: 2919, word: "ball", arabic: "كرة", pronunciation: "بول", example: "Pass the ball.", exampleArabic: "مرر الكرة", category: "رياضة" },
    { id: 2920, word: "stadium", arabic: "ملعب", pronunciation: "ستاديوم", example: "The stadium is full.", exampleArabic: "الملعب ممتلئ", category: "رياضة" },
    { id: 2921, word: "race", arabic: "سباق", pronunciation: "رايس", example: "He won the race.", exampleArabic: "فاز بالسباق", category: "رياضة" },
    { id: 2922, word: "exercise", arabic: "تمرين", pronunciation: "إكسيرسايز", example: "Do exercise every day.", exampleArabic: "قم بالتمرين كل يوم", category: "رياضة" },
    { id: 2923, word: "fitness", arabic: "لياقة", pronunciation: "فيتنس", example: "Fitness is important.", exampleArabic: "اللياقة مهمة", category: "رياضة" },
    { id: 2924, word: "champion", arabic: "بطل", pronunciation: "تشامبيون", example: "He is the champion.", exampleArabic: "هو البطل", category: "رياضة" },
    { id: 2925, word: "medal", arabic: "ميدالية", pronunciation: "ميدال", example: "She won a gold medal.", exampleArabic: "فازت بميدالية ذهبية", category: "رياضة" }
];

// التحقق من التحميل
console.log('✅ beginner-data.js loaded with', BEGINNER_WORDS.length, 'words');

// تصدير البيانات للاستخدام في ملفات أخرى
if (typeof module !== 'undefined' && module.exports) {
    module.exports = BEGINNER_WORDS;
    }
