// intermediate-data.js - 500 كلمة للمستوى المتوسط (كلمات أعمق وأكثر استخداماً)
const INTERMEDIATE_WORDS = [
    // ========== تحيات ومجاملات متقدمة ========== (25 كلمة)
    { id: 3001, word: "greet", arabic: "يحيي", pronunciation: "غريت", example: "She greeted me warmly.", exampleArabic: "استقبلتني بحرارة", category: "تحيات" },
    { id: 3002, word: "welcome", arabic: "يرحب", pronunciation: "ويلكم", example: "They welcomed us to their home.", exampleArabic: "رحبوا بنا في منزلهم", category: "تحيات" },
    { id: 3003, word: "introduce", arabic: "يقدم", pronunciation: "إنتروديوس", example: "Let me introduce my friend.", exampleArabic: "دعني أقدم صديقي", category: "تحيات" },
    { id: 3004, word: "apologize", arabic: "يعتذر", pronunciation: "أبولجايز", example: "I apologize for being late.", exampleArabic: "أنا أعتذر على التأخير", category: "تحيات" },
    { id: 3005, word: "forgive", arabic: "يسامح", pronunciation: "فورغيف", example: "Please forgive me.", exampleArabic: "من فضلك سامحني", category: "تحيات" },
    { id: 3006, word: "polite", arabic: "مهذب", pronunciation: "بولايت", example: "He is always polite.", exampleArabic: "هو دائماً مهذب", category: "تحيات" },
    { id: 3007, word: "rude", arabic: "وقح", pronunciation: "رود", example: "That was rude.", exampleArabic: "كان ذلك وقحاً", category: "تحيات" },
    { id: 3008, word: "formal", arabic: "رسمي", pronunciation: "فورمال", example: "Use formal language.", exampleArabic: "استخدم لغة رسمية", category: "تحيات" },
    { id: 3009, word: "informal", arabic: "غير رسمي", pronunciation: "إنفورمال", example: "We speak informally with friends.", exampleArabic: "نتحدث بشكل غير رسمي مع الأصدقاء", category: "تحيات" },
    { id: 3010, word: "respect", arabic: "احترام", pronunciation: "ريسبكت", example: "Show respect to your elders.", exampleArabic: "أظهر الاحترام لكبار السن", category: "تحيات" },
    { id: 3011, word: "admire", arabic: "يعجب بـ", pronunciation: "أدمير", example: "I admire your work.", exampleArabic: "أنا معجب بعملك", category: "تحيات" },
    { id: 3012, word: "compliment", arabic: "مجاملة", pronunciation: "كومبليمينت", example: "She gave me a nice compliment.", exampleArabic: "قدمت لي مجاملة لطيفة", category: "تحيات" },
    { id: 3013, word: "congratulate", arabic: "يهنئ", pronunciation: "كونغراتشيليت", example: "I congratulate you on your success.", exampleArabic: "أهنئك على نجاحك", category: "تحيات" },
    { id: 3014, word: "celebrate", arabic: "يحتفل", pronunciation: "سيليبريت", example: "We celebrate your birthday.", exampleArabic: "نحتفل بعيد ميلادك", category: "تحيات" },
    { id: 3015, word: "occasion", arabic: "مناسبة", pronunciation: "أوكيشن", example: "A special occasion.", exampleArabic: "مناسبة خاصة", category: "تحيات" },
    { id: 3016, word: "ceremony", arabic: "حفل", pronunciation: "سيريموني", example: "The wedding ceremony was beautiful.", exampleArabic: "حفل الزفاف كان جميلاً", category: "تحيات" },
    { id: 3017, word: "invite", arabic: "يدعو", pronunciation: "إنفايت", example: "I invite you to my party.", exampleArabic: "أدعوك إلى حفلتي", category: "تحيات" },
    { id: 3018, word: "visit", arabic: "يزور", pronunciation: "فيزيت", example: "I visit my grandmother.", exampleArabic: "أزور جدتي", category: "تحيات" },
    { id: 3019, word: "guest", arabic: "ضيف", pronunciation: "جيست", example: "We have guests tonight.", exampleArabic: "لدينا ضيوف الليلة", category: "تحيات" },
    { id: 3020, word: "host", arabic: "مضيف", pronunciation: "هوست", example: "He is a good host.", exampleArabic: "هو مضيف جيد", category: "تحيات" },
    { id: 3021, word: "farewell", arabic: "وداع", pronunciation: "فيرويل", example: "We bid him farewell.", exampleArabic: "ودعناه", category: "تحيات" },
    { id: 3022, word: "absence", arabic: "غياب", pronunciation: "آبسنس", example: "I missed you in your absence.", exampleArabic: "افتقدتك في غيابك", category: "تحيات" },
    { id: 3023, word: "gratitude", arabic: "امتنان", pronunciation: "غراتيتيود", example: "Express your gratitude.", exampleArabic: "عبر عن امتنانك", category: "تحيات" },
    { id: 3024, word: "hospitality", arabic: "كرم الضيافة", pronunciation: "هوسبيتاليتي", example: "Thank you for your hospitality.", exampleArabic: "شكراً لكرم ضيافتك", category: "تحيات" },
    { id: 3025, word: "etiquette", arabic: "آداب السلوك", pronunciation: "إيتيكيت", example: "Learn proper etiquette.", exampleArabic: "تعلم آداب السلوك الصحيحة", category: "تحيات" },

    // ========== المنزل والأثاث متقدم ========== (25 كلمة)
    { id: 3101, word: "furniture", arabic: "أثاث", pronunciation: "فيرنيشير", example: "We bought new furniture.", exampleArabic: "اشترينا أثاثاً جديداً", category: "منزل" },
    { id: 3102, word: "decorate", arabic: "يزين", pronunciation: "ديكوريت", example: "We decorate the house for Christmas.", exampleArabic: "نزين المنزل لعيد الميلاد", category: "منزل" },
    { id: 3103, word: "paint", arabic: "يدهن", pronunciation: "باينت", example: "I paint the walls white.", exampleArabic: "أدهن الجدران باللون الأبيض", category: "منزل" },
    { id: 3104, word: "repair", arabic: "يصلح", pronunciation: "ريبير", example: "I need to repair the door.", exampleArabic: "أحتاج لإصلاح الباب", category: "منزل" },
    { id: 3105, word: "fix", arabic: "يصلح", pronunciation: "فيكس", example: "Can you fix the window?", exampleArabic: "هل يمكنك إصلاح النافذة؟", category: "منزل" },
    { id: 3106, word: "clean", arabic: "ينظف", pronunciation: "كلين", example: "I clean the house on Friday.", exampleArabic: "أنظف المنزل يوم الجمعة", category: "منزل" },
    { id: 3107, word: "sweep", arabic: "يكنس", pronunciation: "سويب", example: "I sweep the floor.", exampleArabic: "أكنس الأرضية", category: "منزل" },
    { id: 3108, word: "mop", arabic: "يمسح", pronunciation: "موب", example: "I mop the kitchen floor.", exampleArabic: "أمسح أرضية المطبخ", category: "منزل" },
    { id: 3109, word: "vacuum", arabic: "مكنسة كهربائية", pronunciation: "فاكيوم", example: "I vacuum the carpet.", exampleArabic: "أنظف السجادة بالمكنسة", category: "منزل" },
    { id: 3110, word: "dust", arabic: "غبار", pronunciation: "داست", example: "I dust the furniture.", exampleArabic: "أنفض الغبار عن الأثاث", category: "منزل" },
    { id: 3111, word: "organize", arabic: "ينظم", pronunciation: "أورغانايز", example: "I organize my closet.", exampleArabic: "أنظم خزانتي", category: "منزل" },
    { id: 3112, word: "tidy", arabic: "مرتب", pronunciation: "تايدي", example: "Keep your room tidy.", exampleArabic: "حافظ على غرفتك مرتبة", category: "منزل" },
    { id: 3113, word: "messy", arabic: "فوضوي", pronunciation: "ميسي", example: "My room is messy.", exampleArabic: "غرفتي فوضوية", category: "منزل" },
    { id: 3114, word: "move", arabic: "ينتقل", pronunciation: "موف", example: "We move to a new house.", exampleArabic: "ننتقل إلى منزل جديد", category: "منزل" },
    { id: 3115, word: "rent", arabic: "يستأجر", pronunciation: "رنت", example: "I rent an apartment.", exampleArabic: "أستأجر شقة", category: "منزل" },
    { id: 3116, word: "own", arabic: "يمتلك", pronunciation: "أون", example: "I own this house.", exampleArabic: "أنا أملك هذا المنزل", category: "منزل" },
    { id: 3117, word: "balcony", arabic: "شرفة", pronunciation: "بالكوني", example: "I sit on the balcony.", exampleArabic: "أجلس على الشرفة", category: "منزل" },
    { id: 3118, word: "yard", arabic: "فناء", pronunciation: "يار-د", example: "The children play in the yard.", exampleArabic: "الأطفال يلعبون في الفناء", category: "منزل" },
    { id: 3119, word: "garden", arabic: "حديقة", pronunciation: "غاردن", example: "I plant flowers in the garden.", exampleArabic: "أزرع الزهور في الحديقة", category: "منزل" },
    { id: 3120, word: "garage", arabic: "مرآب", pronunciation: "غاراج", example: "The car is in the garage.", exampleArabic: "السيارة في المرآب", category: "منزل" },
    { id: 3121, word: "basement", arabic: "قبو", pronunciation: "بيسمنت", example: "We store things in the basement.", exampleArabic: "نخزن الأشياء في القبو", category: "منزل" },
    { id: 3122, word: "roof", arabic: "سقف", pronunciation: "روف", example: "The roof needs repair.", exampleArabic: "السقف يحتاج إصلاحاً", category: "منزل" },
    { id: 3123, word: "fence", arabic: "سياج", pronunciation: "فينس", example: "We built a fence around the house.", exampleArabic: "بنينا سياجاً حول المنزل", category: "منزل" },
    { id: 3124, word: "gate", arabic: "بوابة", pronunciation: "جيت", example: "Close the gate.", exampleArabic: "أغلق البوابة", category: "منزل" },
    { id: 3125, word: "driveway", arabic: "ممر سيارات", pronunciation: "درايف واي", example: "The car is in the driveway.", exampleArabic: "السيارة في الممر", category: "منزل" },

    // ========== العائلة والعلاقات متقدمة ========== (25 كلمة)
    { id: 3201, word: "relative", arabic: "قريب", pronunciation: "ريلاتيف", example: "We visit our relatives.", exampleArabic: "نزور أقاربنا", category: "عائلة" },
    { id: 3202, word: "relationship", arabic: "علاقة", pronunciation: "ريليشنشيب", example: "We have a good relationship.", exampleArabic: "لدينا علاقة جيدة", category: "عائلة" },
    { id: 3203, word: "marriage", arabic: "زواج", pronunciation: "ميريدج", example: "Their marriage is happy.", exampleArabic: "زواجهم سعيد", category: "عائلة" },
    { id: 3204, word: "wedding", arabic: "عرس", pronunciation: "ويدينغ", example: "The wedding was beautiful.", exampleArabic: "العرس كان جميلاً", category: "عائلة" },
    { id: 3205, word: "divorce", arabic: "طلاق", pronunciation: "ديفورس", example: "They got divorced.", exampleArabic: "لقد تطلقوا", category: "عائلة" },
    { id: 3206, word: "engaged", arabic: "مخطوب", pronunciation: "إنجيدجد", example: "They are engaged.", exampleArabic: "هم مخطوبون", category: "عائلة" },
    { id: 3207, word: "single", arabic: "أعزب", pronunciation: "سينغل", example: "He is still single.", exampleArabic: "لا يزال أعزب", category: "عائلة" },
    { id: 3208, word: "married", arabic: "متزوج", pronunciation: "ماريد", example: "She is married.", exampleArabic: "هي متزوجة", category: "عائلة" },
    { id: 3209, word: "parent", arabic: "والد", pronunciation: "بيرنت", example: "My parents are kind.", exampleArabic: "والداي لطيفان", category: "عائلة" },
    { id: 3210, word: "childhood", arabic: "طفولة", pronunciation: "تشايلدهود", example: "I had a happy childhood.", exampleArabic: "كانت طفولتي سعيدة", category: "عائلة" },
    { id: 3211, word: "teenager", arabic: "مراهق", pronunciation: "تينيدجر", example: "He is a teenager.", exampleArabic: "هو مراهق", category: "عائلة" },
    { id: 3212, word: "adult", arabic: "بالغ", pronunciation: "أدالت", example: "She is an adult now.", exampleArabic: "هي بالغة الآن", category: "عائلة" },
    { id: 3213, word: "elderly", arabic: "مسن", pronunciation: "إيلدرلي", example: "We respect the elderly.", exampleArabic: "نحترم المسنين", category: "عائلة" },
    { id: 3214, word: "generation", arabic: "جيل", pronunciation: "جينيريشن", example: "The younger generation.", exampleArabic: "الجيل الأصغر", category: "عائلة" },
    { id: 3215, word: "ancestors", arabic: "أسلاف", pronunciation: "أنسيستورز", example: "My ancestors came from Egypt.", exampleArabic: "أسلافي جاءوا من مصر", category: "عائلة" },
    { id: 3216, word: "heritage", arabic: "تراث", pronunciation: "هيريتيدج", example: "We preserve our heritage.", exampleArabic: "نحن نحافظ على تراثنا", category: "عائلة" },
    { id: 3217, word: "tradition", arabic: "تقليد", pronunciation: "تراديشون", example: "Family traditions are important.", exampleArabic: "تقاليد العائلة مهمة", category: "عائلة" },
    { id: 3218, word: "custom", arabic: "عادة", pronunciation: "كاستوم", example: "Local customs vary.", exampleArabic: "العادات المحلية تختلف", category: "عائلة" },
    { id: 3219, word: "upbringing", arabic: "تنشئة", pronunciation: "أببرينغينغ", example: "Good upbringing is important.", exampleArabic: "التنشئة الجيدة مهمة", category: "عائلة" },
    { id: 3220, word: "support", arabic: "دعم", pronunciation: "سبورت", example: "Family supports each other.", exampleArabic: "العائلة تدعم بعضها", category: "عائلة" },
    { id: 3221, word: "care", arabic: "رعاية", pronunciation: "كير", example: "She cares for her children.", exampleArabic: "هي ترعى أطفالها", category: "عائلة" },
    { id: 3222, word: "protect", arabic: "يحمي", pronunciation: "بروتكت", example: "Parents protect their children.", exampleArabic: "الآباء يحمون أطفالهم", category: "عائلة" },
    { id: 3223, word: "nurture", arabic: "يربي", pronunciation: "نيرتشر", example: "Parents nurture their children.", exampleArabic: "الآباء يربون أطفالهم", category: "عائلة" },
    { id: 3224, word: "bond", arabic: "رابطة", pronunciation: "بوند", example: "The bond between mother and child.", exampleArabic: "الرابطة بين الأم والطفل", category: "عائلة" },
    { id: 3225, word: "kin", arabic: "أقارب", pronunciation: "كين", example: "He is my next of kin.", exampleArabic: "هو أقرب أقربائي", category: "عائلة" },

    // ========== الطعام والشراب متقدم ========== (25 كلمة)
    { id: 3301, word: "recipe", arabic: "وصفة", pronunciation: "ريسيبي", example: "I follow the recipe.", exampleArabic: "أتبع الوصفة", category: "طعام" },
    { id: 3302, word: "ingredient", arabic: "مكون", pronunciation: "إنغريديانت", example: "All ingredients are fresh.", exampleArabic: "كل المكونات طازجة", category: "طعام" },
    { id: 3303, word: "flavor", arabic: "نكهة", pronunciation: "فلايڤر", example: "This has a great flavor.", exampleArabic: "هذا له نكهة رائعة", category: "طعام" },
    { id: 3304, word: "taste", arabic: "طعم", pronunciation: "تيست", example: "I like the taste.", exampleArabic: "أحب الطعم", category: "طعام" },
    { id: 3305, word: "spicy", arabic: "حار", pronunciation: "سبايسي", example: "The food is spicy.", exampleArabic: "الطعام حار", category: "طعام" },
    { id: 3306, word: "sweet", arabic: "حلو", pronunciation: "سويت", example: "This cake is sweet.", exampleArabic: "هذه الكعكة حلوة", category: "طعام" },
    { id: 3307, word: "sour", arabic: "حامض", pronunciation: "ساور", example: "Lemons are sour.", exampleArabic: "الليمون حامض", category: "طعام" },
    { id: 3308, word: "bitter", arabic: "مر", pronunciation: "بيتر", example: "Coffee can be bitter.", exampleArabic: "القهوة قد تكون مرة", category: "طعام" },
    { id: 3309, word: "salty", arabic: "مالح", pronunciation: "سولتي", example: "The soup is too salty.", exampleArabic: "الشوربة مالحة جداً", category: "طعام" },
    { id: 3310, word: "fresh", arabic: "طازج", pronunciation: "فريش", example: "Fresh vegetables are healthy.", exampleArabic: "الخضروات الطازجة صحية", category: "طعام" },
    { id: 3311, word: "frozen", arabic: "مجمد", pronunciation: "فروزن", example: "Frozen food is convenient.", exampleArabic: "الطعام المجمد مريح", category: "طعام" },
    { id: 3312, word: "organic", arabic: "عضوي", pronunciation: "أورغانيك", example: "I prefer organic food.", exampleArabic: "أفضل الطعام العضوي", category: "طعام" },
    { id: 3313, word: "delicious", arabic: "لذيذ", pronunciation: "ديليشس", example: "This meal is delicious.", exampleArabic: "هذه الوجبة لذيذة", category: "طعام" },
    { id: 3314, word: "tasty", arabic: "لذيذ", pronunciation: "تيستي", example: "Very tasty!", exampleArabic: "لذيذ جداً!", category: "طعام" },
    { id: 3315, word: "yummy", arabic: "لذيذ", pronunciation: "يامي", example: "Yummy food!", exampleArabic: "طعام لذيذ!", category: "طعام" },
    { id: 3316, word: "appetizer", arabic: "مقبلات", pronunciation: "أبيتايزر", example: "We start with appetizers.", exampleArabic: "نبدأ بالمقبلات", category: "طعام" },
    { id: 3317, word: "main course", arabic: "طبق رئيسي", pronunciation: "مين كورس", example: "The main course is chicken.", exampleArabic: "الطبق الرئيسي دجاج", category: "طعام" },
    { id: 3318, word: "dessert", arabic: "حلوى", pronunciation: "ديزيرت", example: "I love dessert.", exampleArabic: "أحب الحلوى", category: "طعام" },
    { id: 3319, word: "beverage", arabic: "مشروب", pronunciation: "بيفريدج", example: "We serve beverages.", exampleArabic: "نقدم المشروبات", category: "طعام" },
    { id: 3320, word: "menu", arabic: "قائمة طعام", pronunciation: "مينيو", example: "Let's see the menu.", exampleArabic: "لنرى قائمة الطعام", category: "طعام" },
    { id: 3321, word: "order", arabic: "يطلب", pronunciation: "أوردر", example: "I order pizza.", exampleArabic: "أطلب بيتزا", category: "طعام" },
    { id: 3322, word: "serve", arabic: "يقدم", pronunciation: "سيرف", example: "They serve breakfast.", exampleArabic: "يقدمون الفطور", category: "طعام" },
    { id: 3323, word: "gourmet", arabic: "فاخر", pronunciation: "غورمي", example: "Gourmet restaurant.", exampleArabic: "مطعم فاخر", category: "طعام" },
    { id: 3324, word: "cuisine", arabic: "مطبخ", pronunciation: "كويزين", example: "Italian cuisine.", exampleArabic: "المطبخ الإيطالي", category: "طعام" },
    { id: 3325, word: "appetite", arabic: "شهية", pronunciation: "أبيتايت", example: "I have a good appetite.", exampleArabic: "لدي شهية جيدة", category: "طعام" },

    // ========== التسوق والمال متقدم ========== (25 كلمة)
    { id: 3401, word: "purchase", arabic: "شراء", pronunciation: "بيرتشيس", example: "I made a purchase online.", exampleArabic: "قمت بشراء عبر الإنترنت", category: "تسوق" },
    { id: 3402, word: "afford", arabic: "يستطيع الشراء", pronunciation: "أفورد", example: "I can't afford this car.", exampleArabic: "لا أستطيع شراء هذه السيارة", category: "تسوق" },
    { id: 3403, word: "budget", arabic: "ميزانية", pronunciation: "باجت", example: "I have a monthly budget.", exampleArabic: "لدي ميزانية شهرية", category: "تسوق" },
    { id: 3404, word: "save", arabic: "يوفر", pronunciation: "سايف", example: "I save money for travel.", exampleArabic: "أوفر المال للسفر", category: "تسوق" },
    { id: 3405, word: "spend", arabic: "ينفق", pronunciation: "سبيند", example: "Don't spend too much.", exampleArabic: "لا تنفق الكثير", category: "تسوق" },
    { id: 3406, word: "waste", arabic: "يضيع", pronunciation: "ويست", example: "Don't waste your money.", exampleArabic: "لا تضيع أموالك", category: "تسوق" },
    { id: 3407, word: "bargain", arabic: "صفقة", pronunciation: "بارغين", example: "I got a good bargain.", exampleArabic: "حصلت على صفقة جيدة", category: "تسوق" },
    { id: 3408, word: "deal", arabic: "اتفاقية", pronunciation: "ديل", example: "Great deal!", exampleArabic: "اتفاقية رائعة!", category: "تسوق" },
    { id: 3409, word: "receipt", arabic: "إيصال", pronunciation: "ريسيبت", example: "Keep the receipt.", exampleArabic: "احتفظ بالإيصال", category: "تسوق" },
    { id: 3410, word: "refund", arabic: "استرداد", pronunciation: "ريفاند", example: "I want a refund.", exampleArabic: "أريد استرداد النقود", category: "تسوق" },
    { id: 3411, word: "exchange", arabic: "استبدال", pronunciation: "إكس تشينج", example: "Can I exchange this?", exampleArabic: "هل يمكنني استبدال هذا؟", category: "تسوق" },
    { id: 3412, word: "return", arabic: "إرجاع", pronunciation: "ريترن", example: "I need to return this.", exampleArabic: "أحتاج إرجاع هذا", category: "تسوق" },
    { id: 3413, word: "online shopping", arabic: "تسوق عبر الإنترنت", pronunciation: "أونلاين شوبينغ", example: "I prefer online shopping.", exampleArabic: "أفضل التسوق عبر الإنترنت", category: "تسوق" },
    { id: 3414, word: "delivery", arabic: "توصيل", pronunciation: "ديلفري", example: "Free delivery.", exampleArabic: "توصيل مجاني", category: "تسوق" },
    { id: 3415, word: "shipping", arabic: "شحن", pronunciation: "شيبينغ", example: "Shipping costs $5.", exampleArabic: "تكلفة الشحن 5 دولارات", category: "تسوق" },
    { id: 3416, word: "track", arabic: "يتتبع", pronunciation: "تراك", example: "Track your order.", exampleArabic: "تتبع طلبك", category: "تسوق" },
    { id: 3417, word: "wallet", arabic: "محفظة", pronunciation: "ووليت", example: "I lost my wallet.", exampleArabic: "فقدت محفظتي", category: "تسوق" },
    { id: 3418, word: "purse", arabic: "حقيبة يد", pronunciation: "بيرس", example: "She carries a purse.", exampleArabic: "هي تحمل حقيبة يد", category: "تسوق" },
    { id: 3419, word: "ATM", arabic: "صراف آلي", pronunciation: "إيه تي إم", example: "I withdraw cash from ATM.", exampleArabic: "أسحب نقوداً من الصراف الآلي", category: "تسوق" },
    { id: 3420, word: "bank account", arabic: "حساب بنكي", pronunciation: "بانك أكاونت", example: "Open a bank account.", exampleArabic: "افتح حساباً بنكياً", category: "تسوق" },
    { id: 3421, word: "interest", arabic: "فائدة", pronunciation: "إنترست", example: "Interest rates are low.", exampleArabic: "معدلات الفائدة منخفضة", category: "تسوق" },
    { id: 3422, word: "loan", arabic: "قرض", pronunciation: "لون", example: "I need a loan.", exampleArabic: "أحتاج قرضاً", category: "تسوق" },
    { id: 3423, word: "debt", arabic: "دين", pronunciation: "ديت", example: "I have no debt.", exampleArabic: "ليس علي ديون", category: "تسوق" },
    { id: 3424, word: "credit", arabic: "ائتمان", pronunciation: "كريدايت", example: "Good credit score.", exampleArabic: "درجة ائتمان جيدة", category: "تسوق" },
    { id: 3425, word: "mortgage", arabic: "رهن عقاري", pronunciation: "مورغاج", example: "We have a mortgage.", exampleArabic: "لدينا رهن عقاري", category: "تسوق" },

    // ========== المواصلات والسفر متقدم ========== (25 كلمة)
    { id: 3501, word: "transportation", arabic: "نقل", pronunciation: "ترانسبورتيشن", example: "Public transportation is cheap.", exampleArabic: "النقل العام رخيص", category: "مواصلات" },
    { id: 3502, word: "vehicle", arabic: "مركبة", pronunciation: "فيهيكل", example: "This vehicle is electric.", exampleArabic: "هذه المركبة كهربائية", category: "مواصلات" },
    { id: 3503, word: "commute", arabic: "تنقل", pronunciation: "كوميوت", example: "I commute to work by train.", exampleArabic: "أتنقل إلى العمل بالقطار", category: "مواصلات" },
    { id: 3504, word: "traffic", arabic: "حركة مرور", pronunciation: "ترافيك", example: "Traffic is heavy now.", exampleArabic: "الحركة كثيفة الآن", category: "مواصلات" },
    { id: 3505, word: "rush hour", arabic: "ساعة الذروة", pronunciation: "راش آور", example: "Avoid rush hour.", exampleArabic: "تجنب ساعة الذروة", category: "مواصلات" },
    { id: 3506, word: "fare", arabic: "أجرة", pronunciation: "فير", example: "Bus fare is cheap.", exampleArabic: "أجرة الحافلة رخيصة", category: "مواصلات" },
    { id: 3507, word: "ticket", arabic: "تذكرة", pronunciation: "تيكيت", example: "I bought a ticket.", exampleArabic: "اشتريت تذكرة", category: "مواصلات" },
    { id: 3508, word: "reservation", arabic: "حجز", pronunciation: "ريزيرفيشن", example: "I have a reservation.", exampleArabic: "لدي حجز", category: "مواصلات" },
    { id: 3509, word: "book", arabic: "يحجز", pronunciation: "بوك", example: "I book a hotel room.", exampleArabic: "أحجز غرفة في فندق", category: "مواصلات" },
    { id: 3510, word: "cancel", arabic: "يلغي", pronunciation: "كانسل", example: "I need to cancel my flight.", exampleArabic: "أحتاج إلغاء رحلتي", category: "مواصلات" },
    { id: 3511, word: "delay", arabic: "تأخير", pronunciation: "ديلاي", example: "The flight is delayed.", exampleArabic: "الرحلة متأخرة", category: "مواصلات" },
    { id: 3512, word: "boarding pass", arabic: "بطاقة صعود", pronunciation: "بوردينغ باس", example: "Show your boarding pass.", exampleArabic: "أظهر بطاقة صعودك", category: "مواصلات" },
    { id: 3513, word: "gate", arabic: "بوابة", pronunciation: "جيت", example: "Go to gate 5.", exampleArabic: "اذهب إلى البوابة 5", category: "مواصلات" },
    { id: 3514, word: "luggage", arabic: "أمتعة", pronunciation: "لاجيدج", example: "I have two pieces of luggage.", exampleArabic: "لدي قطعتان من الأمتعة", category: "مواصلات" },
    { id: 3515, word: "suitcase", arabic: "حقيبة سفر", pronunciation: "سوتكيس", example: "Pack your suitcase.", exampleArabic: "احزم حقيبة سفرك", category: "مواصلات" },
    { id: 3516, word: "baggage claim", arabic: "استلام الأمتعة", pronunciation: "باجيدج كليم", example: "Go to baggage claim.", exampleArabic: "اذهب لاستلام الأمتعة", category: "مواصلات" },
    { id: 3517, word: "customs", arabic: "جمارك", pronunciation: "كاستومز", example: "Pass through customs.", exampleArabic: "اعبر الجمارك", category: "مواصلات" },
    { id: 3518, word: "visa", arabic: "تأشيرة", pronunciation: "فيزا", example: "I need a visa to travel.", exampleArabic: "أحتاج تأشيرة للسفر", category: "مواصلات" },
    { id: 3519, word: "passport", arabic: "جواز سفر", pronunciation: "باسبورت", example: "Don't lose your passport.", exampleArabic: "لا تفقد جواز سفرك", category: "مواصلات" },
    { id: 3520, word: "destination", arabic: "وجهة", pronunciation: "ديستينيشن", example: "Our destination is Paris.", exampleArabic: "وجهتنا هي باريس", category: "مواصلات" },
    { id: 3521, word: "journey", arabic: "رحلة", pronunciation: "جورني", example: "Have a safe journey.", exampleArabic: "رحلة آمنة", category: "مواصلات" },
    { id: 3522, word: "tourism", arabic: "سياحة", pronunciation: "توريسم", example: "Tourism is important.", exampleArabic: "السياحة مهمة", category: "مواصلات" },
    { id: 3523, word: "itinerary", arabic: "برنامج الرحلة", pronunciation: "أيتنيراري", example: "Plan your itinerary.", exampleArabic: "خطط لبرنامج رحلتك", category: "مواصلات" },
    { id: 3524, word: "accommodation", arabic: "إقامة", pronunciation: "أكوموديشن", example: "Find accommodation.", exampleArabic: "ابحث عن مكان إقامة", category: "مواصلات" },
    { id: 3525, word: "all-inclusive", arabic: "شامل كل شيء", pronunciation: "أول إنكلوسيف", example: "All-inclusive resort.", exampleArabic: "منتجع شامل كل شيء", category: "مواصلات" },

    // ========== الصحة والجسم متقدم ========== (25 كلمة)
    { id: 3601, word: "health", arabic: "صحة", pronunciation: "هيلث", example: "Health is wealth.", exampleArabic: "الصحة هي الثروة", category: "صحة" },
    { id: 3602, word: "fitness", arabic: "لياقة", pronunciation: "فيتنس", example: "I go to fitness classes.", exampleArabic: "أذهب لحصص اللياقة", category: "صحة" },
    { id: 3603, word: "exercise", arabic: "تمرين", pronunciation: "إكسيرسايز", example: "Exercise is important.", exampleArabic: "التمرين مهم", category: "صحة" },
    { id: 3604, word: "workout", arabic: "تمرين رياضي", pronunciation: "ورك آوت", example: "I do a workout daily.", exampleArabic: "أقوم بتمرين يومي", category: "صحة" },
    { id: 3605, word: "gym", arabic: "نادي رياضي", pronunciation: "جيم", example: "I go to the gym.", exampleArabic: "أذهب إلى النادي الرياضي", category: "صحة" },
    { id: 3606, word: "diet", arabic: "حمية", pronunciation: "دايت", example: "I'm on a diet.", exampleArabic: "أنا على حمية", category: "صحة" },
    { id: 3607, word: "nutrition", arabic: "تغذية", pronunciation: "نيوتريشن", example: "Good nutrition is key.", exampleArabic: "التغذية الجيدة هي المفتاح", category: "صحة" },
    { id: 3608, word: "vitamin", arabic: "فيتامين", pronunciation: "فيتامين", example: "Take vitamin C.", exampleArabic: "خذ فيتامين سي", category: "صحة" },
    { id: 3609, word: "mineral", arabic: "معدن", pronunciation: "مينيرال", example: "Minerals are essential.", exampleArabic: "المعادن ضرورية", category: "صحة" },
    { id: 3610, word: "protein", arabic: "بروتين", pronunciation: "بروتين", example: "Eat enough protein.", exampleArabic: "كل كمية كافية من البروتين", category: "صحة" },
    { id: 3611, word: "carbohydrate", arabic: "كربوهيدرات", pronunciation: "كاربوهيدريت", example: "Carbs give energy.", exampleArabic: "الكربوهيدرات تعطي طاقة", category: "صحة" },
    { id: 3612, word: "calorie", arabic: "سعرة حرارية", pronunciation: "كالوري", example: "Count your calories.", exampleArabic: "احسب سعراتك الحرارية", category: "صحة" },
    { id: 3613, word: "weight", arabic: "وزن", pronunciation: "ويت", example: "I lost weight.", exampleArabic: "فقدت وزناً", category: "صحة" },
    { id: 3614, word: "lose", arabic: "يفقد", pronunciation: "لوز", example: "I want to lose weight.", exampleArabic: "أريد فقدان الوزن", category: "صحة" },
    { id: 3615, word: "gain", arabic: "يكتسب", pronunciation: "جاين", example: "I gain weight easily.", exampleArabic: "أكتسب وزناً بسهولة", category: "صحة" },
    { id: 3616, word: "symptom", arabic: "عَرَض", pronunciation: "سيمبتوم", example: "What are your symptoms?", exampleArabic: "ما هي أعراضك؟", category: "صحة" },
    { id: 3617, word: "diagnosis", arabic: "تشخيص", pronunciation: "دايغ نوسيس", example: "The diagnosis is clear.", exampleArabic: "التشخيص واضح", category: "صحة" },
    { id: 3618, word: "treatment", arabic: "علاج", pronunciation: "تريتمنت", example: "The treatment works.", exampleArabic: "العلاج فعال", category: "صحة" },
    { id: 3619, word: "cure", arabic: "شفاء", pronunciation: "كيور", example: "There is no cure.", exampleArabic: "لا يوجد شفاء", category: "صحة" },
    { id: 3620, word: "recover", arabic: "يتعافى", pronunciation: "ريكوفر", example: "I'm recovering from illness.", exampleArabic: "أنا أتعافى من المرض", category: "صحة" },
    { id: 3621, word: "surgery", arabic: "جراحة", pronunciation: "سيرجري", example: "He needs surgery.", exampleArabic: "يحتاج جراحة", category: "صحة" },
    { id: 3622, word: "emergency", arabic: "طوارئ", pronunciation: "إميرجن سي", example: "Call emergency.", exampleArabic: "اتصل بالطوارئ", category: "صحة" },
    { id: 3623, word: "ambulance", arabic: "سيارة إسعاف", pronunciation: "أمبيولانس", example: "Call an ambulance!", exampleArabic: "اتصل بسيارة إسعاف!", category: "صحة" },
    { id: 3624, word: "prescription", arabic: "وصفة طبية", pronunciation: "بريسكريبشن", example: "Doctor's prescription.", exampleArabic: "وصفة طبية من الطبيب", category: "صحة" },
    { id: 3625, word: "pharmacy", arabic: "صيدلية", pronunciation: "فارماسي", example: "Go to the pharmacy.", exampleArabic: "اذهب إلى الصيدلية", category: "صحة" },

    // ========== العمل والوظائف متقدم ========== (25 كلمة)
    { id: 3701, word: "career", arabic: "مهنة", pronunciation: "كيرير", example: "She has a successful career.", exampleArabic: "لديها مهنة ناجحة", category: "عمل" },
    { id: 3702, word: "profession", arabic: "مهنة", pronunciation: "بروفيشون", example: "Teaching is a noble profession.", exampleArabic: "التدريس مهنة نبيلة", category: "عمل" },
    { id: 3703, word: "occupation", arabic: "مهنة", pronunciation: "أوكيوبيشن", example: "What is your occupation?", exampleArabic: "ما هي مهنتك؟", category: "عمل" },
    { id: 3704, word: "employer", arabic: "صاحب عمل", pronunciation: "إمبلوير", example: "My employer is fair.", exampleArabic: "صاحب عملي منصف", category: "عمل" },
    { id: 3705, word: "employee", arabic: "موظف", pronunciation: "إمبلويي", example: "The employees are happy.", exampleArabic: "الموظفون سعداء", category: "عمل" },
    { id: 3706, word: "staff", arabic: "طاقم", pronunciation: "ستاف", example: "The staff is helpful.", exampleArabic: "الطاقم مساعد", category: "عمل" },
    { id: 3707, word: "team", arabic: "فريق", pronunciation: "تيم", example: "We work as a team.", exampleArabic: "نعمل كفريق", category: "عمل" },
    { id: 3708, word: "colleague", arabic: "زميل", pronunciation: "كوليج", example: "My colleague helps me.", exampleArabic: "زميلي يساعدني", category: "عمل" },
    { id: 3709, word: "coworker", arabic: "زميل عمل", pronunciation: "كووركر", example: "My coworker is friendly.", exampleArabic: "زميل عملي ودود", category: "عمل" },
    { id: 3710, word: "manager", arabic: "مدير", pronunciation: "مانيدجر", example: "The manager is experienced.", exampleArabic: "المدير ذو خبرة", category: "عمل" },
    { id: 3711, word: "supervisor", arabic: "مشرف", pronunciation: "سوبرفايزر", example: "My supervisor guides me.", exampleArabic: "مشرفي يوجهني", category: "عمل" },
    { id: 3712, word: "director", arabic: "مدير", pronunciation: "دايريكتور", example: "He is the director.", exampleArabic: "هو المدير", category: "عمل" },
    { id: 3713, word: "CEO", arabic: "رئيس تنفيذي", pronunciation: "سي إي أو", example: "The CEO makes decisions.", exampleArabic: "الرئيس التنفيذي يتخذ القرارات", category: "عمل" },
    { id: 3714, word: "position", arabic: "منصب", pronunciation: "بوزيشن", example: "I applied for a position.", exampleArabic: "تقدمت لمنصب", category: "عمل" },
    { id: 3715, word: "role", arabic: "دور", pronunciation: "رول", example: "My role is important.", exampleArabic: "دوري مهم", category: "عمل" },
    { id: 3716, word: "responsibility", arabic: "مسؤولية", pronunciation: "ريسبونسيبليتي", example: "I have many responsibilities.", exampleArabic: "لدي مسؤوليات كثيرة", category: "عمل" },
    { id: 3717, word: "task", arabic: "مهمة", pronunciation: "تاسك", example: "Finish your tasks.", exampleArabic: "أنهِ مهامك", category: "عمل" },
    { id: 3718, word: "project", arabic: "مشروع", pronunciation: "بروجكت", example: "We work on a project.", exampleArabic: "نعمل على مشروع", category: "عمل" },
    { id: 3719, word: "deadline", arabic: "موعد نهائي", pronunciation: "ديدلاين", example: "The deadline is Friday.", exampleArabic: "الموعد النهائي الجمعة", category: "عمل" },
    { id: 3720, word: "overtime", arabic: "عمل إضافي", pronunciation: "أوفرتايم", example: "I work overtime.", exampleArabic: "أعمل عملاً إضافياً", category: "عمل" },
    { id: 3721, word: "promotion", arabic: "ترقية", pronunciation: "بروموشن", example: "I got a promotion!", exampleArabic: "حصلت على ترقية!", category: "عمل" },
    { id: 3722, word: "retire", arabic: "يتقاعد", pronunciation: "ريتاير", example: "My father retired.", exampleArabic: "والدي تقاعد", category: "عمل" },
    { id: 3723, word: "resign", arabic: "يستقيل", pronunciation: "ريزاين", example: "He resigned from his job.", exampleArabic: "استقال من وظيفته", category: "عمل" },
    { id: 3724, word: "hire", arabic: "يوظف", pronunciation: "هاير", example: "They hired new staff.", exampleArabic: "وظفوا موظفين جدد", category: "عمل" },
    { id: 3725, word: "fire", arabic: "يطرد", pronunciation: "فاير", example: "He was fired.", exampleArabic: "تم طرده", category: "عمل" },

    // ========== التعليم والدراسة متقدم ========== (25 كلمة)
    { id: 3801, word: "education", arabic: "تعليم", pronunciation: "إديوكيشن", example: "Education is important.", exampleArabic: "التعليم مهم", category: "تعليم" },
    { id: 3802, word: "knowledge", arabic: "معرفة", pronunciation: "نوليدج", example: "Knowledge is power.", exampleArabic: "المعرفة قوة", category: "تعليم" },
    { id: 3803, word: "degree", arabic: "شهادة", pronunciation: "ديغري", example: "I have a university degree.", exampleArabic: "لدي شهادة جامعية", category: "تعليم" },
    { id: 3804, word: "diploma", arabic: "دبلوم", pronunciation: "ديبلوما", example: "He got a diploma.", exampleArabic: "حصل على دبلوم", category: "تعليم" },
    { id: 3805, word: "certificate", arabic: "شهادة", pronunciation: "سيرتيفيكيت", example: "I received a certificate.", exampleArabic: "استلمت شهادة", category: "تعليم" },
    { id: 3806, word: "course", arabic: "دورة", pronunciation: "كورس", example: "I take an English course.", exampleArabic: "أخذ دورة إنجليزية", category: "تعليم" },
    { id: 3807, word: "workshop", arabic: "ورشة عمل", pronunciation: "وركشوب", example: "I attend a workshop.", exampleArabic: "أحضر ورشة عمل", category: "تعليم" },
    { id: 3808, word: "lecture", arabic: "محاضرة", pronunciation: "ليكشر", example: "The lecture is interesting.", exampleArabic: "المحاضرة ممتعة", category: "تعليم" },
    { id: 3809, word: "seminar", arabic: "ندوة", pronunciation: "سيمينار", example: "I go to a seminar.", exampleArabic: "أذهب إلى ندوة", category: "تعليم" },
    { id: 3810, word: "assignment", arabic: "واجب", pronunciation: "أسانمنت", example: "I have an assignment.", exampleArabic: "لدي واجب", category: "تعليم" },
    { id: 3811, word: "homework", arabic: "واجب منزلي", pronunciation: "هوم وورك", example: "Do your homework.", exampleArabic: "قم بواجبك", category: "تعليم" },
    { id: 3812, word: "research", arabic: "بحث", pronunciation: "ريسرتش", example: "I do research.", exampleArabic: "أقوم ببحث", category: "تعليم" },
    { id: 3813, word: "essay", arabic: "مقال", pronunciation: "إيساي", example: "Write an essay.", exampleArabic: "اكتب مقالاً", category: "تعليم" },
    { id: 3814, word: "thesis", arabic: "أطروحة", pronunciation: "ثيسيس", example: "I'm writing my thesis.", exampleArabic: "أنا أكتب أطروحتي", category: "تعليم" },
    { id: 3815, word: "exam", arabic: "امتحان", pronunciation: "إكزام", example: "The exam is hard.", exampleArabic: "الامتحان صعب", category: "تعليم" },
    { id: 3816, word: "quiz", arabic: "اختبار قصير", pronunciation: "كويز", example: "We have a quiz today.", exampleArabic: "لدينا اختبار قصير اليوم", category: "تعليم" },
    { id: 3817, word: "grade", arabic: "درجة", pronunciation: "جرايد", example: "I got a good grade.", exampleArabic: "حصلت على درجة جيدة", category: "تعليم" },
    { id: 3818, word: "score", arabic: "نتيجة", pronunciation: "سكور", example: "What's your score?", exampleArabic: "ما هي نتيجتك؟", category: "تعليم" },
    { id: 3819, word: "pass", arabic: "ينجح", pronunciation: "باس", example: "I passed the exam!", exampleArabic: "نجحت في الامتحان!", category: "تعليم" },
    { id: 3820, word: "fail", arabic: "يرسب", pronunciation: "فيل", example: "I hope I don't fail.", exampleArabic: "أتمنى ألا أرسب", category: "تعليم" },
    { id: 3821, word: "graduate", arabic: "يتخرج", pronunciation: "غرادجيويت", example: "I graduate next year.", exampleArabic: "أتخرج السنة القادمة", category: "تعليم" },
    { id: 3822, word: "scholarship", arabic: "منحة دراسية", pronunciation: "سكولارشيب", example: "I got a scholarship.", exampleArabic: "حصلت على منحة دراسية", category: "تعليم" },
    { id: 3823, word: "tuition", arabic: "رسوم دراسية", pronunciation: "تو إيشن", example: "Tuition is expensive.", exampleArabic: "الرسوم الدراسية غالية", category: "تعليم" },
    { id: 3824, word: "campus", arabic: "حرم جامعي", pronunciation: "كامبس", example: "Beautiful campus.", exampleArabic: "حرم جامعي جميل", category: "تعليم" },
    { id: 3825, word: "dormitory", arabic: "سكن طلابي", pronunciation: "دورميتوري", example: "I live in a dormitory.", exampleArabic: "أعيش في سكن طلابي", category: "تعليم" },

    // ========== الوقت والتاريخ متقدم ========== (25 كلمة)
    { id: 3901, word: "schedule", arabic: "جدول", pronunciation: "شيدجول", example: "Check your schedule.", exampleArabic: "تحقق من جدولك", category: "وقت" },
    { id: 3902, word: "appointment", arabic: "موعد", pronunciation: "أبوينتمنت", example: "I have a doctor's appointment.", exampleArabic: "لدي موعد مع الطبيب", category: "وقت" },
    { id: 3903, word: "deadline", arabic: "موعد نهائي", pronunciation: "ديدلاين", example: "The deadline is approaching.", exampleArabic: "الموعد النهائي يقترب", category: "وقت" },
    { id: 3904, word: "delay", arabic: "تأخير", pronunciation: "ديلاي", example: "There is a delay.", exampleArabic: "هناك تأخير", category: "وقت" },
    { id: 3905, word: "early", arabic: "مبكر", pronunciation: "ايرلي", example: "I arrived early.", exampleArabic: "وصلت مبكراً", category: "وقت" },
    { id: 3906, word: "late", arabic: "متأخر", pronunciation: "ليت", example: "Don't be late.", exampleArabic: "لا تتأخر", category: "وقت" },
    { id: 3907, word: "on time", arabic: "في الموعد", pronunciation: "أون تايم", example: "The train is on time.", exampleArabic: "القطار في الموعد", category: "وقت" },
    { id: 3908, word: "punctual", arabic: "دقيق", pronunciation: "بانكتشوال", example: "She is always punctual.", exampleArabic: "هي دائماً دقيقة", category: "وقت" },
    { id: 3909, word: "century", arabic: "قرن", pronunciation: "سينتشري", example: "The 20th century.", exampleArabic: "القرن العشرين", category: "وقت" },
    { id: 3910, word: "decade", arabic: "عقد", pronunciation: "ديكيد", example: "A decade is 10 years.", exampleArabic: "العقد 10 سنوات", category: "وقت" },
    { id: 3911, word: "era", arabic: "عصر", pronunciation: "إيرا", example: "A new era begins.", exampleArabic: "عصر جديد يبدأ", category: "وقت" },
    { id: 3912, word: "period", arabic: "فترة", pronunciation: "بيريود", example: "A short period of time.", exampleArabic: "فترة قصيرة من الزمن", category: "وقت" },
    { id: 3913, word: "duration", arabic: "مدة", pronunciation: "دوريشون", example: "The duration is 2 hours.", exampleArabic: "المدة ساعتان", category: "وقت" },
    { id: 3914, word: "while", arabic: "بينما", pronunciation: "وايل", example: "Wait for a while.", exampleArabic: "انتظر قليلاً", category: "وقت" },
    { id: 3915, word: "moment", arabic: "لحظة", pronunciation: "مومنت", example: "Just a moment.", exampleArabic: "لحظة فقط", category: "وقت" },
    { id: 3916, word: "instant", arabic: "لحظة", pronunciation: "إنستانت", example: "In an instant.", exampleArabic: "في لحظة", category: "وقت" },
    { id: 3917, word: "annual", arabic: "سنوي", pronunciation: "أنوال", example: "Annual meeting.", exampleArabic: "اجتماع سنوي", category: "وقت" },
    { id: 3918, word: "monthly", arabic: "شهري", pronunciation: "مانثلي", example: "Monthly payment.", exampleArabic: "دفع شهري", category: "وقت" },
    { id: 3919, word: "weekly", arabic: "أسبوعي", pronunciation: "ويكلي", example: "Weekly report.", exampleArabic: "تقرير أسبوعي", category: "وقت" },
    { id: 3920, word: "daily", arabic: "يومي", pronunciation: "دايلي", example: "Daily routine.", exampleArabic: "روتين يومي", category: "وقت" },
    { id: 3921, word: "occasional", arabic: "أحياناً", pronunciation: "أوكيشنال", example: "Occasional visits.", exampleArabic: "زيارات أحياناً", category: "وقت" },
    { id: 3922, word: "frequent", arabic: "متكرر", pronunciation: "فريكوينت", example: "Frequent flights.", exampleArabic: "رحلات متكررة", category: "وقت" },
    { id: 3923, word: "rare", arabic: "نادر", pronunciation: "رير", example: "Rare occasion.", exampleArabic: "مناسبة نادرة", category: "وقت" },
    { id: 3924, word: "permanent", arabic: "دائم", pronunciation: "بيرماننت", example: "Permanent job.", exampleArabic: "وظيفة دائمة", category: "وقت" },
    { id: 3925, word: "temporary", arabic: "مؤقت", pronunciation: "تيمبوراري", example: "Temporary work.", exampleArabic: "عمل مؤقت", category: "وقت" },

    // ========== الملابس والموضة متقدم ========== (25 كلمة)
    { id: 4001, word: "fashion", arabic: "موضة", pronunciation: "فاشون", example: "She follows fashion.", exampleArabic: "هي تتابع الموضة", category: "ملابس" },
    { id: 4002, word: "style", arabic: "أناقة", pronunciation: "ستايل", example: "I like your style.", exampleArabic: "أعجبني أسلوبك", category: "ملابس" },
    { id: 4003, word: "trend", arabic: "اتجاه", pronunciation: "تريند", example: "New fashion trend.", exampleArabic: "اتجاه موضة جديد", category: "ملابس" },
    { id: 4004, word: "designer", arabic: "مصمم", pronunciation: "ديزاينر", example: "Famous designer.", exampleArabic: "مصمم مشهور", category: "ملابس" },
    { id: 4005, word: "outfit", arabic: "زي", pronunciation: "أوتفيت", example: "Nice outfit!", exampleArabic: "زي جميل!", category: "ملابس" },
    { id: 4006, word: "uniform", arabic: "زي موحد", pronunciation: "يونيفورم", example: "School uniform.", exampleArabic: "زي مدرسي", category: "ملابس" },
    { id: 4007, word: "costume", arabic: "زي تنكري", pronunciation: "كوستيوم", example: "Halloween costume.", exampleArabic: "زي تنكري للهالوين", category: "ملابس" },
    { id: 4008, word: "accessory", arabic: "إكسسوار", pronunciation: "أكسيسوري", example: "Fashion accessories.", exampleArabic: "إكسسوارات الموضة", category: "ملابس" },
    { id: 4009, word: "jewelry", arabic: "مجوهرات", pronunciation: "جولري", example: "She loves jewelry.", exampleArabic: "هي تحب المجوهرات", category: "ملابس" },
    { id: 4010, word: "necklace", arabic: "قلادة", pronunciation: "نيكليس", example: "Gold necklace.", exampleArabic: "قلادة ذهب", category: "ملابس" },
    { id: 4011, word: "earrings", arabic: "أقراط", pronunciation: "إيرينغز", example: "Diamond earrings.", exampleArabic: "أقراط ألماس", category: "ملابس" },
    { id: 4012, word: "bracelet", arabic: "سوار", pronunciation: "بريسلت", example: "Silver bracelet.", exampleArabic: "سوار فضي", category: "ملابس" },
    { id: 4013, word: "ring", arabic: "خاتم", pronunciation: "رينغ", example: "Wedding ring.", exampleArabic: "خاتم زواج", category: "ملابس" },
    { id: 4014, word: "watch", arabic: "ساعة", pronunciation: "واتش", example: "Luxury watch.", exampleArabic: "ساعة فاخرة", category: "ملابس" },
    { id: 4015, word: "belt", arabic: "حزام", pronunciation: "بيلت", example: "Leather belt.", exampleArabic: "حزام جلد", category: "ملابس" },
    { id: 4016, word: "scarf", arabic: "وشاح", pronunciation: "سكارف", example: "Silk scarf.", exampleArabic: "وشاح حرير", category: "ملابس" },
    { id: 4017, word: "tie", arabic: "ربطة عنق", pronunciation: "تاي", example: "He wears a tie.", exampleArabic: "يرتدي ربطة عنق", category: "ملابس" },
    { id: 4018, word: "socks", arabic: "جوارب", pronunciation: "سوكس", example: "Warm socks.", exampleArabic: "جوارب دافئة", category: "ملابس" },
    { id: 4019, word: "shoes", arabic: "أحذية", pronunciation: "شوز", example: "Comfortable shoes.", exampleArabic: "أحذية مريحة", category: "ملابس" },
    { id: 4020, word: "boots", arabic: "أحذية طويلة", pronunciation: "بوتس", example: "Winter boots.", exampleArabic: "أحذية شتوية", category: "ملابس" },
    { id: 4021, word: "sandals", arabic: "صنادل", pronunciation: "ساندلز", example: "Summer sandals.", exampleArabic: "صنادل صيفية", category: "ملابس" },
    { id: 4022, word: "sneakers", arabic: "أحذية رياضية", pronunciation: "سنيكرز", example: "I wear sneakers.", exampleArabic: "أرتدي أحذية رياضية", category: "ملابس" },
    { id: 4023, word: "suit", arabic: "بدلة", pronunciation: "سوت", example: "Business suit.", exampleArabic: "بدلة عمل", category: "ملابس" },
    { id: 4024, word: "blouse", arabic: "بلوزة", pronunciation: "بلاوز", example: "Silk blouse.", exampleArabic: "بلوزة حرير", category: "ملابس" },
    { id: 4025, word: "hoodie", arabic: "هودي", pronunciation: "هودي", example: "Comfortable hoodie.", exampleArabic: "هودي مريح", category: "ملابس" },

    // ========== الاتجاهات والأماكن متقدم ========== (25 كلمة)
    { id: 4101, word: "location", arabic: "موقع", pronunciation: "لوكيشن", example: "Perfect location.", exampleArabic: "موقع ممتاز", category: "اتجاهات" },
    { id: 4102, word: "address", arabic: "عنوان", pronunciation: "أدريس", example: "What's your address?", exampleArabic: "ما هو عنوانك؟", category: "اتجاهات" },
    { id: 4103, word: "neighborhood", arabic: "حي", pronunciation: "نيبرهود", example: "Nice neighborhood.", exampleArabic: "حي جميل", category: "اتجاهات" },
    { id: 4104, word: "downtown", arabic: "وسط المدينة", pronunciation: "داون تاون", example: "Let's go downtown.", exampleArabic: "لنذهب إلى وسط المدينة", category: "اتجاهات" },
    { id: 4105, word: "suburb", arabic: "ضاحية", pronunciation: "سابيرب", example: "We live in the suburbs.", exampleArabic: "نعيش في الضواحي", category: "اتجاهات" },
    { id: 4106, word: "countryside", arabic: "ريف", pronunciation: "كانتريسايد", example: "Beautiful countryside.", exampleArabic: "ريف جميل", category: "اتجاهات" },
    { id: 4107, word: "intersection", arabic: "تقاطع", pronunciation: "إنتيرسكشن", example: "Turn at the intersection.", exampleArabic: "انعطف عند التقاطع", category: "اتجاهات" },
    { id: 4108, word: "crossroad", arabic: "مفترق طرق", pronunciation: "كروس رود", example: "Stop at the crossroad.", exampleArabic: "توقف عند مفترق الطرق", category: "اتجاهات" },
    { id: 4109, word: "roundabout", arabic: "دوار", pronunciation: "راونداباوت", example: "Go around the roundabout.", exampleArabic: "لف حول الدوار", category: "اتجاهات" },
    { id: 4110, word: "sidewalk", arabic: "رصيف", pronunciation: "سايدووك", example: "Walk on the sidewalk.", exampleArabic: "امش على الرصيف", category: "اتجاهات" },
    { id: 4111, word: "crosswalk", arabic: "ممر مشاة", pronunciation: "كروس ووك", example: "Use the crosswalk.", exampleArabic: "استخدم ممر المشاة", category: "اتجاهات" },
    { id: 4112, word: "landmark", arabic: "معلم", pronunciation: "لاند مارك", example: "Famous landmark.", exampleArabic: "معلم مشهور", category: "اتجاهات" },
    { id: 4113, word: "monument", arabic: "نصب تذكاري", pronunciation: "مونيومنت", example: "Historical monument.", exampleArabic: "نصب تذكاري تاريخي", category: "اتجاهات" },
    { id: 4114, word: "museum", arabic: "متحف", pronunciation: "ميوزيوم", example: "Art museum.", exampleArabic: "متحف فني", category: "اتجاهات" },
    { id: 4115, word: "gallery", arabic: "معرض", pronunciation: "غاليري", example: "Art gallery.", exampleArabic: "معرض فني", category: "اتجاهات" },
    { id: 4116, word: "theater", arabic: "مسرح", pronunciation: "ثياتر", example: "Movie theater.", exampleArabic: "سينما", category: "اتجاهات" },
    { id: 4117, word: "stadium", arabic: "ملعب", pronunciation: "ستاديوم", example: "Football stadium.", exampleArabic: "ملعب كرة قدم", category: "اتجاهات" },
    { id: 4118, word: "park", arabic: "حديقة", pronunciation: "بارك", example: "Central Park.", exampleArabic: "الحديقة المركزية", category: "اتجاهات" },
    { id: 4119, word: "beach", arabic: "شاطئ", pronunciation: "بيتش", example: "Let's go to the beach.", exampleArabic: "لنذهب إلى الشاطئ", category: "اتجاهات" },
    { id: 4120, word: "river", arabic: "نهر", pronunciation: "ريفر", example: "The Nile river.", exampleArabic: "نهر النيل", category: "اتجاهات" },
    { id: 4121, word: "mountain", arabic: "جبل", pronunciation: "ماونتن", example: "Climb the mountain.", exampleArabic: "تسلق الجبل", category: "اتجاهات" },
    { id: 4122, word: "forest", arabic: "غابة", pronunciation: "فورست", example: "Walk in the forest.", exampleArabic: "تمش في الغابة", category: "اتجاهات" },
    { id: 4123, word: "desert", arabic: "صحراء", pronunciation: "ديزرت", example: "The Sahara desert.", exampleArabic: "الصحراء الكبرى", category: "اتجاهات" },
    { id: 4124, word: "ocean", arabic: "محيط", pronunciation: "أوشن", example: "Atlantic ocean.", exampleArabic: "المحيط الأطلسي", category: "اتجاهات" },
    { id: 4125, word: "island", arabic: "جزيرة", pronunciation: "آيلاند", example: "Beautiful island.", exampleArabic: "جزيرة جميلة", category: "اتجاهات" },

    // ========== المشاعر والأحاسيس متقدمة ========== (25 كلمة)
    { id: 4201, word: "emotion", arabic: "عاطفة", pronunciation: "إيموشن", example: "Show your emotions.", exampleArabic: "أظهر عواطفك", category: "مشاعر" },
    { id: 4202, word: "feeling", arabic: "شعور", pronunciation: "فيلينغ", example: "I have a good feeling.", exampleArabic: "لدي شعور جيد", category: "مشاعر" },
    { id: 4203, word: "mood", arabic: "مزاج", pronunciation: "مود", example: "I'm in a good mood.", exampleArabic: "أنا في مزاج جيد", category: "مشاعر" },
    { id: 4204, word: "attitude", arabic: "موقف", pronunciation: "أتي تيود", example: "Positive attitude.", exampleArabic: "موقف إيجابي", category: "مشاعر" },
    { id: 4205, word: "delighted", arabic: "مسرور", pronunciation: "ديلايتد", example: "I'm delighted to meet you.", exampleArabic: "أنا مسرور بلقائك", category: "مشاعر" },
    { id: 4206, word: "pleased", arabic: "مسرور", pronunciation: "بليزد", example: "I'm pleased with the result.", exampleArabic: "أنا مسرور بالنتيجة", category: "مشاعر" },
    { id: 4207, word: "satisfied", arabic: "راضٍ", pronunciation: "ساتيسفايد", example: "I'm satisfied with my work.", exampleArabic: "أنا راضٍ عن عملي", category: "مشاعر" },
    { id: 4208, word: "content", arabic: "قانع", pronunciation: "كونتنت", example: "I feel content.", exampleArabic: "أشعر بالقناعة", category: "مشاعر" },
    { id: 4209, word: "frustrated", arabic: "محبط", pronunciation: "فراستريتد", example: "I'm frustrated with this.", exampleArabic: "أنا محبط من هذا", category: "مشاعر" },
    { id: 4210, word: "disappointed", arabic: "خائب الأمل", pronunciation: "ديسابوينتد", example: "I'm disappointed.", exampleArabic: "أنا خائب الأمل", category: "مشاعر" },
    { id: 4211, word: "annoyed", arabic: "منزعج", pronunciation: "أنويد", example: "I'm annoyed by the noise.", exampleArabic: "أنا منزعج من الضوضاء", category: "مشاعر" },
    { id: 4212, word: "irritated", arabic: "متهيج", pronunciation: "إيريتيد", example: "He gets irritated easily.", exampleArabic: "يهتاج بسهولة", category: "مشاعر" },
    { id: 4213, word: "upset", arabic: "منزعج", pronunciation: "أب سيت", example: "She is upset.", exampleArabic: "هي منزعجة", category: "مشاعر" },
    { id: 4214, word: "disturbed", arabic: "مضطرب", pronunciation: "ديستيربد", example: "I feel disturbed.", exampleArabic: "أشعر بالاضطراب", category: "مشاعر" },
    { id: 4215, word: "anxious", arabic: "قلق", pronunciation: "أنكشس", example: "I feel anxious.", exampleArabic: "أشعر بالقلق", category: "مشاعر" },
    { id: 4216, word: "nervous", arabic: "عصبي", pronunciation: "نيرفوس", example: "I'm nervous.", exampleArabic: "أنا عصبي", category: "مشاعر" },
    { id: 4217, word: "stressed", arabic: "متوتر", pronunciation: "ستريست", example: "I'm stressed about work.", exampleArabic: "أنا متوتر بسبب العمل", category: "مشاعر" },
    { id: 4218, word: "overwhelmed", arabic: "مغمور", pronunciation: "أوفر ويلمد", example: "I'm overwhelmed.", exampleArabic: "أنا مغمور", category: "مشاعر" },
    { id: 4219, word: "relieved", arabic: "مرتاح", pronunciation: "ريليفد", example: "I'm relieved it's over.", exampleArabic: "أنا مرتاح لأنه انتهى", category: "مشاعر" },
    { id: 4220, word: "grateful", arabic: "ممتن", pronunciation: "غريتفول", example: "I'm grateful for your help.", exampleArabic: "أنا ممتن لمساعدتك", category: "مشاعر" },
    { id: 4221, word: "thankful", arabic: "شاكر", pronunciation: "ثانكفول", example: "I'm thankful.", exampleArabic: "أنا شاكر", category: "مشاعر" },
    { id: 4222, word: "appreciative", arabic: "مقدر", pronunciation: "أبريشيتيف", example: "I'm appreciative.", exampleArabic: "أنا مقدر", category: "مشاعر" },
    { id: 4223, word: "jealous", arabic: "غيور", pronunciation: "جيلوس", example: "He is jealous.", exampleArabic: "هو غيور", category: "مشاعر" },
    { id: 4224, word: "envious", arabic: "حسود", pronunciation: "إنفيوس", example: "She is envious.", exampleArabic: "هي حسودة", category: "مشاعر" },
    { id: 4225, word: "proud", arabic: "فخور", pronunciation: "براود", example: "I'm proud of you.", exampleArabic: "أنا فخور بك", category: "مشاعر" },

    // ========== الأفعال اليومية متقدمة ========== (25 كلمة)
    { id: 4301, word: "prepare", arabic: "يجهز", pronunciation: "بريبير", example: "I prepare breakfast.", exampleArabic: "أجهز الفطور", category: "أفعال" },
    { id: 4302, word: "arrange", arabic: "يرتب", pronunciation: "أرينج", example: "Arrange the meeting.", exampleArabic: "رتب الاجتماع", category: "أفعال" },
    { id: 4303, word: "plan", arabic: "يخطط", pronunciation: "بلان", example: "We plan a trip.", exampleArabic: "نخطط لرحلة", category: "أفعال" },
    { id: 4304, word: "decide", arabic: "يقرر", pronunciation: "ديسايد", example: "I decide to go.", exampleArabic: "قررت الذهاب", category: "أفعال" },
    { id: 4305, word: "choose", arabic: "يختار", pronunciation: "تشوز", example: "Choose carefully.", exampleArabic: "اختر بحذر", category: "أفعال" },
    { id: 4306, word: "select", arabic: "يختار", pronunciation: "سيليكت", example: "Select your option.", exampleArabic: "اختر خيارك", category: "أفعال" },
    { id: 4307, word: "prefer", arabic: "يفضل", pronunciation: "بريفير", example: "I prefer tea.", exampleArabic: "أفضل الشاي", category: "أفعال" },
    { id: 4308, word: "agree", arabic: "يوافق", pronunciation: "أغري", example: "I agree with you.", exampleArabic: "أنا أوافقك", category: "أفعال" },
    { id: 4309, word: "disagree", arabic: "يختلف", pronunciation: "ديسأغري", example: "I disagree.", exampleArabic: "أنا أختلف", category: "أفعال" },
    { id: 4310, word: "accept", arabic: "يقبل", pronunciation: "أكسبت", example: "I accept your offer.", exampleArabic: "أقبل عرضك", category: "أفعال" },
    { id: 4311, word: "refuse", arabic: "يرفض", pronunciation: "ريفيوز", example: "I refuse to go.", exampleArabic: "أرفض الذهاب", category: "أفعال" },
    { id: 4312, word: "deny", arabic: "ينكر", pronunciation: "ديناي", example: "He denies everything.", exampleArabic: "ينكر كل شيء", category: "أفعال" },
    { id: 4313, word: "allow", arabic: "يسمح", pronunciation: "ألاو", example: "Allow me to help.", exampleArabic: "اسمح لي بالمساعدة", category: "أفعال" },
    { id: 4314, word: "forbid", arabic: "يمنع", pronunciation: "فوربيد", example: "Smoking is forbidden.", exampleArabic: "التدخين ممنوع", category: "أفعال" },
    { id: 4315, word: "remind", arabic: "يذكر", pronunciation: "ريمايند", example: "Remind me later.", exampleArabic: "ذكرني لاحقاً", category: "أفعال" },
    { id: 4316, word: "forget", arabic: "ينسى", pronunciation: "فورغيت", example: "Don't forget.", exampleArabic: "لا تنسى", category: "أفعال" },
    { id: 4317, word: "remember", arabic: "يتذكر", pronunciation: "ريميمبر", example: "I remember you.", exampleArabic: "أتذكرك", category: "أفعال" },
    { id: 4318, word: "miss", arabic: "يفتقد", pronunciation: "ميس", example: "I miss you.", exampleArabic: "أفتقدك", category: "أفعال" },
    { id: 4319, word: "wait", arabic: "ينتظر", pronunciation: "ويت", example: "Wait for me.", exampleArabic: "انتظرني", category: "أفعال" },
    { id: 4320, word: "expect", arabic: "يتوقع", pronunciation: "إكسبكت", example: "I expect good news.", exampleArabic: "أتوقع أخباراً جيدة", category: "أفعال" },
    { id: 4321, word: "hope", arabic: "يأمل", pronunciation: "هوب", example: "I hope so.", exampleArabic: "آمل ذلك", category: "أفعال" },
    { id: 4322, word: "wish", arabic: "يتمنى", pronunciation: "ويش", example: "I wish you luck.", exampleArabic: "أتمنى لك الحظ", category: "أفعال" },
    { id: 4323, word: "achieve", arabic: "يحقق", pronunciation: "أتشيف", example: "Achieve your goals.", exampleArabic: "حقق أهدافك", category: "أفعال" },
    { id: 4324, word: "succeed", arabic: "ينجح", pronunciation: "سوكسيد", example: "You will succeed.", exampleArabic: "ستنجح", category: "أفعال" },
    { id: 4325, word: "fail", arabic: "يفشل", pronunciation: "فيل", example: "Don't be afraid to fail.", exampleArabic: "لا تخف من الفشل", category: "أفعال" },

    // ========== التكنولوجيا والإنترنت متقدم ========== (25 كلمة)
    { id: 4401, word: "technology", arabic: "تكنولوجيا", pronunciation: "تكنولوجي", example: "Modern technology.", exampleArabic: "التكنولوجيا الحديثة", category: "تكنولوجيا" },
    { id: 4402, word: "digital", arabic: "رقمي", pronunciation: "ديجيتال", example: "Digital world.", exampleArabic: "العالم الرقمي", category: "تكنولوجيا" },
    { id: 4403, word: "device", arabic: "جهاز", pronunciation: "ديفايس", example: "Electronic device.", exampleArabic: "جهاز إلكتروني", category: "تكنولوجيا" },
    { id: 4404, word: "gadget", arabic: "أداة", pronunciation: "غادجيت", example: "New gadget.", exampleArabic: "أداة جديدة", category: "تكنولوجيا" },
    { id: 4405, word: "screen", arabic: "شاشة", pronunciation: "سكرين", example: "Touch screen.", exampleArabic: "شاشة لمس", category: "تكنولوجيا" },
    { id: 4406, word: "keyboard", arabic: "لوحة مفاتيح", pronunciation: "كي بورد", example: "Wireless keyboard.", exampleArabic: "لوحة مفاتيح لاسلكية", category: "تكنولوجيا" },
    { id: 4407, word: "mouse", arabic: "فأرة", pronunciation: "ماوس", example: "Computer mouse.", exampleArabic: "فأرة كمبيوتر", category: "تكنولوجيا" },
    { id: 4408, word: "battery", arabic: "بطارية", pronunciation: "باتيري", example: "Charge the battery.", exampleArabic: "اشحن البطارية", category: "تكنولوجيا" },
    { id: 4409, word: "charger", arabic: "شاحن", pronunciation: "تشارجر", example: "Phone charger.", exampleArabic: "شاحن هاتف", category: "تكنولوجيا" },
    { id: 4410, word: "cable", arabic: "كابل", pronunciation: "كيبل", example: "USB cable.", exampleArabic: "كابل USB", category: "تكنولوجيا" },
    { id: 4411, word: "wireless", arabic: "لاسلكي", pronunciation: "وايرليس", example: "Wireless connection.", exampleArabic: "اتصال لاسلكي", category: "تكنولوجيا" },
    { id: 4412, word: "bluetooth", arabic: "بلوتوث", pronunciation: "بلوتوث", example: "Bluetooth device.", exampleArabic: "جهاز بلوتوث", category: "تكنولوجيا" },
    { id: 4413, word: "network", arabic: "شبكة", pronunciation: "نيتورك", example: "Network connection.", exampleArabic: "اتصال شبكة", category: "تكنولوجيا" },
    { id: 4414, word: "signal", arabic: "إشارة", pronunciation: "سيجنال", example: "Weak signal.", exampleArabic: "إشارة ضعيفة", category: "تكنولوجيا" },
    { id: 4415, word: "data", arabic: "بيانات", pronunciation: "داتا", example: "Mobile data.", exampleArabic: "بيانات الجوال", category: "تكنولوجيا" },
    { id: 4416, word: "cloud", arabic: "سحابة", pronunciation: "كلاود", example: "Cloud storage.", exampleArabic: "تخزين سحابي", category: "تكنولوجيا" },
    { id: 4417, word: "download", arabic: "تحميل", pronunciation: "داونلود", example: "Download the app.", exampleArabic: "حمّل التطبيق", category: "تكنولوجيا" },
    { id: 4418, word: "upload", arabic: "رفع", pronunciation: "أبلود", example: "Upload the file.", exampleArabic: "ارفع الملف", category: "تكنولوجيا" },
    { id: 4419, word: "update", arabic: "تحديث", pronunciation: "أبديت", example: "Software update.", exampleArabic: "تحديث برمجيات", category: "تكنولوجيا" },
    { id: 4420, word: "install", arabic: "تثبيت", pronunciation: "إنستول", example: "Install the program.", exampleArabic: "ثبّت البرنامج", category: "تكنولوجيا" },
    { id: 4421, word: "uninstall", arabic: "إلغاء تثبيت", pronunciation: "أن إنستول", example: "Uninstall the app.", exampleArabic: "ألغِ تثبيت التطبيق", category: "تكنولوجيا" },
    { id: 4422, word: "settings", arabic: "إعدادات", pronunciation: "سيتينغز", example: "Change settings.", exampleArabic: "غيّر الإعدادات", category: "تكنولوجيا" },
    { id: 4423, word: "password", arabic: "كلمة مرور", pronunciation: "باسوورد", example: "Enter your password.", exampleArabic: "أدخل كلمة المرور", category: "تكنولوجيا" },
    { id: 4424, word: "username", arabic: "اسم مستخدم", pronunciation: "يوزر نيم", example: "Choose a username.", exampleArabic: "اختر اسم مستخدم", category: "تكنولوجيا" },
    { id: 4425, word: "login", arabic: "تسجيل دخول", pronunciation: "لوغ إن", example: "Login to your account.", exampleArabic: "سجل دخول إلى حسابك", category: "تكنولوجيا" },

    // ========== الأعمال والاقتصاد ========== (25 كلمة) - تصنيف جديد
    { id: 4501, word: "business", arabic: "أعمال", pronunciation: "بيزنس", example: "He runs a small business.", exampleArabic: "يدير أعمالاً صغيرة", category: "أعمال" },
    { id: 4502, word: "economy", arabic: "اقتصاد", pronunciation: "إيكونومي", example: "The economy is growing.", exampleArabic: "الاقتصاد ينمو", category: "أعمال" },
    { id: 4503, word: "market", arabic: "سوق", pronunciation: "ماركت", example: "Stock market.", exampleArabic: "سوق الأسهم", category: "أعمال" },
    { id: 4504, word: "investment", arabic: "استثمار", pronunciation: "إنفيستمنت", example: "Make an investment.", exampleArabic: "قم باستثمار", category: "أعمال" },
    { id: 4505, word: "profit", arabic: "ربح", pronunciation: "بروفيت", example: "The company made a profit.", exampleArabic: "حققت الشركة ربحاً", category: "أعمال" },
    { id: 4506, word: "loss", arabic: "خسارة", pronunciation: "لوس", example: "We had a loss this year.", exampleArabic: "تكبدنا خسارة هذا العام", category: "أعمال" },
    { id: 4507, word: "revenue", arabic: "إيرادات", pronunciation: "ريفينيو", example: "Revenue increased.", exampleArabic: "زادت الإيرادات", category: "أعمال" },
    { id: 4508, word: "expense", arabic: "نفقة", pronunciation: "إكسبنس", example: "Reduce expenses.", exampleArabic: "قلل النفقات", category: "أعمال" },
    { id: 4509, word: "budget", arabic: "ميزانية", pronunciation: "باجت", example: "Stay within budget.", exampleArabic: "التزم بالميزانية", category: "أعمال" },
    { id: 4510, word: "finance", arabic: "تمويل", pronunciation: "فاينانس", example: "Finance department.", exampleArabic: "قسم التمويل", category: "أعمال" },
    { id: 4511, word: "accounting", arabic: "محاسبة", pronunciation: "أكاونتينغ", example: "She works in accounting.", exampleArabic: "هي تعمل في المحاسبة", category: "أعمال" },
    { id: 4512, word: "tax", arabic: "ضريبة", pronunciation: "تاكس", example: "Pay your taxes.", exampleArabic: "ادفع ضرائبك", category: "أعمال" },
    { id: 4513, word: "invoice", arabic: "فاتورة", pronunciation: "إنفويز", example: "Send an invoice.", exampleArabic: "أرسل فاتورة", category: "أعمال" },
    { id: 4514, word: "contract", arabic: "عقد", pronunciation: "كونتراكت", example: "Sign the contract.", exampleArabic: "وقع العقد", category: "أعمال" },
    { id: 4515, word: "agreement", arabic: "اتفاقية", pronunciation: "أغريمنت", example: "We reached an agreement.", exampleArabic: "توصلنا لاتفاق", category: "أعمال" },
    { id: 4516, word: "negotiation", arabic: "تفاوض", pronunciation: "نيغوتييشن", example: "Business negotiation.", exampleArabic: "تفاوض تجاري", category: "أعمال" },
    { id: 4517, word: "client", arabic: "عميل", pronunciation: "كلاينت", example: "Important client.", exampleArabic: "عميل مهم", category: "أعمال" },
    { id: 4518, word: "customer", arabic: "زبون", pronunciation: "كاستمر", example: "Satisfied customer.", exampleArabic: "زبون راضٍ", category: "أعمال" },
    { id: 4519, word: "supplier", arabic: "مورد", pronunciation: "سيبلاير", example: "Find a reliable supplier.", exampleArabic: "ابحث عن مورد موثوق", category: "أعمال" },
    { id: 4520, word: "product", arabic: "منتج", pronunciation: "بروداكت", example: "New product launch.", exampleArabic: "إطلاق منتج جديد", category: "أعمال" },
    { id: 4521, word: "service", arabic: "خدمة", pronunciation: "سيرفيس", example: "Customer service.", exampleArabic: "خدمة العملاء", category: "أعمال" },
    { id: 4522, word: "brand", arabic: "علامة تجارية", pronunciation: "براند", example: "Famous brand.", exampleArabic: "علامة تجارية مشهورة", category: "أعمال" },
    { id: 4523, word: "advertising", arabic: "إعلان", pronunciation: "أدفيرتايزينغ", example: "Advertising campaign.", exampleArabic: "حملة إعلانية", category: "أعمال" },
    { id: 4524, word: "marketing", arabic: "تسويق", pronunciation: "ماركتينغ", example: "Marketing strategy.", exampleArabic: "استراتيجية تسويق", category: "أعمال" },
    { id: 4525, word: "entrepreneur", arabic: "رائد أعمال", pronunciation: "أنتربرينور", example: "Successful entrepreneur.", exampleArabic: "رائد أعمال ناجح", category: "أعمال" },

    // ========== البيئة والطبيعة ========== (25 كلمة) - تصنيف جديد
    { id: 4601, word: "environment", arabic: "بيئة", pronunciation: "إنفايرنمنت", example: "Protect the environment.", exampleArabic: "احمِ البيئة", category: "بيئة" },
    { id: 4602, word: "nature", arabic: "طبيعة", pronunciation: "نيشور", example: "Love nature.", exampleArabic: "أحب الطبيعة", category: "بيئة" },
    { id: 4603, word: "ecosystem", arabic: "نظام بيئي", pronunciation: "إيكو سيستم", example: "Delicate ecosystem.", exampleArabic: "نظام بيئي حساس", category: "بيئة" },
    { id: 4604, word: "climate", arabic: "مناخ", pronunciation: "كلايميت", example: "Climate change.", exampleArabic: "تغير المناخ", category: "بيئة" },
    { id: 4605, word: "weather", arabic: "طقس", pronunciation: "ويذر", example: "Nice weather today.", exampleArabic: "الطقس لطيف اليوم", category: "بيئة" },
    { id: 4606, word: "pollution", arabic: "تلوث", pronunciation: "بولوشن", example: "Air pollution.", exampleArabic: "تلوث الهواء", category: "بيئة" },
    { id: 4607, word: "recycle", arabic: "يعيد تدوير", pronunciation: "ريسايكل", example: "Recycle plastic.", exampleArabic: "أعد تدوير البلاستيك", category: "بيئة" },
    { id: 4608, word: "waste", arabic: "نفايات", pronunciation: "ويست", example: "Reduce waste.", exampleArabic: "قلل النفايات", category: "بيئة" },
    { id: 4609, word: "plastic", arabic: "بلاستيك", pronunciation: "بلاستيك", example: "Avoid single-use plastic.", exampleArabic: "تجنب البلاستيك أحادي الاستخدام", category: "بيئة" },
    { id: 4610, word: "renewable", arabic: "متجدد", pronunciation: "رينيوبل", example: "Renewable energy.", exampleArabic: "طاقة متجددة", category: "بيئة" },
    { id: 4611, word: "solar", arabic: "شمسي", pronunciation: "سولار", example: "Solar power.", exampleArabic: "طاقة شمسية", category: "بيئة" },
    { id: 4612, word: "wind", arabic: "رياح", pronunciation: "ويند", example: "Wind energy.", exampleArabic: "طاقة الرياح", category: "بيئة" },
    { id: 4613, word: "conservation", arabic: "حفاظ", pronunciation: "كونسيرفيشن", example: "Wildlife conservation.", exampleArabic: "الحفاظ على الحياة البرية", category: "بيئة" },
    { id: 4614, word: "sustainable", arabic: "مستدام", pronunciation: "سوستينبل", example: "Sustainable development.", exampleArabic: "تنمية مستدامة", category: "بيئة" },
    { id: 4615, word: "green", arabic: "أخضر", pronunciation: "غرين", example: "Green energy.", exampleArabic: "طاقة خضراء", category: "بيئة" },
    { id: 4616, word: "forest", arabic: "غابة", pronunciation: "فورست", example: "Rainforest.", exampleArabic: "غابة مطيرة", category: "بيئة" },
    { id: 4617, word: "ocean", arabic: "محيط", pronunciation: "أوشن", example: "Protect our oceans.", exampleArabic: "احموا محيطاتنا", category: "بيئة" },
    { id: 4618, word: "species", arabic: "نوع", pronunciation: "سبيشيز", example: "Endangered species.", exampleArabic: "أنواع مهددة بالانقراض", category: "بيئة" },
    { id: 4619, word: "extinction", arabic: "انقراض", pronunciation: "إكستينكشن", example: "Prevent extinction.", exampleArabic: "امنع الانقراض", category: "بيئة" },
    { id: 4620, word: "habitat", arabic: "موطن", pronunciation: "هابيتات", example: "Natural habitat.", exampleArabic: "موطن طبيعي", category: "بيئة" },
    { id: 4621, word: "organic", arabic: "عضوي", pronunciation: "أورغانيك", example: "Organic farming.", exampleArabic: "زراعة عضوية", category: "بيئة" },
    { id: 4622, word: "carbon", arabic: "كربون", pronunciation: "كاربون", example: "Carbon footprint.", exampleArabic: "بصمة كربونية", category: "بيئة" },
    { id: 4623, word: "emission", arabic: "انبعاث", pronunciation: "إيميشين", example: "Reduce emissions.", exampleArabic: "قلل الانبعاثات", category: "بيئة" },
    { id: 4624, word: "drought", arabic: "جفاف", pronunciation: "دراوت", example: "Severe drought.", exampleArabic: "جفاف شديد", category: "بيئة" },
    { id: 4625, word: "flood", arabic: "فيضان", pronunciation: "فلاد", example: "Flood warning.", exampleArabic: "تحذير من فيضان", category: "بيئة" },

    // ========== القانون والسياسة ========== (25 كلمة) - تصنيف جديد
    { id: 4701, word: "law", arabic: "قانون", pronunciation: "لو", example: "Obey the law.", exampleArabic: "أطع القانون", category: "قانون" },
    { id: 4702, word: "legal", arabic: "قانوني", pronunciation: "ليغال", example: "Legal advice.", exampleArabic: "استشارة قانونية", category: "قانون" },
    { id: 4703, word: "illegal", arabic: "غير قانوني", pronunciation: "إليغال", example: "It's illegal.", exampleArabic: "هذا غير قانوني", category: "قانون" },
    { id: 4704, word: "right", arabic: "حق", pronunciation: "رايت", example: "Human rights.", exampleArabic: "حقوق الإنسان", category: "قانون" },
    { id: 4705, word: "justice", arabic: "عدالة", pronunciation: "جاستيس", example: "Seek justice.", exampleArabic: "اطلب العدالة", category: "قانون" },
    { id: 4706, word: "court", arabic: "محكمة", pronunciation: "كورت", example: "Go to court.", exampleArabic: "اذهب إلى المحكمة", category: "قانون" },
    { id: 4707, word: "judge", arabic: "قاضي", pronunciation: "جادج", example: "The judge decides.", exampleArabic: "القاضي يقرر", category: "قانون" },
    { id: 4708, word: "lawyer", arabic: "محامي", pronunciation: "لوير", example: "Hire a lawyer.", exampleArabic: "استأجر محامياً", category: "قانون" },
    { id: 4709, word: "trial", arabic: "محاكمة", pronunciation: "ترايل", example: "Fair trial.", exampleArabic: "محاكمة عادلة", category: "قانون" },
    { id: 4710, word: "evidence", arabic: "دليل", pronunciation: "إفيدنس", example: "Provide evidence.", exampleArabic: "قدم دليلاً", category: "قانون" },
    { id: 4711, word: "crime", arabic: "جريمة", pronunciation: "كرايم", example: "Commit a crime.", exampleArabic: "ارتكب جريمة", category: "قانون" },
    { id: 4712, word: "punishment", arabic: "عقوبة", pronunciation: "بانشمنت", example: "Harsh punishment.", exampleArabic: "عقوبة قاسية", category: "قانون" },
    { id: 4713, word: "prison", arabic: "سجن", pronunciation: "بريزن", example: "Go to prison.", exampleArabic: "اذهب إلى السجن", category: "قانون" },
    { id: 4714, word: "politics", arabic: "سياسة", pronunciation: "بوليتيكس", example: "Talk about politics.", exampleArabic: "تحدث عن السياسة", category: "قانون" },
    { id: 4715, word: "government", arabic: "حكومة", pronunciation: "غوفرنمنت", example: "Local government.", exampleArabic: "حكومة محلية", category: "قانون" },
    { id: 4716, word: "president", arabic: "رئيس", pronunciation: "بريزيدنت", example: "President of the country.", exampleArabic: "رئيس البلاد", category: "قانون" },
    { id: 4717, word: "parliament", arabic: "برلمان", pronunciation: "بارلمنت", example: "Member of parliament.", exampleArabic: "عضو برلمان", category: "قانون" },
    { id: 4718, word: "election", arabic: "انتخاب", pronunciation: "إليكشن", example: "General election.", exampleArabic: "انتخابات عامة", category: "قانون" },
    { id: 4719, word: "vote", arabic: "يصوت", pronunciation: "فوت", example: "Vote for change.", exampleArabic: "صوت للتغيير", category: "قانون" },
    { id: 4720, word: "democracy", arabic: "ديمقراطية", pronunciation: "ديموكراسي", example: "Democracy is important.", exampleArabic: "الديمقراطية مهمة", category: "قانون" },
    { id: 4721, word: "freedom", arabic: "حرية", pronunciation: "فريدوم", example: "Freedom of speech.", exampleArabic: "حرية التعبير", category: "قانون" },
    { id: 4722, word: "citizen", arabic: "مواطن", pronunciation: "سيتيزن", example: "Good citizen.", exampleArabic: "مواطن صالح", category: "قانون" },
    { id: 4723, word: "immigration", arabic: "هجرة", pronunciation: "إميغريشن", example: "Immigration policy.", exampleArabic: "سياسة الهجرة", category: "قانون" },
    { id: 4724, word: "border", arabic: "حدود", pronunciation: "بوردر", example: "Cross the border.", exampleArabic: "اعبر الحدود", category: "قانون" },
    { id: 4725, word: "treaty", arabic: "معاهدة", pronunciation: "تريتي", example: "Peace treaty.", exampleArabic: "معاهدة سلام", category: "قانون" },

    // ========== الثقافة والفنون ========== (25 كلمة) - تصنيف جديد
    { id: 4801, word: "culture", arabic: "ثقافة", pronunciation: "كالشر", example: "Rich culture.", exampleArabic: "ثقافة غنية", category: "ثقافة" },
    { id: 4802, word: "art", arabic: "فن", pronunciation: "آرت", example: "Modern art.", exampleArabic: "فن حديث", category: "ثقافة" },
    { id: 4803, word: "music", arabic: "موسيقى", pronunciation: "ميوزيك", example: "Classical music.", exampleArabic: "موسيقى كلاسيكية", category: "ثقافة" },
    { id: 4804, word: "dance", arabic: "رقص", pronunciation: "دانس", example: "Traditional dance.", exampleArabic: "رقص تقليدي", category: "ثقافة" },
    { id: 4805, word: "theater", arabic: "مسرح", pronunciation: "ثياتر", example: "Go to the theater.", exampleArabic: "اذهب إلى المسرح", category: "ثقافة" },
    { id: 4806, word: "cinema", arabic: "سينما", pronunciation: "سينيما", example: "French cinema.", exampleArabic: "السينما الفرنسية", category: "ثقافة" },
    { id: 4807, word: "film", arabic: "فيلم", pronunciation: "فيلم", example: "Watch a film.", exampleArabic: "شاهد فيلماً", category: "ثقافة" },
    { id: 4808, word: "literature", arabic: "أدب", pronunciation: "ليتراتشر", example: "Arabic literature.", exampleArabic: "الأدب العربي", category: "ثقافة" },
    { id: 4809, word: "poetry", arabic: "شعر", pronunciation: "بويتري", example: "Write poetry.", exampleArabic: "اكتب شعراً", category: "ثقافة" },
    { id: 4810, word: "novel", arabic: "رواية", pronunciation: "نوفل", example: "Read a novel.", exampleArabic: "اقرأ رواية", category: "ثقافة" },
    { id: 4811, word: "painting", arabic: "رسم", pronunciation: "بينتينغ", example: "Oil painting.", exampleArabic: "رسم زيتي", category: "ثقافة" },
    { id: 4812, word: "sculpture", arabic: "نحت", pronunciation: "سكلبتشر", example: "Marble sculpture.", exampleArabic: "نحت رخامي", category: "ثقافة" },
    { id: 4813, word: "photography", arabic: "تصوير", pronunciation: "فوتوغرافي", example: "Landscape photography.", exampleArabic: "تصوير المناظر الطبيعية", category: "ثقافة" },
    { id: 4814, word: "museum", arabic: "متحف", pronunciation: "ميوزيوم", example: "Visit the museum.", exampleArabic: "زر المتحف", category: "ثقافة" },
    { id: 4815, word: "gallery", arabic: "معرض", pronunciation: "غاليري", example: "Art gallery.", exampleArabic: "معرض فني", category: "ثقافة" },
    { id: 4816, word: "exhibition", arabic: "معرض", pronunciation: "إكزيبيشن", example: "Photo exhibition.", exampleArabic: "معرض صور", category: "ثقافة" },
    { id: 4817, word: "festival", arabic: "مهرجان", pronunciation: "فيستيفال", example: "Music festival.", exampleArabic: "مهرجان موسيقي", category: "ثقافة" },
    { id: 4818, word: "heritage", arabic: "تراث", pronunciation: "هيريتيدج", example: "Cultural heritage.", exampleArabic: "تراث ثقافي", category: "ثقافة" },
    { id: 4819, word: "tradition", arabic: "تقليد", pronunciation: "تراديشون", example: "Family tradition.", exampleArabic: "تقليد عائلي", category: "ثقافة" },
    { id: 4820, word: "custom", arabic: "عادة", pronunciation: "كاستوم", example: "Local custom.", exampleArabic: "عادة محلية", category: "ثقافة" },
    { id: 4821, word: "folklore", arabic: "فلكلور", pronunciation: "فولكلور", example: "Rich folklore.", exampleArabic: "فلكلور غني", category: "ثقافة" },
    { id: 4822, word: "myth", arabic: "أسطورة", pronunciation: "ميث", example: "Ancient myth.", exampleArabic: "أسطورة قديمة", category: "ثقافة" },
    { id: 4823, word: "legend", arabic: "أسطورة", pronunciation: "ليجند", example: "Famous legend.", exampleArabic: "أسطورة مشهورة", category: "ثقافة" },
    { id: 4824, word: "architecture", arabic: "عمارة", pronunciation: "آركيتيكتشر", example: "Islamic architecture.", exampleArabic: "العمارة الإسلامية", category: "ثقافة" },
    { id: 4825, word: "calligraphy", arabic: "خط", pronunciation: "كالغرفي", example: "Arabic calligraphy.", exampleArabic: "الخط العربي", category: "ثقافة" },

    // ========== الرياضة والترفيه ========== (25 كلمة) - تصنيف جديد
    { id: 4901, word: "sport", arabic: "رياضة", pronunciation: "سبورت", example: "Play sports.", exampleArabic: "مارس الرياضة", category: "رياضة" },
    { id: 4902, word: "game", arabic: "لعبة", pronunciation: "جايم", example: "Video game.", exampleArabic: "لعبة فيديو", category: "رياضة" },
    { id: 4903, word: "team", arabic: "فريق", pronunciation: "تيم", example: "Our team won.", exampleArabic: "فريقنا فاز", category: "رياضة" },
    { id: 4904, word: "player", arabic: "لاعب", pronunciation: "بلاير", example: "Best player.", exampleArabic: "أفضل لاعب", category: "رياضة" },
    { id: 4905, word: "coach", arabic: "مدرب", pronunciation: "كوتش", example: "Football coach.", exampleArabic: "مدرب كرة قدم", category: "رياضة" },
    { id: 4906, word: "fan", arabic: "مشجع", pronunciation: "فان", example: "Football fan.", exampleArabic: "مشجع كرة قدم", category: "رياضة" },
    { id: 4907, word: "match", arabic: "مباراة", pronunciation: "ماتش", example: "Watch the match.", exampleArabic: "شاهد المباراة", category: "رياضة" },
    { id: 4908, word: "tournament", arabic: "بطولة", pronunciation: "تورنمنت", example: "International tournament.", exampleArabic: "بطولة دولية", category: "رياضة" },
    { id: 4909, word: "championship", arabic: "بطولة", pronunciation: "تشامبيونشيب", example: "Win the championship.", exampleArabic: "اربح البطولة", category: "رياضة" },
    { id: 4910, word: "score", arabic: "نتيجة", pronunciation: "سكور", example: "What's the score?", exampleArabic: "ما هي النتيجة؟", category: "رياضة" },
    { id: 4911, word: "goal", arabic: "هدف", pronunciation: "غول", example: "Score a goal.", exampleArabic: "سجل هدفاً", category: "رياضة" },
    { id: 4912, word: "win", arabic: "يفوز", pronunciation: "وين", example: "We want to win.", exampleArabic: "نريد أن نفوز", category: "رياضة" },
    { id: 4913, word: "lose", arabic: "يخسر", pronunciation: "لوز", example: "Don't lose hope.", exampleArabic: "لا تخسر الأمل", category: "رياضة" },
    { id: 4914, word: "draw", arabic: "تعادل", pronunciation: "دراو", example: "The match ended in a draw.", exampleArabic: "انتهت المباراة بالتعادل", category: "رياضة" },
    { id: 4915, word: "competition", arabic: "منافسة", pronunciation: "كومبيتيشن", example: "Fierce competition.", exampleArabic: "منافسة شرسة", category: "رياضة" },
    { id: 4916, word: "training", arabic: "تدريب", pronunciation: "ترينينغ", example: "Daily training.", exampleArabic: "تدريب يومي", category: "رياضة" },
    { id: 4917, word: "exercise", arabic: "تمرين", pronunciation: "إكسيرسايز", example: "Do exercise.", exampleArabic: "قم بتمارين", category: "رياضة" },
    { id: 4918, word: "stadium", arabic: "ملعب", pronunciation: "ستاديوم", example: "Full stadium.", exampleArabic: "ملعب ممتلئ", category: "رياضة" },
    { id: 4919, word: "gym", arabic: "نادي رياضي", pronunciation: "جيم", example: "Go to the gym.", exampleArabic: "اذهب إلى النادي الرياضي", category: "رياضة" },
    { id: 4920, word: "swimming", arabic: "سباحة", pronunciation: "سويمينغ", example: "Go swimming.", exampleArabic: "اذهب للسباحة", category: "رياضة" },
    { id: 4921, word: "running", arabic: "جري", pronunciation: "رنينغ", example: "I like running.", exampleArabic: "أحب الجري", category: "رياضة" },
    { id: 4922, word: "cycling", arabic: "ركوب دراجات", pronunciation: "سايكلينغ", example: "Mountain cycling.", exampleArabic: "ركوب دراجات جبلية", category: "رياضة" },
    { id: 4923, word: "yoga", arabic: "يوغا", pronunciation: "يوغا", example: "Practice yoga.", exampleArabic: "مارس اليوجا", category: "رياضة" },
    { id: 4924, word: "medal", arabic: "ميدالية", pronunciation: "ميدال", example: "Gold medal.", exampleArabic: "ميدالية ذهبية", category: "رياضة" },
    { id: 4925, word: "record", arabic: "رقم قياسي", pronunciation: "ريكورد", example: "Break the record.", exampleArabic: "حطم الرقم القياسي", category: "رياضة" }
];

// التحقق من التحميل
console.log('✅ intermediate-data.js loaded with', INTERMEDIATE_WORDS.length, 'words');
