const VERBS_DATA = [
  // A
  {id:1,v1:"accept",v2:"accepted",v3:"accepted",ar:"يقبل",ex:"I accept your offer.",exAr:"أنا أقبل عرضك.",type:"regular"},
  {id:2,v1:"achieve",v2:"achieved",v3:"achieved",ar:"يحقق",ex:"She achieved her goals.",exAr:"حققت أهدافها.",type:"regular"},
  {id:3,v1:"act",v2:"acted",v3:"acted",ar:"يتصرف",ex:"He acted quickly.",exAr:"تصرف بسرعة.",type:"regular"},
  {id:4,v1:"add",v2:"added",v3:"added",ar:"يضيف",ex:"Add some sugar.",exAr:"أضف بعض السكر.",type:"regular"},
  {id:5,v1:"admit",v2:"admitted",v3:"admitted",ar:"يعترف",ex:"He admitted his mistake.",exAr:"اعترف بخطئه.",type:"regular"},
  {id:6,v1:"affect",v2:"affected",v3:"affected",ar:"يؤثر",ex:"Music affects my mood.",exAr:"الموسيقى تؤثر في مزاجي.",type:"regular"},
  {id:7,v1:"agree",v2:"agreed",v3:"agreed",ar:"يوافق",ex:"I agree with you.",exAr:"أنا أوافقك.",type:"regular"},
  {id:8,v1:"allow",v2:"allowed",v3:"allowed",ar:"يسمح",ex:"Allow me to help.",exAr:"اسمح لي بالمساعدة.",type:"regular"},
  {id:9,v1:"answer",v2:"answered",v3:"answered",ar:"يجيب",ex:"Answer the question.",exAr:"أجب على السؤال.",type:"regular"},
  {id:10,v1:"appear",v2:"appeared",v3:"appeared",ar:"يظهر",ex:"Stars appear at night.",exAr:"النجوم تظهر ليلاً.",type:"regular"},
  {id:11,v1:"apply",v2:"applied",v3:"applied",ar:"يتقدم / يطبق",ex:"Apply for the job.",exAr:"تقدم للوظيفة.",type:"regular"},
  {id:12,v1:"argue",v2:"argued",v3:"argued",ar:"يجادل",ex:"They argued all night.",exAr:"تجادلوا طوال الليل.",type:"regular"},
  {id:13,v1:"arrive",v2:"arrived",v3:"arrived",ar:"يصل",ex:"We arrived on time.",exAr:"وصلنا في الوقت.",type:"regular"},
  {id:14,v1:"ask",v2:"asked",v3:"asked",ar:"يسأل",ex:"Ask me anything.",exAr:"اسألني أي شيء.",type:"regular"},
  {id:15,v1:"avoid",v2:"avoided",v3:"avoided",ar:"يتجنب",ex:"Avoid junk food.",exAr:"تجنب الأكل الجاهز.",type:"regular"},
  // B
  {id:16,v1:"be",v2:"was/were",v3:"been",ar:"يكون",ex:"Be yourself.",exAr:"كن نفسك.",type:"irregular"},
  {id:17,v1:"beat",v2:"beat",v3:"beaten",ar:"يضرب / يهزم",ex:"We beat the other team.",exAr:"هزمنا الفريق الآخر.",type:"irregular"},
  {id:18,v1:"become",v2:"became",v3:"become",ar:"يصبح",ex:"He became a doctor.",exAr:"أصبح طبيباً.",type:"irregular"},
  {id:19,v1:"begin",v2:"began",v3:"begun",ar:"يبدأ",ex:"Let's begin the lesson.",exAr:"لنبدأ الدرس.",type:"irregular"},
  {id:20,v1:"believe",v2:"believed",v3:"believed",ar:"يؤمن / يصدق",ex:"I believe in you.",exAr:"أنا أؤمن بك.",type:"regular"},
  {id:21,v1:"bite",v2:"bit",v3:"bitten",ar:"يعض",ex:"The dog bit him.",exAr:"عضه الكلب.",type:"irregular"},
  {id:22,v1:"blow",v2:"blew",v3:"blown",ar:"ينفخ",ex:"Wind blows the leaves.",exAr:"الريح تنفخ الأوراق.",type:"irregular"},
  {id:23,v1:"break",v2:"broke",v3:"broken",ar:"يكسر",ex:"Don't break the glass.",exAr:"لا تكسر الزجاج.",type:"irregular"},
  {id:24,v1:"bring",v2:"brought",v3:"brought",ar:"يحضر",ex:"Bring me some water.",exAr:"أحضر لي ماء.",type:"irregular"},
  {id:25,v1:"build",v2:"built",v3:"built",ar:"يبني",ex:"They built a house.",exAr:"بنوا بيتاً.",type:"irregular"},
  {id:26,v1:"buy",v2:"bought",v3:"bought",ar:"يشتري",ex:"I bought a new phone.",exAr:"اشتريت هاتفاً جديداً.",type:"irregular"},
  // C
  {id:27,v1:"call",v2:"called",v3:"called",ar:"يتصل / يسمي",ex:"Call me tomorrow.",exAr:"اتصل بي غداً.",type:"regular"},
  {id:28,v1:"carry",v2:"carried",v3:"carried",ar:"يحمل",ex:"Carry the bags.",exAr:"احمل الحقائب.",type:"regular"},
  {id:29,v1:"catch",v2:"caught",v3:"caught",ar:"يمسك",ex:"Catch the ball!",exAr:"أمسك الكرة!",type:"irregular"},
  {id:30,v1:"change",v2:"changed",v3:"changed",ar:"يغير",ex:"Change your habits.",exAr:"غير عاداتك.",type:"regular"},
  {id:31,v1:"choose",v2:"chose",v3:"chosen",ar:"يختار",ex:"Choose wisely.",exAr:"اختر بحكمة.",type:"irregular"},
  {id:32,v1:"clean",v2:"cleaned",v3:"cleaned",ar:"ينظف",ex:"Clean your room.",exAr:"نظف غرفتك.",type:"regular"},
  {id:33,v1:"climb",v2:"climbed",v3:"climbed",ar:"يتسلق",ex:"Climb the mountain.",exAr:"تسلق الجبل.",type:"regular"},
  {id:34,v1:"close",v2:"closed",v3:"closed",ar:"يغلق",ex:"Close the door.",exAr:"أغلق الباب.",type:"regular"},
  {id:35,v1:"come",v2:"came",v3:"come",ar:"يأتي",ex:"Come here please.",exAr:"تعال هنا من فضلك.",type:"irregular"},
  {id:36,v1:"complete",v2:"completed",v3:"completed",ar:"يكمل",ex:"Complete the task.",exAr:"أكمل المهمة.",type:"regular"},
  {id:37,v1:"cook",v2:"cooked",v3:"cooked",ar:"يطبخ",ex:"She cooks every day.",exAr:"هي تطبخ كل يوم.",type:"regular"},
  {id:38,v1:"cost",v2:"cost",v3:"cost",ar:"يكلف",ex:"It costs too much.",exAr:"يكلف كثيراً.",type:"irregular"},
  {id:39,v1:"count",v2:"counted",v3:"counted",ar:"يعد",ex:"Count to ten.",exAr:"عد حتى عشرة.",type:"regular"},
  {id:40,v1:"create",v2:"created",v3:"created",ar:"يخلق / ينشئ",ex:"Create something new.",exAr:"أنشئ شيئاً جديداً.",type:"regular"},
  {id:41,v1:"cut",v2:"cut",v3:"cut",ar:"يقطع",ex:"Cut the paper.",exAr:"اقطع الورقة.",type:"irregular"},
  // D
  {id:42,v1:"decide",v2:"decided",v3:"decided",ar:"يقرر",ex:"Decide now.",exAr:"قرر الآن.",type:"regular"},
  {id:43,v1:"describe",v2:"described",v3:"described",ar:"يصف",ex:"Describe the picture.",exAr:"صف الصورة.",type:"regular"},
  {id:44,v1:"design",v2:"designed",v3:"designed",ar:"يصمم",ex:"Design the logo.",exAr:"صمم الشعار.",type:"regular"},
  {id:45,v1:"destroy",v2:"destroyed",v3:"destroyed",ar:"يدمر",ex:"Fire destroyed the building.",exAr:"دمر الحريق المبنى.",type:"regular"},
  {id:46,v1:"develop",v2:"developed",v3:"developed",ar:"يطور",ex:"Develop your skills.",exAr:"طور مهاراتك.",type:"regular"},
  {id:47,v1:"die",v2:"died",v3:"died",ar:"يموت",ex:"Plants die without water.",exAr:"النباتات تموت بدون ماء.",type:"regular"},
  {id:48,v1:"discover",v2:"discovered",v3:"discovered",ar:"يكتشف",ex:"Columbus discovered America.",exAr:"كولومبس اكتشف أمريكا.",type:"regular"},
  {id:49,v1:"do",v2:"did",v3:"done",ar:"يفعل",ex:"Do your homework.",exAr:"افعل واجبك.",type:"irregular"},
  {id:50,v1:"draw",v2:"drew",v3:"drawn",ar:"يرسم",ex:"Draw a circle.",exAr:"ارسم دائرة.",type:"irregular"},
  {id:51,v1:"dream",v2:"dreamed",v3:"dreamed",ar:"يحلم",ex:"I dream of success.",exAr:"أحلم بالنجاح.",type:"regular"},
  {id:52,v1:"drink",v2:"drank",v3:"drunk",ar:"يشرب",ex:"Drink more water.",exAr:"اشرب ماء أكثر.",type:"irregular"},
  {id:53,v1:"drive",v2:"drove",v3:"driven",ar:"يقود",ex:"Drive carefully.",exAr:"قد بحذر.",type:"irregular"},
  {id:54,v1:"drop",v2:"dropped",v3:"dropped",ar:"يسقط",ex:"Don't drop the phone.",exAr:"لا تسقط الهاتف.",type:"regular"},
  // E
  {id:55,v1:"earn",v2:"earned",v3:"earned",ar:"يكسب",ex:"Earn more money.",exAr:"اكسب أموالاً أكثر.",type:"regular"},
  {id:56,v1:"eat",v2:"ate",v3:"eaten",ar:"يأكل",ex:"Eat your vegetables.",exAr:"كل خضارك.",type:"irregular"},
  {id:57,v1:"enjoy",v2:"enjoyed",v3:"enjoyed",ar:"يستمتع",ex:"Enjoy your vacation.",exAr:"استمتع بإجازتك.",type:"regular"},
  {id:58,v1:"explain",v2:"explained",v3:"explained",ar:"يشرح",ex:"Explain the rule.",exAr:"اشرح القاعدة.",type:"regular"},
  // F
  {id:59,v1:"fail",v2:"failed",v3:"failed",ar:"يفشل",ex:"Don't fail the test.",exAr:"لا تفشل في الاختبار.",type:"regular"},
  {id:60,v1:"fall",v2:"fell",v3:"fallen",ar:"يسقط",ex:"Leaves fall in autumn.",exAr:"الأوراق تسقط في الخريف.",type:"irregular"},
  {id:61,v1:"feel",v2:"felt",v3:"felt",ar:"يشعر",ex:"I feel happy.",exAr:"أنا أشعر بالسعادة.",type:"irregular"},
  {id:62,v1:"fight",v2:"fought",v3:"fought",ar:"يقاتل",ex:"Fight for your rights.",exAr:"قاتل من أجل حقوقك.",type:"irregular"},
  {id:63,v1:"find",v2:"found",v3:"found",ar:"يجد",ex:"Find the key.",exAr:"ابحث عن المفتاح.",type:"irregular"},
  {id:64,v1:"finish",v2:"finished",v3:"finished",ar:"ينهي",ex:"Finish your work.",exAr:"أنهِ عملك.",type:"regular"},
  {id:65,v1:"fly",v2:"flew",v3:"flown",ar:"يطير",ex:"Birds fly south.",exAr:"الطيور تطير جنوباً.",type:"irregular"},
  {id:66,v1:"follow",v2:"followed",v3:"followed",ar:"يتبع",ex:"Follow the rules.",exAr:"اتبع القواعد.",type:"regular"},
  {id:67,v1:"forget",v2:"forgot",v3:"forgotten",ar:"ينسى",ex:"Don't forget your keys.",exAr:"لا تنسَ مفاتيحك.",type:"irregular"},
  {id:68,v1:"forgive",v2:"forgave",v3:"forgiven",ar:"يسامح",ex:"Forgive and forget.",exAr:"سامح وانسَ.",type:"irregular"},
  {id:69,v1:"freeze",v2:"froze",v3:"frozen",ar:"يجمد",ex:"Water freezes at 0°C.",exAr:"الماء يتجمد عند صفر.",type:"irregular"},
  // G
  {id:70,v1:"get",v2:"got",v3:"gotten",ar:"يحصل",ex:"Get some rest.",exAr:"خذ قسطاً من الراحة.",type:"irregular"},
  {id:71,v1:"give",v2:"gave",v3:"given",ar:"يعطي",ex:"Give me a chance.",exAr:"أعطني فرصة.",type:"irregular"},
  {id:72,v1:"go",v2:"went",v3:"gone",ar:"يذهب",ex:"Go to school.",exAr:"اذهب إلى المدرسة.",type:"irregular"},
  {id:73,v1:"grow",v2:"grew",v3:"grown",ar:"ينمو",ex:"Plants grow in sunlight.",exAr:"النباتات تنمو في ضوء الشمس.",type:"irregular"},
  // H
  {id:74,v1:"happen",v2:"happened",v3:"happened",ar:"يحدث",ex:"What happened?",exAr:"ماذا حدث؟",type:"regular"},
  {id:75,v1:"have",v2:"had",v3:"had",ar:"يملك / لديه",ex:"I have a dream.",exAr:"لدي حلم.",type:"irregular"},
  {id:76,v1:"hear",v2:"heard",v3:"heard",ar:"يسمع",ex:"I hear music.",exAr:"أسمع موسيقى.",type:"irregular"},
  {id:77,v1:"help",v2:"helped",v3:"helped",ar:"يساعد",ex:"Help others daily.",exAr:"ساعد الآخرين يومياً.",type:"regular"},
  {id:78,v1:"hide",v2:"hid",v3:"hidden",ar:"يختبئ",ex:"Hide and seek.",exAr:"الاختباء والبحث.",type:"irregular"},
  {id:79,v1:"hit",v2:"hit",v3:"hit",ar:"يضرب",ex:"Hit the target.",exAr:"أصب الهدف.",type:"irregular"},
  {id:80,v1:"hold",v2:"held",v3:"held",ar:"يمسك",ex:"Hold my hand.",exAr:"أمسك يدي.",type:"irregular"},
  {id:81,v1:"hurt",v2:"hurt",v3:"hurt",ar:"يؤلم",ex:"That hurts!",exAr:"هذا يؤلم!",type:"irregular"},
  // I
  {id:82,v1:"ignore",v2:"ignored",v3:"ignored",ar:"يتجاهل",ex:"Ignore the noise.",exAr:"تجاهل الضجيج.",type:"regular"},
  {id:83,v1:"improve",v2:"improved",v3:"improved",ar:"يحسّن",ex:"Improve your English.",exAr:"حسّن إنجليزيتك.",type:"regular"},
  {id:84,v1:"include",v2:"included",v3:"included",ar:"يشمل",ex:"Include everyone.",exAr:"اشمل الجميع.",type:"regular"},
  {id:85,v1:"introduce",v2:"introduced",v3:"introduced",ar:"يقدم",ex:"Introduce yourself.",exAr:"قدّم نفسك.",type:"regular"},
  {id:86,v1:"invite",v2:"invited",v3:"invited",ar:"يدعو",ex:"Invite your friends.",exAr:"ادعُ أصدقاءك.",type:"regular"},
  // J
  {id:87,v1:"join",v2:"joined",v3:"joined",ar:"ينضم",ex:"Join our team.",exAr:"انضم لفريقنا.",type:"regular"},
  {id:88,v1:"jump",v2:"jumped",v3:"jumped",ar:"يقفز",ex:"Jump over the fence.",exAr:"اقفز فوق السياج.",type:"regular"},
  // K
  {id:89,v1:"keep",v2:"kept",v3:"kept",ar:"يحافظ / يستمر",ex:"Keep trying.",exAr:"استمر في المحاولة.",type:"irregular"},
  {id:90,v1:"know",v2:"knew",v3:"known",ar:"يعرف",ex:"I know the answer.",exAr:"أعرف الإجابة.",type:"irregular"},
  // L
  {id:91,v1:"laugh",v2:"laughed",v3:"laughed",ar:"يضحك",ex:"Laugh every day.",exAr:"اضحك كل يوم.",type:"regular"},
  {id:92,v1:"learn",v2:"learned",v3:"learned",ar:"يتعلم",ex:"Learn something new.",exAr:"تعلم شيئاً جديداً.",type:"regular"},
  {id:93,v1:"leave",v2:"left",v3:"left",ar:"يغادر / يترك",ex:"Leave on time.",exAr:"غادر في الوقت.",type:"irregular"},
  {id:94,v1:"lend",v2:"lent",v3:"lent",ar:"يقرض",ex:"Lend me your pen.",exAr:"أقرضني قلمك.",type:"irregular"},
  {id:95,v1:"let",v2:"let",v3:"let",ar:"يسمح",ex:"Let me help you.",exAr:"دعني أساعدك.",type:"irregular"},
  {id:96,v1:"like",v2:"liked",v3:"liked",ar:"يحب",ex:"I like coffee.",exAr:"أنا أحب القهوة.",type:"regular"},
  {id:97,v1:"listen",v2:"listened",v3:"listened",ar:"يستمع",ex:"Listen carefully.",exAr:"استمع بعناية.",type:"regular"},
  {id:98,v1:"live",v2:"lived",v3:"lived",ar:"يعيش",ex:"Live your dream.",exAr:"عش حلمك.",type:"regular"},
  {id:99,v1:"look",v2:"looked",v3:"looked",ar:"ينظر",ex:"Look at the sky.",exAr:"انظر إلى السماء.",type:"regular"},
  {id:100,v1:"lose",v2:"lost",v3:"lost",ar:"يخسر",ex:"Don't lose hope.",exAr:"لا تخسر الأمل.",type:"irregular"},
  {id:101,v1:"love",v2:"loved",v3:"loved",ar:"يحب",ex:"Love your family.",exAr:"أحب عائلتك.",type:"regular"},
  // M
  {id:102,v1:"make",v2:"made",v3:"made",ar:"يصنع",ex:"Make a difference.",exAr:"اصنع فرقاً.",type:"irregular"},
  {id:103,v1:"mean",v2:"meant",v3:"meant",ar:"يعني",ex:"What do you mean?",exAr:"ماذا تقصد؟",type:"irregular"},
  {id:104,v1:"meet",v2:"met",v3:"met",ar:"يقابل",ex:"Meet new people.",exAr:"قابل أشخاصاً جدداً.",type:"irregular"},
  {id:105,v1:"miss",v2:"missed",v3:"missed",ar:"يفتقد",ex:"I miss my family.",exAr:"أفتقد عائلتي.",type:"regular"},
  {id:106,v1:"move",v2:"moved",v3:"moved",ar:"يتحرك",ex:"Move forward.",exAr:"تحرك للأمام.",type:"regular"},
  // N
  {id:107,v1:"need",v2:"needed",v3:"needed",ar:"يحتاج",ex:"I need your help.",exAr:"أحتاج مساعدتك.",type:"regular"},
  // O
  {id:108,v1:"open",v2:"opened",v3:"opened",ar:"يفتح",ex:"Open the window.",exAr:"افتح النافذة.",type:"regular"},
  {id:109,v1:"organize",v2:"organized",v3:"organized",ar:"ينظم",ex:"Organize your desk.",exAr:"نظم مكتبك.",type:"regular"},
  // P
  {id:110,v1:"pay",v2:"paid",v3:"paid",ar:"يدفع",ex:"Pay the bill.",exAr:"ادفع الفاتورة.",type:"irregular"},
  {id:111,v1:"plan",v2:"planned",v3:"planned",ar:"يخطط",ex:"Plan your future.",exAr:"خطط لمستقبلك.",type:"regular"},
  {id:112,v1:"play",v2:"played",v3:"played",ar:"يلعب",ex:"Play fair.",exAr:"العب بنزاهة.",type:"regular"},
  {id:113,v1:"prepare",v2:"prepared",v3:"prepared",ar:"يحضّر",ex:"Prepare for the exam.",exAr:"استعد للامتحان.",type:"regular"},
  {id:114,v1:"promise",v2:"promised",v3:"promised",ar:"يعد",ex:"Promise to be honest.",exAr:"عِد بأن تكون صادقاً.",type:"regular"},
  {id:115,v1:"put",v2:"put",v3:"put",ar:"يضع",ex:"Put it on the table.",exAr:"ضعه على الطاولة.",type:"irregular"},
  // R
  {id:116,v1:"read",v2:"read",v3:"read",ar:"يقرأ",ex:"Read every day.",exAr:"اقرأ كل يوم.",type:"irregular"},
  {id:117,v1:"remember",v2:"remembered",v3:"remembered",ar:"يتذكر",ex:"Remember to call.",exAr:"تذكر أن تتصل.",type:"regular"},
  {id:118,v1:"run",v2:"ran",v3:"run",ar:"يركض",ex:"Run every morning.",exAr:"اركض كل صباح.",type:"irregular"},
  // S
  {id:119,v1:"save",v2:"saved",v3:"saved",ar:"يحفظ / ينقذ",ex:"Save your work.",exAr:"احفظ عملك.",type:"regular"},
  {id:120,v1:"say",v2:"said",v3:"said",ar:"يقول",ex:"Say the truth.",exAr:"قل الحقيقة.",type:"irregular"},
  {id:121,v1:"see",v2:"saw",v3:"seen",ar:"يرى",ex:"See the big picture.",exAr:"انظر للصورة الكبيرة.",type:"irregular"},
  {id:122,v1:"sell",v2:"sold",v3:"sold",ar:"يبيع",ex:"Sell your skills.",exAr:"بِع مهاراتك.",type:"irregular"},
  {id:123,v1:"send",v2:"sent",v3:"sent",ar:"يرسل",ex:"Send the message.",exAr:"أرسل الرسالة.",type:"irregular"},
  {id:124,v1:"show",v2:"showed",v3:"shown",ar:"يُري",ex:"Show me the way.",exAr:"أرني الطريق.",type:"irregular"},
  {id:125,v1:"sing",v2:"sang",v3:"sung",ar:"يغني",ex:"Sing your heart out.",exAr:"غنِّ بكل قلبك.",type:"irregular"},
  {id:126,v1:"sit",v2:"sat",v3:"sat",ar:"يجلس",ex:"Sit down please.",exAr:"اجلس من فضلك.",type:"irregular"},
  {id:127,v1:"sleep",v2:"slept",v3:"slept",ar:"ينام",ex:"Sleep 8 hours daily.",exAr:"نم 8 ساعات يومياً.",type:"irregular"},
  {id:128,v1:"speak",v2:"spoke",v3:"spoken",ar:"يتكلم",ex:"Speak confidently.",exAr:"تكلم بثقة.",type:"irregular"},
  {id:129,v1:"spend",v2:"spent",v3:"spent",ar:"ينفق / يقضي",ex:"Spend time wisely.",exAr:"أمضِ وقتك بحكمة.",type:"irregular"},
  {id:130,v1:"stand",v2:"stood",v3:"stood",ar:"يقف",ex:"Stand up for yourself.",exAr:"دافع عن نفسك.",type:"irregular"},
  {id:131,v1:"start",v2:"started",v3:"started",ar:"يبدأ",ex:"Start today.",exAr:"ابدأ اليوم.",type:"regular"},
  {id:132,v1:"stay",v2:"stayed",v3:"stayed",ar:"يبقى",ex:"Stay focused.",exAr:"ابقَ مركزاً.",type:"regular"},
  {id:133,v1:"stop",v2:"stopped",v3:"stopped",ar:"يوقف",ex:"Stop wasting time.",exAr:"توقف عن إضاعة الوقت.",type:"regular"},
  {id:134,v1:"study",v2:"studied",v3:"studied",ar:"يدرس",ex:"Study hard.",exAr:"ادرس بجد.",type:"regular"},
  {id:135,v1:"swim",v2:"swam",v3:"swum",ar:"يسبح",ex:"Swim every week.",exAr:"اسبح كل أسبوع.",type:"irregular"},
  // T
  {id:136,v1:"take",v2:"took",v3:"taken",ar:"يأخذ",ex:"Take a deep breath.",exAr:"خذ نفساً عميقاً.",type:"irregular"},
  {id:137,v1:"talk",v2:"talked",v3:"talked",ar:"يتحدث",ex:"Talk to someone.",exAr:"تحدث مع أحد.",type:"regular"},
  {id:138,v1:"teach",v2:"taught",v3:"taught",ar:"يعلّم",ex:"Teach what you know.",exAr:"علّم ما تعرفه.",type:"irregular"},
  {id:139,v1:"tell",v2:"told",v3:"told",ar:"يخبر",ex:"Tell the truth.",exAr:"أخبر بالحقيقة.",type:"irregular"},
  {id:140,v1:"think",v2:"thought",v3:"thought",ar:"يفكر",ex:"Think before you speak.",exAr:"فكر قبل أن تتكلم.",type:"irregular"},
  {id:141,v1:"throw",v2:"threw",v3:"thrown",ar:"يرمي",ex:"Throw the ball.",exAr:"ارمِ الكرة.",type:"irregular"},
  {id:142,v1:"try",v2:"tried",v3:"tried",ar:"يحاول",ex:"Try your best.",exAr:"حاول بكل ما لديك.",type:"regular"},
  {id:143,v1:"turn",v2:"turned",v3:"turned",ar:"يدور",ex:"Turn left here.",exAr:"انعطف يساراً هنا.",type:"regular"},
  // U
  {id:144,v1:"understand",v2:"understood",v3:"understood",ar:"يفهم",ex:"Do you understand?",exAr:"هل تفهم؟",type:"irregular"},
  {id:145,v1:"use",v2:"used",v3:"used",ar:"يستخدم",ex:"Use your time well.",exAr:"استخدم وقتك جيداً.",type:"regular"},
  // V
  {id:146,v1:"visit",v2:"visited",v3:"visited",ar:"يزور",ex:"Visit new places.",exAr:"زُر أماكن جديدة.",type:"regular"},
  // W
  {id:147,v1:"wait",v2:"waited",v3:"waited",ar:"ينتظر",ex:"Wait for me.",exAr:"انتظرني.",type:"regular"},
  {id:148,v1:"wake",v2:"woke",v3:"woken",ar:"يصحو",ex:"Wake up early.",exAr:"استيقظ مبكراً.",type:"irregular"},
  {id:149,v1:"walk",v2:"walked",v3:"walked",ar:"يمشي",ex:"Walk in the park.",exAr:"تمشَّ في الحديقة.",type:"regular"},
  {id:150,v1:"want",v2:"wanted",v3:"wanted",ar:"يريد",ex:"I want to improve.",exAr:"أريد أن أتحسن.",type:"regular"},
  {id:151,v1:"watch",v2:"watched",v3:"watched",ar:"يشاهد",ex:"Watch and learn.",exAr:"شاهد وتعلم.",type:"regular"},
  {id:152,v1:"win",v2:"won",v3:"won",ar:"يفوز",ex:"Win with grace.",exAr:"افز بأناقة.",type:"irregular"},
  {id:153,v1:"work",v2:"worked",v3:"worked",ar:"يعمل",ex:"Work hard every day.",exAr:"اعمل بجد كل يوم.",type:"regular"},
  {id:154,v1:"write",v2:"wrote",v3:"written",ar:"يكتب",ex:"Write your thoughts.",exAr:"اكتب أفكارك.",type:"irregular"},
  // Extra
  {id:155,v1:"accept",v2:"accepted",v3:"accepted",ar:"يقبل",ex:"Accept the challenge.",exAr:"اقبل التحدي.",type:"regular"},
  {id:156,v1:"achieve",v2:"achieved",v3:"achieved",ar:"يحقق",ex:"Achieve your dreams.",exAr:"حقق أحلامك.",type:"regular"},
  {id:157,v1:"adapt",v2:"adapted",v3:"adapted",ar:"يتكيف",ex:"Adapt to change.",exAr:"تكيف مع التغيير.",type:"regular"},
  {id:158,v1:"advance",v2:"advanced",v3:"advanced",ar:"يتقدم",ex:"Advance your career.",exAr:"تقدم في مسيرتك.",type:"regular"},
  {id:159,v1:"analyze",v2:"analyzed",v3:"analyzed",ar:"يحلل",ex:"Analyze the data.",exAr:"حلل البيانات.",type:"regular"},
  {id:160,v1:"apologize",v2:"apologized",v3:"apologized",ar:"يعتذر",ex:"Apologize sincerely.",exAr:"اعتذر بصدق.",type:"regular"},
  {id:161,v1:"appreciate",v2:"appreciated",v3:"appreciated",ar:"يقدر",ex:"Appreciate small things.",exAr:"قدّر الأشياء الصغيرة.",type:"regular"},
  {id:162,v1:"assist",v2:"assisted",v3:"assisted",ar:"يساعد",ex:"Assist the elderly.",exAr:"ساعد كبار السن.",type:"regular"},
  {id:163,v1:"boost",v2:"boosted",v3:"boosted",ar:"يعزز",ex:"Boost your confidence.",exAr:"عزز ثقتك بنفسك.",type:"regular"},
  {id:164,v1:"borrow",v2:"borrowed",v3:"borrowed",ar:"يستعير",ex:"Borrow with care.",exAr:"استعر بعناية.",type:"regular"},
  {id:165,v1:"calculate",v2:"calculated",v3:"calculated",ar:"يحسب",ex:"Calculate the cost.",exAr:"احسب التكلفة.",type:"regular"},
  {id:166,v1:"cancel",v2:"cancelled",v3:"cancelled",ar:"يلغي",ex:"Cancel the meeting.",exAr:"ألغِ الاجتماع.",type:"regular"},
  {id:167,v1:"celebrate",v2:"celebrated",v3:"celebrated",ar:"يحتفل",ex:"Celebrate small wins.",exAr:"احتفل بالانتصارات الصغيرة.",type:"regular"},
  {id:168,v1:"challenge",v2:"challenged",v3:"challenged",ar:"يتحدى",ex:"Challenge yourself daily.",exAr:"تحدَّ نفسك يومياً.",type:"regular"},
  {id:169,v1:"collaborate",v2:"collaborated",v3:"collaborated",ar:"يتعاون",ex:"Collaborate with others.",exAr:"تعاون مع الآخرين.",type:"regular"},
  {id:170,v1:"commit",v2:"committed",v3:"committed",ar:"يلتزم",ex:"Commit to your goals.",exAr:"التزم بأهدافك.",type:"regular"},
  {id:171,v1:"communicate",v2:"communicated",v3:"communicated",ar:"يتواصل",ex:"Communicate clearly.",exAr:"تواصل بوضوح.",type:"regular"},
  {id:172,v1:"compete",v2:"competed",v3:"competed",ar:"ينافس",ex:"Compete with respect.",exAr:"نافس باحترام.",type:"regular"},
  {id:173,v1:"concentrate",v2:"concentrated",v3:"concentrated",ar:"يركز",ex:"Concentrate on your work.",exAr:"ركز على عملك.",type:"regular"},
  {id:174,v1:"contribute",v2:"contributed",v3:"contributed",ar:"يساهم",ex:"Contribute to society.",exAr:"ساهم في المجتمع.",type:"regular"},
  {id:175,v1:"convince",v2:"convinced",v3:"convinced",ar:"يقنع",ex:"Convince with facts.",exAr:"أقنع بالحقائق.",type:"regular"},
  {id:176,v1:"deal",v2:"dealt",v3:"dealt",ar:"يتعامل",ex:"Deal with problems calmly.",exAr:"تعامل مع المشاكل بهدوء.",type:"irregular"},
  {id:177,v1:"decide",v2:"decided",v3:"decided",ar:"يقرر",ex:"Decide wisely.",exAr:"قرر بحكمة.",type:"regular"},
  {id:178,v1:"dedicate",v2:"dedicated",v3:"dedicated",ar:"يكرّس",ex:"Dedicate time to learning.",exAr:"كرّس وقتاً للتعلم.",type:"regular"},
  {id:179,v1:"defend",v2:"defended",v3:"defended",ar:"يدافع",ex:"Defend your opinion.",exAr:"دافع عن رأيك.",type:"regular"},
  {id:180,v1:"delegate",v2:"delegated",v3:"delegated",ar:"يفوّض",ex:"Delegate tasks wisely.",exAr:"فوّض المهام بحكمة.",type:"regular"},
  {id:181,v1:"eliminate",v2:"eliminated",v3:"eliminated",ar:"يزيل",ex:"Eliminate bad habits.",exAr:"أزل العادات السيئة.",type:"regular"},
  {id:182,v1:"empower",v2:"empowered",v3:"empowered",ar:"يمكّن",ex:"Empower your community.",exAr:"مكّن مجتمعك.",type:"regular"},
  {id:183,v1:"encourage",v2:"encouraged",v3:"encouraged",ar:"يشجع",ex:"Encourage others.",exAr:"شجع الآخرين.",type:"regular"},
  {id:184,v1:"enhance",v2:"enhanced",v3:"enhanced",ar:"يحسّن",ex:"Enhance your skills.",exAr:"حسّن مهاراتك.",type:"regular"},
  {id:185,v1:"establish",v2:"established",v3:"established",ar:"يؤسس",ex:"Establish clear goals.",exAr:"أسّس أهدافاً واضحة.",type:"regular"},
  {id:186,v1:"evaluate",v2:"evaluated",v3:"evaluated",ar:"يقيّم",ex:"Evaluate your progress.",exAr:"قيّم تقدمك.",type:"regular"},
  {id:187,v1:"exceed",v2:"exceeded",v3:"exceeded",ar:"يتجاوز",ex:"Exceed expectations.",exAr:"تجاوز التوقعات.",type:"regular"},
  {id:188,v1:"explore",v2:"explored",v3:"explored",ar:"يستكشف",ex:"Explore new ideas.",exAr:"استكشف أفكاراً جديدة.",type:"regular"},
  {id:189,v1:"express",v2:"expressed",v3:"expressed",ar:"يعبر",ex:"Express yourself freely.",exAr:"عبّر عن نفسك بحرية.",type:"regular"},
  {id:190,v1:"focus",v2:"focused",v3:"focused",ar:"يركز",ex:"Focus on your goals.",exAr:"ركز على أهدافك.",type:"regular"},
  {id:191,v1:"fulfill",v2:"fulfilled",v3:"fulfilled",ar:"يحقق",ex:"Fulfill your potential.",exAr:"حقق إمكاناتك.",type:"regular"},
  {id:192,v1:"gain",v2:"gained",v3:"gained",ar:"يكتسب",ex:"Gain experience.",exAr:"اكتسب الخبرة.",type:"regular"},
  {id:193,v1:"generate",v2:"generated",v3:"generated",ar:"يولّد",ex:"Generate new ideas.",exAr:"ولّد أفكاراً جديدة.",type:"regular"},
  {id:194,v1:"guide",v2:"guided",v3:"guided",ar:"يرشد",ex:"Guide the new student.",exAr:"أرشد الطالب الجديد.",type:"regular"},
  {id:195,v1:"identify",v2:"identified",v3:"identified",ar:"يحدد",ex:"Identify the problem.",exAr:"حدد المشكلة.",type:"regular"},
  {id:196,v1:"implement",v2:"implemented",v3:"implemented",ar:"ينفذ",ex:"Implement the strategy.",exAr:"نفّذ الاستراتيجية.",type:"regular"},
  {id:197,v1:"improve",v2:"improved",v3:"improved",ar:"يحسّن",ex:"Improve every day.",exAr:"تحسّن كل يوم.",type:"regular"},
  {id:198,v1:"innovate",v2:"innovated",v3:"innovated",ar:"يبتكر",ex:"Innovate constantly.",exAr:"ابتكر باستمرار.",type:"regular"},
  {id:199,v1:"inspire",v2:"inspired",v3:"inspired",ar:"يلهم",ex:"Inspire those around you.",exAr:"ألهم من حولك.",type:"regular"},
  {id:200,v1:"invest",v2:"invested",v3:"invested",ar:"يستثمر",ex:"Invest in yourself.",exAr:"استثمر في نفسك.",type:"regular"},
  {id:201,v1:"lead",v2:"led",v3:"led",ar:"يقود",ex:"Lead by example.",exAr:"قُد بالقدوة.",type:"irregular"},
  {id:202,v1:"manage",v2:"managed",v3:"managed",ar:"يدير",ex:"Manage your time.",exAr:"أدِر وقتك.",type:"regular"},
  {id:203,v1:"motivate",v2:"motivated",v3:"motivated",ar:"يحفّز",ex:"Motivate yourself daily.",exAr:"حفّز نفسك يومياً.",type:"regular"},
  {id:204,v1:"negotiate",v2:"negotiated",v3:"negotiated",ar:"يتفاوض",ex:"Negotiate a good deal.",exAr:"تفاوض على صفقة جيدة.",type:"regular"},
  {id:205,v1:"observe",v2:"observed",v3:"observed",ar:"يلاحظ",ex:"Observe and learn.",exAr:"لاحظ وتعلم.",type:"regular"},
  {id:206,v1:"overcome",v2:"overcame",v3:"overcome",ar:"يتغلب",ex:"Overcome your fears.",exAr:"تغلب على مخاوفك.",type:"irregular"},
  {id:207,v1:"participate",v2:"participated",v3:"participated",ar:"يشارك",ex:"Participate actively.",exAr:"شارك بفاعلية.",type:"regular"},
  {id:208,v1:"perform",v2:"performed",v3:"performed",ar:"يؤدي",ex:"Perform at your best.",exAr:"أدِّ بأفضل ما لديك.",type:"regular"},
  {id:209,v1:"persist",v2:"persisted",v3:"persisted",ar:"يصر",ex:"Persist through challenges.",exAr:"أصرّ رغم التحديات.",type:"regular"},
  {id:210,v1:"practice",v2:"practiced",v3:"practiced",ar:"يمارس",ex:"Practice makes perfect.",exAr:"الممارسة تصنع الكمال.",type:"regular"},
  {id:211,v1:"prioritize",v2:"prioritized",v3:"prioritized",ar:"يرتب الأولويات",ex:"Prioritize health first.",exAr:"اجعل الصحة أولوية.",type:"regular"},
  {id:212,v1:"pursue",v2:"pursued",v3:"pursued",ar:"يسعى",ex:"Pursue your dreams.",exAr:"اسعَ لتحقيق أحلامك.",type:"regular"},
  {id:213,v1:"realize",v2:"realized",v3:"realized",ar:"يدرك",ex:"Realize your potential.",exAr:"أدرك إمكاناتك.",type:"regular"},
  {id:214,v1:"recover",v2:"recovered",v3:"recovered",ar:"يتعافى",ex:"Recover from failure.",exAr:"تعافَ من الفشل.",type:"regular"},
  {id:215,v1:"reflect",v2:"reflected",v3:"reflected",ar:"يتأمل",ex:"Reflect on your actions.",exAr:"تأمل في تصرفاتك.",type:"regular"},
  {id:216,v1:"resolve",v2:"resolved",v3:"resolved",ar:"يحل",ex:"Resolve conflicts quickly.",exAr:"حل النزاعات بسرعة.",type:"regular"},
  {id:217,v1:"respect",v2:"respected",v3:"respected",ar:"يحترم",ex:"Respect everyone.",exAr:"احترم الجميع.",type:"regular"},
  {id:218,v1:"seize",v2:"seized",v3:"seized",ar:"يستغل",ex:"Seize every opportunity.",exAr:"استغل كل فرصة.",type:"regular"},
  {id:219,v1:"share",v2:"shared",v3:"shared",ar:"يشارك",ex:"Share your knowledge.",exAr:"شارك معرفتك.",type:"regular"},
  {id:220,v1:"solve",v2:"solved",v3:"solved",ar:"يحل",ex:"Solve the problem.",exAr:"حل المشكلة.",type:"regular"},
  {id:221,v1:"strengthen",v2:"strengthened",v3:"strengthened",ar:"يقوي",ex:"Strengthen your mindset.",exAr:"قوِّ عقليتك.",type:"regular"},
  {id:222,v1:"strive",v2:"strove",v3:"striven",ar:"يسعى بجد",ex:"Strive for excellence.",exAr:"اسعَ للتميز.",type:"irregular"},
  {id:223,v1:"succeed",v2:"succeeded",v3:"succeeded",ar:"ينجح",ex:"Succeed through persistence.",exAr:"انجح من خلال المثابرة.",type:"regular"},
  {id:224,v1:"support",v2:"supported",v3:"supported",ar:"يدعم",ex:"Support each other.",exAr:"ادعم بعضكم البعض.",type:"regular"},
  {id:225,v1:"transform",v2:"transformed",v3:"transformed",ar:"يحوّل",ex:"Transform your life.",exAr:"حوّل حياتك.",type:"regular"},
  {id:226,v1:"trust",v2:"trusted",v3:"trusted",ar:"يثق",ex:"Trust the process.",exAr:"ثق بالعملية.",type:"regular"},
  {id:227,v1:"unlock",v2:"unlocked",v3:"unlocked",ar:"يفتح",ex:"Unlock your potential.",exAr:"افتح إمكاناتك.",type:"regular"},
  {id:228,v1:"upgrade",v2:"upgraded",v3:"upgraded",ar:"يطوّر",ex:"Upgrade your skills.",exAr:"طوّر مهاراتك.",type:"regular"},
  {id:229,v1:"visualize",v2:"visualized",v3:"visualized",ar:"يتخيل",ex:"Visualize your success.",exAr:"تخيّل نجاحك.",type:"regular"},
  {id:230,v1:"volunteer",v2:"volunteered",v3:"volunteered",ar:"يتطوع",ex:"Volunteer for a cause.",exAr:"تطوع لقضية.",type:"regular"},
  {id:231,v1:"welcome",v2:"welcomed",v3:"welcomed",ar:"يرحب",ex:"Welcome new challenges.",exAr:"رحّب بالتحديات الجديدة.",type:"regular"},
  {id:232,v1:"withdraw",v2:"withdrew",v3:"withdrawn",ar:"يسحب",ex:"Withdraw from negativity.",exAr:"ابتعد عن السلبية.",type:"irregular"},

  // ===== EXTRA VERBS (233-500) =====
  // D
  {id:233,v1:"damage",v2:"damaged",v3:"damaged",ar:"يتلف",ex:"The storm damaged the roof.",exAr:"العاصفة أتلفت السقف.",type:"regular"},
  {id:234,v1:"dare",v2:"dared",v3:"dared",ar:"يجرؤ",ex:"Dare to be different.",exAr:"اجرأ على أن تكون مختلفاً.",type:"regular"},
  {id:235,v1:"deal",v2:"dealt",v3:"dealt",ar:"يتعامل",ex:"Deal with it calmly.",exAr:"تعامل معه بهدوء.",type:"irregular"},
  {id:236,v1:"deliver",v2:"delivered",v3:"delivered",ar:"يسلّم",ex:"Deliver the package today.",exAr:"سلّم الطرد اليوم.",type:"regular"},
  {id:237,v1:"demand",v2:"demanded",v3:"demanded",ar:"يطالب",ex:"She demanded an apology.",exAr:"طالبت باعتذار.",type:"regular"},
  {id:238,v1:"demonstrate",v2:"demonstrated",v3:"demonstrated",ar:"يوضح",ex:"Demonstrate your skills.",exAr:"أوضح مهاراتك.",type:"regular"},
  {id:239,v1:"deny",v2:"denied",v3:"denied",ar:"ينكر",ex:"He denied the accusations.",exAr:"أنكر الاتهامات.",type:"regular"},
  {id:240,v1:"depend",v2:"depended",v3:"depended",ar:"يعتمد",ex:"Depend on yourself.",exAr:"اعتمد على نفسك.",type:"regular"},
  {id:241,v1:"deserve",v2:"deserved",v3:"deserved",ar:"يستحق",ex:"You deserve the best.",exAr:"تستحق الأفضل.",type:"regular"},
  {id:242,v1:"dig",v2:"dug",v3:"dug",ar:"يحفر",ex:"Dig a deep hole.",exAr:"احفر حفرة عميقة.",type:"irregular"},
  {id:243,v1:"disappear",v2:"disappeared",v3:"disappeared",ar:"يختفي",ex:"The sun disappeared.",exAr:"اختفت الشمس.",type:"regular"},
  {id:244,v1:"disappoint",v2:"disappointed",v3:"disappointed",ar:"يخيب",ex:"Don't disappoint your parents.",exAr:"لا تخيب والديك.",type:"regular"},
  {id:245,v1:"discuss",v2:"discussed",v3:"discussed",ar:"يناقش",ex:"Let's discuss this plan.",exAr:"لنناقش هذه الخطة.",type:"regular"},
  {id:246,v1:"distribute",v2:"distributed",v3:"distributed",ar:"يوزع",ex:"Distribute the gifts equally.",exAr:"وزّع الهدايا بالتساوي.",type:"regular"},
  {id:247,v1:"divide",v2:"divided",v3:"divided",ar:"يقسم",ex:"Divide the work fairly.",exAr:"قسّم العمل بعدل.",type:"regular"},
  // E
  {id:248,v1:"educate",v2:"educated",v3:"educated",ar:"يثقف",ex:"Educate yourself daily.",exAr:"ثقّف نفسك يومياً.",type:"regular"},
  {id:249,v1:"elect",v2:"elected",v3:"elected",ar:"ينتخب",ex:"Elect the best leader.",exAr:"انتخب أفضل قائد.",type:"regular"},
  {id:250,v1:"emerge",v2:"emerged",v3:"emerged",ar:"يظهر",ex:"New ideas emerge daily.",exAr:"أفكار جديدة تظهر يومياً.",type:"regular"},
  {id:251,v1:"employ",v2:"employed",v3:"employed",ar:"يوظف",ex:"They employ 500 people.",exAr:"يوظفون 500 شخص.",type:"regular"},
  {id:252,v1:"end",v2:"ended",v3:"ended",ar:"ينهي",ex:"End on a positive note.",exAr:"انهِ على نبرة إيجابية.",type:"regular"},
  {id:253,v1:"enter",v2:"entered",v3:"entered",ar:"يدخل",ex:"Enter the building.",exAr:"ادخل المبنى.",type:"regular"},
  {id:254,v1:"examine",v2:"examined",v3:"examined",ar:"يفحص",ex:"Examine the evidence.",exAr:"افحص الأدلة.",type:"regular"},
  {id:255,v1:"exchange",v2:"exchanged",v3:"exchanged",ar:"يتبادل",ex:"Exchange contact details.",exAr:"تبادل معلومات التواصل.",type:"regular"},
  {id:256,v1:"exercise",v2:"exercised",v3:"exercised",ar:"يمارس الرياضة",ex:"Exercise for 30 minutes.",exAr:"مارس الرياضة 30 دقيقة.",type:"regular"},
  {id:257,v1:"exist",v2:"existed",v3:"existed",ar:"يوجد",ex:"Problems exist everywhere.",exAr:"المشاكل موجودة في كل مكان.",type:"regular"},
  {id:258,v1:"expand",v2:"expanded",v3:"expanded",ar:"يوسّع",ex:"Expand your network.",exAr:"وسّع شبكة علاقاتك.",type:"regular"},
  {id:259,v1:"expect",v2:"expected",v3:"expected",ar:"يتوقع",ex:"Expect the unexpected.",exAr:"توقع غير المتوقع.",type:"regular"},
  {id:260,v1:"experience",v2:"experienced",v3:"experienced",ar:"يختبر",ex:"Experience new cultures.",exAr:"اختبر ثقافات جديدة.",type:"regular"},
  // F
  {id:261,v1:"face",v2:"faced",v3:"faced",ar:"يواجه",ex:"Face your challenges.",exAr:"واجه تحدياتك.",type:"regular"},
  {id:262,v1:"feed",v2:"fed",v3:"fed",ar:"يطعم",ex:"Feed the stray cats.",exAr:"أطعم القطط الضالة.",type:"irregular"},
  {id:263,v1:"fix",v2:"fixed",v3:"fixed",ar:"يصلح",ex:"Fix the problem now.",exAr:"أصلح المشكلة الآن.",type:"regular"},
  {id:264,v1:"focus",v2:"focused",v3:"focused",ar:"يركز",ex:"Focus on one task.",exAr:"ركز على مهمة واحدة.",type:"regular"},
  {id:265,v1:"force",v2:"forced",v3:"forced",ar:"يجبر",ex:"Don't force others.",exAr:"لا تجبر الآخرين.",type:"regular"},
  {id:266,v1:"form",v2:"formed",v3:"formed",ar:"يشكّل",ex:"Form a good habit.",exAr:"شكّل عادة جيدة.",type:"regular"},
  {id:267,v1:"fund",v2:"funded",v3:"funded",ar:"يموّل",ex:"Fund the project.",exAr:"موّل المشروع.",type:"regular"},
  // G
  {id:268,v1:"gather",v2:"gathered",v3:"gathered",ar:"يجمع",ex:"Gather all the data.",exAr:"اجمع كل البيانات.",type:"regular"},
  {id:269,v1:"grab",v2:"grabbed",v3:"grabbed",ar:"يمسك",ex:"Grab every opportunity.",exAr:"امسك كل فرصة.",type:"regular"},
  {id:270,v1:"grant",v2:"granted",v3:"granted",ar:"يمنح",ex:"Grant the request.",exAr:"امنح الطلب.",type:"regular"},
  // H
  {id:271,v1:"handle",v2:"handled",v3:"handled",ar:"يتعامل مع",ex:"Handle pressure well.",exAr:"تعامل مع الضغط بشكل جيد.",type:"regular"},
  {id:272,v1:"hate",v2:"hated",v3:"hated",ar:"يكره",ex:"Hate no one.",exAr:"لا تكره أحداً.",type:"regular"},
  {id:273,v1:"heal",v2:"healed",v3:"healed",ar:"يشفى",ex:"Time heals everything.",exAr:"الوقت يشفي كل شيء.",type:"regular"},
  {id:274,v1:"hire",v2:"hired",v3:"hired",ar:"يوظف",ex:"Hire the best talent.",exAr:"وظّف أفضل المواهب.",type:"regular"},
  {id:275,v1:"hope",v2:"hoped",v3:"hoped",ar:"يأمل",ex:"Hope for the best.",exAr:"أمل في الأفضل.",type:"regular"},
  // I
  {id:276,v1:"imagine",v2:"imagined",v3:"imagined",ar:"يتخيل",ex:"Imagine a better world.",exAr:"تخيل عالماً أفضل.",type:"regular"},
  {id:277,v1:"impact",v2:"impacted",v3:"impacted",ar:"يؤثر في",ex:"Your words impact others.",exAr:"كلماتك تؤثر في الآخرين.",type:"regular"},
  {id:278,v1:"increase",v2:"increased",v3:"increased",ar:"يزيد",ex:"Increase your productivity.",exAr:"زد إنتاجيتك.",type:"regular"},
  {id:279,v1:"indicate",v2:"indicated",v3:"indicated",ar:"يشير",ex:"Data indicates growth.",exAr:"البيانات تشير إلى نمو.",type:"regular"},
  {id:280,v1:"influence",v2:"influenced",v3:"influenced",ar:"يؤثر",ex:"Leaders influence people.",exAr:"القادة يؤثرون في الناس.",type:"regular"},
  {id:281,v1:"inform",v2:"informed",v3:"informed",ar:"يُبلّغ",ex:"Inform me immediately.",exAr:"أبلغني فوراً.",type:"regular"},
  {id:282,v1:"insist",v2:"insisted",v3:"insisted",ar:"يُصر",ex:"She insisted on going.",exAr:"أصرّت على الذهاب.",type:"regular"},
  {id:283,v1:"interview",v2:"interviewed",v3:"interviewed",ar:"يقابل",ex:"Interview the candidate.",exAr:"قابل المرشح.",type:"regular"},
  // J
  {id:284,v1:"judge",v2:"judged",v3:"judged",ar:"يحكم",ex:"Don't judge quickly.",exAr:"لا تحكم بسرعة.",type:"regular"},
  // K
  {id:285,v1:"kick",v2:"kicked",v3:"kicked",ar:"يركل",ex:"Kick the ball hard.",exAr:"اركل الكرة بقوة.",type:"regular"},
  {id:286,v1:"knock",v2:"knocked",v3:"knocked",ar:"يطرق",ex:"Knock on the door.",exAr:"اطرق الباب.",type:"regular"},
  // L
  {id:287,v1:"lack",v2:"lacked",v3:"lacked",ar:"يفتقر",ex:"Don't lack confidence.",exAr:"لا تفتقر للثقة.",type:"regular"},
  {id:288,v1:"launch",v2:"launched",v3:"launched",ar:"يطلق",ex:"Launch the product soon.",exAr:"أطلق المنتج قريباً.",type:"regular"},
  {id:289,v1:"lay",v2:"laid",v3:"laid",ar:"يضع",ex:"Lay the foundation first.",exAr:"ضع الأساس أولاً.",type:"irregular"},
  {id:290,v1:"lift",v2:"lifted",v3:"lifted",ar:"يرفع",ex:"Lift each other up.",exAr:"ارفعوا بعضكم.",type:"regular"},
  {id:291,v1:"limit",v2:"limited",v3:"limited",ar:"يحد",ex:"Don't limit yourself.",exAr:"لا تحد نفسك.",type:"regular"},
  {id:292,v1:"link",v2:"linked",v3:"linked",ar:"يربط",ex:"Link effort to success.",exAr:"اربط الجهد بالنجاح.",type:"regular"},
  {id:293,v1:"locate",v2:"located",v3:"located",ar:"يحدد موقع",ex:"Locate the nearest exit.",exAr:"حدد أقرب مخرج.",type:"regular"},
  // M
  {id:294,v1:"maintain",v2:"maintained",v3:"maintained",ar:"يحافظ",ex:"Maintain a healthy diet.",exAr:"حافظ على نظام غذائي صحي.",type:"regular"},
  {id:295,v1:"measure",v2:"measured",v3:"measured",ar:"يقيس",ex:"Measure your progress.",exAr:"قس تقدمك.",type:"regular"},
  {id:296,v1:"mentor",v2:"mentored",v3:"mentored",ar:"يُرشد",ex:"Mentor the younger team.",exAr:"أرشد الفريق الأصغر.",type:"regular"},
  {id:297,v1:"mix",v2:"mixed",v3:"mixed",ar:"يمزج",ex:"Mix the ingredients well.",exAr:"امزج المكونات جيداً.",type:"regular"},
  {id:298,v1:"modify",v2:"modified",v3:"modified",ar:"يعدّل",ex:"Modify your approach.",exAr:"عدّل أسلوبك.",type:"regular"},
  {id:299,v1:"monitor",v2:"monitored",v3:"monitored",ar:"يراقب",ex:"Monitor your spending.",exAr:"راقب إنفاقك.",type:"regular"},
  // N
  {id:300,v1:"notify",v2:"notified",v3:"notified",ar:"يُبلّغ",ex:"Notify me when ready.",exAr:"أبلغني عند الاستعداد.",type:"regular"},
  // O
  {id:301,v1:"obtain",v2:"obtained",v3:"obtained",ar:"يحصل على",ex:"Obtain the required documents.",exAr:"احصل على الوثائق المطلوبة.",type:"regular"},
  {id:302,v1:"offer",v2:"offered",v3:"offered",ar:"يعرض",ex:"Offer your help.",exAr:"اعرض مساعدتك.",type:"regular"},
  {id:303,v1:"oppose",v2:"opposed",v3:"opposed",ar:"يعارض",ex:"Oppose bad decisions.",exAr:"عارض القرارات السيئة.",type:"regular"},
  {id:304,v1:"overcome",v2:"overcame",v3:"overcome",ar:"يتغلب",ex:"Overcome your obstacles.",exAr:"تغلب على عقباتك.",type:"irregular"},
  {id:305,v1:"owe",v2:"owed",v3:"owed",ar:"يدين",ex:"I owe you a favor.",exAr:"أنا مدين لك بمعروف.",type:"regular"},
  {id:306,v1:"own",v2:"owned",v3:"owned",ar:"يملك",ex:"Own your mistakes.",exAr:"تملّك أخطاءك.",type:"regular"},
  // P
  {id:307,v1:"pass",v2:"passed",v3:"passed",ar:"يجتاز",ex:"Pass the exam.",exAr:"اجتز الامتحان.",type:"regular"},
  {id:308,v1:"pick",v2:"picked",v3:"picked",ar:"يختار",ex:"Pick the right path.",exAr:"اختر الطريق الصحيح.",type:"regular"},
  {id:309,v1:"point",v2:"pointed",v3:"pointed",ar:"يشير",ex:"Point out the errors.",exAr:"أشر إلى الأخطاء.",type:"regular"},
  {id:310,v1:"post",v2:"posted",v3:"posted",ar:"ينشر",ex:"Post your achievements.",exAr:"انشر إنجازاتك.",type:"regular"},
  {id:311,v1:"prefer",v2:"preferred",v3:"preferred",ar:"يفضل",ex:"I prefer tea.",exAr:"أنا أفضل الشاي.",type:"regular"},
  {id:312,v1:"present",v2:"presented",v3:"presented",ar:"يقدّم",ex:"Present your ideas clearly.",exAr:"قدّم أفكارك بوضوح.",type:"regular"},
  {id:313,v1:"prevent",v2:"prevented",v3:"prevented",ar:"يمنع",ex:"Prevent mistakes early.",exAr:"امنع الأخطاء مبكراً.",type:"regular"},
  {id:314,v1:"produce",v2:"produced",v3:"produced",ar:"ينتج",ex:"Produce quality content.",exAr:"أنتج محتوى جيد.",type:"regular"},
  {id:315,v1:"protect",v2:"protected",v3:"protected",ar:"يحمي",ex:"Protect what matters.",exAr:"احمِ ما يهمك.",type:"regular"},
  {id:316,v1:"prove",v2:"proved",v3:"proven",ar:"يثبت",ex:"Prove them wrong.",exAr:"أثبت خطأهم.",type:"irregular"},
  {id:317,v1:"provide",v2:"provided",v3:"provided",ar:"يوفر",ex:"Provide clear instructions.",exAr:"وفّر تعليمات واضحة.",type:"regular"},
  {id:318,v1:"push",v2:"pushed",v3:"pushed",ar:"يدفع",ex:"Push your limits.",exAr:"ادفع حدودك.",type:"regular"},
  // Q
  {id:319,v1:"quit",v2:"quit",v3:"quit",ar:"يستقيل / يتوقف",ex:"Never quit on your dreams.",exAr:"لا تتوقف أبداً عن أحلامك.",type:"irregular"},
  // R
  {id:320,v1:"raise",v2:"raised",v3:"raised",ar:"يرفع",ex:"Raise your standards.",exAr:"ارفع معاييرك.",type:"regular"},
  {id:321,v1:"reach",v2:"reached",v3:"reached",ar:"يصل",ex:"Reach for the stars.",exAr:"اصل إلى النجوم.",type:"regular"},
  {id:322,v1:"react",v2:"reacted",v3:"reacted",ar:"يتفاعل",ex:"React wisely to criticism.",exAr:"تفاعل بحكمة مع النقد.",type:"regular"},
  {id:323,v1:"receive",v2:"received",v3:"received",ar:"يتلقى",ex:"Receive feedback gracefully.",exAr:"تلقّ التغذية الراجعة بأناقة.",type:"regular"},
  {id:324,v1:"recommend",v2:"recommended",v3:"recommended",ar:"يوصي",ex:"I recommend this book.",exAr:"أنا أوصي بهذا الكتاب.",type:"regular"},
  {id:325,v1:"reduce",v2:"reduced",v3:"reduced",ar:"يقلل",ex:"Reduce screen time.",exAr:"قلل وقت الشاشة.",type:"regular"},
  {id:326,v1:"refuse",v2:"refused",v3:"refused",ar:"يرفض",ex:"Refuse to give up.",exAr:"ارفض الاستسلام.",type:"regular"},
  {id:327,v1:"release",v2:"released",v3:"released",ar:"يُطلق",ex:"Release the new version.",exAr:"أطلق الإصدار الجديد.",type:"regular"},
  {id:328,v1:"rely",v2:"relied",v3:"relied",ar:"يعتمد",ex:"Rely on your strengths.",exAr:"اعتمد على نقاط قوتك.",type:"regular"},
  {id:329,v1:"repeat",v2:"repeated",v3:"repeated",ar:"يكرر",ex:"Repeat until perfect.",exAr:"كرر حتى تتقن.",type:"regular"},
  {id:330,v1:"replace",v2:"replaced",v3:"replaced",ar:"يستبدل",ex:"Replace bad habits.",exAr:"استبدل العادات السيئة.",type:"regular"},
  {id:331,v1:"report",v2:"reported",v3:"reported",ar:"يُبلّغ",ex:"Report the issue.",exAr:"أبلّغ عن المشكلة.",type:"regular"},
  {id:332,v1:"request",v2:"requested",v3:"requested",ar:"يطلب",ex:"Request feedback often.",exAr:"اطلب التغذية الراجعة كثيراً.",type:"regular"},
  {id:333,v1:"require",v2:"required",v3:"required",ar:"يتطلب",ex:"Success requires effort.",exAr:"النجاح يتطلب جهداً.",type:"regular"},
  {id:334,v1:"research",v2:"researched",v3:"researched",ar:"يبحث",ex:"Research before deciding.",exAr:"ابحث قبل أن تقرر.",type:"regular"},
  {id:335,v1:"respond",v2:"responded",v3:"responded",ar:"يرد",ex:"Respond professionally.",exAr:"ردّ باحترافية.",type:"regular"},
  {id:336,v1:"review",v2:"reviewed",v3:"reviewed",ar:"يراجع",ex:"Review your notes daily.",exAr:"راجع ملاحظاتك يومياً.",type:"regular"},
  {id:337,v1:"ride",v2:"rode",v3:"ridden",ar:"يركب",ex:"Ride a bicycle.",exAr:"اركب دراجة.",type:"irregular"},
  {id:338,v1:"rise",v2:"rose",v3:"risen",ar:"يرتفع",ex:"Rise above the challenges.",exAr:"ارتفع فوق التحديات.",type:"irregular"},
  // S
  {id:339,v1:"search",v2:"searched",v3:"searched",ar:"يبحث",ex:"Search for answers.",exAr:"ابحث عن الإجابات.",type:"regular"},
  {id:340,v1:"select",v2:"selected",v3:"selected",ar:"يختار",ex:"Select the best option.",exAr:"اختر الخيار الأفضل.",type:"regular"},
  {id:341,v1:"serve",v2:"served",v3:"served",ar:"يخدم",ex:"Serve your community.",exAr:"اخدم مجتمعك.",type:"regular"},
  {id:342,v1:"set",v2:"set",v3:"set",ar:"يضع / يحدد",ex:"Set clear goals.",exAr:"ضع أهدافاً واضحة.",type:"irregular"},
  {id:343,v1:"settle",v2:"settled",v3:"settled",ar:"يستقر",ex:"Settle the dispute.",exAr:"أنهِ النزاع.",type:"regular"},
  {id:344,v1:"shake",v2:"shook",v3:"shaken",ar:"يهز",ex:"Shake hands firmly.",exAr:"صافح بقوة.",type:"irregular"},
  {id:345,v1:"shape",v2:"shaped",v3:"shaped",ar:"يشكّل",ex:"Shape your future now.",exAr:"شكّل مستقبلك الآن.",type:"regular"},
  {id:346,v1:"shoot",v2:"shot",v3:"shot",ar:"يطلق",ex:"Shoot for the moon.",exAr:"اطلق نحو القمر.",type:"irregular"},
  {id:347,v1:"sign",v2:"signed",v3:"signed",ar:"يوقّع",ex:"Sign the contract.",exAr:"وقّع العقد.",type:"regular"},
  {id:348,v1:"simplify",v2:"simplified",v3:"simplified",ar:"يبسّط",ex:"Simplify complex problems.",exAr:"بسّط المشاكل المعقدة.",type:"regular"},
  {id:349,v1:"skip",v2:"skipped",v3:"skipped",ar:"يتخطى",ex:"Skip unnecessary steps.",exAr:"تخطَّ الخطوات غير الضرورية.",type:"regular"},
  {id:350,v1:"smile",v2:"smiled",v3:"smiled",ar:"يبتسم",ex:"Smile every morning.",exAr:"ابتسم كل صباح.",type:"regular"},
  {id:351,v1:"spread",v2:"spread",v3:"spread",ar:"ينشر",ex:"Spread kindness.",exAr:"انشر اللطف.",type:"irregular"},
  {id:352,v1:"steal",v2:"stole",v3:"stolen",ar:"يسرق",ex:"Never steal from others.",exAr:"لا تسرق أبداً من الآخرين.",type:"irregular"},
  {id:353,v1:"stick",v2:"stuck",v3:"stuck",ar:"يلتزم",ex:"Stick to your plan.",exAr:"التزم بخطتك.",type:"irregular"},
  {id:354,v1:"strike",v2:"struck",v3:"struck",ar:"يضرب",ex:"Strike while it's hot.",exAr:"اضرب الحديد وهو ساخن.",type:"irregular"},
  {id:355,v1:"submit",v2:"submitted",v3:"submitted",ar:"يُقدّم",ex:"Submit the report on time.",exAr:"قدّم التقرير في الوقت.",type:"regular"},
  {id:356,v1:"suggest",v2:"suggested",v3:"suggested",ar:"يقترح",ex:"Suggest a solution.",exAr:"اقترح حلاً.",type:"regular"},
  {id:357,v1:"supply",v2:"supplied",v3:"supplied",ar:"يزود",ex:"Supply quality materials.",exAr:"زوّد بمواد جيدة.",type:"regular"},
  {id:358,v1:"surpass",v2:"surpassed",v3:"surpassed",ar:"يتجاوز",ex:"Surpass your own records.",exAr:"تجاوز سجلاتك الخاصة.",type:"regular"},
  {id:359,v1:"survive",v2:"survived",v3:"survived",ar:"ينجو",ex:"Survive and thrive.",exAr:"انجُ وازدهر.",type:"regular"},
  {id:360,v1:"switch",v2:"switched",v3:"switched",ar:"يبدّل",ex:"Switch to a better method.",exAr:"بدّل إلى طريقة أفضل.",type:"regular"},
  // T
  {id:361,v1:"tackle",v2:"tackled",v3:"tackled",ar:"يتصدى",ex:"Tackle the issue head-on.",exAr:"تصدَّ للمشكلة مباشرة.",type:"regular"},
  {id:362,v1:"target",v2:"targeted",v3:"targeted",ar:"يستهدف",ex:"Target the right audience.",exAr:"استهدف الجمهور الصحيح.",type:"regular"},
  {id:363,v1:"test",v2:"tested",v3:"tested",ar:"يختبر",ex:"Test your assumptions.",exAr:"اختبر افتراضاتك.",type:"regular"},
  {id:364,v1:"touch",v2:"touched",v3:"touched",ar:"يلمس",ex:"Touch people's hearts.",exAr:"الامس قلوب الناس.",type:"regular"},
  {id:365,v1:"track",v2:"tracked",v3:"tracked",ar:"يتتبع",ex:"Track your progress daily.",exAr:"تتبع تقدمك يومياً.",type:"regular"},
  {id:366,v1:"train",v2:"trained",v3:"trained",ar:"يتدرب",ex:"Train hard every day.",exAr:"تدرب بجد كل يوم.",type:"regular"},
  {id:367,v1:"transfer",v2:"transferred",v3:"transferred",ar:"ينقل",ex:"Transfer your knowledge.",exAr:"انقل معرفتك.",type:"regular"},
  {id:368,v1:"travel",v2:"travelled",v3:"travelled",ar:"يسافر",ex:"Travel broadens the mind.",exAr:"السفر يوسّع الأفق.",type:"regular"},
  {id:369,v1:"treat",v2:"treated",v3:"treated",ar:"يعامل",ex:"Treat others with kindness.",exAr:"عامل الآخرين بلطف.",type:"regular"},
  {id:370,v1:"trigger",v2:"triggered",v3:"triggered",ar:"يُثير",ex:"Trigger positive change.",exAr:"أثر تغييراً إيجابياً.",type:"regular"},
  // U
  {id:371,v1:"underestimate",v2:"underestimated",v3:"underestimated",ar:"يستهين",ex:"Never underestimate yourself.",exAr:"لا تستهن بنفسك أبداً.",type:"regular"},
  {id:372,v1:"unite",v2:"united",v3:"united",ar:"يوحّد",ex:"Unite for a common goal.",exAr:"توحّد من أجل هدف مشترك.",type:"regular"},
  {id:373,v1:"update",v2:"updated",v3:"updated",ar:"يحدّث",ex:"Update your skills regularly.",exAr:"حدّث مهاراتك بانتظام.",type:"regular"},
  {id:374,v1:"utilize",v2:"utilized",v3:"utilized",ar:"يستغل",ex:"Utilize every resource.",exAr:"استغل كل مورد.",type:"regular"},
  // V
  {id:375,v1:"validate",v2:"validated",v3:"validated",ar:"يُصادق",ex:"Validate your ideas.",exAr:"صادق على أفكارك.",type:"regular"},
  {id:376,v1:"value",v2:"valued",v3:"valued",ar:"يُقدّر",ex:"Value your time.",exAr:"قدّر وقتك.",type:"regular"},
  {id:377,v1:"vary",v2:"varied",v3:"varied",ar:"يختلف",ex:"Results vary by effort.",exAr:"النتائج تختلف حسب الجهد.",type:"regular"},
  // W
  {id:378,v1:"warn",v2:"warned",v3:"warned",ar:"يحذّر",ex:"Warn others of the danger.",exAr:"حذّر الآخرين من الخطر.",type:"regular"},
  {id:379,v1:"waste",v2:"wasted",v3:"wasted",ar:"يضيع",ex:"Don't waste your potential.",exAr:"لا تضيع إمكاناتك.",type:"regular"},
  {id:380,v1:"wear",v2:"wore",v3:"worn",ar:"يلبس",ex:"Wear your confidence.",exAr:"البس ثقتك.",type:"irregular"},
  {id:381,v1:"weigh",v2:"weighed",v3:"weighed",ar:"يزن",ex:"Weigh the pros and cons.",exAr:"زن الإيجابيات والسلبيات.",type:"regular"},
  {id:382,v1:"wonder",v2:"wondered",v3:"wondered",ar:"يتساءل",ex:"Wonder and explore.",exAr:"تساءل واستكشف.",type:"regular"},
  {id:383,v1:"worry",v2:"worried",v3:"worried",ar:"يقلق",ex:"Don't worry, take action.",exAr:"لا تقلق، تصرف.",type:"regular"},
  // Extra irregular
  {id:384,v1:"bind",v2:"bound",v3:"bound",ar:"يربط",ex:"Bind the pages together.",exAr:"اربط الصفحات معاً.",type:"irregular"},
  {id:385,v1:"bend",v2:"bent",v3:"bent",ar:"يثني",ex:"Bend but don't break.",exAr:"انثنِ لكن لا تنكسر.",type:"irregular"},
  {id:386,v1:"burst",v2:"burst",v3:"burst",ar:"ينفجر",ex:"Burst with energy.",exAr:"انفجر بالطاقة.",type:"irregular"},
  {id:387,v1:"cast",v2:"cast",v3:"cast",ar:"يلقي",ex:"Cast your vote.",exAr:"ألقِ صوتك.",type:"irregular"},
  {id:388,v1:"creep",v2:"crept",v3:"crept",ar:"يزحف",ex:"Doubts crept in slowly.",exAr:"تسللت الشكوك ببطء.",type:"irregular"},
  {id:389,v1:"feed",v2:"fed",v3:"fed",ar:"يغذي",ex:"Feed your curiosity.",exAr:"غذِّ فضولك.",type:"irregular"},
  {id:390,v1:"flee",v2:"fled",v3:"fled",ar:"يفر",ex:"Flee from negativity.",exAr:"فرّ من السلبية.",type:"irregular"},
  {id:391,v1:"fling",v2:"flung",v3:"flung",ar:"يقذف",ex:"Fling open the doors.",exAr:"ارمِ الأبواب مفتوحة.",type:"irregular"},
  {id:392,v1:"forbid",v2:"forbade",v3:"forbidden",ar:"يحظر",ex:"Forbid harmful behavior.",exAr:"احظر السلوك الضار.",type:"irregular"},
  {id:393,v1:"grind",v2:"ground",v3:"ground",ar:"يطحن",ex:"Grind daily for success.",exAr:"اعمل بجد يومياً للنجاح.",type:"irregular"},
  {id:394,v1:"hang",v2:"hung",v3:"hung",ar:"يعلّق",ex:"Hang the picture there.",exAr:"علّق الصورة هناك.",type:"irregular"},
  {id:395,v1:"kneel",v2:"knelt",v3:"knelt",ar:"يركع",ex:"Kneel and pray.",exAr:"اركع وصلِّ.",type:"irregular"},
  {id:396,v1:"lean",v2:"leant",v3:"leant",ar:"يميل",ex:"Lean on your team.",exAr:"اتكأ على فريقك.",type:"irregular"},
  {id:397,v1:"light",v2:"lit",v3:"lit",ar:"يضيء",ex:"Light up the room.",exAr:"أضئ الغرفة.",type:"irregular"},
  {id:398,v1:"seek",v2:"sought",v3:"sought",ar:"يسعى",ex:"Seek knowledge always.",exAr:"اسعَ للمعرفة دائماً.",type:"irregular"},
  {id:399,v1:"shed",v2:"shed",v3:"shed",ar:"يتخلص",ex:"Shed old habits.",exAr:"تخلص من العادات القديمة.",type:"irregular"},
  {id:400,v1:"shrink",v2:"shrank",v3:"shrunk",ar:"يتقلص",ex:"Don't shrink from challenges.",exAr:"لا تتقلص أمام التحديات.",type:"irregular"},
  {id:401,v1:"slide",v2:"slid",v3:"slid",ar:"ينزلق",ex:"Slide into good routines.",exAr:"انزلق نحو روتين جيد.",type:"irregular"},
  {id:402,v1:"spin",v2:"spun",v3:"spun",ar:"يدور",ex:"Spin ideas into reality.",exAr:"حوّل الأفكار إلى واقع.",type:"irregular"},
  {id:403,v1:"spring",v2:"sprang",v3:"sprung",ar:"ينبثق",ex:"Spring into action.",exAr:"انطلق للعمل.",type:"irregular"},
  {id:404,v1:"sting",v2:"stung",v3:"stung",ar:"يلسع",ex:"Failure stings but teaches.",exAr:"الفشل يؤلم لكنه يعلّم.",type:"irregular"},
  {id:405,v1:"stride",v2:"strode",v3:"stridden",ar:"يخطو",ex:"Stride toward your goals.",exAr:"اخطُ نحو أهدافك.",type:"irregular"},
  {id:406,v1:"sweep",v2:"swept",v3:"swept",ar:"يكنس",ex:"Sweep away the clutter.",exAr:"اكنس الفوضى.",type:"irregular"},
  {id:407,v1:"swing",v2:"swung",v3:"swung",ar:"يتأرجح",ex:"Swing between options.",exAr:"تأرجح بين الخيارات.",type:"irregular"},
  {id:408,v1:"tear",v2:"tore",v3:"torn",ar:"يمزق",ex:"Tear down old barriers.",exAr:"مزّق الحواجز القديمة.",type:"irregular"},
  {id:409,v1:"tread",v2:"trod",v3:"trodden",ar:"يدوس",ex:"Tread carefully.",exAr:"تقدم بحذر.",type:"irregular"},
  {id:410,v1:"weave",v2:"wove",v3:"woven",ar:"ينسج",ex:"Weave your own story.",exAr:"انسج قصتك الخاصة.",type:"irregular"},
  {id:411,v1:"weep",v2:"wept",v3:"wept",ar:"يبكي",ex:"Weep then rise again.",exAr:"ابكِ ثم قم مجدداً.",type:"irregular"},
  {id:412,v1:"wring",v2:"wrung",v3:"wrung",ar:"يعصر",ex:"Wring out every opportunity.",exAr:"استخرج كل فرصة.",type:"irregular"},
  {id:413,v1:"abide",v2:"abided",v3:"abided",ar:"يلتزم",ex:"Abide by the rules.",exAr:"التزم بالقواعد.",type:"regular"},
  {id:414,v1:"absorb",v2:"absorbed",v3:"absorbed",ar:"يمتص",ex:"Absorb new information.",exAr:"امتص معلومات جديدة.",type:"regular"},
  {id:415,v1:"accelerate",v2:"accelerated",v3:"accelerated",ar:"يسرّع",ex:"Accelerate your growth.",exAr:"سرّع نموك.",type:"regular"},
  {id:416,v1:"accumulate",v2:"accumulated",v3:"accumulated",ar:"يراكم",ex:"Accumulate good habits.",exAr:"راكم العادات الجيدة.",type:"regular"},
  {id:417,v1:"acknowledge",v2:"acknowledged",v3:"acknowledged",ar:"يعترف",ex:"Acknowledge your progress.",exAr:"اعترف بتقدمك.",type:"regular"},
  {id:418,v1:"acquire",v2:"acquired",v3:"acquired",ar:"يكتسب",ex:"Acquire new skills.",exAr:"اكتسب مهارات جديدة.",type:"regular"},
  {id:419,v1:"activate",v2:"activated",v3:"activated",ar:"يفعّل",ex:"Activate your potential.",exAr:"فعّل إمكاناتك.",type:"regular"},
  {id:420,v1:"address",v2:"addressed",v3:"addressed",ar:"يتناول",ex:"Address the main concern.",exAr:"تناول المخاوف الرئيسية.",type:"regular"},
  {id:421,v1:"align",v2:"aligned",v3:"aligned",ar:"يوازن",ex:"Align your actions with goals.",exAr:"وازن أفعالك مع أهدافك.",type:"regular"},
  {id:422,v1:"allocate",v2:"allocated",v3:"allocated",ar:"يخصص",ex:"Allocate time wisely.",exAr:"خصص وقتك بحكمة.",type:"regular"},
  {id:423,v1:"amplify",v2:"amplified",v3:"amplified",ar:"يضخّم",ex:"Amplify your strengths.",exAr:"ضخّم نقاط قوتك.",type:"regular"},
  {id:424,v1:"anticipate",v2:"anticipated",v3:"anticipated",ar:"يتوقع",ex:"Anticipate future needs.",exAr:"توقع الاحتياجات المستقبلية.",type:"regular"},
  {id:425,v1:"articulate",v2:"articulated",v3:"articulated",ar:"يعبّر",ex:"Articulate your thoughts.",exAr:"عبّر عن أفكارك.",type:"regular"},
  {id:426,v1:"assemble",v2:"assembled",v3:"assembled",ar:"يجمع",ex:"Assemble the team.",exAr:"اجمع الفريق.",type:"regular"},
  {id:427,v1:"assess",v2:"assessed",v3:"assessed",ar:"يقيّم",ex:"Assess the situation first.",exAr:"قيّم الوضع أولاً.",type:"regular"},
  {id:428,v1:"assign",v2:"assigned",v3:"assigned",ar:"يكلّف",ex:"Assign tasks clearly.",exAr:"كلّف بالمهام بوضوح.",type:"regular"},
  {id:429,v1:"attract",v2:"attracted",v3:"attracted",ar:"يجذب",ex:"Attract positive energy.",exAr:"اجذب الطاقة الإيجابية.",type:"regular"},
  {id:430,v1:"balance",v2:"balanced",v3:"balanced",ar:"يوازن",ex:"Balance work and life.",exAr:"وازن بين العمل والحياة.",type:"regular"},
  {id:431,v1:"bond",v2:"bonded",v3:"bonded",ar:"يترابط",ex:"Bond with your team.",exAr:"ترابط مع فريقك.",type:"regular"},
  {id:432,v1:"clarify",v2:"clarified",v3:"clarified",ar:"يوضّح",ex:"Clarify your message.",exAr:"وضّح رسالتك.",type:"regular"},
  {id:433,v1:"classify",v2:"classified",v3:"classified",ar:"يصنّف",ex:"Classify your priorities.",exAr:"صنّف أولوياتك.",type:"regular"},
  {id:434,v1:"comply",v2:"complied",v3:"complied",ar:"يمتثل",ex:"Comply with the guidelines.",exAr:"امتثل للإرشادات.",type:"regular"},
  {id:435,v1:"confirm",v2:"confirmed",v3:"confirmed",ar:"يؤكد",ex:"Confirm the appointment.",exAr:"أكّد الموعد.",type:"regular"},
  {id:436,v1:"connect",v2:"connected",v3:"connected",ar:"يتواصل",ex:"Connect with great people.",exAr:"تواصل مع أناس رائعين.",type:"regular"},
  {id:437,v1:"consider",v2:"considered",v3:"considered",ar:"يأخذ بعين الاعتبار",ex:"Consider all options.",exAr:"خذ كل الخيارات بعين الاعتبار.",type:"regular"},
  {id:438,v1:"construct",v2:"constructed",v3:"constructed",ar:"يبني",ex:"Construct a solid plan.",exAr:"ابنِ خطة صلبة.",type:"regular"},
  {id:439,v1:"consume",v2:"consumed",v3:"consumed",ar:"يستهلك",ex:"Consume content mindfully.",exAr:"استهلك المحتوى بوعي.",type:"regular"},
  {id:440,v1:"contact",v2:"contacted",v3:"contacted",ar:"يتصل",ex:"Contact the support team.",exAr:"اتصل بفريق الدعم.",type:"regular"},
  {id:441,v1:"continue",v2:"continued",v3:"continued",ar:"يستمر",ex:"Continue despite the obstacles.",exAr:"استمر رغم العقبات.",type:"regular"},
  {id:442,v1:"convert",v2:"converted",v3:"converted",ar:"يحوّل",ex:"Convert ideas into actions.",exAr:"حوّل الأفكار إلى أفعال.",type:"regular"},
  {id:443,v1:"coordinate",v2:"coordinated",v3:"coordinated",ar:"ينسّق",ex:"Coordinate the efforts.",exAr:"نسّق الجهود.",type:"regular"},
  {id:444,v1:"correct",v2:"corrected",v3:"corrected",ar:"يصحح",ex:"Correct your mistakes.",exAr:"صحّح أخطاءك.",type:"regular"},
  {id:445,v1:"craft",v2:"crafted",v3:"crafted",ar:"يصنع",ex:"Craft your message carefully.",exAr:"اصنع رسالتك بعناية.",type:"regular"},
  {id:446,v1:"customize",v2:"customized",v3:"customized",ar:"يخصّص",ex:"Customize your learning path.",exAr:"خصّص مسار تعلمك.",type:"regular"},
  {id:447,v1:"differentiate",v2:"differentiated",v3:"differentiated",ar:"يميز",ex:"Differentiate yourself.",exAr:"ميّز نفسك.",type:"regular"},
  {id:448,v1:"direct",v2:"directed",v3:"directed",ar:"يوجّه",ex:"Direct your energy wisely.",exAr:"وجّه طاقتك بحكمة.",type:"regular"},
  {id:449,v1:"double",v2:"doubled",v3:"doubled",ar:"يضاعف",ex:"Double your efforts.",exAr:"ضاعف جهودك.",type:"regular"},
  {id:450,v1:"draft",v2:"drafted",v3:"drafted",ar:"يصيغ",ex:"Draft a clear plan.",exAr:"صُغ خطة واضحة.",type:"regular"},
  {id:451,v1:"drive",v2:"drove",v3:"driven",ar:"يحرك",ex:"Drive positive change.",exAr:"حرّك التغيير الإيجابي.",type:"irregular"},
  {id:452,v1:"earn",v2:"earned",v3:"earned",ar:"يكسب",ex:"Earn trust through action.",exAr:"اكسب الثقة من خلال العمل.",type:"regular"},
  {id:453,v1:"edit",v2:"edited",v3:"edited",ar:"يحرر",ex:"Edit your work carefully.",exAr:"حرّر عملك بعناية.",type:"regular"},
  {id:454,v1:"execute",v2:"executed",v3:"executed",ar:"ينفّذ",ex:"Execute the plan perfectly.",exAr:"نفّذ الخطة بكمال.",type:"regular"},
  {id:455,v1:"facilitate",v2:"facilitated",v3:"facilitated",ar:"يسهّل",ex:"Facilitate team collaboration.",exAr:"سهّل تعاون الفريق.",type:"regular"},
  {id:456,v1:"filter",v2:"filtered",v3:"filtered",ar:"يصفّي",ex:"Filter out distractions.",exAr:"صفِّ المشتتات.",type:"regular"},
  {id:457,v1:"formulate",v2:"formulated",v3:"formulated",ar:"يصيغ",ex:"Formulate a strategy.",exAr:"صُغ استراتيجية.",type:"regular"},
  {id:458,v1:"foster",v2:"fostered",v3:"fostered",ar:"يعزز",ex:"Foster a growth mindset.",exAr:"عزّز عقلية النمو.",type:"regular"},
  {id:459,v1:"highlight",v2:"highlighted",v3:"highlighted",ar:"يُبرز",ex:"Highlight your achievements.",exAr:"أبرز إنجازاتك.",type:"regular"},
  {id:460,v1:"illustrate",v2:"illustrated",v3:"illustrated",ar:"يوضّح",ex:"Illustrate your point.",exAr:"وضّح نقطتك.",type:"regular"},
  {id:461,v1:"impact",v2:"impacted",v3:"impacted",ar:"يؤثر",ex:"Impact the world positively.",exAr:"أثّر في العالم إيجابياً.",type:"regular"},
  {id:462,v1:"integrate",v2:"integrated",v3:"integrated",ar:"يدمج",ex:"Integrate feedback into work.",exAr:"ادمج الملاحظات في العمل.",type:"regular"},
  {id:463,v1:"interpret",v2:"interpreted",v3:"interpreted",ar:"يفسّر",ex:"Interpret the data correctly.",exAr:"فسّر البيانات بشكل صحيح.",type:"regular"},
  {id:464,v1:"introduce",v2:"introduced",v3:"introduced",ar:"يقدّم",ex:"Introduce new ideas.",exAr:"قدّم أفكاراً جديدة.",type:"regular"},
  {id:465,v1:"leverage",v2:"leveraged",v3:"leveraged",ar:"يستثمر",ex:"Leverage your strengths.",exAr:"استثمر نقاط قوتك.",type:"regular"},
  {id:466,v1:"maximize",v2:"maximized",v3:"maximized",ar:"يعظّم",ex:"Maximize your potential.",exAr:"عظّم إمكاناتك.",type:"regular"},
  {id:467,v1:"minimize",v2:"minimized",v3:"minimized",ar:"يقلّل",ex:"Minimize distractions.",exAr:"قلّل المشتتات.",type:"regular"},
  {id:468,v1:"mobilize",v2:"mobilized",v3:"mobilized",ar:"يحشد",ex:"Mobilize your resources.",exAr:"احشد مواردك.",type:"regular"},
  {id:469,v1:"model",v2:"modeled",v3:"modeled",ar:"يمثّل",ex:"Model the behavior you want.",exAr:"مثّل السلوك الذي تريده.",type:"regular"},
  {id:470,v1:"network",v2:"networked",v3:"networked",ar:"يبني علاقات",ex:"Network with industry leaders.",exAr:"ابنِ علاقات مع قادة الصناعة.",type:"regular"},
  {id:471,v1:"nurture",v2:"nurtured",v3:"nurtured",ar:"يرعى",ex:"Nurture your talents.",exAr:"ارعَ مواهبك.",type:"regular"},
  {id:472,v1:"optimize",v2:"optimized",v3:"optimized",ar:"يحسّن",ex:"Optimize your workflow.",exAr:"حسّن سير عملك.",type:"regular"},
  {id:473,v1:"outline",v2:"outlined",v3:"outlined",ar:"يضع مخططاً",ex:"Outline your ideas first.",exAr:"ضع مخططاً لأفكارك أولاً.",type:"regular"},
  {id:474,v1:"overcome",v2:"overcame",v3:"overcome",ar:"يتغلب على",ex:"Overcome fear with action.",exAr:"تغلب على الخوف بالعمل.",type:"irregular"},
  {id:475,v1:"pitch",v2:"pitched",v3:"pitched",ar:"يعرض فكرة",ex:"Pitch your idea clearly.",exAr:"اعرض فكرتك بوضوح.",type:"regular"},
  {id:476,v1:"position",v2:"positioned",v3:"positioned",ar:"يضع في موضع",ex:"Position yourself for success.",exAr:"ضع نفسك في موقع النجاح.",type:"regular"},
  {id:477,v1:"prepare",v2:"prepared",v3:"prepared",ar:"يستعد",ex:"Prepare for every scenario.",exAr:"استعد لكل سيناريو.",type:"regular"},
  {id:478,v1:"progress",v2:"progressed",v3:"progressed",ar:"يتقدم",ex:"Progress every single day.",exAr:"تقدم كل يوم.",type:"regular"},
  {id:479,v1:"project",v2:"projected",v3:"projected",ar:"يتوقع",ex:"Project confidence.",exAr:"أظهر الثقة.",type:"regular"},
  {id:480,v1:"promote",v2:"promoted",v3:"promoted",ar:"يروّج",ex:"Promote a healthy culture.",exAr:"روّج لثقافة صحية.",type:"regular"},
  {id:481,v1:"qualify",v2:"qualified",v3:"qualified",ar:"يؤهل",ex:"Qualify for the next level.",exAr:"تأهّل للمستوى التالي.",type:"regular"},
  {id:482,v1:"question",v2:"questioned",v3:"questioned",ar:"يتساءل",ex:"Question the status quo.",exAr:"اشكّك في الوضع الراهن.",type:"regular"},
  {id:483,v1:"refine",v2:"refined",v3:"refined",ar:"يصقل",ex:"Refine your craft.",exAr:"اصقل مهارتك.",type:"regular"},
  {id:484,v1:"reinforce",v2:"reinforced",v3:"reinforced",ar:"يعزز",ex:"Reinforce good habits.",exAr:"عزّز العادات الجيدة.",type:"regular"},
  {id:485,v1:"reshape",v2:"reshaped",v3:"reshaped",ar:"يُعيد تشكيل",ex:"Reshape your mindset.",exAr:"أعد تشكيل عقليتك.",type:"regular"},
  {id:486,v1:"restructure",v2:"restructured",v3:"restructured",ar:"يُعيد هيكلة",ex:"Restructure your approach.",exAr:"أعد هيكلة أسلوبك.",type:"regular"},
  {id:487,v1:"retain",v2:"retained",v3:"retained",ar:"يحتفظ",ex:"Retain what you learn.",exAr:"احتفظ بما تتعلمه.",type:"regular"},
  {id:488,v1:"reveal",v2:"revealed",v3:"revealed",ar:"يكشف",ex:"Reveal your true potential.",exAr:"اكشف عن إمكاناتك الحقيقية.",type:"regular"},
  {id:489,v1:"scale",v2:"scaled",v3:"scaled",ar:"يوسّع نطاق",ex:"Scale your business.",exAr:"وسّع نطاق عملك.",type:"regular"},
  {id:490,v1:"schedule",v2:"scheduled",v3:"scheduled",ar:"يجدول",ex:"Schedule your priorities.",exAr:"جدوِل أولوياتك.",type:"regular"},
  {id:491,v1:"simplify",v2:"simplified",v3:"simplified",ar:"يبسّط",ex:"Simplify your routine.",exAr:"بسّط روتينك.",type:"regular"},
  {id:492,v1:"spark",v2:"sparked",v3:"sparked",ar:"يُشعل",ex:"Spark curiosity in others.",exAr:"أشعل الفضول في الآخرين.",type:"regular"},
  {id:493,v1:"specialize",v2:"specialized",v3:"specialized",ar:"يتخصص",ex:"Specialize in your field.",exAr:"تخصص في مجالك.",type:"regular"},
  {id:494,v1:"standardize",v2:"standardized",v3:"standardized",ar:"يوحّد المعيار",ex:"Standardize your process.",exAr:"وحّد معيار عمليتك.",type:"regular"},
  {id:495,v1:"stimulate",v2:"stimulated",v3:"stimulated",ar:"يحفّز",ex:"Stimulate creative thinking.",exAr:"حفّز التفكير الإبداعي.",type:"regular"},
  {id:496,v1:"streamline",v2:"streamlined",v3:"streamlined",ar:"يبسّط",ex:"Streamline your workflow.",exAr:"بسّط سير عملك.",type:"regular"},
  {id:497,v1:"synthesize",v2:"synthesized",v3:"synthesized",ar:"يدمج",ex:"Synthesize different ideas.",exAr:"ادمج أفكاراً مختلفة.",type:"regular"},
  {id:498,v1:"tailor",v2:"tailored",v3:"tailored",ar:"يخصّص",ex:"Tailor your message.",exAr:"خصّص رسالتك.",type:"regular"},
  {id:499,v1:"think",v2:"thought",v3:"thought",ar:"يفكر",ex:"Think outside the box.",exAr:"فكّر خارج الصندوق.",type:"irregular"},
  {id:500,v1:"thrive",v2:"thrived",v3:"thrived",ar:"يزدهر",ex:"Thrive in every condition.",exAr:"ازدهر في كل الظروف.",type:"regular"}
];
